- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/VeniceMetadataRepositoryBuilder.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AbstractVeniceAggVersionedStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedStorageEngineStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/RocksDBMemoryStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/VeniceVersionedStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageEngineMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageEngineRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StatusReportAdapterTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/helper/SortBasedCollectionFieldOperationHandlerTestBase.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/AbstractVeniceMapper.java
Internal tests passed (green).
> [da-vinci] Use interpolation for logging in da-vinci-client

- internal/venice-common/src/main/java/com/linkedin/venice/utils/VeniceLock.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ApacheKafkaProducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/KafkaMessageCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/SharedKafkaProducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/SharedKafkaProducerService.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/guid/GuidUtilsTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/StoreStatusMessageHandler.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixReadOnlyStorageEngineRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/TopicManagerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/SharedKafkaProducerServiceTest.java
- internal/venice-compatibility-test/src/test/java/com/linkedin/venice/VeniceClientCompatibilityTest.java
- internal/venice-compatibility-test/src/test/java/com/linkedin/venice/VeniceClusterInitializer.java
- internal/venice-compatibility-test/src/test/java/com/linkedin/venice/utils/ClassPathSupplierForVeniceCluster.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/AdminCommandExecutionTracker.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ErrorPartitionResetTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/InstanceStatusDecider.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/TerminalStateTopicCheckerForParentController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/UserSystemStoreLifeCycleHelper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerStateModel.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkAdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkExecutionIdAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/authorization/SystemStoreAclSynchronizationTask.java
…ontroller
This rb contains the logging clean ups for venice-common and venice-controller module.
Internal CI (yellow)
> [controller][server] Use interpolation logging in venice-common and controller

- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/hadoop/TestVenicePushJob.java
Allow repush of write compute enabled non active-active stores.
> [H2V] Allow repush of write compute stores

- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- docs/README.md
Memory allocation reduction for repush
Internal CI and manual test on an OOMing job.
No
> [h2v][doc] Repush optimization

- clients/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
The controller client calls in SystemProducer are retried 2 times including stat method. 
But for start method often times timeouts and 2 retries might not be enough which leads to failure to start samza jobs.  Increasing the retry limit to 10 for start method.
> [samza] Add longer retries for SystemProducer start routine

- build.gradle
Resolves the problem when test suite is not able to continue due to failing AfterClass methods.
> [test] Update test-retry plugin to 1.4.1

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- docs/README.md
- docs/dev_guide/doc_guide.md
- docs/dev_guide/recommended_development_workflow.md
- docs/quickstart/quickstart.md
- gradle/helper/git.gradle
- gradle/helper/publishing.gradle
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/http2/AbstractHttp2StreamFrameCodec.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/http2/Http2StreamFrameClientCodec.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/http2/Http2StreamFrameServerCodec.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/D2ControllerClient.java
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/TestControllerClient.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- make_tag.py
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/NodesAndReplicas.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- settings.gradle
1. Remove some non-inclusive language
2. Change `make_tag.py` script to use the `main` branch
3. Changes to gradle functions to use `main` branch and use upstream remote instead of `origin`
Internal CI passed
- Some non-inclusive configs have been removed
- make_tag and gradle scripts will operate against primary venice repo's `main` branch instead of `origin/master`
> [controller][samza][vpj][router][fast-client][server][build][doc] Remove non-inclusive terms where possible

- docs/CODE_OF_CONDUCT.md
- docs/CONTRIBUTING.md
- docs/README.md
- docs/SECURITY.md
- docs/community_guidelines.md
- docs/dev_guide/dev_guide.md
- docs/dev_guide/doc_guide.md
- docs/dev_guide/recommended_development_workflow.md
- docs/dev_guide/workspace_setup.md
- docs/ops_guide/ops_guide.md
- docs/ops_guide/repush.md
- docs/quickstart/quickstart.md
- docs/user_guide/ttl.md
- docs/user_guide/user_guide.md
Replace URL links with Markdown relative links. Github has jekyll-relative-links plugin enabled by default - [reference](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins). 
This helps the reader travel between docs on the same platform where they are consuming the docs from - markdown or via the docs webpage.
Verified locally and deployed the pages to https://nisargthakkar.github.io/venice
> [doc] Use relative links in docs

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DataRecoveryTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestStreaming.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
Increased test timeout since these tests require more time when running with JDK8
> [test] Increase test timeout for some long-running test

- make_tag.py
Typo fix github-token-> github-actor in make_tags.sh
> [Build] Fix the argument name in make_tags.

- make_tag.py
Remove the API call to create tag and do git push instead.
> [build] Remove the API call to create tag

- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/rmd/v1/CollectionRmdTimestamp.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/rmd/v1/TestCollectionRmdTimestamp.java
> [test] Add unit tests for CollectionRmdTimestampTest

- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/TestAdminSparkServerAcl.java
Internal CI with 100 iteration of this test
> [test] Fix flaky test TestAdminSparkServer::testCleanupInstanceCustomizedStates

- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/AvroCollectionElementComparator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/IndexedHashMap.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/merge/AvroCollectionElementComparatorTest.java
> [test] Add unit test for AvroCollectionElementComparator

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
[server] Wrapped InterruptException should not fail ingestion during graceful shutdown
InterruptedException during graceful shutdown shouldn't mark ingestion as error. This is already handled in StoreIngestionTask's catch block. However, some InterruptedException gets caught earlier and end up wrapped by VeniceException by other components prior to the StoreIngestionTask's catch block. Instead of trying to unwrap InterruptedExceptions case by case we will recursively check in StoreIngestionTask for any exceptions caused by InterruptedException and not mark push as failure during graceful shutdown.
Added an unit test in StoreIngestionTaskTest just for the scenario described.
> [server] Wrapped InterruptException should not fail ingestion during graceful shutdown

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/TestAdminConsumptionTask.java
Before this code change, `AdminConsumptionTask` already has logic to handle execution id gap when producers are different and the missing scenario is that the execution id gap could happen in the first poll request where there is no previous producer info in memory.
This PR seeks to one older offset than the persisted offset to initialize the in memory producer info.
Internal CI passed
> [controller] Handled execution id gap when firstly becoming a leader controller

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
> [da-vinci][server] Fixed disk usage metric to collect store-level usage

- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
Use the correct flag to decide whether to put RMD payload or RMD manifest in the chunking top level message.
Internal CI
> [common] Fix a bug in new writer chunking RMD feature

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestD2ControllerClient.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/D2TestUtils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/MockD2ServerWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/MockVeniceRouterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceMultiClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiColoMultiClusterWrapper.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/StoreReadThrottler.java
> [test] Removed the unused D2 sticky routing

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionServerTest.java
Both RHEL & CentOS require an abs path of lsof. However, this path is not the same on Ubuntu. Also, the abs path is
not required on ubuntu. So we first try with the abs path and if it returns an empty string, that likely
means that the command did not succeed and hence we try it again without the abs path.
Internal CI
> [test] Use lsof without abs path IsolatedIngestionServerTest::testReleaseTargetPortBinding

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
Resolves a bug in recently added feature. ClientFactory relies on config cloning, the missing flag resulted in misconfigured clients.
> [client] Copy PreferredSchemaFilter on config cloning

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
Fixes a bug in `ClientConfig::clone()`
> [client] Copy ProjectionFieldValidationEnabled flag on config cloning

- clients/venice-admin-tool/build.gradle
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/QueryTool.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRead.java
The new query allows us to query Venice Topics via the following params:
1. Key.
2. Topic name, which could be RT topic or Version topic.
3. Time range.
Manual test
> [admin-tool] Added a new command to query Kafka topic

- build.gradle
./gradlew spotlessCheck
./gradlew spotlessApply
> [build] Update test-retry and spotless plugins

- build.gradle
./gradlew clean :internal:alpini:netty4:alpini-netty4-base:test
> [build] Skip Alpini Netty tests for regular builds

- internal/venice-test-common/src/main/java/com/linkedin/venice/testng/VeniceSuiteListener.java
Resolves build timing out due to memory pressure.
~40 builds on internal CI (all completed either successfully or with known issues)
> [test] Limit logging to venice sources only in tests

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/ReplicationMeadataRocksDBStoragePartitionCFTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
Add a config to control the format version for rocksDB blockbased table.
CI build.
> [server] Add config to control the block-based format version.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
Tested with integration test in main branch.
> [server] Make sure LEADER drainer DIV logic does not skip value chunks and manifest messages

- internal/venice-test-common/build.gradle
> [build] Fixed regression in PR #161 related to Java 8

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Adjust timeout of PartialUpdateTest for CI on Github.
Internal CI
Github CI also pass.
> [test] Adjust partial update test timeout for Github CI

- build.gradle
- docs/dev_guide/code_coverage_guide.md
Per our discussion, lower the threshold and add more details on how to generate and view the code coverage reports.
N/A
> add code coverage guide

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StoragePartitionConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/DeepCopyStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
> [da-vinci][server] Removed unused delay compaction and cache warming features

- .github/workflows/gh-ci.yml
- build.gradle
- docs/dev_guide/code_coverage_guide.md
- docs/dev_guide/workspace_setup.md
- internal/venice-test-common/build.gradle
Add the exclusion filter back since Internal CI now upgrades its git version. 
See #206.
JDK11 #7601 and JDK8 #1186 (pending)
> [build][doc] add diffCoverage exclusion filter and doc

- build.gradle
- gradle/helper/publishing.gradle
- internal/venice-avro-compatibility-test/build.gradle
- internal/venice-test-common/build.gradle
Publishes IntegrationTest Utils artifact so that it can be used in other projects.
` ./gradlew -Pversion="0.0.1-SNAPSHOT" publishToMavenLocal`
> [build] Publish IntegrationTest utils

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientFactory.java
Restore backward compatibility lost in https://github.com/linkedin/venice/pull/172
> [clients] Add legacy interface for backward compatibility

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MapKeyStringAnnotatedStoreSchemaCache.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeResultValueSchemaResolverImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/DaVinciClientMetaStoreBasedRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePutWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithValueLevelTimestamp.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadOnlySchemaRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadOnlySchemaRepositoryAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadWriteSchemaRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadWriteSchemaRepositoryAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlySchemaRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/HelixReadOnlySchemaRepositoryTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StoreValueSchemasCacheService.java
Remove unnecessary optional object creations in schema lookup.
CI build.
> [server] Remove optional in schema lookup.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionReportHandler.java
Use correct notifier API so inc push status can be reported correctly with version info
Test Suite
> [server] Let isolated ingestion report incremental push version

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
> [test] Make CorruptedKafkaProducer static inner class

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
Utils.waitStoreVersionOrThrow() logic in startConsumption() API impl can take up to 30s to complete with exception and this does not work well with Netty's threading model. 
In some test environment we have observed this slow operation can lead to other ingestion request timeout and fail sometimes during bootstrap.
The problem can be addressed by either making startConsumption() call in isolated ingestion server handler executed in a different thread pool or checking the version existence in Helix thread before submitting to isolated ingestion process. 
This PR takes the latter approach as it is considered easy to implement and performance is also guaranteed. Compared to Server read handler, it only has one action need to be offloaded to other thread pool so it is not necessary to …
> [server] Execute time-consuming method Utils.waitStoreVersionOrThrow() in main process for isolated ingestion for startConsumption() API call

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/build-and-upload-archives-on-demand.yml
- .github/workflows/build-and-upload-archives-upon-pushing-tags.yml
- .github/workflows/build-and-upload-archives.yml
- .github/workflows/gh-ci.yml
Our GitHub Actions pin the Gradle wrapper validation and Grade builds plugins to specific commits that correspond to older releases. This commit changes these to pin them to a more dynamic, but stable release instead.
Actions will test it
> [build] Use standard github actions for Gradle wrapper validation and Gradle builds

- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
Fix the emission of Read compute deserialization latency metric
Github CI
> [server][da-vinci] Fix read-compute deserialization latency

- clients/venice-thin-client/config/sslconfig.properties
> [client] House cleaning

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-server/build.gradle
- services/venice-server/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorAccessor.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
New config: fast.avro.field.limit.per.method (default 100)
> [server] Added config for fast-avro field limit per method

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/gh-ci.yml
> [build] Cache gradle deps to speed up GH-CI

- .github/workflows/gh-ci.yml
- internal/venice-test-common/build.gradle
> [build] Split UnitTestsAndCodeCoverage GH-CI job into UnitTestsAndCodeCoverage and AvroCompatibilityTests

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/NodesAndReplicas.java
This change will allow `cluster-health-instances` admin command to re-enable disabled replica. Currently leader replica renable is not working which might create lots of disabled replicas in a cluster and take the cluster down. This PR will add a tooling workaround to renable disabled replicas.
CI
> [controller] Enable disabled replica admin command

- internal/venice-common/src/main/java/com/linkedin/venice/meta/VersionStatus.java
This change introduces a new version status, KILLED, to indicate that this version is killed. The reason of having this new status is that it is a critical info to later fix the race condition between kill job and version swap.
Internal CI passed.
> [controller][server] Introduce a new version status

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixLiveInstanceMonitor.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixLiveInstanceMonitor.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestLeaderReplicaFailover.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorDelegator.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
The HelixLiveInstanceMonitor does not subscribe to changes unless refresh is called. This PR adding a call to refresh on HelixLiveInstanceMonitor during controller start to listen to live instance change.
Integ test. CI
> [controller] Call refresh on HelixLiveInstanceMonitor on controller start

- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreInfo.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestStoreInfo.java
> [controller] Add leaderFollowerModelEnabled to StoreInfo for Controller::ControllerClient compatibility

- services/venice-router/src/main/java/com/linkedin/venice/router/AdminOperationsHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/HealthCheckHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterThrottleHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterResourceType.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParserHelper.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVenicePathParserHelper.java
The router resource type was used as a raw string and compared in hot path in various request handler. This PR creates an enum class for various router resource types for a cleaner and better usage in various handler classes. 
unit/CI tests
> [router] Create enum type for router resources

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/resources/avro/AdminOperation/v70/AdminOperation.avsc
Added admin command to update latestSupersetSchemaId
CI
Need to deploy Child Controller before Parent Controller
> [controller] Added admin command to update latestSupersetSchemaId

- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClusterInitializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriterFactory.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciLiveUpdateSuppressionTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestLeaderReplicaFailover.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestMultiDataCenterAdminOperations.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputFormat.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputRecordReader.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/restart/TestRestartServerDuringIngestion.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/storagenode/ReadComputeValidationTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/storagenode/StorageNodeComputeTest.java
Use `VWF::createVeniceWriter(VeniceWriterOptions)` instead of `VWF::createBasicVeniceWriter(String)`   
and `VWF::createVeniceWriter(String, VeniceKafkaSerialize, VeniceKafkaSerializer, boolean)`.
> [server][test] Cleanup VeniceWriterFactory

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- internal/venice-common/src/test/java/com/linkedin/venice/acl/StoreAclHandlerTest.java
Added check in `StoreAclHandler` to check if the request is for the `/metadata/${storeName}` endpoint. If so, we can skip ACL checks just as we do for the system store. There's no sensitive information in the response so this is okay
Added unit test to `StoreAclHandlerTest`
> [server][router] Skip ACL check for requests to metadata endpoint

- gradle/wrapper/gradle-wrapper.properties
Upgrades Gradle to 7.3 for JDK17 support.
> [build] Upgrade Gradle to 7.3 for JDK17 support

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
In a previous resilience enhancement, there is a race condition that the store init retry thread could spin up many threads if the store init keeps failing with a lot of concurrent requests.
This code change guarantees there is only one thread initialized for the retry logic to avoid zoomie threads.
CI
> [thin-client] Fixed a race condition of thin-client store init retry

- build.gradle
JVM deoptimization causing latency spike.
Cutting a hotfix release Including float array deoptimization using VarHandle from fast-avro version 0.2.150 to help with the latency issues.
CI build
> [server] Fork hotfix feature branch off Venice release 0.4.52

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducedRecordContext.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/NearlineE2ELatencyTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
This change adds two metrics for nearline streaming writes. Note that we use nearline terminology instead of realtime to align with current design thinking and avoid confusion with realtime client API.
1. nearlineProducerToLocalBrokerLatency - This metric measures the time between message received by venice from a nearline producer ( such as samza) to the time it is committed into the local version topic in the partition leader
2. nearlineLocalBrokerToReadyToServeLatency - Time between receiving the message from the local VT and when the message is committed in the local db and ready to serve. For a leader , this is calculated from the time when the callback to the version topic write returns.
An important consideration is to only record this metric for streaming records . We check this …
> [server] Add nearline end to end latency Metrics.

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerAclHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerAclHandlerTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/Gauge.java
- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- internal/venice-common/src/main/java/com/linkedin/venice/listener/ServerHandlerUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/listener/VerifySslHandler.java
- internal/venice-common/src/test/java/com/linkedin/venice/listener/VerifySslHandlerTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerAclHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStoreAclHandler.java
Also removed an unnecessary optional from ServerHandlerUtils.
> [all] Bumped Tehuti to 0.10.0 (lock performance improvement)

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Add more info to log on total instances count ingesting the a push and how many of them are alive. This wont give more context on the health of DVC ingestions.
CI
> [controller] Add more details on total/live instance count from DVC pushstatus store

- build.gradle
Upgrade rocksDB version to 7.9.2, hopes reduce write amplification factor. 
https://rocksdb.org/blog/2022/10/31/align-compaction-output-file.html
CI
> [server][davinc-client] Upgrade rocksDB version to 7.9.2

- build.gradle
- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClusterInitializer.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciLiveUpdateSuppressionTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/ProcessWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterCreateOptions.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapperConstants.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerCreateOptions.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- internal/venice-test-common/src/jmh/java/com/linkedin/venice/benchmark/DaVinciClientBenchmark.java
- internal/venice-test-common/src/jmh/resources/log4j2.properties
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- Fixed DaVinciClientBenchmark hanging caused by missing MetaSystemStore
- Fixed javax.servlet dependency conflict in venice-test-common
- Added BatchGet benchmark to DaVinciClientBenchmark
- Replaced hand-crafted JMH scaffoldings with Gradle JMH plugin
- Added log4j2 configuration for JMH benchmarks
Internal CI
> [test] Fix and improve DaVinciClientBenchmark

- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
When routers receive a request_topic API call, they will check if the store has writes enabled
Added unit test. GH CI
> [router] Check if a store has writes enabled in a request_topic call

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientUnitTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/ClientConfigTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DualReadAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/VeniceClientBasedMetadataTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/utils/RequestBasedMetadataTestUtils.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
1. Add unit tests for `DispatchingAvroGenericStoreClient`
2. Fix some metrics based on the new tests
3. cleaned up metrics verification in integration tests
4. Moved some utils function from ` meta/RequestBasedMetadataTest` to `meta/utils/RequestBasedMetadataTestUtils` to be reused for `DispatchingAvroGenericStoreClientTest`
GH CI
> [fc][test] Add unit tests for Fast client DispatchingAvroGenericStoreClient

- .github/workflows/build-and-upload-archives-on-schedule.yml
Weekly once release deemed too less and developers  often cut multiple release almost every week. Making the weekly release cadence to twice a week on Tuesday and Thursday.
CI
> Increase release schedule to 2 times a week.

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
This test is flaky because when new push job is completed, router will refresh its metadata, if the client get happens faster than metadata refresh, Router will throw 5xx error indicating the resource does not exist.
This can be fixed in two ways:
(1) Add retry to client get
(2) Force router metadata refresh before client call.
This PR takes the 1st approach.
There might be other flaky tests in the codebase having the same symptom, will tackle them once we located it in test log.
Locally run the integration test 20 times. Before fix, every 10 invocation there will be 2-3 error due to resource not exist. After the test, all test passed.
> [test] Fix flaky test PushStatusStoreTest#testIncrementalPushStatusStoredInPushStatusStore

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- docs/user_guide/ttl.md
- docs/user_guide/write_api/push_job.md
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
Update some doc for targeted region push. Removed some contexts that are still under development. Will add them back once we ship them.
GHCI.
> [vpj][doc] Update targeted region push doc

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryClient.java
In data recovery executor, there is an issue in detecting if there is an ongoing push in system. `getFutureVersions` can return NON_EXISTING_VERSION to indicate that none of future version is available to read, but current implementation doesn't check it, thus could cause a false positive in the result. This rb fixes this bug by adding additional check against NON_EXISTING_VERSION value.
Local manual test against EI.
Internal CI passed.
> [admin-tool] Fix an issue in data recovery executor

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/config/VeniceServerConfigTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
Fixed davinci memory limiter calculation
unit test
> [da-vinci] Fixed davinci memory limiter calculation

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
Enabled admin-tool to update configs for Admin topics
Tested in EI
> [admin-tool] Enabled admin-tool to update configs for Admin topics

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Restrict fail pushes due to maintenance mode from target colo push only. Otherwise during some outrages too many jobs would fail and create bad user experience.
CI
> [controller] Fail pushes due to maintenance mode from target colo push only

- docker/docker-compose-multi-dc-setup.yaml
- docker/docker-compose-single-dc-setup.yaml
- docs/README.md
Manually tested the Docker images.
Rendered docs here: https://felixgv.github.io/venice/
> [docs] Mentioned stable releases in the README

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkWithMocks.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
[Controller] Emergency source region config should be scoped per cluster to help with testing and can also be useful with complex deployments
Existing integration tests
- [x ] No. You can skip the rest of this section.
> [Controller] Emergency source region config scoped per cluster

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/heartbeat/DefaultPushJobHeartbeatSender.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
Added some log to indicate push completion to target regions. 
GHCI
> [vpj] minor logging improvements

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Problem: There is a race condition during HaaS transition, which causes the flakiness of testTransitionToHAASControllerAsStorageClusterLeader. The test case stops 1 old controller that disables HaaS and starts 1 new controller that enables HaaS 3 times. When the 2nd new controller starts, if the get leader controller request is sent to an old controller, since the old controller disables HaaS, it returns storage cluster controller leader property. However, since a controller that enables HaaS is added, the property becomes a Helix controller instead of Venice controller. Helix controller could not handle system schema requests at controller start time. The new controller could not start and the test fails.
Fix: Always get leader controller from EV of the controller cluster because for …
> [controller] Always get leader controller from EV of the controller cluster

- build.gradle
> [build] bump the diff coverage requirement

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreGraveyardCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
This rb fixes several problems found by our IDE framework without modifying any semantics.
VeniceControllerWrapper.java
-- remove unnecessary initialization to empty string.
-- remove unnecessary null check before 'instanceof'.
-- remove unused functions.
VeniceController.java
-- stop controller services in the reverse order as they are started.
StoreBackupVersionCleanupService.java
StoreGraveyardCleanupService.java
-- use AtomicBoolean to avoid potential race.
> [controller] Minor code cleanup

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/VeniceProducer.java
- docs/ops_guide/repush.md
- docs/user_guide/write_api/online_producer.md
- docs/user_guide/write_api/online_writer.md
Add some docs for online producer
Viewed locally in intellij. The docs can also be accessed here: https://nisargthakkar.github.io/venice/docs/user_guide/write_api/online_writer
> [doc] Add docs for Online Producer

- build.gradle
Due to backwards incompatible changes, only versions up to 1.49.2 will be supported for now
> [fast-client][server] Bump io.grpc down to 1.49.2

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/streaming/ClientComputeRecordStreamDecoder.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/storagenode/ReadComputeValidationTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceDispatcher.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ErrorCountAppender.java
In a previous schema optimization, Venice Server/DaVinci could pass an inconsistent schema id from the reused record when decoding the binary payload from the database.
When mismatch happens, object reuse won't work, and Avro deserializer will create a new object for every call.
For Server, this could happen in the following setup:
1. The user evolves the value schema, which would also trigger a new superset schema.
2. The new value/superset schema won't be used by any data entries.
3. Client will continue to use the locally-known latest value schema.
4. The mismatch will happen in Venice Server when handling such compute request.
For DaVinci, the chance of mismatch is very low since the request will be executed locally, and that is the reason this PR uses a lightweight change to make …
> [da-vinci][server] Fixed a small perf regression when handling compute request

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
For topic which are missing START_OF_PUSH control message, the store ingestion task keeps waiting on it thus blocking ST threads till it barfs out after 24hrs. This PR fails the push if it does not see SOP for 1 hour.
GHCI
> [server][da-vinci-client] Kill SIT if missing SOP for 1 hr

- build.gradle
The latest version of fast-avro added the support of splitting large methods in fast serializer.
CI
> [all] Bumped up avro-util dep to pick up a fix in fast serializer generation

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerTest.java
> [server] Fix ApacheKafkaConsumerAdapter::batchUnsubscribe

- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
There is a regression in a recent code refactoring, the following mapping in StorageReadRequestHandler can stale during rebalance: Map<String, PerStoreVersionState> perStoreVersionStateMap
In the following rebalance scenario, the storage engine reference in the above map will be stale:
1. There is only one assigned partition for this resource, and let us say the storage engine instance is 'se1'.
2. When Helix rebalance decides to move this partition to another node, there is no partition left, so this storage engine: 'se1' will be closed and removed from the storage engine factory.
3. Later, Helix decides to move back another partition to this node, Storage engine factory will create a new instance of storage engine: 'se2'.
4. This particular node will bootstrap the rebalanced partition …
> [server] Refresh the PerStoreVersionState mapping for each request in StorageReadRequestHandler

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
To help with debugging flakiness. Also added a waitForNonDeterministicAssertion in testNativeReplicationForBatchPush, which might help.
CI.
> [test] Improved some assertions in TestPushJobWithNativeReplication

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- The debug info map inserted in SOS control messages now omits entries for which it could not find the info. Log statements related to the info gathering are also lowered, as they were noisy.
- Deleted dead code.
- Addressed various IDE hints in the Utils class.
CI
> [all] Minor Utils cleanups

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
Should help with excessive logging.
GHCI
> [server] Set log level to debug in PartitionTracker

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
In `ProducerTool`, some logic to strip top-level unions has been inherited from the Query tool. From the commit history, it seems that the logic was added for VSON stores. We do not need to continue building systems that support legacy stores at the expense of stores that use Avro. Hence, removed the special handling of top-level unions in the shell producer.
Tested locally on a store
> [producer] Allow top-level union-schema in the shell producer

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestDeleteStoreDeletesRealtimeTopic.java
This PR addresses a potential issue with resource management in `TestDeleteStoreDeletesRealtimeTopic`.  
The previous code prematurely closed the `TopicManagerRepository` within a try-with-resources block,  
causing early closure of internal topic managers and its associated PubSub clients.  
To resolve this, we close the `TopicManagerRepository` only when its local topic manager is no longer  
required. This change ensures proper resource management.
CI
> [test] Fix TestDeleteStoreDeletesRealtimeTopic for correctness

- docs/README.md
Also fixed the build badge which was broken by a recent CI refactoring.
> [docs] Added two talks to the list

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
There are two issues with DaVinci shutdown:
1. `VersionBackend#close` is calling `KafkaStoreIngestionService#shutdownStoreIngestionTask`, which
would wait for up to 10s to complete the shutdown (best effort).
2. Each SIT will shutdown the partition sequentially.
When shutting down a DaVinci instance, the Store Versions hosted will be shut down sequentially and
if there are x number of DaVinci stores, the last store will receive the shutdown signal after 10 * x seconds,
which is too late.
If there are y number of partitions, based on the logs, each partition graceful shutdown would take roughly 2 seconds
for a hybrid store partition,
so it will take 2 * y seconds to gracefully shut down one `SIT`.
For some heavy DaVinci users, they normally use multiple DaVinci stores (5+) stores and each …
> [da-vinci] Speed up shutdown

- .github/workflows/VeniceCI-E2ETests.yml
- internal/venice-common/src/main/java/com/linkedin/venice/writer/update/UpdateBuilderImpl.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/update/UpdateBuilderImplTest.java
Resolves #661 
Catch UnresolvedUnionException and AvroRuntimeException in UpdateBuilder and log extracted unresolvedDatum object for different versions of Avro
> [da-vinci]Log more informative details in UpdateBuilder using unresolvedDatum object

- internal/venice-common/src/main/java/com/linkedin/venice/writer/update/UpdateBuilderImpl.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/update/UpdateBuilderImplTest.java
Also expanded unit test.
Unit test.
> [producer] Fixed NPE in UpdateBuilderImpl::validateUpdateRecordIsSerializable

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubAdminAdapter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestFabricBuildout.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/admin/PubSubAdminAdapterTest.java
Added tests to verify contracts of PubSubAdminAdapter APIs. 
CI
> [controller][test] Add verification tests for PubSubAdminAdapter APIs

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
Previously, the topic dumper only worked on RT and version topics, now this should work on SR
and CC topics.
In production!
> [changelog] Patch topic dumper to work on change capture topics

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/repository/NativeMetadataRepositoryTest.java
[da-vinci] Improve NativeMetadataRepository schema retrieval efficiency
Currently metadata refresh in DVC would generate many unnecessary schema requests to the meta system store. The severity increases with the number of DVC instances and the number of value schema versions for the subscribed stores. Since value schemas are immutable in Venice we will now:
1. Only retrieve value schemas that we don't have and reuse the SchemaData object that we cache in the NativeMetadataRepository.
New unit test and existing integration test.
> [da-vinci] Improve NativeMetadataRepository schema retrieval efficiency

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfig.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
> [server][controller] Handle exceptions from KafkaConumer::ParitionsFor API

- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
Today, in some cases, controller doesn't report the details of unfinished partitions if partition ingestion has issues and makes the debugging work laborious.
This change adds log lines for such cases and combines existing inc push status logs to make it concise.
CI passed.
Example output:
```
2023-11-16 21:00:57 - [] INFO [AbstractPushMonitor] [TestNG-method=testGetOfflineStatusIncrementalPush-1] 0 out of 2 partitions are sufficiently replicated, kafkaTopic: testIncPushStore_58746ca808a6_f2eae3f5_v1, incrementalPushVersion: incPush2, unfinished partitions (partitionId, minRequired, No. of EOIP replicas): [(0, U, U), (1, U, U)], size: 2
2023-11-16 21:00:57 - [] INFO [AbstractPushMonitor] [TestNG-method=testGetOfflineStatusIncrementalPush-1] 0 out of 2 partitions are sufficiently …
```
> [controller] Log improvement for inc push status report

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
This fixes a regression introduced in PR #735.
CI
> [server] Fixed NPE in recent AASIT refactoring

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
Patch the missing line in original hot fix
N/A
> [server] ViewWriter use correct original old value fetcher

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/StuckConsumerRepairStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStuckConsumerRepair.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
Recently, we noticed that some shared consumers were stuck since they
were blocked by producing to some non-existing topics, and many other
store versions got affected since the stuck consumer is being shared
by many other stores.
This PR introduces a way to detect and repair stuck consumer for above
situation.
In the high level, there will be a thread periodically check whether consumer#poll
is being invoked regularly or not, and if not, the thread will scan all
the ingestion tasks to see whether they are producing to any non-existing topics
or not. And for the store ingestion task, which is talking to some non-existing topic,
the repair thread will try to close the stuck KafkaProducer and kill the corresponding
ingestion task.
This PR also checked the non-existing topics for a …
> [server] Introduced a repair service for stuck shared consumer

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/MetadataRetriever.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/davinci/listener/response/ServerCurrentVersionResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/CurrentVersionResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/ZkRoutersClusterManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/QueryAction.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RoutersClusterManager.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helix/ZkRoutersClusterManagerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/StoreBackupVersionCleanupServiceStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreBackupVersionCleanupService.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterResourceType.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceVersionFinder.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/OutboundHttpWrapperHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/RouterRequestHttpHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/CurrentVersionRequest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/OutboundHttpWrapperHandlerTest.java
Venice backup version deletion currently oblivious to the state of version being served by the router. If due to some issues router did not switch to the latest version, the controller might delete versions which are being read, which would cause catastrophic failures of client requests.  
This PR validates 
1. The current version state from every router and every server before proceeding to delete the version.  A new router end point is added to server the in memory current version by that router.
2.  A new server metadata fetch endpoint added to query the current version for every server.
TODO: make all version deletion in controller async, ie early delete backup version and repush deleting current version after push completion to go through this `StoreBackupVersionCleanupService` .
CI …
> [controller][router] Safe backup version deletion

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DisabledPartitionEnablerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDisabledPartitionEnablerService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
Venice disables a leader replica during future version ingestion error for Helix to elect a new leader replica. But that could create deployment issue when many partition with disabled replica becomes online as the disabled partition stay in OFFLINE state. This PR adds a periodic refresh service to reenable disabled replicas on every cluster's servers in child controller. This a best effort as re-enabling does not guarantee its successful transition back to LEADER. 
The config to enable this feature `"controller.renable.disabled.replica.enabled"`
> [controller] Add disabled replica cleanup service

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumerTest.java
waitAfterUnsubscribe was introduced to make a best effort in moving records from the SharedConsumer into the drainer queue for unsubscribe and it has a timeout value. This change adds a warning log to track if any timed out event can actually happen.
Passed CI.
Example:
```
2023-12-19 07:57:23 INFO [SharedKafkaConsumer] [Test worker] Shared consumer SharedKafkaConsumer unsubscribed 1 partition(s): ([Mock for PubSubTopicPartition, hashCode: 312353788]) in 0 ms
2023-12-19 07:57:24 WARN [SharedKafkaConsumer] [Test worker] Wait for poll request after unsubscribe topic partition(s) ([Mock for PubSubTopicPartition, hashCode: 312353788]) timed out after 1 seconds
```
> [da-vinci] Add a logline when waitAfterUnsubscribe timed out

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDisabledPartitionEnablerService.java
Maybe it doesn't worth a PR but we'd like to know whether targeted reigon push can work with repush and turned out our integ tests don't have that.
So, this PR adds this part so we can ensure this compatibility doesn't break.
Also tried to fix a flaky unit test..
GHCI.
> [test] Use targeted region push in conjunction with repush

- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
> [vpj][controller][server] Change log level from INFO to DEBUG in VW::endSegment to reduce spamming

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/VeniceVersionedStatsReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceDispatcher.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/AggRouterHttpRequestStats.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
- services/venice-router/src/test/java/com/linkedin/venice/router/AggRouterHttpRequestStatsTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/VeniceRequestEarlyTerminationException.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggVersionedDIVStatsTest.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/VersionedDIVStatsReporterTest.java
Add server current version metric + added logging when server gets error request for easier debugging.
GHCI
> [server][da-vinci-client] Add server current version metric and other changes

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStuckConsumerRepair.java
This change aims to stabilize the flaky test 'testStuckConsumerRepair' with the following modifications:
1. Reduce the number of servers in cluster from 2 to 1.
2. Avoid pushing the 2nd data version as it will achieve the same testing purpose.
Internal CI.
> [test] Stabilize the flaky test 'testStuckConsumerRepair'

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- internal/venice-common/src/test/java/com/linkedin/venice/acl/StoreAclHandlerTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceVersionFinder.java
StoreAclHandler was trying to get the Store object for a is system store check. This step was before the VeniceVersionFinder and VenicePathParser which is where we perform the redirect for migrated store.
Modified the StoreAclHandler to check system store by name without accessing the Store object. Alternatively we could add a new SimpleChannelInboundHandler to perform the check as early as possible in the pipeline. However that would involve a lot of change since the 301 response is currently built as part of the ScatterGatherHelper. Other requests like metadata does not support redirect so it's a bit of an overkill to do that.
> [common][router] Fixed redirect request for migrated store

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
Currently, there are some codepaths that lead to parent controller updating the current version. Another unexpected code path that gets triggered in parent controller is `RealTimeTopicSwitcher#transmitVersionSwapMessage`. Since this piece wasn't written with the intention of getting executed in parent controller, it causes failures in executing tasks from the admin channel. This causes the Admin channel to get stuck for this store.
This commit adds checks that prevent the current version in parent controller to be updated.
CI
> [controller] Parent controller should not update the current version

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
In PR #862, we prevented parent controllers from updating the current version in Zk. However, we added a provision to allow the current version to still be updated by operators in a restricted mode. However, this custom upgrade doesn't work as it too gets skipped due to certain conditional checks. This commit fixes that issue.
GH CI
> [controller] Parent controller allows updating the current version in a special UpdateStore call

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/metrics/MetricsRepositoryUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- services/venice-router/src/test/java/com/linkedin/venice/router/RouteHttpRequestStatsTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/stats/AdminOperationsStatsTest.java
Bump up the tehuti dep to pick up the latest AsyncGauge execution optimization.
CI
> [all] Bumped up the tehuti dep to pick up the latest release

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractInputRecordProcessor.java
Currently VPJ either builds a dictionary or fetches it from various sources to optimize the compression ratios. However, this logic seemed a bit confusing and there was scope to streamline the implementation. This commit splits `VenicePushJob#getCompressionDictionary()` into two functions - `VenicePushJob#getCompressionDictionary()` and `VenicePushJob#fetchOrBuildCompressionDictionary()`. `VenicePushJob#fetchOrBuildCompressionDictionary()` handles the logic of how to get the compression dictionary based on various store and job properties, and `VenicePushJob#getCompressionDictionary()` unifies the error handling and fallback to synthetic dictionaries if the compression strategy is `ZSTD_WITH_DICT`.
The case where `use.mapper.to.build.dictionary` is `false`, and dictionary build fails, …
> [vpj] Cleanup dictionary fetching logic from various sources

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
The nuage page shows the version status from parent colo. For killed pushes, the status was not updated on the nuage leading users to think it was successful. This PR update the status for killjob on parent colo. Also fixes list_backup_version admin path.
CI
> [controller] Update parent colo version status on killjob

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
> [Server] Keep producerStateMaxAgeMs unchanged if time-based clearing of expired DIV state is disabled

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
Topic partition ingestion context query is for debugging purpose, it will not access user' store's content, so it should not need the ACL check. 
Resolves #XXX
CI
> [admin-tool][server] Skip ACL checking for topic partition ingestion context query from admin tool for server host

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/config/DaVinciConfigTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/RecordTransformerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/TestAvroRecordTransformer.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/TestStringRecordTransformer.java
- docs/user_guide/read_api/da_vinci_client.md
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestRecordTransformer.java
1. Added the `Experimental` annotation to `DaVinciRecordTransformer`, since it's still in its experimental stage.
2. Added back key as a parameter to the `put` function in `DaVinciRecordTransformer` in case if the user wants to utilize it for transformation. Updated the documentation to reflect this, which is viewable [here](https://kvargha.com/venice/docs/user_guide/read_api/da_vinci_client).
CI
> [dvc] Add experimental annotation to DaVinciRecordTransformer, and add back the key parameter to put

- docs/README.md
added link to contributors guide to README.md
N/A
> [doc] Added link to contributor's guide

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
Store migration's end migration command assumes /store returns null for non-existing store. However, it actually throws exception instead and is not handled properly which causes confusion for the user.
existing unit and integration tests
> [admin-tool] Fixed mishandling of get store response in store migration

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
Without VT offset, it's difficult to find the right offset to dump VT for troubleshooting.
CI
> [server][da-vinci] Log VersionTopic offset when logging lossy rewind error

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
Do not allow target region push for deferred version swap and hybrid stores. Since hybrid store uses repush which allow concurrent pushes, this PR disable target region push for such cases.
GHCI
> [vpj] Do not enable target region push for deferred version swap stores

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
During batch pushes controller queries all child controller to fetch store config to validate the deferred version swap flag. This could be flaky if the some colo fails to respond in timely manner (it does 5 retries). Since the parent colo has the required store config, this PR checks only that instead of doing a expensive remote call to the child controller.
GHCI
> [controller] Check only parent colo store defered swap config

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
> [controller] CI build fix

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-CompatibilityTests.yml
- .github/workflows/VeniceCI-E2ETests.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
- .github/workflows/build-and-upload-archives-on-demand.yml
- .github/workflows/build-and-upload-archives-on-schedule.yml
- .github/workflows/build-and-upload-archives-upon-pushing-tags.yml
- .github/workflows/build-and-upload-archives.yml
- .github/workflows/publish-javadoc.yml
- build.gradle
Our javadoc publish workflow is broken because Github updated the default git version and some commands/workflows are no longer working.
This PR updates some out-of-dated Github Action versions
CI
https://github.com/adamxchen/venice/actions/runs/9276409190/job/25523408597
> [CI] Update some Github Action versions

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
In VHA::deleteOneStoreVersion, there is a bug that trying to get the push status after the push monitor is stopped. It is introduced in PR d7997d782. This PR fixes the issue by calling hasFatalDataValidationError before stopMonitorOfflinePush.
Passed CI
> [controller] Fix a bug in deleteOneStoreVersion

- make_tag.py
> Revert "[build] Bump minor version when patch versions reach 100"

- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/BlobTransferManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/P2PBlobTransferManager.java
Originally I was thinking we always find the current version in the rocksdb directory or have the version included in the `storeName` such as `myTest_v2`. I changed my mind now since we may support backup version in the future and I don't want to bring many dependencies to the blob manager just for finding out what's the current version so it's better to include this in the method signature.
N/A
> [common] Add version signature to the blob manager interface

- docs/dev_guide/how_to/workspace_setup.md
I updated the Venice Workspace Setup page on the open-source docs with information that I wish I knew when I first got started. This should make it easier for external contributors to get setup.
N/A
> [doc] Update open-source docs to make getting started easier

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
When target region push is enabled, after pushing to the target region, rest of the regions do not delete the backup version before the start of the push. This increases the disk usage during the duration of the push to 3x of the store size (backup + current + future versions).  This PR deletes the backup version before starting ingestion in non-target regions.
integ test.
> [controller] Delete backup version before start of new push in target regions

- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
Today, Controller would check push status system store partition by partition in the following way:
1. Iterate the partition by partition, and get all the subscribed DaVinci instances per partition.
2. Check whether instance partition status is completed or not.
3. If not, check the liveness of the instance to decide whether the status should be ignored or not.
If one DaVinci store is being used in unpartitioned way, the total number of calls to push status system store for liveness check will be partition_num * host_num, which will be a very high number, which would timeout the Controller status polling request for inc push, which is still doing real-time status check against push status system store.
With this change, Controller will skip the duplicate liveness calls, so that the total …
> [controller] Improved the perf of DaVinci push status polling for inc push

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
If users set deferred version swap for a push, they could decide to swap the current version at much later time than 24hr of push timeout. Starting next push after 24hr would cause the previously pushed version to be killed even though the push has finished successfully. This PR fixes that by failing new pushes till the previously pushed version is swapped to current version.
integ test.
> [controller] Check deferred version swap flag before lingering push

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
Changed a parameter to allow for blob transfer testing
Created a jar
> [config] Changed parameter to allow for blob transfer

- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
Modified an integration test to account for DaVinci blob transfer
Ran the test and it worked as expected
> [admin-tool]Modified integration test for blob-transfer

- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreBackupVersionCleanupService.java
If there are still leaking versions due to consecutive repush and intermittent failed push, there could be versions with repushSourceVersion which does not match the current version. This PR will delete those versions after backup retention period.
CI
> [controller] Delete leaking backup versions from repush

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
Fixed a bug in DaVinci bootstrapping mode
CI
> [da-vinci]Fixed a bug in DaVinci bootstrapping mode

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
The flaky test make assertions based on the --migration-status admin command which also polls the child fabrics for migration status. e.g. store existence and migration flags. However, the endMigration call only checks and waits on the parent controller's state to be reflected. Therefore there is a race where the --migration-status can be executed while the child controller is still processing the end migration. Assertion will fail when such race happens.
integration tests, test only change.
> [test] Fix store migration test flakiness

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
Do not print key/value info as they could contain PII.
CI
> [thin-client] Do not print key/value info in log

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/D2ControllerClient.java
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/TestD2ControllerClient.java
- `D2ControllerClient` - In future iterations, there could be local ZooKeeper instances in each region so we want to add support to iterate through all D2Clients to find the leader parent controller.
- Added new constructors to accept `List<D2Client> d2Clients` or `List<String> d2ZkHosts`
- Updated `discoverLeaderController` and `discoverCluster` to iterate through the list of `D2Client`
- Tested constructors and implementation of methods above in `TestD2ControllerClient`
Unit Tests
> [vpj][server][samza][admin-tool][controller] Added parent controller discovery through multiple D2 clients

- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/DaVinciUserApp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
This PR does not yet resolved all the issues regarding the integration test for Blob Transfers, however it sets up the environment to accurately test blob transfers. Validations have not yet been added to the test.
Github IC
> [da-vinci][test]Modified Integration Test for DVC Blob Transfer

- internal/venice-common/build.gradle
Pull in jacksonCore into venice-common which should be reflected in all modules.
> [controller][router][server][da-vinci] Pull jacksonCore into venice-common

- docs/README.md
- docs/user_guide/learn_more.md
Updating the docs by adding some 2024 links, especially the podcast interview with The Geek Narrator and the QCon talk.
> [doc] Add 2024 Video Links

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
This reverts commit c9304b2c0ac4d61904298d4d66a0eb7dc9b48bbe.
Tested in prod-ltx1 venice-5 routers.
> [fast-client][router] Revert "[fast-client][router] Fixed one slow start issue (#1125)"

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionBatchProcessor.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/IngestionBatchProcessorTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceStats.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/AbstractVeniceStatsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
This PR added the following metrics:
Host/store-version level:
batch_processing_request
batch_processing_request_size
batch_processing_request_records
batch_processing_request_latency
batch_processing_request_error
Host/Store level:
leader_produce_latency
CI
> [server] Added metrics to track batch processing perf 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
This reverts commit 262101c6968abbd47b5d2ea28e4eb9e0c4784778.
> Revert "[common][server][dvc-client] Make a true non-blocking end-offset fetcher

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
> [server] tweak heartbeat reporting to use completion check

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestPushJobStatusStats.java
Emit logs for push job status whenever push job metrics are emitted
GH CI
> [controller] add logs for push job status

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
Besides, change the tasks list to a private member variable to help with heapdump analysis.
Github CI
> [Controller] Added loggings for admin messages processing

- .github/workflows/UnitTests-core.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
Refactor Unit Tests suites to have better visibility of the tests being run in different top level modules.  Added bonus it cuts total UT/CodeCov runtime by ~10mins due to more parallelism.
GHCI
> Refactor Unit Test Suites

- docs/user_guide/learn_more.md
> [docs] Updated the Learn More page with the latest conference talks

- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/GzipCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/NoopCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/VeniceCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compression/TestVeniceCompressor.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerReadQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
This PR includes two changes:
https://github.com/linkedin/venice/pull/1312
https://github.com/linkedin/venice/pull/1307
CI
> Hotfix 0.4.348

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
Disabled info logging for duplicate records
CI
> [server][da-vinci]Disabled info logging for duplicate records

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
Disabled info logging for duplicate records
Resolves #XXX
CI
> [server][da-vinci]Disabled info logging for duplicate records (#1315)

- .github/workflows/UnitTests-core.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
It should improve visibility of the unit test jobs tab.
GHCI
> Shorten Unit Test Job Names

- .github/workflows/UnitTests-core.yml
> Publish unit test CI report

- build.gradle
change OpenTelemetry version to 1.33.0 
Existing tests
> [all] change OpenTelemetry version to 1.33.0 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/NettyP2PBlobTransferManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/BlobTransferStats.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/BlobP2PTransferAmongServersTest.java
This PR fixes the following:
1. Fix the flaky integration test.
integration test.
> [server][dvc] Fix flaky integration test BlobP2PTransferAmongServersTest

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-E2ETests.yml
Resolves #XXX
- [X ] No. You can skip the rest of this section.
> [build] Integrate BuildPulse for flaky test analysis

- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerReadQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/ServerReadQuotaUsageStatsTest.java
Hot fix applied on top of OSS 0.4.380
CI
> Hot fix: [server] Use thread safe map for versioned stats in SN read quota (#1415)

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatchForRocksDB.java
Previously, snapshot generation was controlled by a store-version-level config, _**Enable_blob_transfer**_, while bootstrap from blob transfer was controlled by a combination of server-level config **_Blob_transfer_manager_enable_** and store-version-level config **_Enable_blob_transfer_**.
During the rollout testing, we observed that enabling these two configs will cause: several production hosts, in addition to those intended testing hosts, will generate snapshots. This will occur because the store-version-level config is enabled, leading to snapshot generation on production hosts as well. However, our intent is to limit snapshot generation and bootstrap operations from blob transfer only to the testing hosts.
To fully isolate operations between testing and production hosts, we want to …
> [server][dvc] Restrict the conditions for snapshot generation used in blob transfer.

- .github/workflows/VeniceCI-CompatibilityTests.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
- build.gradle
- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/HelloWorldTest.java
- settings.gradle
Created a new integrations/venice-duckdb module, which is currently pretty barebones (just has the dependency and a unit test).
Miscellaneous build changes:
- The proto-related tasks are now only going to run in modules that have proto schemas defined.
- Also reshuffled the CI tasks a bit:
- There is a new Integrations bucket in the unit tests, which includes all of the unit tests coming from integrations/ (previously, samza and pulsar unit tests ran in the Clients bucket).
- The Alpini unit tests are moved to the Router bucket.
- Reduced repetitions and boilerplate throughout the CI files.
New unit test.
There is a new module which will henceforth be published (though as of this commit it will be empty).
> [duckdb] Hello World

- gradle/spotbugs/exclude.xml
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/HelloWorldTest.java
PR is itself a couple of tests.
> [test] Testing basic DuckDB functionality

- gradle/spotbugs/exclude.xml
- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBAvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/HelloWorldTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
> [duckdb] Avro to SQL UPSERT statement generation and processor

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
We would like to skip {@link com.linkedin.davinci.store.rocksdb.RocksDBSstFileWriter} for hybrid stores when RocksDB blob mode is enabled and here are the reasons:
1. Hybrid stores will use the same amount of MemTables eventually even not in batch processing phase.
2. SSTFileWriter + RocksDB blob mode will introduce additional space overhead in the following way: a. SSTFileWriter doesn't support RocksDB blob mode, which means even with blob enabled, SSTFileWriter will still write both key and value into the same SST file regardless of value size. b. When RocksDB ingests the generated SST files, it will put them in the bottom level. c. After finishing the batch portion, RocksDB won't use SSTFileWriter anymore and in the regular mode, when RocksDB blob mode is enabled, RocksDB will store …
> [server][da-vinci] Skip SSTFileWriter for hybrid store when RocksDB blob mode is on

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
Do not send heartbeat is VW is closed as it will spam the logs without adding a value.
GHCI
> [server] Do not send heartbeat is VW is closed

- .gitignore
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/BlockingDaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/RecordTransformerTest.java
- gradle/spotbugs/exclude.xml
- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/DuckDBDaVinciRecordTransformerTest.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
Create first implementation of DuckDB x DVRT
New integration test
> [duckdb] Create first implementation of DuckDB x DVRT

- all-modules/build.gradle
Excluding venice-duckdb as it's experimental and causes build issues
CI
> [duckdb] Exclude venice-duckdb from all modules

- all-modules/build.gradle
> [duckdb] Other attempt at excluding duckdb from all-modules

- build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
Undo duckdb snapshot as it is causing build failures.
CI
> [duckdb] Undo duckdb snapshot

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
> [server] fix npe in adaptive throttler code

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/AbstractStoreMetadata.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/HelixScatterGatherRoutingStrategy.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/InstanceHealthMonitor.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/InstanceHealthMonitorConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/LeastLoadedClientRoutingStrategy.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/HelixScatterGatherRoutingStrategyTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/InstanceHealthMonitorTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/LeastLoadedClientRoutingStrategyTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/utils/TestClientSimulator.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientGrpcServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/grpc/VeniceGrpcEndToEndTest.java
This PR is trying to improve the failure detection in Fast Client. In the past, Fast Client was relying on organic traffic to detect unhealthy nodes and once it detects some unhealthy nodes, it won't stop sending traffic to these nodes completely as it would try to use organic traffic to detect whether the unhealthy nodes are recovered or not, which could result in high latency issue.
This PR is trying to address two issues:
1. It is confirmed that httpclient5 lib doesn't provide an accurate request level timeout, so we will enforce a timeout in Fast Client by setting up a timer and the default timeout is 1s.
2. Failure detection logic will be as follows: 
<ol type="a">
<li>When the organic traffic encounters timing out, the corresponding backend instances will be put into the suspicious …
> [fast-client] Improved the failure detection

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HeartbeatMonitoringServiceStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerParticipantModelFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
Thread "Ingestion-Heartbeat-Reporter-Service-Thread" could exit due to unhandled exceptions, which leads to stopped HB threads. This PR handles such exceptions. 
GHCI
> [server] Handle exceptions in HB reporting threads

- .github/dependabot.yml
This is necessary because venice-duckdb depends on a snapshot version of duckdb which keeps getting deleted. This PR intends to automatically check/update the snapshot version for duckdb.
CI
> [build] Configure dependabot to automatically update duckdb snapshots

- .github/dependabot.yml
- all-modules/build.gradle
- build.gradle
- clients/da-vinci-client/build.gradle
- settings.gradle
Miscellaneous:
- Got rid of the build tech debt related to the previous dependency on a SNAPSHOT release.
- Moved the asm dependency from all sub-modules to DVC, which is the only module that actually uses it.
Resolves #XXX
> [duckdb] Bumped duckdb_jdbc to 1.2.0

- .github/dependabot.yml
> [build] Fixed dependabot syntax

- .github/workflows/limit-pr-files-changed.yml
Without fetching the commits, the command 'git diff --numstat origin/main'  will see the following error
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
GHCI
> Fetch commits to limit line changes in a PR

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/AbstractStoreAclHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/acl/RouterStoreAclHandlerTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStoreAclHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ServerStoreAclHandlerTest.java
Re-ordered some operations to minimize ACL handling overhead, based on profiling.
> [router][server] ACL handler efficiency improvement

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformerUtility.java
The logging doesn't match up with the logic, so I swapped them.
CI
> [dvc] Fix logging in DVRT

- build.gradle
Bumped up pulsar and jackson dependencies.
The new command: `./gradlew allDeps` will show the dependencies for all the subprojects.
NA
> [all] Bumped up pulsar and jackson dependencies

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
Adding a test timeout for deferred version swap test
Existing tests
> [controller] Add test timeout for deferred version swap test

- internal/venice-common/src/main/resources/avro/GlobalRtDivState/v1/GlobalRtDivState.avsc
Avro `.avsc` schema changes split from #1385.
N/A
> [compat] Global RT DIV: Schema Changes

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Remove SystemSchemaInitializationRoutine for store properties in order to temporarily fix the schema parsing issue located in `AvroProtocolDefinition.SERVER_STORE_PROPERTIES_RESPONSE`. This section will be re-added to `initRoutines` once a long term fix is determined.
Tests will be written when this section is re added.
> remove SystemSchemaInitializationRoutine for store properties.

- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/ssl/SslInitializer.java
- internal/alpini/netty4/alpini-netty4-base/src/test/java/com/linkedin/alpini/netty4/ssl/TestSslLogging.java
Besides, use error level logging when handshake fails.
Github CI
> [router] Added failed cause into the logs when ssl handshake fails

- .github/workflows/limit-pr-files-changed.yml
Skip test-common files in PR validation as they are part of test code even if under `src/main` path.
CI
> Skip test-common files in PR validation

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Some implementations of PubSubAdminAdapter may retry multiple times to get/update topic's config in order to truncate it. Because of this, `truncateKafkaTopic` may take long enough time to make `delete store` operation time out. Therefore, we need to check for the existence of RT topic before trying to truncate it. No known implementation of PubSubAdminAdapter does retries for `containsTopic`, so that should not increase the risk of timing out.
Resolves #XXX
> [controller] check rt topic existence before trying to truncate it

- build.gradle
Upgrade Opentelemetry version to 1.47.0
GH CI
> [all] Upgrade Opentelemetry from 1.33.0 to 1.47.0

- build.gradle
Revert [PR 1600](https://github.com/linkedin/venice/pull/1600)
GH CI
> [all] Revert Opentelemetry from 1.47.0 to 1.33.0

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Retry controller leadership check in data recovery as other admin endpoints are retriable, but the datarecovery is used in target colo push and not retried, so during controller leadership change it could fail the entire push job.
CI
> [controller] Retry controller leadership check in data recovery

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/StoreBackendTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/AbstractStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestZKStore.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
1) `createNewVersion` flag is always `false` in the code, so removing it
2) `peekNextVersion` in Admin has no caller
3) All callers of `Store.peekNextVersion()` want version number, not version
Resolves #XXX
> [controller] remove unnecessary code

- .github/pull_request_template.md
Revise PR Template to Strengthen Code Quality and Thread Safety Checks
It will looks like this
> Update PR coding guideline template

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
In production, we found that servers had been querying PubSub offsets from an completely unintended region in some cases. This is pretty gnarly and can lead to data-loss.
We found a concurrency issue in `KafkaStoreIngestionService` where the shared server config object would be replaced by temporarily created configs for different regions. The expectation of this code was to only create this object for local use.
> [server] Fix multi-threading bug in shared multi-region PubSub configs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AdaptiveThrottlingServiceStats.java
Add limiter signals for AAWC ingestion throttlers.
CI
> [server] Add limiting signal to adaptive throttelr for AAWC workload

- .github/pull_request_template.md
- .github/workflows/limit-pr-files-changed.yml
PR commit change check should run only against main branch, otherwise hotfix releases might fail.
This PR ignore the workflow for non-main branch.
> [build] Make line check run only on main branch

- services/venice-router/src/main/java/com/linkedin/venice/router/streaming/VeniceChunkedResponse.java
Based on a deep investigation of this issue with a debug version of Netty (manually add more debug logs), I finally figured out with H2 enabled, the Netty version Router is using doesn't provide a right progress, which triggered the following behavior:
1. Router will release chunks aggressively while the response sent is progressing.
2. The underlying H2 channel handler is still in the middle of consuming the chunks.
3. Race condition would happen since the progress is not fully accurate, which causes a byte ref cnt issue. Here is the exception we observed:
io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1489) ~[io.netty.netty-all-4.1.52.Final.jar:4.1.52.Final]
at …
> [routee] Fixed Router H2

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/RequestBasedMetaRepository.java
Introducing the RouterBasedSchemaReader has resolved schema compatibility issues; however it has introduced dependency between the controller and dvc.
In order to alleviate this dependency in most cases where the server and dvc are running on the same version of the protocol, we can simply use the locally known schemas to deserialize the payload.
> [dvc] add a check to see if schemas are available locally before querying in RBMD 

- build.gradle
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/AbstractStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Version.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ZKStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDaVinciRequestBasedMetaRepository.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/UserSystemStoreLifeCycleHelper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
If child controller fails to add version, there may be inconsistency between local RT version numbers of child controllers
In this PR parent controller will pass RT version number in addVersion admin command and child controllers are not going to use the local copy of that.
In https://github.com/linkedin/venice/pull/1616 I introduced a new field `largestUsedRTVersionNumber` and `currentRTVersionNumber` in admin tool commands. In this PR, I am using them.
> [controller] use largestUsedRTVersionNumber in addVersion and updateStore commands

- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
The logs in DeferredVersionSwapService log every minute and they are frequent and noisy
Change log level to debug and have logs print once every 10 minutes
Existing tests
> [controller] Add rate limiter to logs in DeferredVersionSwapService

- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReader.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
Excessive logging for stores with many DVC instances ingestion.
Skip such instance level logs.
> [controller] Trim controller logs for DVC instance push status

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- docs/dev_guide/how_to/style_guide.md
In a profiling, we noticed that the SIT's run loop (background thread) was spending a somewhat large % of CPU on checkIngestionProgress(). This commit attempts to reduce the overhead. It should be minor overall but probably can't hurt.
> [dvc][server] Minor optimization to SIT background thread

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- Reduced the number of maps and lookups per partition of a poll.
- Eliminated unnecessary string-parsing function call.
- Fixed mem leak due to missing cleanup in removeDataReceiver().
> [dvc][server] Cleaned up metrics code in ConsumptionTask

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
New semantic usage detector when we set a non-null value as a default for nullable field `largestUsedRTVersionNumber`. 
In this PR, I am changing it to null when it is not provided in `updateStore` admin command
> [controller] set null to nullable field largestUsedRTVersionNumber when it is absent in updateStore command

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
After batch store unsubscription, SIT still runs in full force wasting CPU cycles, while it just needs to handle any consumer action if needed. 
This fixes that by skipping most of the tasks if batch sub is completed.
> [server] Skip Idle SIT tasks after the batch unsubscription

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairServiceTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairTaskTest.java
In previous config rollout we found many problems in different cluster, this will create a lot of noise and hard to investigate.  This PR change the config knob to be per-cluster, so we can enable this feature cluster-by-cluster.
> [controller] Control system store auto-repair service in cluster level

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- gradle/spotbugs/exclude.xml
> [consumer] Fixed NPE in ChangelogClientConfig

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestBootstrappingChangelogConsumer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
- services/venice-controller/src/test/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcherTest.java
Version swap emission is not backwards compatbile with older CDC clients.
Make version swap emission configurable.
> [controller] Make version swap emission configurable

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/DiskHealthCheckService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/DiskHealthCheckServiceTest.java
In case when disk health check fails due to seeing a stale status update, the logs only contain:
```
Disk is not healthy according to the disk health check service: null
```
This does not provide enough information about the issue
This commit adds a reasonable error message in this case.
To avoid running into this issue again, this commit also changes the error tracking to always require an error message when marking the disk health as unhealthy. It also ensures to clean up the error message when the disk is marked healthy.
GH CI will run tests
> [server][dvc] Improve disk healthcheck error reporting

- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
- build.gradle
- Added a GitHub Actions step to annotate pull requests with SpotBugs findings  
using the spotbugs-github-action plugin.  
- Updated `build.gradle` to support generating both XML and HTML reports when  
`-Pspotbugs.reports.all` is specified.
This improves static analysis visibility directly in the PR UI.  
Tested on fork: https://github.com/sushantmane/venice/pull/24/files
> [build][ci] Enable SpotBugs annotations on PR via GitHub Actions

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
Recently, we cleaned up the code for the dedicated MR job to build a dictionary, but this code piece was left over
Deleted dead code
N/A
> [vpj] Cleanup left-over dead code in VPJ

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestInstanceRemovable.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/InstanceStatusDecider.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/NodeRemovableResult.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/NodesAndReplicas.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestInstanceStatusDecider.java
Today, in Helix's aggregated stoppable check call (`/aggregatedHealthStatus`), the response when removal is blocked only contains enums like `WILL_LOSE_DATA` or `WILL_TRIGGER_LOAD_REBALANCE`. This does not include any details about the actual resource that is blocking the removal making the engineer go through additional hoops to get that information. 
This change adds the a detailed reason for preventing the removal of a node to the response message
Since this is mostly a logging or string content change, this was tested manually, and GH CI will run regression tests
> [controller] Report detailed reason for failing an instance's stoppability request

- docs/quickstart/quickstart-single-datacenter.md
There's a discrepancy between the documented schemas in the Venice single-datacenter quickstart guide and the actual schema files at `/opt/venice/sample-data/schema/keySchema.avsc` and `/opt/venice/sample-data/schema/valueSchema.avsc` within the Venice client container.
The documentation shows key schema with `"name": "id"` and value schema with `"name": "name"`, while the actual schema files define `"name": "key"` and `"name": "value"` respectively. This inconsistency can confuse users following the quickstart tutorial.
Updated the documentation in `docs/quickstart/quickstart-single-datacenter.md` to match the actual schema definitions found in the sample files. This ensures users following the quickstart guide have accurate information about the schemas being used.
Both reviewer and PR …
> [doc] Fix schema examples in single-datacenter quickstart

- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
Possible fix for "HttpError: Resource not accessible by integration" error when the
StaticAnalysis job attempts to annotate PRs with SpotBugs results.
Adds explicit permissions to allow writing checks, pull request comments,
and accessing issues when triggered by workflows with limited default token
scopes (e.g., pull_request or pull_request_target events).
> [build][ci] Grant required permissions to StaticAnalysis job

- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerReadMetadataRepository.java
Current implementation of cloneStoreProperties does not work with store versions with the dataRecoveryConfig set due to a bad type conversion. This PR is to resolve this and add test coverage to that field.
Remove type casting and replace with a helper function to convert DataRecoveryConfig to DataRecoveryVersionConfig
Unit test cases now set this field so the conversion step is not skipped.
> [server] fix clone store properties data recovery config conversion

- integrations/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
`pipelineV2` is required in D2 Client to talk H2 to the backend.
In the future, we should construct a D2Client from the internal factory, where we can manage all the D2 configs in a centralized fashion.
Enabled pipelineV2 for now and in the future, using the centralized factory to create the d2 client in samza producer.
> [venice-samza] Enabled pipelineV2 for the d2 client being used in samza producer

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AdaptiveThrottlerSignalService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AdaptiveThrottlerSignalServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
Currently not all subscription management for various pools are not controlled by adaptive throttler.
This PR adds throttler for various consumer pools. Also adds heart-beat signals to limit ingestions when lag is high.
> [controller] Setup adaptive throttler for all consumer pool types

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputUtils.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputUtilsTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/ApacheKafkaUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/DictionaryUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/ApacheKafkaUtilsTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfigTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/EndToEndKafkaWithSASLTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Refactored Kafka client configuration to move SASL-related property extraction to the  
adapter layer. This removes duplication across consumer, producer, and admin config  
classes and centralizes logic in ApacheKafkaUtils.  
Introduced getValidKafkaClientProperties to validate and extract supported Kafka  
client properties, including required SSL fields when applicable. Replaced scattered  
per-client logic with a unified method call, improving maintainability and consistency.  
Also removed redundant utility methods and enforced stricter validation on SSL and  
SASL-related configuration to catch misconfigurations early.  
> 
> This pull request refactors Kafka configuration handling across the codebase to improve modularity, reduce redundancy, and enhance maintainability. The most …
> [controller][server][vpj][dvc][producer][cc] Extract Kafka SASL config handling into adapter layer for reuse and consistency 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
[dvc][consumer] Fix NPE when PartitionConsumptionState is Null in SYNC_OFFSET command
- When we gracefully shutdown server, we tried to async the offset to disk. However, at that point, PCS can be null, resulting to NPE when trying to`updateOffsetMetadataAndSyncOffset`. 
For the `SYNC_OFFSET` command, if the PCS is null, we will mark the command to complete and shutdown the server as normal.
> [dvc][consumer] Fix NPE when PartitionConsumptionState is Null in SYNC_OFFSET command

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
During `getLatestOffset` call if the Kafka client throw different errors eg, DNS resolution error, it gets thrown to the store buffer service which then process the exception and make the push fail. 
This PR retries all exception for `getLatestOffset` call.
- [x ] Code has **no race conditions** or **thread safety issues**.
> [server][dvc] Allow all exceptions from getLatestOffset to be retried

- internal/venice-common/src/main/java/com/linkedin/venice/meta/VersionStatus.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DeferredVersionSwapStats.java
1. When a push job is killed, it takes some time for the push to be marked as complete after the parent version status is marked as KILLED. This gap causes the DeferredVersionSwapService to roll forward in the non target regions because it thinks the push is complete when the version status is marked as KILLED, but in reality, it isn't complete yet in all target regions yet because we only check for ERROR status before allowing it to proceed.
1. Wait for all target regions to reach either `COMPLETED` or `ERROR` status before trying to roll forward in non target regions
2. Add in a metric for failed roll forward calls & mark the version status as `PARTIALLY_ONLINE` if it fails for any reason
Existing tests
> [controller] Add metric for failed roll forward & wait for push completion in all target regions

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-E2ETests.yml
> Updated buildpulse account for Li GH

- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
These should not be null as they are required for store create, but a safety check is good practice.
Add safety check for nullable fields even though they are required.
> [server] add safety checks for clone store properties fields

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionNotificationDispatcher.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/IngestionNotificationDispatcherTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
During ingestion, if after EOP server or DVC instance hits any error, it will not be reported as an error to the controller. The controller then waits for 24hrs limit to mark the push as failed blocking further pushes.
This PR reports error for such failed pushes even if EOP is received for batch stores.
- [] Confirmed if logs need to be **rate limited** to avoid excessive logging.
> [server] Report ingestion error to controller for batch stores

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Version.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestVersion.java
When DVC store injection fails on disk full, we fail to report it as a specific error indicating the real problem, resulting in error reporting to classify it as a generic error.
By checking for the specific error message, we can throw a `DiskLimitExhaustedException` which will be classified as a `DVC_INGESTION_ERROR_DISK_FULL`.
Exceptions are classified here: https://github.com/linkedin/venice/blob/757e95956d85d21a027c022e765ef850dd73c46f/clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java#L844
> [dvc] add specific errors on store injestion failure for disk full

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHybridStoreRepartitioningWithMultiDataCenter.java
Breaking a big test into multiple smaller ones that run sequentially. This will help in debugging.
> [test] break a big test into smaller ones

- build.gradle
We are observing a high space amplification in one of the heavy use cases and we would like to evaluate whether the latest BlobDB related optimizations can improve that or not.
Picked up the additional tuning of BlobDB, which is available since 9.7.0:
Changed the semantics of the BlobDB configuration option blob_garbage_collection_force_threshold to define a threshold for the overall garbage ratio of all blob files currently eligible for garbage collection (according
to blob_garbage_collection_age_cutoff). This can provide better control over space amplification at the cost
of slightly higher write amplification.
> [server][da-vinci] Bumped up rocksdb-9.10.0

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepository.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntity.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityState.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityStateBase.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityStateGeneric.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityStateOneEnum.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityStateThreeEnums.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityStateTwoEnums.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepositoryTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateGenericTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateOneEnumTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateThreeEnumTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateTwoEnumTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
Existing subclasses of `MetricEntityState` are for specific cases with specific number of dimensions which should be enums that are perf and GC optimized by reusing `Attributes` rather than recreate it everytime. But for cases like controllers where the metric emission is infrequent and is not processing tens of thousands or more of QPS, it would benefit to have a generic non cached version of a subclass rather than creating multiple new subclasses for all combination of dimensions.
1. Introduce `MetricEntityStateGeneric` which takes in `baseDimensionsMap` during init and all remaining dimensions as a `Map` during `record()` call where it validates the data for all required dimensions. This can be reused for most of the metrics in controllers. This will also help in code maintainability …
> [router] Add MetricEntityStateGeneric for flexible dimension handling for OTel

- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
Today, when hitting 429/503 responses in Fast Client, the latency will go beyond 1s.
HttpClient5 has a feature: auto retry and check this class to find more details: {@link org.apache.hc.client5.http.impl.DefaultHttpRequestRetryStrategy} This feature is enabled by default, when this feature is enabled, upon 429/503 responses, it will introduce a delay of 1s (default), and retry, which means the user of this lib: Fast-Client and Router will observe
>1s latency, which is unexpected.
This PR disables this feature to avoid the above behavior. Whether retry upon these error response or not will be decided by the user instead of the transporting layer.
> [fast-client][router] Disable auto retry in httpclient5 to avoid delay upon 429/503 response

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-E2ETests.yml
Update artifact packaging to include core.* and hs_err_pid*.log files generated during  
E2E test failures for easier troubleshooting. 
> [build] Upload core dumps and JVM crash logs from E2E test runs

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-E2ETests.yml
This pull request updates the artifact generation process in CI workflows to enhance logging by appending the names of compressed files to the artifact list. The changes ensure better traceability of generated artifacts during the CI process.
Changes to CI workflows:
* [`.github/rawWorkflows/gh-ci-parameterized-flow.txt`](diffhunk://#diff-848536c444d2d2c0dcc4df7a1f538522f5cacf0353f181dd77680b0cfe1fe00aL50-R50): Modified the `find` command to include an additional `-exec echo "{}.xz"` step, appending the names of compressed files to the artifact list.
* [`.github/workflows/VeniceCI-E2ETests.yml`](diffhunk://#diff-f9e1d410d81b4ceb4ff1f674ae236cbda5ae9cc36f34dcfb4e53e43448e723a8L63-R63): Applied the same modification to multiple sections of the file, ensuring consistency across all jobs in …
> [build] Fix JVM core file upload path in GHA

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
Trying to fix a potential rocksDB core dump
Add safeguards for rocksdb property call
> [server] Add safeguards for rocksdb property call

- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoresRoutesTest.java
Right now we pick isRealTimeTopicVersioningEnabled based on common configs, which force us to set same value for all the clusters and prevent us to do a cluster-wise rollout of RT versioning
As a solution, now we would pick this config from cluster-specific config object. Also to avoid inconsistency, we will prohibit store migration from a cluster where RT versioning is enabled/disabled to a cluster where it is disabled/enabled.
> [controller] provide option to enable/disable RT versioning based on cluster

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/BackfillMinIsrTask.java
Some topics can have incorrect min isr values set because they haven't had a push in a long time or if they have a rt topic that was created before the min isr value was updated
Add in a new task, `BackfillMinIsrTask`, to `clusterBatchTask` in the admin tool in order to bulk update the min isr value to `KAFKA_MIN_IN_SYNC_REPLICAS` for the vt and `KAFKA_MIN_IN_SYNC_REPLICAS_RT_TOPICS` for the rt topics.
Existing tests
> [admin-tool] Add new task to clusterBatchTask to update min isr

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/BackfillMinIsrTask.java
We are using `store.getLargestVersionNumber()` to get the version topic to update the min isr value for, but that can be inaccurate if there is a future push happening
Use `store.getCurrentVersion()` instead to get the current serving version
Tested using admin tool locally
> [admin-tool] Use current version when updating vt min isr

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceMetricsConfig.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceMetricsConfigTest.java
Adding a setter for otel headers which the clients can use.
> Add a setter for otel headers

- internal/venice-common/src/main/resources/avro/PartitionState/v17/PartitionState.avsc
Patch the new v17 PartitionState schema to have another field: "heartbeatTimestamp".
It is to store previously checkedpointed most stale timestamp among all the regions for this partitions.
This field will be used for fast server restart when using heartbeat lag to determine ready to serve case.
> [protocol] Add heartbeatTimestamp field in latest(v17) PartitionState protocol change

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
Lack of units in the update-store storage-quota option can cause confusion when setting the parameter. 
Adding the unit of measure to the update-store storage-quota option to avoid confusion.
> add units to admin command update-store storage quota help desc

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/MetaSystemStoreTest.java
Integration test flaky due to multi push jobs being requested.
Add a `waitForNonDeterministicPushCompletion` after initial push job so there is no overlap in push requests.
> [test][dvc] fix flaky thin client based metadata test

- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/SQLUtils.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/SQLUtilsTest.java
DuckDB DVRT doesn't support table or column names with special characters, such as hyphens in the store name.
To solve this problem, we escape them.
PS: Prepared statements automatically escape variables for us.
> [dvc] Escape table and column names for DuckDB DVRT

- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
Any internal system in LinkedIn is only able to measure QPS when the metric is of type Count. But the only metric we offer today in our router to measure is an OccurenceRate.
To solve this issue, I created a separate metric to measure router QPS using the sensor type Count.
> [router] Create a router QPS sensor of type count

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/StoreMetadataRecoveryTest.java
TestUtils.getUniqueTopicString should be used to create topic names in a particular way.
It was being used to create stores, not topics, in test `testStoreMetadataRecoveryAfterDeletion` , which was making store name ending with "_rt" sometimes, which is not allowed and failing the test
stores should be created using Utils.getUniqueString
> [test] Create stores with randomized name in StoreMetadataRecoveryTest

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
Currently key count and duplicate key counts are emitted only total metric which is not helpful to deletecting per store usage.
This PR emits duplicate key count metric per stores as well as total
> [server] Emit duplicate key count metric per stores as well as total

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/factory/CachingDaVinciClientFactory.java
- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/DaVinciUserApp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/ActiveActiveReplicationForHybridTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientDiskFullTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClusterAgnosticTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciLiveUpdateSuppressionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatchReportIncrementalPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDaVinciRequestBasedMetaRepository.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMaterializedViewEndToEnd.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientDaVinciClientCompatTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/DaVinciTestContext.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestBlobDiscovery.java
Adding pubsub clients configs to CachingDaVinciClientFactory in tests, so that DaVinciClient can connect to all the pubsub client implementations.
> [test] add pubsub clients configs in da vinci client factory in tests

- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/ssl/SslInitializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestReadForApacheAsyncClient.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
Today, Router is doing reverse DNS lookup to do IP spoofing check, and when DNS service is not suitable, the incoming SSL handshakes would be heavily affected.
Venice is not a public service, so the IP spoofing check is not necessary, so this PR introduces a config to disable this behavior. Once the new behavior is fully validated, we will have a following PR to remove this IP spoofing check completely.
New Router config:
router.client.ip.spoofing.check.enabled: default true
CI
> [router] Introduced a new config to disable IP spoofing check

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
Change log consumer is creating a specific type of metadata repository, `ThinClientMetaStoreBasedRepository`. Eventually we will migrate this to use the new `RequestBasedMetaRepository`.
By using the `NativeMetadataRepository.getInstance()` helper to create the repository, we will be able to create the correct type using a config.
Currently this config is `clientConfig.useRequestBasedMetaRepository`. We will add a global config in the near future.
> [changelog] create metadata repository in change log consumer using helper

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/NativeMetadataRepositoryStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/repository/NativeMetadataRepositoryTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDaVinciRequestBasedMetaRepository.java
Setting the type of NativeMetadataRepository should be global and not a store config.
Add a new config to enable request based metadata in dvc.
`client.use.request.based.metadata.repository`
> [dvc] add global config to enable request based metadata

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/P2PFileTransferClientHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/P2PMetadataTransferHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PFileTransferServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
1. Add file name, topic, partition information in logs.
2. Before bootstrap from blob transfer, double check that the partition folder is not existed. 
1. log update
2. Check folder existence before bootstrap. 
> [server][dvc] Add file name information in logs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/RmdSerDe.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/RmdSerDeTest.java
The SIT failed to fetch a newly registered RMD schema on time, causing ingestion failure. To address this issue, we imitated the changes introduced by PR (https://github.com/linkedin/venice/pull/1690) to the RMD deserializer and implemented additional retries for fetching the RMD schema.
This PR includes the following changes:
1. Implement retry logic for fetching the RMD schema. 
2. Add unit tests.
> [server] Allow retry for fetching RMD schema

- build.gradle
- internal/venice-common/src/main/resources/avro/PushJobDetails/v5/PushJobDetails.avsc
VPJ needs to report the number of records exceeding records size limit before compression.
Adding this field will allow tracking of the stores exceeding this limit in the system store.
> [schema] evolve push job details avro schema to include total records exceeding size limit before compression

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineTest.java
Skip querying rocksdb stat for keycount metric. Proper fix is WIP
> [server] Skip querying rocksdb stat for keycount metric

- internal/venice-common/src/main/resources/avro/PushJobDetails/v5/PushJobDetails.avsc
VPJ needs to report the largest value size before compression.
Adding this field will allow tracking of the largest value size per push in the system store.
> [schema] add field to pushjobdetails schema for largest uncompressed value size

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/logcompaction/CompactionManager.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/logcompaction/TestCompactionManager.java
1. Nature of System Store Data:
The data in system stores is metadata and is colo-specific (specific to a co-location). This implies that the data may not require the same level of redundancy or compaction as other types of stores.
2. Alternative Handling:
1. System stores do not necessarily need to go through external compaction mechanisms because they can be compacted or repaired internally through a dedicated "system store repair service." This suggests that external log compaction might be an unnecessary operational burden .
2. Periodic "empty pushes" can suffice for the functionality of system stores, which may eliminate the need for regular log compaction.
3. Throughput Characteristics:
1. System stores typically have very low throughput, and their schema often results in redundant …
> [log-compaction][controller] exclude system store and non-AA stores from candidate selection

- build.gradle
- internal/venice-common/src/main/resources/avro/PartitionState/v18/PartitionState.avsc
Add a new field in PartitionState v18: lastCheckpointTimestamp.
This maintains the latest checkpoint timestamp, with this and the `heartbeatTimestamp` it can infer the previous HB lag during server restart.
> [protocol] Add PartitionState schema v18 with lastCheckpointTimestamp

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/StatTrackingStoreClient.java
Some client exceptions do not end up propagating back to the caller to be handled and exposed due to async nature of streaming requests.
Log exceptions seen when tracking request errors in the StatTrackerStoreClient.
> [client] add exception logging for client request errors

- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreType.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/StoreDeletedValidationResponse.java
- internal/venice-common/src/test/java/com/linkedin/venice/common/TestVeniceSystemStoreType.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithIsolatedEnvironment.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreDeletedValidation.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreDeletionValidationUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreDeletionValidationUtils.java
Venice lacks reliable store deletion validation across all subsystems. The current `validateStoreDeleted` method only provides basic checks, missing:
- System stores validation
- Kafka topics cleanup verification  
- Helix resources cleanup verification
This leads to resource conflicts when recreating stores. No programmatic API exists for external systems to validate deletion status.
**Built comprehensive store deletion validation system with full REST API.**
**Core Architecture:**
- New utility classes: `StoreDeletionValidationUtils` and `StoreDeletedValidation`
- Validates across 5 Venice subsystems with smart detection logic
- Early termination for performance optimization
**Validation Flow:**
```mermaid
graph TD
A["validateStoreDeleted()"] --> B["Check Store Config<br/>(ZooKeeper)"] …
```
> [controller] Store Deleted Validation REST Endpoint

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
The CDC client is facing this exception:
```
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
```
This is because two threads are invoking poll, but we don't handle it correctly. Inside `internalPoll`, we first call `subscriptionLock.writeLock().tryLock(timeoutInMs, TimeUnit.MILLISECONDS)`. However, if we don't acquire the lock within `timeoutInMs`, we still call `pubSubConsumer.poll(timeoutInMs)`.  This leads to the exception in the `KafkaConsumer`. To fix this, we check if we acquired the lock. If we didn't then we return immediately with an empty collection.
> [cc] Correctly handle concurrent polling

- services/venice-controller/src/main/java/com/linkedin/venice/controller/AuditInfo.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/AuditInfoTest.java
We would like to gather preliminary latency data on controller endpoints and filter them by request path. Current metric cannot achieve this.
Add latency to the request logging, leverage log observability to extract per route latency. 
OpenTelemetery migration will export this information for us in the future.
> [controller] add request latency to logging

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/DefaultIngestionBackendTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
In the previous code path, `isOffsetLagged` determines whether a partition is lagged for both hybrid and batch stores by checking the `offsetRecord.getOffsetLag() `field. However, `getOffsetLag` is only updated for hybrid stores. As a result, when using a batch store, the check will always fail, since the offset lag for every partition in a batch store is set to the maximum value of a long.
For the batch store, we check if `isEndOfPushReceived`. 
> [server][dvc] Enhance validation of batch store lag before initiating blob transfer

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Previous change: https://github.com/linkedin/venice/pull/1779 introduces incompatible venice controller interface of `VeniceHelixAdmin` without d2Clients Map, a validation logic preventing empty `d2Clients` during rollout.  The `d2Clients` MP is for avoiding creating D2Client inside `VeniceHelixAdmin`.  During rollout, `VeniceHelixAdmin` should work without passing `d2Clients` map.  
This PR tries to keep previous interface to unblock the release. 
> [controller] Fix incompatible venice controller interface without D2Clients Map.

- internal/venice-common/src/main/resources/avro/ParentControllerMetadata/v1/ParentControllerMetadata.avsc
- internal/venice-common/src/main/resources/avro/ParentControllerMetadataValue/v1/ParentControllerMetadataValue.avsc
Directly related to [PR-1938](https://github.com/linkedin/venice/pull/1938). In this PR, I am simply isolating adding the ParentControllerMetadataValue system store avro schema from the other PR to conform to the CI rules for venice.
> [schema][controller] Create ParentControllerMetadataValue Schema for System Store

- services/venice-controller/src/main/java/com/linkedin/venice/controller/logcompaction/CompactionManager.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/logcompaction/CompactionManagerTest.java
The method `CompactionManager.getStoresForCompaction` will call multiple child controllers for a list of stores to filter for log compaction nomination. An issue arises where 2 child controllers will return the same store, resulting in duplicate store nomination.
Also, the `CompactionManager.isCompactionReady` helper function was filtering out system stores after checking for valid versions, causing many warnings to be logged.
To resolve the duplication issue, this PR will employ a `HashMap` to de duplicate `StoreInfo` by name.
To resolve the system store false warnings, this PR reorders the `isCompactionReady` check.
> [controller] fix log compaction bug causing stores to be repushed twice

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubMessageHeaders.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/AbstractTestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdminWithAcl.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
In future, we want to rely on execution id to skip admin messages. For this purpose, I am adding execution id in the header of the kafka messages that are meant to be written into admin topic.
added integration and unit tests
> [controller] Add execution id in the header of admin topic messages

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdminWithAcl.java
Speed up fast-client adoption
Enable storage node read quota by default for new stores.
> [controller] Enabled storage node read quota by default for new stores

- internal/venice-common/src/main/resources/avro/StoreMetaValue/v34/StoreMetaValue.avsc
- services/venice-controller/src/main/resources/avro/AdminOperation/v89/AdminOperation.avsc
Store lifecycle hooks field is not in camel case
Change capitalization of store lifecycle hooks field to camel case
n/a
> Use camel case for store lifecycle hooks field in schemas

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
When `server.database.checksum.verification.enabled` is set to true when DaVinciRecordTransformer is enabled with its default configs, an exception will be thrown.
Instead of throwing an exception, we gracefully handle this config incompatability by skipping checksum validation.
> [dvc][cc] Gracefully handle database checksum enablement with DVRT

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/SystemStoreHealthCheckStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairTaskTest.java
This PR performs some refactor to system store repair service:
(1) Add system store version staleness check, as will auto re-materialize a new version every X(default 30) days
Add a new config "**controller.parent.system.store.version.refresh.threshold.in.days**" default value = 30
(2) Skip system store that is under migration
(3) Change to also issue repair job for unreachable system store, as it might be these stores has bad or no version in certain regions. System store repair service should try its best to fix it.
(4) With (3) delete unreachable system store count metric as it is attempted to be fixed.
(5) Refactor heartbeat check logic so that it does not blindly wait for 10 minutes before start checking HB, instead, we placed a timeout and periodically check it every 30 seconds. …
> [controller] Check version freshness for system store in system store repair service

- build.gradle
v35 store schema and v90 admin operation schema was introduced before version was bumped for v34 and v88 and version pin was removed for v33 and v88. This causes tests to break because the compiled version and expected version is different
Pin admin operation to v89 and store to v34 until they are bumped to v90 and v35
Existing tests
> [protocol] Pin admin operation to v89 and store to v34

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
To speed up admin message handling.
Flush every write to let Admin Consumption Task to consume the message as soon as possible.
> [controller] flush after write in Parent Controller

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
Push completion does not stall until version swap is complete for deferred swap, but it should stall until version swap is complete as well so that push issues are easy to triage
- Stall push completion until version swap completes. Push is marked as complete if version swap succeeds and if it does not, it will be marked as failed
- Removed unnecessary api call to get region <-> version in DeferredVersionSwapService since that was only used to get the regions
> [vpj] Stall push completion until version swap is complete

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/logcompaction/CompactionManager.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/logcompaction/CompactionManagerTest.java
Log compaction cluster level setting are being improperly applied. Enabling log compaction for one cluster will enable for all in the same environment. 
Pass cluster level configs to `CompactionManager` so it may filter out stores using this config.
> [controller] pass log compaction cluster configs to compaction manager

- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateWithParallelProcessingTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestIncrementalPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestRepush.java
1. Split PartialUpdateTest into 3 test classes and move into two different buckets to reduce CI runtime and potential resource leaks
2. Remove the parallel processing config override and make it default enabled for PartialUpdateTest
3. Use try-with-resource for VeniceSystemProducer usage.
4. Delete one stale test which is covered by other tests
There might be some other changes to come, but this PR intends to focus on test splitting for now.
> [test] Split PartitialUpdate integration tests

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
fix: enhance error logging for offset and timestamp regression by adding store version name.
CI
Logging change
> [server] Fix Missing DCR Error Log

- build.gradle
Tehuti version is out of date, upgrading to 0.12.4
Bump tehuti version
> bump tehuti version to 0.12.4

- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/StoreConstantsTest.java
As part of migrating users to fast client, we want to have the same batch get limits on fast client that are similar to the thin client.  
This change makes the defaults the same between fast client and thin client.
> [fc] Update the Fast client batch get config to be on par with thin client batch get config

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/NettyFileTransferClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/P2PFileTransferClientHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PFileTransferServerHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestP2PFileTransferClientHandler.java
Through server test environment test, we found that checksum calculation in client side will block EventLoop and this will slow down transfer as (1) Blocking next file's transfer from sender side (2) Slow down other blob transfer request assigned to the same EventLoop thread.
This PR tries to address this issue by creating a separate thread pool and offload the CPU intensive job into separated thread to unblock the receiver EventLoop thread to ingest more efficient.
> [server][dvc] Improve blob transfer performance by offloading checksum calculation from EventLoop thread

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/dimensions/StoreRepushTriggerSource.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/dimensions/VeniceMetricsDimensions.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/dimensions/StoreRepushTriggerSourceTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/dimensions/StreamProgressTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/dimensions/VeniceMetricsDimensionsTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/OpenTelemetryDataPointTestUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/logcompaction/LogCompactionService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/repush/RepushJobRequest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/ControllerMetricEntity.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/LogCompactionStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/logcompaction/CompactionManagerTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/stats/LogCompactionStatsTest.java
Fix names of log compaction Otel metrics
Fix names of log compaction Otel metrics
> [controller] Cleanup log compaction metrics and add some tests

- gradle/spotbugs/exclude.xml
- internal/venice-common/src/main/proto/hooks/GrpcStoreLifecycleHook.proto
Introduce new proto for GrpcStoreLifecycleHooks. This will be used for users to run custom validation logic for deferred swap
- GrpcStoreLifecycleHooksService - This is the service that users will implement with their custom validation logic
- GrpcStoreLifecycleHooksRequest - This is the request that the GrpcStoreLifecycleHook will send to the GrpcStoreLifecycleHooksService
- GrpcStoreLifecycleHooksResponse - This is the response that the GrpcStoreLifecycleHook will expect from GrpcStoreLifecycleHooksService. This response will be used to decide whether to roll forward or roll back
CI
> [protocol] Add proto for GrpcStoreLifecycleHooks

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestAdminOperationWithPreviousVersion.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
Currently, when a version is rolled back, the user can roll forward back to the same version again. This is problematic with deferred swap because if there are two consecutive bad versions, automatic roll back will roll back to the first bad version when the second bad version comes in
- Mark version as ERROR after rollback to prevent rolling forward to this version again
- Fix NPE in DeferredVersionSwapService from accessing store response when it is null
- Update check in AbstractPushMonitor to only perform a sequential roll forward when target region push with deferred swap is enabled
New e2e test
> [controller] Mark rolled back version as ERROR
