linkedin/venice

- internal/venice-common/src/main/java/com/linkedin/venice/httpclient/CachedDnsResolver.java
- internal/venice-common/src/main/java/com/linkedin/venice/httpclient/HttpClientUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/KafkaClientFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/admin/KafkaAdminClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/consumer/ApacheKafkaConsumer.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/partitionoffset/PartitionOffsetFetcherImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/ProducerTracker.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/checksum/CheckSum.java
- internal/venice-common/src/main/java/com/linkedin/venice/listener/ListenerManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/listener/VerifySslHandler.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Partition.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/SchemaPresenceChecker.java
- internal/venice-common/src/main/java/com/linkedin/venice/service/AbstractVeniceService.java
- internal/venice-common/src/main/java/com/linkedin/venice/stats/ZkClientStatusStats.java
This rb mainly contains the logging clean ups for venice-common module.
Internal CI (yellow)
> [server] Use interpolation for logging in venice-common

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClusterAgnosticTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestWritePathComputation.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/multicluster/TestMetadataOperationInMultiCluster.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceMultiClusterCreateOptions.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceMultiClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiColoMultiClusterWrapper.java
Remove overloaded versions of ServiceFactory::getVeniceMultiClusterWrapper.
Add a new method to create a multi-cluster wrapper that takes just one argument,
VeniceMultiClusterCreateOptions, which is constructed using a builder design
pattern.
Resolves #5 
UT & IT via CI
> [test] ServiceFactory::getVeniceMultiClusterWrapper cleanup

- docs/dev_guide/recommended_development_workflow.md
The original guide suggests following the README to run tests but README doesn't contain any instruction of that. The updated instruction is located in the `workspace_setup.md`
> [doc] update the documentation on testing

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestControllerEnforceSSL.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestD2ControllerClient.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClusterAgnosticTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/MetaSystemStoreTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/ParticipantStoreTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PushJobDetailsTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/StoragePersonaTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestStoreUpdateStoragePersona.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/ssl/AdminChannelWithSSLTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceControllerCreateOptions.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceMultiClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiColoMultiClusterWrapper.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/TestAdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/AbstractTestAdminSparkServer.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/TestAdminSparkServerGetLeader.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/TestBackupControllerResponse.java
Removed all existing variations of ServiceFactory::getVeniceController and ServiceFactory::getVeniceParentController. Added a new method that takes just one argument: ServiceFactory::getVeniceController(VeniceControllerCreateOptions). VeniceControllerCreateOptions uses builder to collect controller creation options. To get parent controller, set 'parent' to true while building VeniceControllerCreateOptions.
Resolves #12 
UT & IT via Li CI
> [test] ServiceFactory::getVeniceParentController cleanup

- .gitignore
- docs/CODE_OF_CONDUCT.md
- docs/CONTRIBUTING.md
- docs/Gemfile
- docs/README.md
- docs/SECURITY.md
- docs/_config.yml
- docs/community_guidelines.md
- docs/dev_guide/dev_guide.md
- docs/dev_guide/doc_guide.md
- docs/dev_guide/recommended_development_workflow.md
- docs/quickstart/quickstart.md
This PR sets up docs on GitHub Pages using the [JustTheDocs](https://just-the-docs.github.io/just-the-docs/) template.
Tested on my personal fork: https://nisargthakkar.github.io/venice/
It adds a public facing documentation page that can be updated in-repo.
> [doc] Use GitHub Pages for documentation

- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/AbstractVeniceFilter.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/AbstractVeniceMapper.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/VeniceAvroMapper.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/VeniceVsonMapper.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputMapper.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/TTLResolutionPolicy.java
- clients/hadoop-to-venice-bridge/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/VeniceKafkaInputTTLFilter.java
- clients/hadoop-to-venice-bridge/src/test/java/com/linkedin/venice/hadoop/TestVeniceAvroMapper.java
- clients/hadoop-to-venice-bridge/src/test/java/com/linkedin/venice/hadoop/TestVenicePushJobConfig.java
- clients/hadoop-to-venice-bridge/src/test/java/com/linkedin/venice/hadoop/TestVeniceVsonMapper.java
- clients/hadoop-to-venice-bridge/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputMapper.java
- clients/hadoop-to-venice-bridge/src/test/java/com/linkedin/venice/hadoop/input/kafka/ttl/TestVeniceKafkaInputTTLFilter.java
This commit introduces two new config REPUSH_TTL_IN_HOURS and REPUSH_TTL_POLICY. They are used in conjunction to apply corresponding TTL logic to records. Note that as for now, we only support one REPUSH_TTL_POLICY so its value is hardcoded.
The TTL filter uses the chain of responsibility pattern so we can introduce more filters to the Mapper stage. TTL filter also comes with 3 policies w.r.t batch writes. The core implementation will be added in a separate commit.
unit tests and integration tests
Users now can specify the ttl time in hours in the repush job. When the config is specified, the filter will be present during H2V mapper stage. Currently, this filter doesn't do anything but allowing everything flow thru. Its implementation will be introduce in a different PR.
> [h2v] Add repush ttl config and filter to the H2V.

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VeniceReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/chunk/ChunkAssembler.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputReducer.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/chunk/TestChunkAssembler.java
- docs/ops_guide/ops_guide.md
- docs/ops_guide/repush.md
- docs/user_guide/ttl.md
- docs/user_guide/user_guide.md
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/SslUtils.java
Implemented object reuse for chunked topics. Because the logic is more complex, it is still not as efficient as non-chunked, but nonetheless better than before. The memory requirement is now to buffer the bytes of all shuffled chunks rather than the objects of all shuffled events.
Also removed an unnecessary optional for the reducer hot path for all implementations (including regular VPJ and repush).
Unit tests (updated to new code structure)
Internal CI (green!)
> [h2v] Repush optimization for chunked topics

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
This PR address the issue found during a GCN investigation. Da Vinci client was able to emit disk_usage_in_bytes metrics during/after version push, however once customer application restart it will emit -18 signal (indicating NULL_STORAGE_ENGINE_STATS error)
1. This is caused by a bug in NativeMetadataRepository. When application restart, during store metadata repository subscription, it will add a store object into the map slot which was previously null. In this case it should ask listener to handle store change event, instead of store creation event. This signal miss will let stats class failed to link up with the current version.
2. Also, due to how AggVersionedStorageEngineStats links storage engine with the correct store version is implemented and called, Da Vinci backend for now …
> [da-vinci] Make sure Da Vinci client can emit metrics after application restart and before next version push

- build.gradle
- clients/venice-admin-tool/build.gradle
- clients/venice-push-job/build.gradle
- gradle/helper/publishing.gradle
Shadow plugin configures artifact publishing to publish shadow jars to maven ([venice-controller example](https://linkedin.jfrog.io/ui/repos/tree/General/venice/com/linkedin/venice/venice-controller/0.4.3)). If we don't publish regular jars, then the `all-modules` component cannot depend on any published artifacts for `venice-push-job` and `venice-admin-tool`.
Published to maven local: https://gist.github.com/nisargthakkar/48977caca2dd59561c603e7d6a7f7a30
> [build] Remove separate publishing for shadow jars

- .github/workflows/build-and-upload-archives-on-demand.yml
- .github/workflows/build-and-upload-archives-upon-creating-tags.yml
- gradle/helper/git.gradle
- make_tag.py
Previously, this action failed: https://github.com/linkedin/venice/actions/runs/3192717384
In the failed action, I found that github adds the repo without `.git`. Then I tested https and ssh ones and found that it works without `.git` for both
Tested here: https://github.com/nisargthakkar/venice/actions/runs/3193114715
> [build] Fix upstream remote check. Add explicit upstream in GithubActions

- wc-test
[script]
Make sure wc-test uses upstream/main as a default baseline to compute local changes.
Internal CI
> [misc] Use upstream/main as a default baseline for wc-test

- .github/workflows/build-and-upload-archives-on-demand.yml
- .github/workflows/build-and-upload-archives-upon-creating-tags.yml
Set fetch-depth to 0 to get all history instead of just the current tag. This was the previous behavior till I incorrectly changed in #36
For example: https://github.com/linkedin/venice/actions/runs/3185966029/jobs/5196103210 ran on the older code and fetched all tags. It wouldn't have run into the issue that https://github.com/linkedin/venice/actions/runs/3193427287/jobs/5211964867 did
(Checkout Code -> Checking out the ref)
Ran action: https://github.com/nisargthakkar/venice/actions/runs/3193477299
> [build] Revert fetch-depth to get all history

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreWriteComputeProcessor.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/RmdSerDe.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithValueLevelTimestamp.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/avro/MapOrderPreservingDatumReader.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/avro/MapOrderPreservingDeserializer.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/avro/MapOrderPreservingGenericDatumWriter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/avro/MapOrderPreservingSerializer.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/avro/MapOrderPreservingSpecificDatumWriter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/avro/MapOrderingPreservingSerDeFactory.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/serializer/avro/MapOrderPreservingSerDeTest.java
Move Rmd serialization utils to common package such that other packages, e.g. h2v, can utilize them. Have to separate these changes into a single PR to reduce the change list.
internal CI
> [da-vinci][server] Move Rmd serialization util to common package

- internal/venice-client-common/src/main/java/com/linkedin/venice/exceptions/ErrorType.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceStats.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/exceptions/PreconditionCheckFailedException.java
- internal/venice-common/src/main/java/com/linkedin/venice/exceptions/ResourceStillExistsException.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixStoreGraveyard.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreGraveyard.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestStoreGraveyardCleanupService.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreGraveyardCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithoutCluster.java
Today when a store is deleted, it will be put into store graveyard to avoid the version overlapping between the deleted store and re-created store. But store graveyard zk nodes are never removed and will continue increasing with more stores being deleted.
This commit adds store graveyard cleanup service. When the controller cluster level config is enabled, the service running on parent controller will gather stale and removable store graveyards and calls child controllers. Each child controller checks if the store can be removed from graveyard in the child colo. If so, remove it and respond OK. Otherwise, respond with error. Once all child controllers respond OK, parent controller will remove the store graveyard in parent colo.
A store is removable from graveyard when the following …
> [controller][common] Support store graveyard cleanup

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- The default value for config routingUnavailableRequestCounterResetDelayMS was set to 1000 minutes or 16+ hours by mistake. This causes instances that encountered a one-off exception to be blocked for extended periods of time which reduces SN availability. 
- One-off exceptions should be rare, further reducing the default delay to 10s so instance can join back the healthy pool sooner rather than later.
Existing unit and integration tests.
> [fast-client] Fix default value for routingUnavailableRequestCounterResetDelayMS

- build.gradle
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRead.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceDelegateMode.java
Netty dependencies clashed between fat jar and specific modules, leading to NoSuchMethodErrors. Fixed via build exclusions.
Disabled the marking of JMH sources in IntelliJ as it has issues.
Re-enabled TestRead::testRead and added a try-with-resources to it. Also added a TODO about a potentieal issue in HttpClient5.
CI (yellow)
> [build][test] Fixed Netty dependencies and TestRead::testRead

- docs/dev_guide/recommended_development_workflow.md
- internal/venice-common/src/main/java/com/linkedin/venice/meta/AbstractStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/VersionStatus.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixReadOnlyStorageEngineRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixReadOnlyStoreRepositoryAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixReadOnlyZKSharedSystemStoreRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixReadWriteStorageEngineRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixReadWriteStoreRepositoryAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestStoreJsonSerializer.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestZKStore.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/InstanceStatusDecider.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithoutCluster.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVenicePartitionFinder.java
2 new version status:
CREATED - Version is created and persisted inside ZK, but controller hasn't finished preparation works yet. PARTIALLY_ONLINE - Version has been pushed to Venice and is ready to serve in some regions, but failed in other regions.
These new version status are prerequisite for two future works:
1. Make AddVersion command processing idempotent
2. Stop using empty topic in parent Kafka cluster to indicate ongoing pushes, instead, leverage versin status.
Introduce new version statuses in the code base, deploy them first, so that rollback is allowed in future when there is a need to rollback the codes but new version statuses are already persisted on ZK.
Other changes:
Clean up deprecated API Store#increaseVersion which is only used in test cases.
> [controller][test] Add 2 new version status without writing them in ZK yet

- .github/workflows/build-and-upload-archives-upon-creating-tags.yml
- .github/workflows/build-and-upload-archives-upon-pushing-tags.yml
Since we are using git API to create tags in the actions workflow, it does not trigger the `push` tag workflow. Creating this workflow action to get triggered on tag creation event.
> [Build] Add build/upload archive workflow for tag

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/consumer/ApacheKafkaConsumer.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/consumer/KafkaConsumerWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/consumer/MockInMemoryConsumer.java
This is a test only issue and there is no data loss issue discovered. And this code change also leverages `KafkaConsumerWrapper#batchUnsubscribe` in `KafkaConsumerService`.
Internal CI passed
`No`
> [Test][da-vinci] Fixed a flakiness of StoreIngestionTaskTest

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AvroGenericStoreClientImplTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/integration/utils/MockHttpServerWrapper.java
In thin-client, if the store init isn't done in the start method because of the delay start of d2 client, each request could trigger the store init procedure at runtime, and this has introduced some issue in the past especailly when the store isn't in a good state, such as store was deleted/disabled and the 10-time retry triggered by each request will put the application thread pool in a stuck state, and application's fallback logic can't kick in since the Venice call will be blocked by the internal store init procedure.
This code change introduces a change of the retry strategy: If d2 client isn't ready during the start invocation, the store init with retry triggered by the online request will only be executed once, and if the store init fails, all the subsequent requests will receive an …
> [thin-client] Changed the retry strategy of store init

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
[controller] Call  instead indexing it using largestVersionNumber
Fix ArrayIndexOutOfBoundsException in HB system store init routine.
> [controller] Dont index store::version  using largestVersionNumber 

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/DumpAdminMessages.java
There was a bug in AdminTool#printObject method, which can't handle a list of response because of the internal filtering logic. Since field filtering is not being used actively, this code change removes the field filtering option.
In the meantime, this code change also skips the Control Message when dumping admin topic to avoid confusion.
Manual test in test env.
The command option: `filter-json` is removed from admin tool
> [admin-tool] Fixed the admin tool command to dump admin topic

- internal/venice-common/src/main/java/com/linkedin/venice/utils/ForkedJavaProcess.java
- internal/venice-compatibility-test/src/test/java/com/linkedin/venice/VeniceClientCompatibilityTest.java
> [da-vinci][server][test] Fix empty log line printing from forked process. Added additional wait to VeniceClientCompatibilityTest

- .github/workflows/build-and-upload-archives-on-schedule.yml
- make_tag.py
Add a git fetch to get all the commits in make_tags. Currently make_tags fails as it cannot find the sha of the latest commits.
[No tags can describe 'sha_code`](fatal: No tags can describe 'ebac2af4b831cd5294cea214c42da239fcf7fe5a'.)
> [build] Add a git fetch to get all the commits in make_tags

- docs/dev_guide/doc_guide.md
- docs/user_guide/write_api/push_job.md
Also fleshed out the doc's doc further.
On my fork of the docs. Notable changes include:
https://felixgv.github.io/venice/docs/dev_guide/documentation_guideline
https://felixgv.github.io/venice/docs/user_guide/write_api (the table of content is now populated)
https://felixgv.github.io/venice/docs/user_guide/write_api/push_job (now has correct breadcrumbs)
> [doc] Fixed nesting of Push Job docs

- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestValidateSchemaAndBuildDictMapperOutputReader.java
> [test] Fix flakies in TestValidateSchemaAndBuildDictMapperOutputReader

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
This PR fixes a bug: Avg/Max metric of e2e record consumption latency is missing. The bug was introduced during previous refactor of metrics and the retrieval and registration of these two metrics were lost.
Internal CI
> [server] Add back emission of avg/max of consumed record e2e processing latency metric

- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChunkHelper.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChunkedPayloadAndManifest.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/ChunkHelperTest.java
This PR adds support of chunking RMD in Venice Writer only. It is controlled by a "isRmdChunkingEnabled" flag and for now we hardcode it to false as there is no downstream handling logic. Once downstream logic is ready it will be configurable.
Internal CI
> [common] Adding chunking support for large RMD payload in Venice Writer

- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceHostHealth.java
0 should be emitted instead of no emission when there are no unhealthy hosts.
- unhealthy_host_count_caused_by_router_heart_beat is not in the hot path so we can emit the current unhealthy host count every time when the heartbeat succeeds (regardless if the count changed).
- unhealthy_host_count_caused_by_pending_queue is in the hot path but we should still emit the updated unhealthy host count when a host is recovered from an unhealthy state.
Existing unit and integration tests.
> [router] unhealthy host metrics should initialize/reset to 0

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngine.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceStats.java
The aggregated metrics are using the cached disk usage to reduce the overhead, and the cached value should be updated regularly since there are store-level metrics for them as well.
Internal CI test passed
> [da-vinci][venice] Added aggregated metrics for disk usage and rmd usage

- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/HashCodeComparator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compression/TestVeniceCompressor.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocalTest.java
- internal/venice-client-common/src/test/resources/log4j.properties
- internal/venice-client-common/src/test/resources/log4j2.properties
This commit uses a thread-local `ZstdCompressorCtx` objects since they are not thread-safe. To help with closing of these objects cleanly, a new `CloseableThreadLocal` class is also created
Resolves #88
Added new unit tests.
Internal CI - JDK11 #6647
> [vpj][server] Make Zstd compression threadsafe

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingVsonStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/factory/ClientFactory.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/VsonGenericStoreClientImpl.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/AbstractVsonSchemaAdapter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonAvroDatumReader.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonAvroDatumWriter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonAvroSchemaAdapter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonAvroSerializer.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonReader.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonSchema.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonSchemaAdapter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonTypes.java
Vson was a legacy format from Voldemort, and to smooth the migration from thin-client to fast-client, we need to add vson support to fast-client, and this format is currently supported by thin-client today.
This code change also added `@Deprecate` to all the vson related classes.
Internal CI passed: wc-test#6663
> [venice-fast-client] Added vson support to fast-client

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreInfo.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreBackupVersionCleanupService.java
To make version rollback a self-service, we need to support it in parent controller.
Add a new controller API rollbackToBackupVersion. Callers do not need to specify
any version number. Parent controller will find the backup version to roll back by
calling child controllers. If backup version is consistent across child regions,
current version in all child regions will be rolled back to backup version.
Otherwise, current version won't be changed.
Integration test testStoreRollbackToBackupVersion
Internal CI
> [controller][common] Support version rollback in parent controller

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/AbstractTestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/TestAdminConsumptionTask.java
Kafka replication factor can now be configured with:
- "kafka.replication.factor" for version topics
- "kafka.replication.factor.rt.topics" for RT topics
- "admin.topic.replication.factor" for admin topics
Kafka minimum in sync replicas can now be configured with:
- "kafka.min.isr" for version topics
- "kafka.min.isr.rt.topics" for RT topics
- "kafka.min.isr.admin.topics" for admin topics
> [common][controller] Separate kafka RF and minIsr config for VT, RT and admin topics

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
Add this unit test to make sure merge update can work with field level timestamp
This PR does not change any behavior, just add 3 unit tests. There is a potential to merge this class with TestMergeUpdateWithValueLevelTimestamp, as most of the operations have large overlaps. I plan to do this after Map DCR String / UTF-8 issue is resolved.
Local Test
> [test] Add TestMergeUpdateWithFieldLevelTimestamp

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/ReplicationMetadataRocksDBStoragePartition.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChunkAwareCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChunkedPayloadAndManifest.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/WriterChunkingHelper.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/WriterChunkingHelperTest.java
This PR adds implementation for server side handling logic for RMD chunking. 
1. Added a new StorageOperationType RMD in AASIT which handles RMD chunks PUT operation. Changed NORMAL type to VALUE, changed RMD to VALUE_AND_RMD to reflect its purpose. 
2. Tweaks the getStorageOperationType logic to make it backward compatible.
3. Add logic the storage layer to put RMD only data into storage.
4. Some minor changes in LeaderProducerCallback/ChunkAwareCallback to support setting RMD chunking information.
Internal CI
There is no integration test / unit test added as at this point there is no end to end path to validate the logic. 
Please feel free to comment if you think there is any logic should be unit tested.
> [server] Implement server side handling logic for RMD chunking

- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
During my testing, the push jobs failed due to not able to construct VeniceWriter but the exception contains very long props information that makes the debugging difficult as the real exception is **swallowed** due to the length limit.
For examples
```
com.linkedin.venice.exceptions.VeniceException: Error while constructing VeniceWriter for store name: testStore_EI_adchen_02_v5, props: {abstractfs.failover.overload.scheme.target.hdfs.impl: org.apache.hadoop.fs.Hdfs, adl.feature.ownerandgroup.enableupn: false, adl.http.timeout: -1, allow.duplicate.key: true, amplification.factor: 1 ..... } // this props has over 20000 characters. Azkaban and Hadoop couldn't display the full msg.
```
After deploying this change, the actual exception can be revealed.
```
Error: …
```
> [all] Move VeniceWriter props out of exception msg

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroComputeRequestBuilder.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroBlackHoleResponseStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderV3.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderV4.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroGenericReadComputeStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientFactory.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ComputeGenericRecord.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ComputeRequestBuilder.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/DelegatingStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/StatTrackingStoreClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AbstractAvroStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/StatTrackingStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/StoreClientPerfTest.java
- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClientCompatibilityTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/controllerapi/MultiSchemaResponse.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRead.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRouterRetry.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestStreaming.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/storagenode/ReadComputeValidationTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/storagenode/StorageNodeComputeTest.java
- internal/venice-test-common/src/jmh/java/com/linkedin/venice/benchmark/DaVinciPartialKeyLookupBenchmark.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
[thin-client] [da-vinci] Return original value schema along with the read compute result
Original value schema may contain metadata fields that aren't carried over to computed result schema. PR changes Read-Compute API to return `ComputeGenericRecord` wrapper instead of `GenericRecord` so that additional information can be passed along. Also added synchronized section to `RouterBackedSchemaReader::refreshAllValueSchema` to avoid data race in `latestValueSchemaEntry` handling.
- Added new test `RouterBackedSchemaReaderTest.testGetLatestValueSchemaWithSupersetSchema` to verify `preferredSchemaFilter` behavior.
- Updated `AbstractAvroStoreClientTest.testCompute` to verify that compute results contains original value schema.
- Updated `AvroComputeRequestBuilderTest.testComputeRequestBuilder` …
> [client] Return original value schema along with the read compute result

- make_tag.py
Adding error logs in sys.exit method in make_tags. 
Without any error log, it would indicate a successful run which would trigger the next part the workflow to publish artifact which would fail eventually.
> Add error messages to sys.exit to indidate failure

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandlerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClientTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestBatch.java
This PR fixes recent regression added to the ingestion isolation command request logics.
1. Do not throw exception when remote ingestion process reject command as it should be a transient state during unsubscription from II to main process. (improvement)
2. Try to initialize topic partition status to be subscribed in the forked process before START_CONSUMPTION command execution check. If the topic partition has not been touched in the forked process this action will initialize the state so ingestion command can go through (bug fix)
3. For any commands other than START_CONSUMPTION, if a topic partition is not hosted in a server, the default go-to process should be main process instead of forked process. (bug fix)
Local test fixes the TestBatchForIngestionIsolation test failures and hanging …
> [server][da-vinci] Fix regression in recent ingestion isolation improvements.

- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonAvroDatumWriter.java
The old Hashmap was throwing java.util.ConcurrentModificationException. Use a ConcurrentHashMap should solve this.
> [client] Use VeniceConcurrentHashMap in VsonAvroDatumWriter to make it thread safe

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/AbstractAvroChunkingAdapter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/GzipCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/NoopCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/VeniceCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/ByteUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compression/TestVeniceCompressor.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/jmh/java/com/linkedin/venice/benchmark/RouterDecompressionBenchmark.java
- internal/venice-test-common/src/jmh/java/com/linkedin/venice/benchmark/ZstdDecompressionBenchmark.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceResponseDecompressor.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceDispatcher.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVenicePathParser.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceResponseAggregator.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceResponseDecompressor.java
1. Zstd decompression used to reload the dictionary on every payload. This is now done upfront, via ZstdDictDecompress and via the use of a thread-local. A new JMH benchmark is added for this, which reveals the following results:
- At 64 KB of decompressed payload: 
- the decompression latency drops from 73 micros to 10 micros,
- garbage generated from 329 KB to 65 KB.
- At 500 B of decompressed payload:
- the decompression latency drops from 31 micros to 387 nanos,
- garbage generated from 141 KB to 568 B.
2. Zstd decompression also used to rely on an InputStream in all cases, which would result in the allocation and copy of many byte[] instances. Now, it instead directly instantiates the byte[] of the correct size and populates it (except in the case of chunked value decompression, …
> [router][server][tc][fc][dvc] Compression optimizations

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/HttpClientTransport.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StatusReportAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestBatch.java
This PR fixes the CI build hanging issue in TestBatchForIngestionIsolation#cleanup() method.
The issue is caused by IsolatedIngestionServer failed to serialize COMPLETE report from forked process to main process and cause ingestion task to fail and test time out. (Most likely happening in testIncrementalPushWritesToRealTimeTopicWithPolicy() as it sets AMP=2 and increase the likelyhood). The root cause of the serailization failure is: ready-to-serve check and COMPLETE report of a same subPartition can actually be invoked from (1) Drainer thread who is processing the records of this subPartition (2) SIT thread checking long running task state (this was introduced long before to avoid the edge case that no data in RT topic and (1) will never be invoked to complete the ingestion). The race …
> [server] Fix hanging isolated ingestion server issue caused by race condition in status reporting

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/protocol/enums/ControlMessageType.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/ProducerTracker.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/resources/avro/KafkaMessageEnvelope/v11/KafkaMessageEnvelope.avsc
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/protocol/enums/ControlMessageTypeTest.java
- internal/venice-consumer/src/test/java/com/linkedin/venice/consumer/ConsumerTest.java
- internal/venice-consumer/src/test/java/com/linkedin/venice/kafka/validation/KafkaDataIntegrityValidatorTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
This change add a new control message that will be consumed by the Venice consumer client and the Venice leader. 
It is initially emitted by the controller to a local RT and consumed by a venice leader. The message should contain BOTH the source version (the version we're switching FROM) and the destination version (the version we're switching TO). 
When a leader node sees this message on the RT, it produces the message to it's VT by adding its local real-time topic high watermark, indicating the latest offsets of all RT's that it's consumed up until now. We also add two flags into this control message: 
1. Whether this version push is triggered by repush.
2. Whether this version swap message in VT is triggered by the last RT's message the leader server has read. 
Besides, we bundled some …
> [venice-common] Upgrade KME with adding new change capture topic switch control message event and cleanups.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/WriterChunkingHelper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
This PR fixes the issue that A/A producer callback does not implement ChunkAwareCallback interface. This results in all values will be stored in a single un-chunked value for leader node even if the value produced to VT and saved by follower is chunked. It makes RocksDB data not consistent between leader and follower.
This PR fixes the issue by letting the wrapper callback also implement the ChunkAwareCallback API and in the LeaderProducerCallback it also add support for RMD payload if A/A enabled.
Currently only one PROD store has this issue, we can re-push to create a new version with consistent state when this fix is deployed.
Internal CI
Added a new unit test to capture the issue.
> [server] Add chunking aware support for A/A producer callback

- clients/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemFactory.java
Overridden implementations of VeniceSystemFactory might need the Config arg to create a custom VeniceSystemProducer instance. Added an overridden function to pass these as arguments.
Internal CI passed (Build #7316)
> [samza] Add a function to create a VeniceSystemProducer with a Config argument

- da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
This is a hot fix PR on top of current server release version to make sure leader replica drainer won't skip chunks and manifest due to DIV logic.
Tested the fix on the main branch with full integration test.
> [server] Make sure LEADER drainer DIV logic does not skip value chunks and manifest messages

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
Problem: Parent controller does not enforce minimal partition count for hybrid stores. When an existing store is converted to hybrid, if owners do not specify, store partition count remains as 0, and version partition count will be re-calculated for every new push. As a result, version topic and real-time topic partiton counts might mismatch.
Fix: Add a config default.partition.count.for.hybrid whose default value is the same with default.partition.count. Config value will be increased in production. Parent controller will uses this config to set new hybrid store partition count if it is not speified by store owners.
For existing stores with 0 partition count, this commit also allows updating it to a value that matches real-time topic partition count.
CI
> [controller] Enforce minimal hybrid store partition count and allow hybrid store partition count backfill

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducedRecordContext.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/InternalAvroSpecificSerializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChunkAwareCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ErrorPropagationCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/PutMetadata.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/WriterChunkingHelper.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/WriterChunkingHelperTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/consumer/ConsumerIntegrationTest.java
The VeniceWriter::putLargeValue function used to block on every chunk, purportedly for reliability reasons, but this appears unnecessary. Furthermore, it imposes a significant throughput penalty on clusters containing stores that exercise both write compute and chunking.
In order to avoid silently swallowing producer errors, we introduce a new class called ErrorPropagationCallback, which forwards exceptions to another Kafka callback, but does nothing on successfully produced messages.
Miscellaneous clean ups:
1. Eliminated unnecessary Optionals from the VeniceWriter's hot path.
2. Eliminated many unnecessary properties from LeaderProducerCallback, greatly simplifying the constructor, and eliminating 4 object pointers (5 for non-A/A) and 2 primitives from each instance.
3. Introduced a …
> [server][vpj] Producing chunks is now async

- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/GzipCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/GzipPool.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ReusableGzipOutputStream.java
Ported a reusable Gzip compression from https://github.com/mp911de/reusing-gzip-streams for use in Venice mapper phase. For Gzip enabled stores this should improve mapper memory usage.
A reusable GZIPOutputStream differs from the JDK-provided class in some points:
Do not write the GZIP header upon instance creation but expose a writeHeader() method
Expose a reset() method to reset the deflater state
Do not close the stream to keep it reusable
CI run
No
> [controller][H2V]  Add a reusable Gzip compressor for Venice mapper

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/HttpClientTransport.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionRequestClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionStorageMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/utils/IsolatedIngestionUtils.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionServerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClientTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
During the rolling out of isolated ingestion in EI enviorment, an issue was detected: Each server handles large amount of requests from different stores and drop partition command can be time consuming (it needs to potentially stop consumption and drain records and then close RocksDB) and taking up available threads (currently 10) in the thread pool. New requests can be piling up and eventually time out for the default 60s timeout. The problem can be more severe when the request is actually processed (partition removed from II host and cleaned up the status from II server but does not reset it in main process due to the fact it thinks the request time out and still retrying). The next retry will get rejected as II thinks this topic partition resources does not being to II process. It will …
> [server] Enhance isolated ingestion request handling logic

- .github/workflows/gh-ci.yml
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/utils/IsolatedIngestionUtils.java
- internal/venice-test-common/build.gradle
Run Venice tests on the following matrix:
OS: macOS, Ubuntu
JDK: 11
While we figure out how we want to run CI with GitHub actions, I think it would be good to have
something up and running in the meantime. With this RB, CI will be run on every commit/pull request. 
It triggers one job/OS for unit tests (~42 mins) and one for integration tests/OS (2.30 hours and a bit flaky).
> [build] Run Venice CI with GitHub Actions

- internal/venice-common/src/main/resources/avro/KafkaMessageEnvelope/v11/KafkaMessageEnvelope.avsc
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/protocol/ProtocolCompatibilityTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/protocol/admin/AdminOperationProtocolCompatibilityTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/protocol/kme/KMEProtocolCompatibilityTest.java
This PR fixes the incompatible v11 KME with the deletion of the deprecated `StartOfBufferReplay` control message. We plan to keep this control message in case some old topics still have this messages causing ingestion error. Besides, add a unit test to test the compatibility of newest KME protocol. 
Internal CI
> [controller][compat] Add back deprecated StartOfBufferReplay and KME compatibility test.

- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Test testStoreRollbackToBackupVersion is flaky in JDK8. The second empty push sometimes fails as previous empty push
version topic is truncated during getOffLinePushStatus and sometimes the topic is deleted quickly. Then isTopicTruncated 
inside truncateTopicsBasedOnMaxErroredTopicNumToKeep throws topic does not exist exception and fails the second 
empty push job.
The commit catches TopicDoesNotExistException and returns true for TopicManager#isTopicTruncated.
Internal WcTest8 1103 1104 1105: No testStoreRollbackToBackupVersion failure
FYI, previous failed test exception stack trace:
```
com.linkedin.venice.kafka.TopicDoesNotExistException: Topic: testStoreRollbackToBackupVersion_53201a239c474_b5510b98_v1 doesn't exist
at com.linkedin.venice.kafka.admin.KafkaAdminClient.getTopicConfig(Kaf …
```
> [common] Catch TopicDoesNotExistException and return true for TopicManager#isTopicTruncated

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/ActiveActiveReplicationForHybridTest.java
This commit fixes RMD retrieval bug when chunking is enabled in A/A mode.
Current implementation always use raw key bytes to retrive RMD from storage, however, when chunking is enabled, it should be adjusted with chunking specific suffix. Current code will miss old RMD from storage and will make incoming record always accepted by DCR, unless a cache hit from transient record.
This PR fixes it by checking the chunking flag and adjust the key accordingly. This PR also adjusts an existing integration test to make sure chunking+AA will work correctly.
Internal CI 3 times. 
Adjust existing integration test to make sure A/A+Chunking combination is covered.
> [server] Fix RMD retrieval bug when chunking is enabled

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/gh-ci.yml
- build.gradle
- internal/venice-test-common/build.gradle
The buckets are controlled by a map defined in:
internal/venice-test-common/build.gradle
The build can now also dynamically generate the GitHub CI workflow file according to the content of the build, by running:
./gradlew generateGHCI
This reduces the wall-clock time of the build to roughly half an hour.
Example run: https://github.com/FelixGV/venice/actions/runs/3877390120/usage
> [build] Split integration tests into 18 buckets

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
Previous commit 4bb6c9115 enforces partition count when a store is converted to hybrid by providing hybrid configs. But it does not enforce partition count for another implicit hybrid conversion: when a store enables inc push, the store will be converted to hybrid.
The commit moves inc push store hybrid conversion logic to parent controller. It also moves partition count enforcement logic right before parent controller sending update_store admin message. As long as the store is converted to hybrid through parent controller update store and partition count is not specified, store partition count will be set to the value of default.partition.count.for.hybrid config.
testUpdateStore
CI
> [controller] Enforce default partition count for new inc push store

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/TestMainIngestionRequestClient.java
- internal/venice-common/src/main/resources/avro/IngestionTaskReport/v1/IngestionTaskReport.avsc
During the rollout of isolated ingestion we found that IsolatedIngestionBackend swallows the exception thrown in isolated ingestion process during ingestion. This does not align with the non-II behavior and will let server stuck in infinitive retry when there is a zombie resource in Helix that does not exist in ZK. When zombie resources exists, start consumption should throw exception after timeout as it could not locate the store version in the store repo. 
This PR fixes it by adding a new state in ingestion task report to declare there is exception thrown during the action and main process should also throw it.
Internel CI
Add new unit tests to cover the case.
> [server] Main process should throw exception when isolated ingestion process throws exception during the ingestion

- internal/venice-common/src/main/java/com/linkedin/venice/meta/SystemStore.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
The system stores can be updated even the user's store is disabled. For example, meta system store needs to be updated whenever there is a store config change or replica rebalance, and DaVinci push status system store still needs to take write from DaVinci or incremental push jobs.
System stores are for internal use and it won't affect the user store behavior.
Internal CI passed.
> [controller] Update system store read/write check to follow the ZK shared store

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/CachedKafkaMetadataGetter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/CachedKafkaMetadataGetterTest.java
This PR makes CachedKafkaMetadataGetter value update logic async so metric call to fetch the offset won't be slowdown due to slowness in Kafka metadata fetching.
This PR will issue async call to update value when it found the cached value TTL has expired. All the call to fetch the value will return immediately except the very first call, when the cache is empty.
TEST NOT ADDED, will added after main logic acknowledged.
> [server] Async update CachedKafkaMetadataGetter to avoid metric fetch slowdown

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/gh-ci.yml
- internal/venice-test-common/build.gradle
We want to make a dummy stage that all other tasks depend on, such that we can manage the status check on github easier.
Checked the dependency graph and confirmed that the dummy stage depends on every task.
https://github.com/adamxchen/venice/actions/runs/3952777862
> [build] make Github CI all depend on a dummy task

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/cache/VeniceStoreCacheStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/DeepCopyStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/AbstractStorageEngineTest.java
When active/active or write-compute is enabled, the consumer thread could read the local database, while the drainer threads could be adjusting the storage partition when receiving some special Control Messages/signals, such as StartOfPush or ReadyToServe signal.
Previously, we coded a fix to make sure the partition id list is always valid for the above race condition, but that fix couldn't make sure the partition will be accessible in consumer thread when the same partition is being adjusted, such as close and reopen.
This fix introduces an additonal safeguard to make sure the partition being accessed will be always valid and it also updates the locking granularity to be partition-level.
Internal CI
> [da-vinci][server] fixed an ingestion race condition

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
This PR fixes a bug: ingestion isolation heartbeat timeout uses wrong time unit so it won't timeout until 10000 seconds rather than 10 seconds. If request stuck for some reason, the forked process will exit first due to correct timeout detection. However, main process won't detect until 10000s and it will make following ingestion all failed.
This PR also makes following adjustments:
1. Adjust periodic requests(Heartbeat/Metric) timeout to 5 seconds, so it won't be blocking forever. It is expected to complete fast, unless soemthing wrong happened and we should be able to detect it in the short period.
2. Do not update heartbeat timestamp in metric request. Only update it in heartbeat request so it is easier for debugging.
3. Adjust logging to make it more clear.
4. Align default heartbeat …
> [server] Fix ingestion isolation heartbeat request timeout

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestsHandler.java
Since its been enabled in venice-9 for very long time, removing this config "venice.rocksdb.compute.access.mode" along with code using it. Also added object reuse in A/A ingestion path object lookup
CI build
> [server] clean up read compute access mode config, enable object reuse in write path lookups.

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
Currently, when chunking is enabled, for DELETE op records we calculate the target partition after adding a chunkedKeySuffix. However, for PUT ops we calculate the target partition before adding any suffix to the key. The suffix added to the key changes the partition on which the record lands. This means that the records with the same key but different operations may end up on different partitions.
To send records to the proper partition we need to get the target partition without chunkedKeySuffix addition to the key.
Internal CI
> [server][vpj] Calculate target partition before adding chunkedKeySuffix in VeniceWriter::delete

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
**Context:**
After adding a few fixes and more logging messages to isolated ingestion implementation, current test environment baking seems fine for ingestion behaviors / server start & stop for the most active clusters. However, it also reveal that metrics fetching failed constantly with log saying: "Unable to collect metrics from ingestion service".
With metrics fetching working correctly since beginning for Da Vinci use case, I suspect it is too many metrics number causing either metrics fetching timeout or message delivery failure, but will need to see the exact exception message to determine.
**Change:**
This PR tries to log exception message when main process failed to retrieve metrics from isolated ingestion process.
Internal CI, will need to reveal the exception in EI and propose …
> [server] Log exception message when forked process metric fetching request failed

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionRequestClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionStorageMetadataService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClientTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/TestMainIngestionRequestClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/davinci/DaVinciUserApp.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/davinci/ingestion/IsolatedIngestionServerTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
We found that ingestion isolation metric request cannot completed within 5s timeout in recent releases debugging. After frankenWar experiment we found that it takes ~15s to complete in venice-1 EI environment. 
This PR adjusts the request timeout as a short term solution to make sure metrics will be collected successfully. In the long term, we should find a solution to collect the metrics efficiently with much less query time.
**Changes in this PR:**
1. Introduces 2 new configs to control heartbeat and metric request timeout:
SERVER_INGESTION_ISOLATION_HEARTBEAT_REQUEST_TIMEOUT_SECONDS (default = 5s)
SERVER_INGESTION_ISOLATION_METRIC_REQUEST_TIMEOUT_SECONDS (default = 60s)
We can continue to tweak it with config change PR in venice-backend.
2. Minor refactor to let request client class …
> [server] Bump ingestion isolation metric request timeout to 60 seconds

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VeniceReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/chunk/ChunkAssembler.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputReducer.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
This PR adds:
1. Available RMD info during repush when chunking is enabled
2. In the KIF reducer when chunking is enabled, make sure DELETE message is included when RMD data is present.
Internal CI, adjusted integration tests and unit tests.
> [server] Fix A/A RMD missing during repush when chunking is enabled

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
client.startConsumption() could throw exception when there is zombie resource (resource removed from store repo but exists in Helix). Removing zombie resources is another effort, this PR improves isolated ingestion logic to handle such failure gracefully.
Also this PR removes some unused variables.
Added new unit test to cover logic changes.
> [server] Forked process should catch and log exception when resuming ingestion tasks

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VeniceMRPartitioner.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputFormat.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputFormatCombiner.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputKeyComparator.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputMRPartitioner.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReader.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputValueGroupingComparator.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputMapper.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/chunk/ChunkAssembler.java
- clients/venice-push-job/src/main/resources/avro/KafkaInputMapperKey.avsc
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputKeyComparator.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputMRPartitioner.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputValueGroupingComparator.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputMapper.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputReducer.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/chunk/TestChunkAssembler.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/ByteUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/ByteUtilsTest.java
- internal/venice-common/src/main/java/org/apache/avro/io/OptimizedBinaryDecoderFactory.java
- internal/venice-common/src/test/java/org/apache/avro/io/OptimizedBinaryDecoderTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputRecordReader.java
Without MR secondary sorting, the KIF reducer needs to cache all the messages belonging to the same key, which includes regular put/delete and chunks and manifest to figure out the latest value, which is not sustainable for some hot keys, which have been updated many times, and another known issue to make it worse is that Venice doesn't cleanup the previous chunks when there is a new update, since the backend will just replace the chunk manifest entry, but leave alone the previous chunks.
With secondary sort, the assembly of chunked messages is much simpler and cost efficient since manifest is always with a higher offset than the corresponding chunks, and there is no need to cache all the decoded messages any more.
Internal CI
> [vpj] Added a secondary sorting for KIF repush to reduce the memory usage in reducer

- build.gradle
Planned to use native git diff exclude syntax to exclude files we don't need for `diffCoverage` but it requires git version >= 1.9 and our internal CI has lower version.
Comment it out for now and will try to work on an alternative fix
jdk11 7584
jdk8 1180
> [build] Revert the git diff change

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionExceptionInfo.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
Previously, StoreIngestionTask is using a memory-bounded queue to buffer
the ingestion exception, which is working fine for most of the scenarios,
but it could block StoreBufferService if the exception queue is full without
draining, and it happened when some StoreInestionTask is closed, but there
are still some pending messages in the drainer queue, which would throw a lot
of exceptions to stuck the SToreBufferService since the exception queue is full.
The fix is to use Map to store the last exception per partition, which would never block.
In the meantime, this code change also fixed a couple of flaky tests in StoreIngestionTaskTest.
Also this code change modified the way how to track the ingestion exception per partition:
1. Record the ingestion exception whenever there is an exception …
> [da-vinci][server] Got rid of bounded memory queue for ingestion exceptions

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapperConstants.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/restart/TestRestartServer.java
Periodically refresh quota usage metric to report up-to-date values. Previously the metric was refreshed only during consumption, which led to incorrect (stale) values reported for fully ingested stores or/and after server restart. Also the change helps to reflect quota changes in runtime rather than on a new push.
Added additional checks to `TestRestartServer` to verify new
> [server] Add periodic refresh of quota usage metric

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
In PR #195, we started with `colo` to denote data centers. Felix suggested that `colo` was not an industry term and we decided to change it to `region`. I changed it in most places, but now realize that I missed one config name. Since this change is pretty new, changing the config to align with the industry.
Github CI will run for this
> [vpj] Change config name from parent.controller.colo.name to parent.controller.region.name

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
MergeConflictResult.mergeDeleteWithFieldLevelTimestamp() should not result input as its data was not prepend with int header buffer. Integration test with DELETE op reveals that it can lead to ingestion task failure.
Add new integration test logic to cover the case. Test both DELETE that partially removes some data and also fully removes data.
> [server] A/A merge delete with field-level TS result should not reuse input

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
There is a race condition between "STANDBY->OFFLINE" ST and "OFFLINE->DROP" ST since the former will be executed aysnchronously.
Previously, SIT only clears the exception at drop time, and when race condition happens, there will be some buffered messages in drainer queue, which will continue to throw exception and persist in SIT and no code will clear it up, which will result in excessive logging in SIT#processIngestionException.
The fix to prevent excessive logging even with the race condition:
1. Clear the exception list during un-subscribing.
2. Clear the exception list if there is no active subscription when executing SIT#processIngestionException.
> [da-vinci][server] Fixed excessive logging because of a race condition

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/AbstractMapReduceTask.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VeniceReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/chunk/ChunkAssembler.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/chunk/TestChunkAssembler.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/WriterChunkingHelper.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/WriterChunkingHelperTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/writer/VeniceWriterTest.java
This PR adds RMD chunking supports in KIF repush.
KIF reducer now is aware of the rmd chunking flag and will use this to determine whether to collect RMD chunks as well when encountering manifest as the last message of a key.
Integration Test
Added unit test in TestChunkAssembler
> [server] Support RMD chunking on KIF repush

- internal/venice-common/src/main/java/com/linkedin/venice/meta/PartitionDetail.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatus.java
Getter function PartitionStatus.getReplicaStatusMap() will cause duplicate info (replicaStatuses/replicaStatusMap) to be serialized into Znode, thus increase its contents. This commit fixes the issue by removing this getter function.
Internal CI tests passed.
> [controller][server] avoid serializing PartitionStatus.replicaStatusMap into ZK node

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
This PR adds resiliency to isolated ingestion remote request:
(1) startConsumption on forked process will set resource ingestion status, this PR makes sure it get reset (clean up) when exception is thrown (failure case), so following rollback(stopConsumption) triggered by Helix rollback operation will be successful. (Note: improvement for startConsumption slow down caused by zombie resource is not covered in this PR, will be covered by follow up PR)
(2) In case of regression or extreme request errors, a topic partition may be considered ingesting in remoted process but it might actually in main process. This can be blocking server shutdown if it happens to STOP_CONSUMPTION command.
To tackle this, this PR adds a simple logic to check if local ingestion service contains this resource when …
> [server] Add resiliency to isolated ingestion remote requests

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/DaVinciClientMetaStoreBasedRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/repository/DaVinciClientMetaStoreBasedRepositoryTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/meta/DaVinciClientBasedMetadataTest.java
The old metaSystemStoreChangeListener implementation to refresh metadata for meta system store only works if the repository is also subscribed to the corresponding user store. This is usually the case for a DVC use case but not in the fast-client use case. In FC we only subscribe to the store's meta system store and not the actual user store. Meaning the periodic refresh will do nothing after we bootstrap the corresponding meta system store's current version at the time of initialization. This is because we stored meta system stores in a separate map and the subscribedStoreMap in NativeMetadataRepository will be empty in the FC use case.
Fix:
1. On subscribe we also add meta system stores to the subscribedStoreMap in NativeMetadataRepository so subsequent refresh store will be triggered …
> [da-vinci][fast-client] Fix stale meta system store metadata in DaVinciClientMetaStoreBasedRepository

- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestVeniceAvroMapper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/CompressorFactory.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/GzipPool.java
1. Moved mapper creation as try-with-resources in `TestVeniceAvroMapper.java` to close properly.
2. This ends up closing the mapper leading to closing the `CompressorFactory->GzipCompressor->GzipPool->reusableObjectsThreadLocal`. But because `GZIP_COMPRESSOR` in `CompressorFactory` and `reusableObjectsThreadLocal` in `GzipPool` are defined to be static, it is not recreated for the next mapper instance for the next tests leading to failures. Changed them to be instance variables. 
Internal CI
> [vpj][test] Make GZIP compressor and its reusableObjectsThreadLocal to be instance variables

- clients/venice-samza/build.gradle
We added some unit tests to this module `venice-samza` so the module-level coverage fails as it defaults to 0.6.
Github CI.
> [build] override the module-level coverage for venice-samza

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-server/build.gradle
- services/venice-server/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorAccessor.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
New config: fast.avro.field.limit.per.method (default 100)
Resolves #XXX
> [server] Added config for fast-avro field limit per method (#257)

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputDictTrainer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputFormat.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReader.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputMapper.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/utils/VPJSSLUtils.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReaderTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputDictTrainer.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputReducer.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/GzipCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/NoopCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/VeniceCompressor.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compression/TestVeniceCompressor.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestBatch.java
This code change adds re-compression support in KIF repush, which means the new dest version can use a different compression algo from the source version.
Even for the same compression algo: dict compression, KIF repush will re-train a new dict in the dest version by default, and here is the config to reuse the same dict from the source version:
kafka.input.compression.build.new.dict.enabled: default `true`
This option is especially useful for streaming-only store since when dict compression is enabled for a streaming only store, the dict is built on dummy records, which are not quite representative.
Currently, dict build in KIF repush is built inside Azkaban Job thread and it doesn't support MR-based dict build yet.
Venice CI.
> [vpj] Recompression support in KIF repush

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/AbstractVeniceMapper.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestVenicePushJobCheckpoints.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
* Add javaDoc for `COMPRESSION_METRIC_COLLECTION_ENABLED` and `USE_MAPPER_TO_BUILD_DICTIONARY`
* Add more tests in `TestVenicePushJobCheckpoints.java` validating the flow for different value to the above configurations by validating checkpoints.
* Added `expectedExceptionsMessageRegExp` to other tests in the file as the tests in the file.
* minor cleanup of some test cases in `VenicePushJobTest`
Internal CI
> [vpj][test] Add javaDoc and more tests in TestVenicePushJobCheckpoints

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/gh-ci.yml
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/main/java/com/linkedin/venice/testng/VeniceTestListener.java
> [build] Save build artifacts on GH-CI runs

- .github/workflows/gh-ci.yml
- internal/venice-test-common/build.gradle
We introduced the Gradle flag to run unit tests in parallel in #262 and hope it can run tasks faster but turned out for some reasons, Gradle will run `diffCoverage` and `JacocoTestCoverageVerification` together at first, though the first task should depend on the latter one.
We didn't figure out how to make `diffCoverage` depends on the `JacocoTestCoverageVerification` yet so the changes above will cause the  `diffCoverage` fail immediately because the Jacoco coverage reports aren't ready yet - it's still running.
Right now, let's disable it and unblock other PRs (reported by #250 )
Github CI
> [build] Disable parallel running for unit tests

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputDictTrainer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputUtils.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputDictTrainer.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestEmptyPush.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybridQuota.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/utils/IntegrationTestPushUtils.java
For many real-time only stores, it is quite common to schedule an empty push to deprecate the stale entries.
This code change adds the dict compression support for the empty push to the hybrid stores.
In the meantime, this code change also fixes a bug in the existing KIF dict compression support, and it will decompress the payload in the source topic if the compression is enabled.
CI
> [vpj] dict compression for empty push to the hybrid store

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorServiceTest.java
When isolated ingestion process crash, we do have detection and restart mechanism but we do not keep leader status so when resuming ongoing TP ingestion, we will not resume the LEADER partition replica state correctly and LEADER partition could stuck forever.
This PR fixes it by keeping track of the LEADER status and resend STANDBY->LEADER for those LEADER replicas during restart of the forked process. No matter it was in LEADER or in transition to LEADER, this message will let it go through the promotion so it could become LEADER again.
Add new logic to cover resume ongoing ingestion logic unit test.
> [server] Isolated ingestion server should resume LEADER state when restarting forked ingestion process upon crash

- internal/venice-common/src/main/java/com/linkedin/venice/writer/update/UpdateBuilderImpl.java
This PR improves UpdateBuilderImpl by using SerializerDeserializerFactory to create serializer, so it should create one serializer per schema and reuse it per container instance.
> [samza] Use FastSerializerDeserializerFactory to fetch schema on cache when creating UpdateBuilderImpl

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/RmdWithValueSchemaId.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolverFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeGenericRecord.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/MergeGenericRecordTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeDelete.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeDeleteWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePut.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/rmd/RmdUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/writecompute/WriteComputeHandlerV2.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Mix use of value-level TS and field-level TS will result in race condition and result could be different when there are two PUT/UPDATE setField operations competing with each other.
This PR fixes the issue by making sure we always use field-level TS in A/A + WC store. When it sees a value level TS during RMD record initialization it will convert it to field level TS upon PUT/DELETE operation and will never collapse the field-level back to value-level.
Also, since WC flag is a store level flag, this PR also adds safeguard to existing version that has WC = false: when it sees its TS is field-level (due to UPDATE operation), it will still handle it correctly. (Ideally this version should be deprecated)
**Note for reviewer**: For changes in MergeConflictResolver, I only changed logic in put() …
> [server] Make A/A + partial update store always use field-level timestamp

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SeparatedStoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/utils/StoragePartitionDiskUsage.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallbackTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithPWiseAndBufferAfterLeaderTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithPWiseWithoutBufferAfterLeaderTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithTWiseAndBufferAfterLeaderTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithTWiseWithoutBufferAfterLeaderTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/utils/StoragePartitionDiskUsageTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/RedundantExceptionFilter.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/ImmutablePubSubMessage.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DataRecoveryTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/OneTouchDataRecoveryTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestPushJobWithEmergencySourceRegionSelection.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/helix/HelixLiveInstanceMonitorIntegrationTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapterITest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- internal/venice-test-common/src/test/java/com/linkedin/venice/utils/TestUtilsTest.java
The new mode is controlled by:
store.writer.buffer.after.leader.logic.enabled (default = true)
The current behavior (which matches the default of the new config), is to have 3 threads involved in leader ingestion:
1. Consume from RT -> DCR logic -> produce to VT
2. Producer callback -> enqueue to SBS
3. SBS run loop -> dequeue from buffer -> persist to local storage
When the new mode is enabled, it skips SBS and uses only 2 threads:
1. Consume from RT -> DCR logic -> produce to VT
2. Producer callback -> persist to local storage
In the new mode, the pub sub producer’s callback acts as the only buffer, instead of chaining two buffers one right after the other. Unless the producer callback queue has some weakness in the way it handles buffering, then this should reduce the end-to-end …
> [server] Introduced mode to disable post leader logic buffering

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapterITest.java
In the test, we want to simulate a case in which there are some records in the producer's buffer that 
are not yet sent to Kafka when an ungraceful close is issued. However, when producer::close() is not  
run before unblocking the producer's ioThread, records are sent to Kafka, which is not what we want.
To prevent sending records to Kafka, this PR added a check that guarantees producer::close() is
invoked before unblocking ioThread.
Resolves #XXX
Ran 200x2 iterations with the change in this PR:  [[402 tests completed, 1 failed](https://github.com/sushantmane/venice/actions/runs/4425159730/jobs/7759865659)]. The test failed once but it was due to topic creation timeout.
> [test] Fix flaky testProducerCloseDoesNotLeaveAnyFuturesIncomplete

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRead.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceDelegateMode.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/NoopRouterThrottler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/RouterThrottler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/StoreReadThrottler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceDelegateMode.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/ReadRequestThrottlerTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/RouterRequestThrottlingTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/StoreReadThrottlerTest.java
Router quota of a store per node in router is distributed as follows.  
quota = store_quota/num_router/num_partitions/num_replica.  The calculated quota for  a store with very high partition count and cluster with many routers becomes very small and causes frequent quota rejection in router. This PR adds a config to disable such calculation and consider only router count to distribute the store quota. Also add a buffer for per store quota config and removes optional in storage host name param.
unit tests
> [router] Implement per store quota in router

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryClient.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryExecutor.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryTask.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/StoreRepushCommand.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestDataRecoveryClient.java
This change does the following improvements to admin-tool execute-data-recovery command:
1. Remove password related codes as passing password plaintext from admin-tool to venice-tools is not an acceptable solution.
2. Support sentinel run in DataRecoveryExecutor. By having a sentinel run (normally requires manually inputting credentials thus creating a local Azkaban session file), the follow-up repush tasks can reuse the local session info for following interactions with Azkaban without the need to input user credentials before the session is expired. So, we only need to type in user credentials once for multiple stores.
If the sentinel run succeeds, it will continue to run (probably in parallel but depends on the executor pool size configs) for remaining stores. However, if the sentinel …
> [admin-tool] Some improvements to execute-data-recovery command

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AbstractVeniceAggVersionedStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedDIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/VeniceVersionedStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/VeniceVersionedStatsReporter.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggVersionedDIVStatsTest.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggVersionedIngestionStatsTest.java
Venice keep a backup version for possible rollback from an accidental bad/wrong push or other transient issues.
But Venice backup versions are deleted 
1. eagerly whenever a new push comes.
2. After a week of current version being online.
Since its a keep as a possible rollback, there is not much point in emitting tons of metrics for it. This PR restrict metric emission only to future and current versions.
> [server][da-vinci-client] Do not emit metrics for backup version

- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
This commit makes routers capable of handling request_topic queries to write to Venice. This will enable us to have more online writers.
The data consistency guarantees remain the same as that for all nearline writes.
Will test on GHCI
This will add a new endpoint on routers to be able to handle request_topic queries that were previously only handled by controllers
> [router] Routers can handle request_topic queries for nearline writes

- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/CollectionFieldOperationHandler.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/CollectionTimestampMergeRecordHelper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/SortBasedCollectionFieldOpHandler.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/TestSchemaUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/merge/CollectionMergeTest.java
- internal/venice-client-common/src/test/resources/testMergeSchema.avsc
Current RMD/PartialUpdate schema generation consider [null, map] and [null, list] as legit collection field, same as simple map/list, so we need to handle it properly, especially for the NULL value.
Existing non-AA partial update logic treat null as a special type of empty collection:
When setting field to null, it does set the actual value to null. If there is another collection merge operation (add/remove entry), it will first initialize an empty collection and perform collection merge.
This PR address the feature gap by introducing the same logic to A/A PartialUpdate:
(1) When setting a field to null, if it is in put only state (no active elements), it will set to null. 
(2) When setting a field to null, if it is not in put only state (has active elements), it will initialize new empty …
> [server] Align nullable collection field behavior in A/A + Partial Update with existing non-AA logic

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/JobStatusQueryResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/UncompletedPartition.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/UncompletedReplica.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestIncrementalPush.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/OneTouchDataRecoveryTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/JobRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorDelegator.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/JobRoutesTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
In the report of data recovery progress, in addition to job status in the recovering
region, we also want to know which partitions and replicas are still in progress or
in trouble. This commit makes job status api able to report uncompleted partitions
and replicas, as well as replica status, consumed offset, and status details like
the reason of failure.
Other changes:
1. Removes unused fields in JobStatusQueryResponse including messagesConsumed,
messagesAvailable, perTaskProgress, perPartitionCapacity, their related methods
and tests.
2. Removes Optional for statusDetails in OfflinePushStatusInfo.
Tested the improved api in testBatchOnlyDataRecoveryAPIs.
> [controller] Make job status api able to report uncompleted partitions and replicas

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadWriteSchemaRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadWriteSchemaRepositoryAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadWriteSchemaRepository.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- internal/venice-test-common/src/integrationtest/resources/supersetschemas/ValueV6.avsc
- services/venice-controller/build.gradle
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/supersetschema/DefaultSupersetSchemaGenerator.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/supersetschema/SupersetSchemaGenerator.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/supersetschema/SupersetSchemaGeneratorWithCustomProp.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/supersetschema/TestSupersetSchemaGeneratorWithCustomProp.java
- services/venice-controller/src/test/resources/superset_schema_test/v1.avsc
- services/venice-controller/src/test/resources/superset_schema_test/v1_without_custom_prop.avsc
- services/venice-controller/src/test/resources/superset_schema_test/v2.avsc
- services/venice-controller/src/test/resources/superset_schema_test/v3.avsc
- services/venice-controller/src/test/resources/superset_schema_test/v4_without_custom_prop.avsc
Currently, superset schema generation is ignoring all the properties from value schemas, which are critical for some use cases.
This code change exposes a hook to allow customized superset schema generation, so that different service deployment can apply customized logic during the generation.
This code change also provides a custom implementation, which takes a custom property name, and it will carry the custom property value to the superset schema during generation.
Unit test and integration test
> [controller] Expose hooks in Controller to allow customized superset schema generation

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedDIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStatsReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/LongAdderRateGauge.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/lazy/Lazy.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/ProducerTracker.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/validation/TestProducerTracker.java
- internal/venice-consumer/src/main/java/com/linkedin/venice/kafka/validation/KafkaDataIntegrityValidator.java
Eliminated a bunch of metrics of dubious value.
Also replaced the total-only metrics in HostLevelIngestionStats with LongAdders, wrapped inside a new class called LongAdderRateGauge. If this works well, we can consider adopting it elsewhere as well, but we need to keep in mind that the memory footprint of LongAdder grows proportionally to contention and can be quite high in the worst case, so it may never be appropriate to use this for more numerous metrics, like per-store ones.
Also refactored some of the DIV code to eliminate a hot spot... according to profiling, the remaining portion of the DIV code is ~20% of the CPU of what the whole thing used to take.
> [dvc][server] Metrics clean up

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeBase.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePut.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdate.java
- clients/da-vinci-client/src/test/resources/avro/PartialUpdateWithMapField.avsc
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/SchemaUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/CollectionTimestampMergeRecordHelper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/SortBasedCollectionFieldOpHandler.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/writecompute/WriteComputeHandlerV2.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/writecompute/WriteComputeOperation.java
Previous fixes only validates nullable collection field in low level unit tests, while there happens to have a lot of incorrect safeguard in the WC handler level.
This PR fixes the nullable collection partial update bug found in experiments:
1. setField to null should work for nullable collection
2. add/delete items to a nullable collection field which has null value should work.
Add a lot of new unit test logics in higher level to cover the changes and cases.
> [server] Fix bugs in nullable collection field in A/A Partial Update

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeBase.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeDelete.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePut.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdate.java
- clients/da-vinci-client/src/test/resources/avro/PartialUpdateWithMapField.avsc
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/SortBasedCollectionFieldOpHandler.java
This PR fixes bug that list object comparator fail to parse array schema in the nullable array field. This PR fixes the issue by parsing the union field and fetch the array branch.
Add more unit tests to cover different scenarios.
> [server] Fix array comparator schema bug in nullable array field in A/A Partial Update

- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/httpclient5/HttpClient5Test.java
With the latest bump of httpclient5 lib, we saw a lot of ConnectionClosedException in some prod cluster and it seems this is caused by the newly introduced connection config builder, which Venice wasn't using.
I manually tested this code change in prod, and the exception disapeared.
CI
> [router][fast-client] Picked up the new connect timeout builder from httpclient5

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
Added retry for cluster discovery via router in `RequestBasedMetadata`. The current implementation has this set to false which is resulting in flakiness in the jenkins test runs.
Also added a non-deterministic wait which uses a thin client to query a key. This will ensure D2 and the router are running before the tests run.
Testing suite
> [fc] retry for cluster discovery

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
This PR fixes a bug that MergeConflictResolver.update() will throw exception when it sees oldValue without a RMD.
The assumption is wrong because in the batch phase, AASIT call LFSIT logic to process batch data without creating RMD value. The fix is to find the correct writer schema for the original value and create the new field-level RMD schema.
Add new integration test.
> [server] A/A + WC should handle update on key that were written in the batch phase

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
The missing default value of `cluster.to.server.d2` has caused the failure of internal sanity test. We have null check for the map retrieved from this config key but don't have the check on whether this key exists or not.
github CI
> [router][controller] handle missing prop value for cluster.to.server.d2

- docker/apply-config-from-env-with-prefix.py
- docker/build-venice-docker-images.sh
- docker/venice-client/Dockerfile
- docker/venice-controller/Dockerfile
- docker/venice-router/Dockerfile
- docker/venice-server/Dockerfile
This patches imports a file inspired by the Pulsar scripts that allows injecting configuration variables from the ENV.
This is pretty common in K8S as you can use `configmaps` to configure the system.
Changes:
- adapt apply-config-from-env-with-prefix.py from Apache Pulsar
- support building on Mac M1 using docker buildx
This code is used by the Helm Chart that I am building
> [build][script] Dockerimages: add tools to replace ENV variables (k8s support)

- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/SystemStoreAttributesImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/VersionImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ZKStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/ListSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/MapSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/NoOpSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/RecordSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/SchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/UnionSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/AvroRecordUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/update/UpdateBuilderImpl.java
- internal/venice-common/src/test/java/com/linkedin/venice/schema/SchemaAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/AvroRecordUtilsTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/update/UpdateBuilderImplTest.java
- internal/venice-common/src/test/resources/AvroRecordUtilsTest/EvolvedRecordSchema.avsc
- internal/venice-common/src/test/resources/AvroRecordUtilsTest/OldRecordSchema.avsc
- internal/venice-common/src/test/resources/AvroRecordUtilsTest/SimpleRecordSchema.avsc
- internal/venice-common/src/test/resources/TestEvolvedWriteComputeBuilder.avsc
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/TopicManagerTest.java
The original intention of creating the `UpdateBuilder` abstraction was that the users need not be aware of other fields in the schema when making partial updates to records. Hence, it is possible that a framework generates the base `UpdateBuilder` object and the user code only fills in the fields they wish to update. In such a case, the schema of the value object might be different from what is used by the `UpdateBuilderImpl` object. This is possible if sub fields are evolved, but the writer is still only writing using older schemas.
To reduce the number of user disruptions, the `UpdateBuilderImpl` will make a best effort to adapt the records specified by the user to the schema that the `UpdateBuilderImpl` object uses. This is achieved by:
1. Filling in default values for fields that are …
> [samza] Adapt modified records in UpdateBuilderImpl to the specified update schema using default values

- clients/venice-producer/build.gradle
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/DurableWrite.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/VeniceProducer.java
- settings.gradle
Today, Venice only allows updates to it's records via nearline frameworks (currently, only Samza) or incremental pushes. This commit adds an API that online applications can use to write data to Venice. The writes are only eventaually consistent and read-after-write patterns are still not supported
Resolves #XXX
Github CI
> [online-producer] Add an interface for an online producer to write to Venice

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcher.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/StoreSchemaFetcher.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcherTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlySchemaRepository.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterResourceType.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
After PR #323, when writing partial update values that do not conform to the schema specified in the `UpdateBuilderImpl` object, the values will be adapted to the schema specified; by filling default values for missing fields and dropping additional fields.
In the case where fields are dropped, from the user's perspective, this is a data-loss. To minimize such cases, the application/framework must always use a superset schema to create the `UpdateBuilderImpl` object. This commit adds an API on the routers to fetch the superset schema and a corresponding function in the `StoreSchemaFetcher` interface.
Added unit tests. GH CI
> [thin-client] Add an API to fetch the current superset schema for a store

- build.gradle
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/NodesAndReplicas.java
Add manual tooling to enable disabled replicas through admin-tool `cluster-health-instances` command to take in optional parameter --enable-disabled-replicas which will call helix endpoint to reenable disabled replicas  which were previously disabled during some ingestion errors.
CI
> [admin-tool] Support passing options to cluster_health_stores to enable disabled replicas

- .github/rawWorkflows/gh-ci-alpini-parametrized-flow.txt
- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/rawWorkflows/gh-ci-validate-gradle-wrapper.txt
- .github/workflows/gh-ci.yml
- internal/venice-test-common/build.gradle
We have seen CI jobs fail frequently due to SSL errors while running the Gradle wrapper validation tasks. This could be due to the increased load on the server where the validation is run against. Since the use of the validation is only to validate if the `gradle-wrapper.jar` is not a trojan horse, we can run the check only once
Inspected visually, will wait for GH CI
> [build] Try to reduce CI job failures by running Gradle Wrapper validation only once

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcher.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/StoreSchemaFetcher.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcherTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlySchemaRepository.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterResourceType.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
This reverts commit 2499edfce9d127af870c6890239a0b1943027f08.
In [a discussion](https://github.com/linkedin/venice/pull/327#discussion_r1157488958) on PR #327, we decided to revert this change as we would not like to expose the superset schema concept to users. I will raise a separate PR to return the superset schema in the `getLatestValueSchema` call to align it with the behavior of `thin-client` and `da-vinci-client`
GH CI will run
Since this is a revert commit, the APIs added to the router and functions added to StoreSchemaFetcher will have been removed. This is okay since we have not yet cut a release tag, and this would not be a breaking change
> Revert "[thin-client] Add an API to fetch the current superset schema for a store"

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AbstractStoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SeparatedStoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedDIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStatsReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/WritePathLatencySensor.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggVersionedDIVStatsTest.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/VersionedDIVStatsReporterTest.java
Removed ~30 calls to the clock / ingested message.
Fixed a concurrency correctness issue in DIVStats' manually-maintained counters and changed success and duplicate message counters into LongAdders, since they are expected to be hot path counters. Also added the code to reset the success msg counter, which was missing (all other counters in this class had it...).
Changed consumed_record_end_to_end_processing_latency so that it gets recorded on every message. Previously, it was recorded only when DCR determined that the write should be dropped, which seemed incorrect.
Removed following metrics:
- leader_delegate_real_time_record_latency (consistently very low, didn't seem useful)
- current_idle_time (unused)
- overall_idle_time (unused)
> [dvc][server] Reduced hot path calls to the clock in metrics

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AbstractAvroStoreClientTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/LatencyUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
This code change added an infinite retry of store initialization when the first round of blocking initalization fails.
The infinite retry will happen in the background, and the request will fail before the async thread can successfully initialize the client. This is a resilience improvement and in theory, this behavior shouldn't happen often.
Unit test
> [thin-client] Async retry for store initialization when it fails

- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/OfflinePushStatus.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClusterAgnosticTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/helixrebalance/LeaderFollowerThreadPoolTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/init/ClusterLeaderInitializationManager.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorDelegator.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
Other changes:
- Backup version early deletion will happen befor resource assignment for new resource completes, which better matches the original intention of early backup version deletion.
Internal CI:
JDK11: 7317 (yellow)
JDK8: 1072, 1073 (red)
Also added a new test case to enforce controller shutdown needs to complete within 5 minutes.
> [controller] Release cluster level lock while sleeping for next poll of resource assignment status

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerCallback.java
In case of error while writing to Kafka the response from Kafka is null and this leads to a NPE.
Manually
> [common] Prevent NPE in case of Exception while writing to Kafka

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/D2ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/D2ControllerClientFactory.java
- internal/venice-consumer/src/main/java/com/linkedin/venice/client/consumer/ChangelogClientConfig.java
- internal/venice-consumer/src/main/java/com/linkedin/venice/client/consumer/VeniceChangelogConsumerClientFactory.java
- internal/venice-consumer/src/test/java/com/linkedin/venice/client/consumer/VeniceChangelogConsumerClientFactoryTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
This will enable us to leverage offspring's lifecycle aware to manage the d2clients
Unit tests
Yes?  but it's a good one I promise!  Basically the underlying d2 client can now be configured and managed by LinkedIn's deployment infra.
> [changelog] Add d2Client as a passable parameter to change capture client config

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionReportHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionStorageMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StatusReportAdapter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
**Issue:**
When there is no sufficient realtime messages compared to store hybrid lag setup, replica can report completion when processing TOPIC_SWITCH_RECEIVED. There is an additional ready-to-serve check in follower replica in TOPIC_SWTICH processing logic, but it could be a bit problematic with ingestion isolation.
If TS message is at offset X, when ingestion to this message, ready to serve check will report completed and II will shutdown and storage engine. However, the X is not checkpoint to OffsetRecord and when main process starts ingestion, it will re-consume TS message and report. 
**Impact:**
No impact to read/write/server restart, only additional TS is written into OfflinePushStatus only (not CV).
**Fix:**
1. Add force offset sync-up when II report completion
2. Since when …
> [server] Force sync offset records when ingestion isolation reports ingestion completion

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/TestTopicManager.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/TopicManagerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
New admin command:
--update-kafka-topic-min-in-sync-replica --url controller_url --kafka-topic-name topic_name --kafka-topic-min-in-sync-replica newMinISR
Controller will apply the changes locally, changing minISR for the topic in the local Kafka cluster only. Then Kafka cluster will adjust the replication factor number accordingly to minISR+2.
Added both unit test and integration test.
> [controller][admin-tool] Added tooling to update topic minISR

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcher.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/StoreSchemaFetcher.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcherTest.java
Per user request, we add a new API to retrieve all value schemas in StoreSchemaFetcher so they can use this API to compare and match incoming record with a existing schema.
New unit test
> [thin-client] Add a new API to retrieve all value schemas in StoreSchemaFetcher

- internal/venice-common/src/main/java/com/linkedin/venice/utils/KafkaSSLUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/KafkaSSLUtilsTest.java
Allow to configure kafka.security.protocol=SASL_PLAINTEXT and SASL_SSL.
Added new tests. Tested manually
> [common] Support configuring SASL authentication to Kafka

- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestsHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestsHandlerTest.java
Previously, when amplification factor is enabled, server needs to assess request's key to get sub-partitition id. Original implementation directly passes the entire back array from request's key byte buffer, it can contain extra bytes causing issues for deserialization. To avoid using the entire back array, we rely on `ByteUtils.extractByteArray` to get real meaningful key bytes. 
Besides, we create a unit test to simulate the real batch get behavior by using `SimplePartitioner`, which only consider the first byte of key to get partition id. If we keep using the entire back array with extra bytes, this test will fail. 
Internal CI
> [server][test] Fix using the entire back array in ByteBuffer to deserialize for multi-get request. 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRead.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ListenerService.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/HttpChannelInitializerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ListenerServiceTest.java
1. Two new configs to limit the concurrency of ssl handshakes for Venice servers: server.ssl.handshake.thread.pool.size server.ssl.handshake.queue.capacity
2. The ssl handshake executor will emit ThreadPoolStats which includes: active_thread_number, max_thread_number and queued_task_number
Resolves #XXX
Existing unit and integration tests, will also test in EI with VSC
> [server][common] Server ssl handshake throttling using dedicated thread pool executor

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/router/TestRead.java
Skip recording metric for control messages and the record size is returned as 0 anyways from downstream methods. Also fix stat 'LongAdderRateGauge' name to 'Rate' to match previous name and not break any existing alerts and added a check to LARG metric emission.
CI
> [server][da-vinci-client] Skip recording metric for control messages

- docker/build-venice-docker-images.sh
- quickstart/docker-compose.yaml
Docker compose pulls latest image from docker hub
The latest image is about 6 months old.
The change allows docker compose override of a tag.
To simplify  the dev workflow/scripting when version change, the build script also tags the latest built image as `latest-dev`.
```bash
cd ~/src/venice/docker
./build-venice-docker-images.sh
docker image ls | grep latest-dev
cd ../quickstart
docker compose up -d
docker compose down
TAG=latest-dev docker compose up -d
docker compose down
```
> [script] Docker: tag last images as latest-dev, allow to use custom tag in docker compose

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
This PR fixes an issue discovered in production deployment:
When a push is happening while bootstrapping an ingestion isolation enabled host at the same time, it is possible that old backup version is removed from the disk while the host already submitted the version partition ingestion request into child process. When the child process completes it will report COMPLETED back to main process and try to restart consumption on main process. Since the store version is gone in the store repo, the start consumption will wait 30s and throw. Also, the report client has 10 times retry and the report queue in isolated ingestion server is single threaded (to guarantee report order), each this kind of replica will take 300s and in that case it will end up taking too many time in bootstrap and might …
> [server] Isolated ingestion backend will handle ingestion completion report in async way

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/StoreMetadata.java
The FC currently throws a NPE if it tries to handle requests when it can't reach the servers and initialize its metadata. It does retry the metadata fetch but the issue is it doesn't block FC.
This PR adds logic to block FC requests if the metadata hasn't been initialized. This should also handle the case for when Dual Read is enabled so the FC will be blocked but the TC can still handle requests while the FC is retrying metadata initialization.
> [fast-client] Blocking Retry FC Metadata Init

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
1. Venice storage node quota is enabled by default for test classes using the AbstractClientEndToEndSetup.
2. Added a new integration test verifying storage node read quota behavior using fast client.
Existing and new tests
> [test] Added integration test for server read quota

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionRequestClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionRequestClientTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerTest.java
We observed a transient issue in test env that an OffsetRecord failed to be deserialized result in COMPLETED report failed. The expected behavior would be failing the push, however, server also failed to stop because we unsubscribe the topic partition in child process first before we check report result. Thus when new Helix ST comes in to this topic partition, non of the process will take it and hence stuck the stop progress.
This fix checks report before unsubscribe. If COMPLETED report failed (with retries), it should not do the unsubscribe. New Helix ST towards this topic partition (like standby->offline / leader->standby) should be accepted and executed and hence the server stop will not be stuck.
New unit test.
> [server] Isolated ingestion server should only unsubscribe partition when completion report is successful

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Problem: Migrated store system store flags in parent region are still false
after commit 1c31666. Even though addVersionOnly has code to enable system
store flags in the user store, existing store object is not updated and does
not have system store flag changes. Later, at repository.updateStore(store),
this store object is used to update store, and therefore, system store flag
changes are reverted.
Fix: In addVersionOnly, after the code of setting system store flags, obtain
the latest store and update the store object.
Test: Assert that migrated store system store flags in parent region are
enabled in the integ test. Test failed before the code change and passes now.
Described in summary.
> [controller] Fix migrated store system store flags in parent region

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/CachedKafkaMetadataGetterTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/partitionoffset/PartitionOffsetFetcherImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubTopicType.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/TopicManagerTest.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/TopicManagerITest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/TopicManagerIntegrationTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/writer/VeniceWriterTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
Previous refactoring of `TopicManager` cause these issues:
1) When `PubSubAdminAdapter` listing topics, the pubsub system could involve unsupported venice pub sub topic type
2) There is race condition inside PartitionOffsetFetcherImpl, as internal kafka consumer is not thread safe. 
3) When `TopicManager` updating min in-sync replica configuration, the integer config is not converted to string. 
This PR adds Unknown pub sub topic type to avoid listing topic failure, unify the lock usage inside `PartitionOffsetFetcher` to avoid `ConcurrentModificationException`, and adds back the integration test `TopicManagerITest` for `TopicManager` test by constructing the `PubSubBroker`. Besides, a test case for testing race condition of `PartitionOffsetFetcherImpl` has been added to …
> [venice-common][test] Support unknown pubsub topic type and fix race condition in PartitionOffsetFetcherImpl

- .github/workflows/gh-ci.yml
- .gitignore
- internal/venice-test-common/build.gradle
Resolves NPE during spotlessCheck gradle task caused by bad .gitignore rule. Recent change in it filtered out some java classes, which in turn broke spotless.
./gradlew spotlessCheck
> [build] Enable spotlessCheck in GH CI

- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PushStatusDecider.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/WaitNMinusOnePushStatusDeciderTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
When Venice disables a leader replica due to error,  Helix ideally elects a new leader. But the while counting the number of error replicas, we include previously disabled replica count so that it does not disables more than 1 replica. But it  double counts the ERROR status of the disabled replica and previously disabled replica leading to fail the push. This PR fixes the double counting of ERROR replicas.
CI
> [controller] Do not count previously disabled replica as ERROR replica

- build.gradle
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
Today, the code coverage check runs for all sub-modules. It does not check if it is a leaf. Our code structure uses nested sub-modules such as `:internal:venice-client-common`, `:internal:venice-common`, etc. 
If some code in a submodule is changed, which is not easily testable, we might choose to reduce the coverage threshold for that module. We have provision to do this via `diffCoverageThreshold` property in the `build.gradle` for that module.
However, the `diffCoverage` check runs on all modules. Hence, the coverage thresholds need to be applied to modules higher in the directory tree too - which might not be ideal.
This PR makes the coverage checks to be enforced only on modules that are at the leaf of the tree.
GH CI. Adam is also testing it locally.
> [build] Enforce coverage only on leaf submodules

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionRequestClient.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
This PR fixes an issue found in test env when testing store migration. When migration is aborted, store is deleted and store partition is dropped. However, the drop action throws exception in getStoreOrThrow in MetaSystemStoreReplicaStatusNotifier#report() method. This exception in non-II env should abort the drop partition behavior. For II, it did not drop the partition, same as non-II logic, but the resource ingestion status was cleared only in main process, but not in II process. (We maintain resource ingestion status: which process owns the resource in both processes together). This out of sync of metadata lead to II process reject future ingestion action of the same topic partition (likely triggered by a successful migration). 
Since we have a logic to retry indefinitely to make sure …
> [server] Isolated ingestion backend will make sure topic partition metadata get cleaned up together in case of exception

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/PubSubTopicConfigResponse.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
New admin command:
--get-kafka-topic-configs --url <controller_url> --kafka-topic-name <kafka-topic-name>
WIP
> [admin-tool][controller] Added tooling to get kafka topic configs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroSpecificDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DelegatingAvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/StatsAvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/StatsAvroSpecificDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/factory/CachingDaVinciClientFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/StatsAvroGenericDaVinciClientTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/stats/BasicClientStats.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/stats/ClientStats.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/stats/BasicClientStatsTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
This code change adds the following basic metrics for DaVinci read path:
1. Request.
2. Healthy/Unhealthy request.
3. Healthy request latency.
4. Key count.
5. Successful ratio.
Currently, this code change only adds the above metrics for single-get and batch-get requests, and if there is need to support other request types, we can add them later.
Currently, this feature is controlled by `DaVinciConfig#readMetricsEnabled`, and it is off by default.
CI
If DaVinci customers would like to enable the read path metrics, they need to explicitly enable it by `DaVinciConfig#readMetricsEnabled`, which is off by default.
> [da-vinci] Added some basic metrics for DaVinci read path

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/DaVinciClientMetaStoreBasedRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/repository/DaVinciClientMetaStoreBasedRepositoryTest.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/factory/ClientFactory.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/StoreMetadataFetchMode.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/VeniceClientBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/VeniceClientBasedMetadataTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientDaVinciClientCompatTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/fastclient/utils/ClientTestUtils.java
Previously in PR #253, we deprecated the da-vinci client based metadata fetch in favor of a thin-client based metadata fetch. Recently, we saw in production that the thin-client based metadata fetch can cause quota exceeds exception when there are lots of fast-clients deployed.
This commit adds back the wiring for setting a da-vinci client based metadata fetcher to temporarily mitigate the issue. In the future, however, we would like to move completely to the server-based metadata fetch.
GH CI
- By default fast-clients will use a DaVinci based metadata instead of a thin-client based metadata
> [fast-client] Allow using DaVinci client based store metadata fetch for fast client

- internal/venice-common/src/main/java/com/linkedin/venice/helix/ZkRoutersClusterManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RoutersClusterConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RoutersClusterManager.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/RoutersClusterConfigJSONSerializerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/RoutersClusterConfigTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/helix/ZkRoutersClusterManagerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/NoopRouterThrottler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/ReadRequestThrottlerTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/RouterRequestThrottlingTest.java
There is a bug in how `ReadRequestThrottler` initialized store throttlers in the constructor. 
`buildAllStoreReadThrottlers` relies on various config values , but they were initialized after the method was called. So after a router bounce it will initialize the store throttlers with buffer values of `0` but inside store update handler it will rebuild the throttler with proper value of the configs. This leads to diverted per store router quota in the same cluster depending on the state of start time of various hosts and store version changes.
This PR fixes the order of initialization and also removed code to update `quotaRebalanceEnabled` which is never called in router code.
CI unit tests.
> [router] Fix initialization bug in router quota throttler

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/VeniceIngestionBackend.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
With all the recent bug fixes, it is unlikely that main process and isolation process will run out of sync for a particular resource's metadata. However, when real bug happens, current infinite retry logic might lead to blocking Venice server from shutting down, which is not acceptable as it needs manual shutdown for all impacted hosts in the cluster.
This PR adds an additional safeguard to guard this behavior. When HelixParticipantService is shutting down, we will inject a boolean into IsolatedIngestionBackend notifying it is preparing to shutdown. When Helix manager is sending stop consumption command to all the resources, if a resource has out-of-sync metadata and reject remote execution, we will skip the retry.
Added new unit test to test the behavior.
> [server] Additional safeguard to make sure server will always be able to shutdown successfully with ingestion isolation

- build.gradle
DaVinciBackend currently is not unit testable and would require major refactor before we can write unit tests for it. Similar to VeniceHelixAdmin, hence adding it to the exclude list.
Test only change, existing tests
> [test] Exclude DaVinciBackend from unit test coverage requirement

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientDaVinciClientCompatTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
Users that have ran DaVinci based metadata or store repository will run into the following exception: java.lang.UnsupportedOperationException: The implementation ThinClientMetaStoreBasedRepository should not be subscribing to system store...
when they try to run DaVinci client with thin client based store repository. This is because DaVinci backend will try to restore all on disk stores upon initialization, including meta system stores. User would then have to perform manual cleanup in the data.base.path in order to proceed.
1. Added logic to skip restoring meta system stores so they will only be subscribed explictly when needed.
2. Added an integration test with static data.base.path to reproduce the exact problem.
Existing tests and added new integration test
> [da-vinci-client] Do not attempt to restore meta system store on DaVinciBackend initialization

- internal/venice-common/src/main/java/com/linkedin/venice/system/store/MetaStoreWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/system/store/MetaStoreWriterTest.java
This PR tries to enhance the produce logic in meta store writer. When VW#sendMessage throws exception that might be result from for example stale DNS information or failed internal state (like finalized checksum issue) due to bug, we might want to retry by restarting a new VW and clean internal state so it might be able to have healthy producer and internal state to produce the message. If it fails all retry we should log the error message.
Add new unit test to cover the retry logic.
> [server] Restart meta store writer when hitting produce exception

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- internal/venice-client-common/build.gradle
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/SslUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/SslUtilsTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/KafkaSSLUtils.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterCreateOptions.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/kafka/ssl/TestProduceWithSSL.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
This code change is leveraging `conscrypt-openjdk-uber` lib to support openssl in Http Client lib being used by Router. Once this is verified in Router, we will apply the similar optimization to fast-client.
New Router config:
router.http.client.openssl.enabled: default false
This code change also removed the Kafka openssl support, which was proved to be unstable.
Resolves #XXX
CI
> [router] Added openssl support to Router http client and removed Kafka openssl support

- clients/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
This PR tries to resolve slowness in VeniceSystemProducer's send() method. 
Through profiling we found that serializer is slow, in this PR we use FastAvro serializer instead.
Also schema-string based map is also found slow in get() as schema.toString() is heavy. We rely on FastAvro Factory's internal map cache to speed up. 
TODO
> [samza] Use Fast-Avro serializer in VeniceSystemProducer

- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixBaseRoutingRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixCustomizedViewOfflinePushRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixExternalViewRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadOnlyStoreRepositoryAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/HelixCustomizedViewOfflinePushRepositoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/HelixReadOnlyStoreRepositoryAdapterTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestBatch.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybridQuota.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/helix/TestHelixCustomizedViewOfflinePushRepository.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/MockTestStateModelFactory.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
ExternalView(EV) and CustomizedView (CV) repository listens to IdealState from Helix to filter invalid state changes. This add a lots of delay to execute those callbacks (Helix callbackHandler).  Currently EV is used by the controller and CV is used by router and servers to query replica statuses and mostly server and routers would be exposed to the problem of slow transitions. 
This PR
1.  moves the ideal state watch to EV.
2.  make CV repository filter invalid states by query store version metadata. 
That way updates router and servers host wont add many callbacks to helix and hopefully results in faster state transitions.
test WIP
> [controller][server] Move ideal state listener to EV repository and read Store Metadata for CV updates

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/AbstractStoreMetadata.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/ClientRoutingStrategyType.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/HelixScatterGatherRoutingStrategy.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/HelixScatterGatherRoutingStrategyTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/VeniceClientBasedMetadataTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/utils/TestClientSimulator.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
1. RequestBasedMetadata was forcing the fast client routing strategy to be HelixScatterGatherRoutingStrategy which is unintended. The routing strategy should be selected based on config.
2. HelixScatterGatherRoutingStrategy did not take InstanceHealthMonitor into consideration. Meaning it will continue to route requests to bad hosts when routing table is out of sync. This is witnessed when servers are going through deployment in our certification cluster and causing latency spikes.
3. ClientRoutingStrategy is difficult to set/instantiate in factory. Changing the config to an enum and instantiate the actual strategy in AbstractStoreMetadata instead.
Existing unit and integration tests. Added new unit test for HelixScatterGatherRoutingStrategy.
> [fast-client] Fix routing strategy issue when using request based metadata update

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
VeniceRouter.main() was not honoring passed in SSL parameters when running, opting to instead use the test environment settings by relying on a self signed certificate.  This PR preserves this default behavior (as it is useful in testing), but adds the ability to override this behavior so that custom options can be passed.
running normal test suite which relied on this path.
No
> [router] Add Property keys for configuring SSL for RouterServer.main()

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
This was a client feature request.  We expect underlying pubsub implementations to provide this functionality, so it seemed a low hanger.  Expected semantics of the behavior of the new API's s documented in the interface javadoc attached to this PR.
Added new integration test cases
Yes, but only extends the interface.  Will not impact current users.
> [changelog-consumer][client] Add seek by time API's to Venice Changelog Consumer

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/RetryUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/RetryUtilsTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubAdminAdapter.java
The contains topic check expects to spent at most 180s with 3 retries, however with current impl, it will spent a few hundred ms on 3 fast attempts and fail as we don't wait enough time to begin the next retry attempt.
This PR uses DelayFunction in FailSafe module to add a new retry mechanism to make sure after each attempt, it will wait until the desired attempt total duration is spent before it begins next attempt.
With the setup, in the worst case (topic does not exist), it will be:
Attempt 0, wait until T=60s, Retry 1, wait until T=120s, Retry 2, wait until T=180s, Retry 3, Fail loudly.
Add a new unit test to make sure new try mechanism is working as expected.
> [server] Make sure containsTopic check spent desired amount of time on retries

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/VeniceProperties.java
Revert access specifier for a VeniceProperties constructor
NA
> [all] Revert access specifier for a VeniceProperties constructor

- .github/workflows/gh-ci.yml
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/AvroStoreClientGzipEndToEndTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/AvroStoreClientZstdEndToEndTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
1. Moved `AvroStoreClientGzipEndToEndTest` and `AvroStoreClientZstdEndToEndTest` to `IntegrationTestsG` as it was taking too much time in `IntegrationTestsI`
2. Trimmed down the number of tests run for the above classes
3. Trimmed down the number of tests in `testFastClientWithLongTailRetry` which needs to be fixed further as its flaky, will handle it as a separate task, as these issues are blocking other PRs to be merged due to test failures.
4. Added timeouts for all tests
These tests will be be cleaned up further:
1. once we validate `SERVER_BASED_METADATA`, we will probably remove the cases with `DA_VINCI_CLIENT_BASED_METADATA` and `THIN_CLIENT_BASED_METADATA`
2. once `useStreamingBatchGetAsDefault` is validated, the code and tests for single get based batch get will be removed
GH CI
> [test] Mitigate FC integration tests taking long time in CI

- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/RetryUtilsTest.java
This PR fixes the flaky test by introducing some non-trivial time on the attempted action. With additional logging we found that the total time spent was 1999ms/2000ms, less than expected > 2000ms. This might be because the RetryUtils's calculation precision loss on wait time. In theory, the logic should be good enough, hence just make the action a bit longer to make sure 2 * 1 second wait + 3rd attempt > 2seconds.
Unit test.
> [test] Fix flaky unit test RetryUtilsTest#testFixAttemptDurationOnSupplier

- services/venice-router/src/main/java/com/linkedin/venice/router/streaming/VeniceChunkedResponse.java
- services/venice-router/src/test/java/com/linkedin/venice/router/streaming/VeniceChunkedResponseTest.java
This commit fixes a regression introduced in PR #412, where a race condition would result in VeniceChunkedResponse's responseMetadata to be not initialized yet. The field is actually not necessary at all, and its content can be determined the one and only time it's used, rather than stored ahead of time. Also eliminated the responseMetadataWriteInitiated AtomicBoolean, since the responseCompression field being null already has an equivalent meaning. Therefore, VeniceChunkedResponse now carries two fewer properties.
> [router] Fixed a NPE occurring in router's streaming batch get

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryWorker.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/MonitorCommand.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestDataRecoveryClient.java
This rb supports a new argument (datetime) in the admin-tool data-recovery monitor command. With this new argument, monitor command checks if there exists a successfully pushed version (current version) for the given store in the target region whose start time is newer than the input argument. If it does, monitor can report success, otherwise, it keeps polling/reporting a future version push job status until the future version is finished. During the real data recovery scenario, we can set the datetime argument to a timestamp at which we believe all related components (e.g. Kafka service) are recovered. If the argument is unspecified, we choose `now` as the default value.
- Unit test
- Internal CI test
- Manually tested against EI environment
example output (with masks)
```
lelu@lelu-mn1 …
```
> [admin-tool] Support a new datetime argument in data-recovery monitor

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixResources.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/ExecutionStatusWithDetails.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorDelegator.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/ExecutionStatusWithDetailsTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushStatusCollectorTest.java
Offline Push monitor today only monitors Venice Server push status (changes from ZK). However, when Da Vinci is also reporting ingestion status to this store push job, only VPJ is monitoring the DVC push status store but not push monitor. When the failure from DVC is deterministic (OOM detected by memory limiter (not yet implemented) for example), it will lead to infinite retry of DVC future version ingestion (as the bad version becomes current version after backend push completed).
This PR fixes the issue by introducing a new PushStatusCollector class that has a scheduler thread to periodically scan DVC push status enabled store and aggregate server push status with Da Vinci push status to come up with the aggregated status. With this change, when controller detects server push status …
> [controller] Offline push status will also monitor Da Vinci push status store if enabled

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/AbstractVeniceProducer.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/OnlineProducerFactory.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/vson/VsonAvroSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfig.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfigTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestEnablingSSLPushInVeniceHelixAdminWithIsolatedEnvironment.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestHybridQuota.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
1. Make routers return if the Kafka cluster is SSL enabled in request_topic call
2. Set Kafka `security.protocol` config for online producer
3. Deprecated `ssl.to.kakfa` due to the misspelling and added a config `kafka.over.ssl` to replace it
Manual tested so far
> [router][producer] A couple of fixes related to SSL for online producer

- build.gradle
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/restart/TestRestartController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/init/ControllerClientBackedSystemSchemaInitializer.java
Problem: Today only system schema cluster leader controller is able to register new meta system store value and write compute schemas into local region system store. When meta system store value schema upgrades, we must deploy system schema cluster leader controller first, and then deploy other controllers, which is painful and error prone.
If another controller deploys first, does not register new schemas, but produces value with new schemas, servers could not find the schema in local region system store for deserialization. Meta system store ingestion will fail.
Fix: When any controller starts, call system schema cluster leader controller to register unknown meta system store value schema and write compute schema via controller client. If this step fails, controller start will fail too, …
> [controller] Make any controller able to register meta system store schemas

- build.gradle
- clients/venice-producer/build.gradle
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
- gradle/spotbugs/exclude.xml
Add a CLI tool to write a single key-value pair to Venice
```
usage: venice-producer [-cp <arg>] [-dsn <arg>] [-h] -k <arg> -s <arg> -v
<arg> -vu <arg>
Write a single key-value pair to Venice
-cp,--configPath <arg>       Path to config file
-dsn,--d2ServiceName <arg>   D2 service name for cluster discovery.
Mandatory if Venice URL is a ZK address
-h,--help                    Print this help message
-k,--key <arg>               Key string
-s,--store <arg>             Store name
-v,--value <arg>             Value string
-vu,--veniceUrl <arg>        Router URL with http or https scheme or ZK
address if using D2
Please report issues to Venice team or at
https://github.com/linkedin/venice/issues
```
Tested manually
> [producer] Add a CLI to write a single key-value pair using OnlineVeniceProducer

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
[Server] When processing per-store Admin messages, the default threadpool size of 1 would result in one bad admin message
to cause timeouts for other stores admin operations. In effect breaking the isolation of stores.
Added test to demonstrate this effect. Changed default thread pool size to 3 to prevent this situation
> [Server] Increase default worker threads for admin tasks to avoid starvation

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
Today pushjobs are failed if they run over `bootstrapToOnlineTimeoutInHours` time limit, but its checked in server in `checkLongRunningTaskState` which kicks in only if its actively ingesting. But if due to some reason it does not ingest the job is left hanging forever. This PR add a check in vpj to honor the bootstrap time limit config and fail the push proactively.
> [vpj] Fail pushjobs running over 24 hr bootstrap limit

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Fix for prod issue when decomming old parent broker. This should be all thats needed based on what calls we make to read the controller parent broker list. It's ok to barf an exception here at time of truncation and move on as if/when the broker comes back, topic clean up service will run through and clean up anything left behind.
> [controller] Make Controller Resilient to Parent Broker Unavailability

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubClientsFactory.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/AbstractTestVeniceHelixAdmin.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestClusterLevelConfigForActiveActiveReplication.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithIsolatedEnvironment.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/KafkaBrokerFactory.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerContext.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/VeniceControllerContextTest.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
This PR focus on:
1) Change dependency of `MapreduceClientJobClient` from `testImplementation` to implementation, as internal project needs to depend on this module and run test implementation. 
2) Add `PubSubConsumerAdapterFactory` and `PubSubAdminAdapterFactory` to `PubSubClientFactory`'s constructor.
3) Change `VeniceController` constructor to make `PubSubClientFactory` configurable for test and downstream project depending on it. 
Resolves #XXX
internal CI
> [test][server][dvc] Change test dependency and add consumer and admin adapter to PubSubClientFactory.

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
It was noticed that many threads were being created from `RouterBackedSchemaReader` which caused OOM issues in controllers. While the root cause of why so many threads were being created and not getting cleaned up is still unknown, this is a preemptive optimization to not create executors where they are unnecessary
GH CI
> [all] Do not create schema refresh executors unless necessary

- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreType.java
- internal/venice-common/src/test/java/com/linkedin/venice/common/TestVeniceSystemStoreType.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
1. Execution order of admin messages for user store and their corresponding system store matters.
If the messages are processed in separate queues in AdminConsumptionTask then the following race is possible: expected order: create user store -> empty push to system store -> delete user store execution order: empty push to system store -> create user store -> delete user store or create user store -> delete user store -> empty push to system store.
The empty push to system store will fail due to VeniceNoStoreException.
2. Added new unit test for similar scenario as the race described above.
Existing tests and added a new test
> [controller] system store admin messages should be processed in the same queue as their user store

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroGenericStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroSpecificStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/VsonGenericStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpTransportClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpsTransportClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/TransportClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AbstractAvroStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/StatTrackingStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/TestAvroStoreClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
There is a cyclic dependency between `AbstractAvroStoreClient` and `RouterBackedSchemaReader` which needed creating a new store client for each internal `RouterBackedSchemaReader` so that `RouterBackedSchemaReader` could release resources when it is closed.
Recently, we've added the notion of ownership of the store client in `RouterBackedSchemaReader`. With this change, we no longer need to create a new store client for each `RouterBackedSchemaReader` and so, we can now always close the `SchemaReader` object when the store client itself is closed.
GH CI
This commit introduces breaking changes to the public API of two classes:
1. `AbstractAvroStoreClient`: Removed the `getStoreClientForSchemaReader` method
2. `HttpTransportClient`: Removed the `getCopyIfNotUsableInCallback` method
However, …
> [all][tc][controller] Always close SchemaReader in AvroStoreClients. Reuse store clients in Controller

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/MetaSystemStoreReplicaStatusNotifier.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/notifier/TestMetaSystemStoreReplicaStatusNotifier.java
Found this some time ago in Venice Server in test env with (both ingestion isolation on and off)
This may result in OFFLINE->DROPPED being rollbacked by Helix mechanism, which results in storage engine lingering. (Although it might eventually be cleaned up by cleaner service, I still think it is not good action to have).
Existing tests.
> [server] Do not throw exception in MetaStoreNotifier for DROPPED action when store is being deleted

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestVeniceHelixResources.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushMonitorUtilsTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushStatusCollectorTest.java
If many instances are not reporting heartbeat status to DaVinci pushstatus store, we can assume the ongoing push is not healthy. In this PR if more than certain number of instances are not alive, and its been more 5 mins its returns ERROR and fails the push job.
CI build
> [controller] Report push error if too many DVC instances are dead

- clients/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientFactory.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpTransportClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpsTransportClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/ClientFactoryTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/TestTransportClient.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/client/store/TestSslTransportClient.java
The Store Client currently has some limitations about performances: it uses only HTTP 1.1 and opens only at most 2 connections. This means that you cannot have more than 2 inflight requests.
Un order to achieve better latencies this patch introduces:
- configuration parameters to tune the number. of HTTP 1.x connections
- upgrade of HttpClient to 5.x, with HTTP2 support
- a configuration flag to require HTTP2
Please note that HTTP2 works only with TLS enabled on the Router  
The code change is almost covered by existing tests, as the core of the change is the upgrade of HC to 5.x.
Currently there is no documentation about the client
> [client] Allow to configure the number of connections and upgrade HttpClient to 5.x async with HTTP2 support

- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClientCompatibilityTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/httpclient5/HttpClient5Test.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/D2ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/D2ControllerClientFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/TestD2ControllerClient.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/davinci/ingestion/IsolatedIngestionServerTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controllerapi/TestControllerClient.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/endToEnd/TestChangeCaptureIngestion.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/DaVinciTestContext.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/KafkaBrokerFactory.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/MockD2ServerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/MockHttpServerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/MockVeniceRouterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/integration/utils/ZkServerWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/InMemoryKafkaBroker.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
To instantiate a URL based ControllerClient, we need to pass in a list of Router or Controller URLs. Since this is a static list that might be configured by operators, it can grow stale over time to include hosts that are no longer running Venice routers or controllers on that port. When querying these endpoints the following cases are possible:
1. A different service is now listening on that port and it is likely to throw a 4XX for route not supported or some 5XX that might trigger some error scenarios in the new service.
2. `java.net.ConnectException` is thrown. This is the most probable option since even though different services might get deployed on that host, the ports are kept mutually exclusive.
In error scenarios, we wish to try our best to provide the user with an actionable …
> [all] Raise ConnectException only if all hosts in ControllerClient are unreachable

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestClusterLevelConfigForActiveActiveReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
This PR aims to fix the bug that when changing store type (e.g. batch <-> pure hybrid <-> inc push), we set the store A/A config based on default config only but not looking at store's existing A/A config: If the default A/A config for new store type is false and existing config is true, we should also keep A/A enabled.
Update existing integration test to reflect the logic.
> [controller] Check store existing A/A config when updating store type

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
It seems this causes some bad behavior, otherwise the effect is that the internal schema reader will try and make it's own d2client
> [changelog] Move d2Client to innerclient config

- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/controller/TestAdminToolEndToEnd.java
On Kafka side, if a topic hasn't been fully deleted before asked to create a new topic with the same name, it can fail. This change fixes the issue by waiting all topics to be fully removed from Kafka service before proceeding to the next steps in the test.
Internal CI (No testWipeClusterCommand failure in Venice-WcTest: #8046, #8047; Venice-WcTest8 #1225, #1226)
> [test] Fix flaky test TestAdminToolEndToEnd.testWipeClusterCommand

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryEstimator.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryExecutor.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryMonitor.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/EstimateDataRecoveryTimeCommand.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/MonitorCommand.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/StoreRepushCommand.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestDataRecoveryClient.java
This is a change intended to fix an issue discovered with the logic for instantiating new Params in the Data Recovery module. There were multiple Commands using the same Params pointer incorrectly, resulting in some inconsistencies between the intended target store, and which store may actually wind up being targeted by the command.
Local build, intent to test on EI store(s) before merge.
> [admin-tool][data-recovery] Fixes an issue with parameter instantiation.

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/LogConfigurator.java
The shell producer currently prints loads of logs that clutter the terminal. The previous attempt at stopping logs did not stop all logs. This one prevents all logs from being printed to the terminal.
Tested locally
> [producer] Disable logs for the shell producer

- internal/venice-common/src/main/java/com/linkedin/venice/utils/PartitionUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterFactoryTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFiles.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/init/InternalRTStoreInitializationRoutine.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/AbstractTestVeniceParentHelixAdmin.java
Ensures the number of partitions for a hybrid store is based on storage quota. This should help to better scale ingestion path. Also fixes a bug in `PartitionUtils` that caused the min partition count assigned when unlimited quota is specified.
Updated TestParentControllerWithMultiDataCenter to verify new behavior.
> [controller] Calculate partition count for hybrid stores based on storage quota

- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
During push, if too many instances become offline and crosses per cluster config `MAX_OFFLINE_INSTANCES_ALLOWED` Helix puts the cluster into maintenance mode. This PR would detect such maintenance mode and marks such pushes as ERROR which will fail the pushjob. This will stop further pushes during target colo push or waiting infinitely for regular pushes when cluster in such state.
GHCI
> [controller] Check for cluster health during poll status query

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoreRoutesTest.java
When a store doesn't exist, the `list_future_versions` API on controllers returns a map with 0 as the future version. This commit changes the response to error with a `STORE_NOT_FOUND` ErrorType
> [controller] Return proper ErrorType in getFutureVersion API when Store doesn't exist

- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
Fixed a map config parsing issue
unit test
> [common] Fixed a map config parsing issue

- gradle.properties
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceSingleGetPath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/AggRouterHttpRequestStats.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
- services/venice-router/src/test/java/com/linkedin/venice/router/AggRouterHttpRequestStatsTest.java
Currently is KV profiling is enabled it generates key value fine grained profiling stats for each store which creates many metrics (num_stores X 20 X 2 X 2). This PR makes KV profiling metrics emit per router total only. 
GHCI
Added a new metric named `value_size_in_byte` but kept the per store response_size metrics intact.
> [router] Make key/value profiling sensor per router only

- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
If the OfflinePushStatus was dropped right before handling COMPLETED/ERROR report, it will throw NPE in scanner's periodic scanning logic and lead to push status stuck. This PR fixes issue by checking if retrieved OfflinePushStatus is null before action. Also it adds a try catch in scanning logic to make sure if there is any exception happening in one topic, it will not break scanner.
> [controller] Make sure push status handlers check OfflinePushStatus before action

- internal/venice-common/src/main/java/com/linkedin/venice/utils/SharedObjectFactory.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/SharedObjectFactoryTest.java
Currently, `SharedObjectFactory` is not thread-safe and if there are multiple threads trying to create an object that previously didn't exist, then there can be multiple objects created. While this may be okay in most cases, the issue occurs when releasing these objects, the objects do not have the correct refcount. Hence, there will be an `Reference counter underflow` error. This commit attempts to fix this issue by wrapping all operations using the synchronization offered by `ConcurrentHashMap#compute`
Added a unit test
> [samza][vpj][controller] Make SharedObjectFactory threadsafe

- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/merge/SortBasedCollectionFieldOpHandler.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPartialUpdateWithActiveActiveReplication.java
- internal/venice-test-common/src/integrationTest/resources/PartialUpdateWithRecordMapField.avsc
This PR fixes the bug in A/A partial update map collection merge tie breaking logic.
**Problem:**
Existing logic tries to get the map schema and then try to compare the value of two active keys that have same TS.
However, there are issues: We are actually not comparing the map item value but instead we are putting KeyValPair (which contains key and value) to the comparator and in certain case it will lead to exception and SIT ingestion failure. If the map value type is primitive (int/string or so) it will be fine as the logic in comparator won't cast the value, however if it is record, then the logic will try to cast the value and throw.
**Change in this PR:**
Instead of comparing value, let's only compare KV's key string to break tie. This should be more performant considering (1) we …
> [server] Fix bug in A/A partial update Map field merge update timestamp tie braking logic bug

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/RocksDBMemoryStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushStatusCollectorTest.java
This code change makes the following changes:
1. Keeping polling DaVinci status if it is empty before encountering the following conditions:
a. DaVinci status becomes non-empty.
b. Server ingestion status becomes terminal: Complete or Error.
2. Updated the default DaVinci empty status retry to be 6 (3 mins).
The reason to have more empty retry is as follows:
1. When firstly create the version, DaVinci may not send ingestion status quickly enough before
PushStatusCollector polls the push status system store, which might return empty result, which would lead
Controller think that all DaVinci instances have completed the ingestion.
2. Right now, there are two logic, which will trigger empty DaVinci status retry to minimize the risk, but it is
still a best effort:
a. Before DaVinci status …
> [controller][da-vinci] Updated PushStatusCollector to allow more chances to poll DaVinci status and fixed several DVC memory limiter issues

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/exceptions/VeniceValidationException.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/validation/NoOpValidator.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/validation/Validator.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- docs/user_guide/write_api/push_job.md
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/VersionCreationResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/RegionUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/TestRegionUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/datarecovery/DataRecoveryManager.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
This commit completes the targeted region push feature by adding the functionality of automatically pushing data to the rest of regions when targeted region push is used. User can turn off this config so they can chain the targeted region push as they want.
newly added unit tests and integ tests.
See the newly added doc for this.
> [vpj][controller][doc] Add post validation and consumption for targeted region push

- build.gradle
The OSS maintainer has already released the fix required by Venice in 5.2.2: https://issues.apache.org/jira/browse/HTTPCORE-750
CI
> [router][fast-client] Picked up the latest release of httpcore5

- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubTopicPartitionInfo.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/TopicManagerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/consumer/ApacheKafkaPubSubConsumerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubTopicPartitionInfoTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/MockInMemoryAdminAdapter.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
The way we get the replication factor for VTs is not reliable since `partitionInfo.replicas().length != RF` in some  
cases (e.g., offline replicas,  partition reassignment). Besides Kafka doesn't offer an API to get RF at the moment.   
Hence use `kafka.replication.factor` config value as it is a safer option.
> [controller]  Do not lookup RF of existing topics when creating a new topic as it may not be accurate

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/InputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
In VPJ, `PushJobZstdConfig` calculates number of bytes to be collected per input file baed on the configurable sample size(default `200MB`). If that ends up being less than size of first value in file, no samples get collected from that file potentially leading to skipping zstd dictionary creation. Changing this to add an extra check to add at least 1 sample per input file(until reaching 200MB).
github ci
> [vpj] Force collect at least 1 sample per input file for zstd dict

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
In the VPJ, we call the controller 4 times to get the `StoreResponse` which is wasteful. For configurations, they are unlikely to change during a push job and should be cached to reduce the duplicate call. This PR caches the response so we can reduce the duplicate calls by 2.
GHCI
- [x ] No. You can skip the rest of this section.
> [vpj] Consolidate controller requests for retrieving store info

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java
If server rocksDB directories have resources which are bad and cannot be opened by rocksdb during restart, they are not loaded into storage engine and none of the background resource cleaner kicks for those directories. This leads to massive disk space waste. This PR if rocksDB open fails, it cleans up unused resources.
GHCI
> [server] RocksDB cleanup on bad store/store versions

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/utils/IsolatedIngestionUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/D2/D2ClientUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/d2/D2ClientFactory.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
Currently, when creating a D2 client via `D2ClientFactory`, the code only waits for 5 seconds. This commit increases the timeout to 60 seconds.
GH CI
> [vpj][samza][controller][tc][fc] Increase timeout for D2Client startup

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/init/ControllerClientBackedSystemSchemaInitializer.java
Current behavior: After helix manager initialization, controller finds system schema cluster leader controller url from helix manager, build controller client using the url, register schemas via the controller client.
Problem: During deployment, when leader controller A stops, helix assigns controller B as leader. When A's controller service starts again, helix wants to hand over leadership to A so it transits B from leader to standby. Before transition completes, B is still the leader and all A's requests are sent to B. But since B clears in-memory store map, it throws no store exception to A's requests. A fails to start.
Fix: Before helix manager initialization, controller builds controller client using url or d2 configs and registers system schemas. Since the controller instance is …
> [controller] register meta system store schema before initializing helix manager

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionReportHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
1. Fix a log bug happen during ingestion isolation handover: When the SIT partition is shutdown in time, the old logic still log wrong msg that it does not stop in time and the log is ERROR level. This causes in house deployment tooling to report ERROR logging issues. This PR fixes the logic to only log it when it is actually times out and reduce the log to WARN level.
2. Remove StoreVersionState.toString() logging in handover as this is the underlying SpecificRecord's toString and will print out binary data we store inside SVS. This PR simply remove the logging as we are not interested into the content of the SVS. 
Existing tests.
> [server] Minor improvement of ingestion isolation logging

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/TestPubSubTopic.java
The old measure is out of the date with what we actually use for ready to serve. So this will remove false alarms and give more transparency in our metrics.
Resolves #XXX
test suite
> [server][da-vinci] Standardize ingestion stats on ready to serve lag check

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/system/store/ControllerClientBackedSystemSchemaInitializer.java
- internal/venice-common/src/test/java/com/linkedin/venice/system/store/ControllerClientBackedSystemSchemaInitializerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
When a server starts, if system schema initialization is enabled, it will call controller to check and register new meta system store schemas. Therefore, servers can be deployed before controllers when meta system store schema is upgraded. Controller url (for open source users who do not want to onboard d2) or d2 configs must be provided to enable system schema initialization at start time.
Unit test and integration test
> [server][controller] Support meta system store schema registeration at server start time

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/PubSubBrokerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- internal/venice-test-common/src/test/java/com/linkedin/venice/utils/TestUtilsTest.java
This commit adds support for passing non-mergeable broker details to the Venice components. This 
means that if there is a key that is present in the broker details for multiple brokers, only the value for 
the last broker will be kept. Previously, all values for the same key would be concatenated together.
> [pubsub] Support passing non-mergeable broker details

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducedRecordContext.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/RmdWithValueSchemaId.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/RmdSerDe.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/AbstractAvroChunkingAdapter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/ChunkedValueManifestContainer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/ChunkingUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/SingleGetChunkingAdapter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallbackTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/RmdSerDeTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/chunking/ChunkingTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChunkAwareCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/WriterChunkingHelper.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/writer/VeniceWriterTest.java
This PR aims to clean up deprecated value and RMD chunks to avoid storage engine chunking leaks. When we processed a partial update request, it will also try to look up old value and RMD manifest and will produce DELETE messages to old value and RMD chunks to remove them.
Note:
1. As discussed offline, this solution will be a short term solution to clean up disk space, but it will not clean up Kafka version topic garbage chunks as even after log compression there will be one DELETE message left per deprecated chunk key, but we think this is acceptable at this stage as DELETE message is considered small and we can work on long term complete solution later.
2. Based on current implementation, we could not fully delete a RMD of a key. We can only insert an empty RMD into it. (If this is not …
> [server][dvc] Delete deprecated chunks when processing partial update

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/ByteUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/ByteUtilsTest.java
- internal/venice-test-common/src/jmh/java/com/linkedin/venice/benchmark/RocksDBLookupApiBenchmark.java
RocksDB offers a set of multiget API besides single-get API, and it claims that it should improve the performance by parallelizing the IO operations with linux kernal 5.1 or later.
We also want to benchmark these APIs for PT format since in theory, it should reduce the cost of JNI because of less JNI calls.
Based on the benchmarking, the performance of multiget API is performing worse than single-get API (which is weird), and we would like to keep these benchmarks and code, so that we can evaluate BT format in the future.
PT benchmark result (subset):
Benchmark                                                   (BATCH_SIZE)  Mode  Cnt      Score      Error  Units
RocksDBLookupApiBenchmark.measureMultiGetAPI                           1  avgt    5  18195.987 ± 1484.887  ms/op …
> [server] Integrated with RocksDB multiget API and benchmark

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/ConsumerIntegrationTestWithSchemaReader.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/init/SystemSchemaInitializationRoutine.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/SchemaRoutes.java
Existing implementation updates the superset schema id as soon as we add a new value or superset schema. This is problematic because in parent controller we perform schema addition in the following order:
1. Add new value schema (superset schema id is also updated).
2. Check if A/A is enabled and update RMD schema.
3. Check if WC is enabled and update derived schema.
This execution order allows race to happen when superset schema id is updated but the corresponding RMD schema and derived schema are not available yet. Resulting in failure in downstream consumers like the Venice storage node during ingestion.
The fix is to perform superset schema id as the last step and separate it into its own update store admin message.
Existing unit and integration tests.
> [controller] Update superset schema ID after all value schema related operations

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/SchemaRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/SchemaRoutesTest.java
To resolve KME upgrade deployment order, one action is to make child controllers and servers register KME from the code into local system store at startup time. However, KME is only backward compatible. Adding schema that is not fully compatible via controller client is not supported. This commit supports adding value schema with id and compat type via child controller client.
New unit test
CI
> [controller] Support adding value schema with id and compat type via child controller client

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputDictTrainer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputFormat.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReader.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputDictTrainer.java
Previously, `KafkaInputDictTrainer` would initiate a new KafkaConsumer per partition, which results in ton of KafkaConsumer related logs printed in VPJ log, which would make VPJ log analyzing less efficient. This code change will reuse the same consumer when extracting data messages from different partitions to reduce the total amount of logs produced by KafkaInputDictTrainer.
CI
> [vpj] Reuse KafkaConsumer when building dict from an existing topic

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
During ingestion error in leader, we add  disabled partition map config in helix. But even if those resources are dropped later, the disabled map not cleared, which later might cause znode to blow up. This PR will cleanup disabled partition map (by calling enable, which will clear the node) during dropping of resources.
unit test
> [controller] Cleanup Helix disabled partition map

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/transport/HttpClient5BasedR2Client.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/fastclient/utils/ClientTestUtils.java
A bunch of flaky fast-client tests (eg `testFastClientGetWithDifferentHTTPVariants `) fail with the following socket timeout exception. 
Caused by: java.util.concurrent.ExecutionException: com.linkedin.venice.client.exceptions.VeniceClientException: java.net.SocketTimeoutException: 1000 MILLISECONDS
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
This PR tries to increase the timeout to 5s to reduce flakiness.
GHCI
> [client][test] Increase socket timeout for HTTP client5

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceResponseAggregator.java
In the VeniceResponseAggregator, the router used to check that all responses from servers had a consistent compression scheme, and then if they were 200 OK. This leads to misleading logs about inconsistent compression in cases where servers return an error, since the error itself may be missing the compression header.
This commit flips the order of the checks to avoid the misleading logs.
> [router] Fixed order of checks in compressed batch gets

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
[test] Fix flaky FastClientServerReadQuotaTest
The previous test behavior would stop making requests as soon as it receives one
VeniceClientRateExceededException while checking the metric of only one server.
This is problematic when the test cluster has multiple servers since the rejected
request might not be handled by the server metric that we picked arbitrarily. 
The fix is to refactor the test to take multiple servers into consideration when
validating their metrics.
Test only fix and verified by running the test itself multiple times.
> [test] Fix flaky FastClientServerReadQuotaTest

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryClient.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryExecutor.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryTask.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/DataRecoveryWorker.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/EstimateDataRecoveryTimeCommand.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/MonitorCommand.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/StoreRepushCommand.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/meta/RepushViabilityInfo.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestDataRecoveryClient.java
This set of changes adds additional logic for handling batch stores during a repush request. Additionally, this commit moves some functionality for determining whether or not a store can be repushed to the task execution level, parallelizing a previously introduced single-threaded linear check.
Tested on a couple EI stores.
```
$ java -jar venice-admin-tool-all.jar --execute-data-recovery --recovery-command venice-tools --stores akozma_test_store_EI,HB_VPJtarget_ei-venice-0,cert-histogram-dataset-copy --source-fabric ei-ltx1 --dest-fabric ei-ltx1 --extra-command-args 'repush kafka --force --format' --datetime "2023-07-24T20:00:00" --url "http://ltx1-app5774.stg.linkedin.com:1576"
2023-07-19 14:14:36 INFO [DataRecoveryExecutor] [main] [store: akozma_test_store_EI, status: started, message: …
```
> [admin-tool][data-recovery] Added handling for batch stores during store repush.

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/listener/response/ReadResponse.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/predicate/EqualsRelationalOperator.java
- internal/venice-avro-compatibility-test/build.gradle
- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClusterInitializer.java
- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/utils/ClassPathSupplierForVeniceCluster.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeRequestWrapper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/CosineSimilarityOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/CountOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/DotProductOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/HadamardProductOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ReadComputeOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/protocol/request/enums/ComputeOperationType.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compute/ComputeUtilsTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/vson/TestVsonAvroDatumWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/schema/SchemaAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/ConsumerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPartialUpdateWithActiveActiveReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestStreaming.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/ComputeRouterRequestWrapper.java
The upgrade of Avro from 1.9 to 1.10 carries one major change which is that GenericRecords no longer return null for fields they do not have, but rather throw AvroRuntimeException. This makes the read compute code fail.
This commit also optimizes various usages of Avro in the read compute hot path, including:
- The ComputeRequestWrapper now carries a list of operation result fields, which is looked up once at the start of the query, rather than redundantly during each processed key. This reduces map lookups from 1/op/key to 1/op/query.
- The getNullableFieldValueAsList function removes 1/op/key map lookups.
- The validateNullableFieldAndGetErrorMsg function removes 1 to 2/op/key map lookups.
- The ComputeRouterRequestWrapper now uses a static final deserializer rather than looking it up …
> [server][dvc][tc] Avro fixes, optimizations and 1.10.2 upgrade

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClientCompatibilityTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfig.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/consumer/ApacheKafkaPubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceMultiClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/TopicManagerIntegrationTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Previous server and controller prepare specific properties map with only kafka related properties from server config and controller config, respectively. To support other type of pub sub system, we may need to pass additionally properties to pub sub adapters. Instead of creating new empty properties, we just use copied properties of server configs and controller configs and the overriding logic is still the same. 
Besides, fix some additional configs merge logic issues inside test utils. 
internal CI
> [controller][server] Pass all properties from server and controller to pub sub adatpers to include special properties we need.

- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/AvroSerializer.java
- internal/venice-client-common/src/main/java/org/apache/avro/generic/DeterministicMapOrderDatumWriter.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/serializer/AvroSerializerTest.java
When using `DeterministicMapOrderDatumWriter`, the code compares the keys to sort them. However, it assumes that the datatype is a `Comparable`. The code also doesn't specify the generic classes, leaving it up to the runtime to figure that out. Since `CharSequence` is not a comparable, If the map contains a `String` and a `Utf8`, the runtime will use either one of the two as the class for the generic type (say `Utf8`) and on running `compareTo`, it will try to cast `String` to `Utf8` which throws an exception:
```class java.lang.String cannot be cast to class org.apache.avro.util.Utf8```
This change copies code from `CharSequence#compare` (only available in JDK11+) to allow comparing two `CharSequence` objects.
Added UT. GH CI.
> [all] Fix Avro serialization errors when map contains keys of different subclasses

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerCallback.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerCallbackTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapterITest.java
When the producer is closed forcefully, we skip the callback processing. Nevertheless, we  
ensure that any future returned by the producer to the caller is completed, either normally  
or exceptionally.
> [pubsub][kafka] Skip callback processing when the producer is closed forcefully

- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreType.java
- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/common/TestVeniceSystemStoreType.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
The system stores are mostly read from controller and their router metrics are hardly useful for debugging system store issues as most of the time system store issues stems from write path to them. But nonetheless for each user store router emits 2x the number of system store metrics, one for its DVC push status and one for meta store system stores. This PR will stop emitting system store router metrics thus cutting down router metric count by 1/3.
GHCI
> [router] Skip registering router metrics for system stores

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
This PR fixes the bug that TransientRecord is not saving correct value/RMD manifest when updating a key. In the current code, it will try to save the old value/RMD manifest and it will be fetching the same value/RMD manifest until cache expires. This mean chunk is still leaking. 
This PR fixes it by updating the TransientRecord cache's manifests when VeniceWriter invokes ChunkAwareCallback#setChunkingInfo() API. This is prior to the next value record processing so it will be processed correctly.
Will add unit test to make sure LPC API is called.
> [server] Make sure TransientRecord saves correct value and RMD manifest

- internal/venice-common/src/main/java/com/linkedin/venice/meta/AbstractStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Bug fixed in this PR: During store migration, versions created in the destination cluster only replicates the hybrid configs, partition count from the version configs in the source cluster; other configs values are from the store configs. However, store configs might change after current version is created; if destination cluster uses those updated store configs, it could conflict with the current version resources like Kafka topics, Helix resource, etc.
Incident due to the above bug: a store didn't have compression enabled when current version was created, and later compression was enabled. After store migration, destination cluster thought compression was enabled and thus trying to leverage ZSTD dictionary in the topic which didn't exist.
Chunking feature would have the same problem, …
> [controller] Store Migration Fix: destination cluster will replica version configs from source cluster

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/SchemaAndToString.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroComputeRequestBuilder.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroBlackHoleResponseStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderV3.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderV4.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeRequestWrapper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/CosineSimilarityOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/CountOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/DotProductOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/HadamardProductOperator.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ReadComputeOperator.java
- internal/venice-client-common/src/main/resources/avro/ComputeRequest.avsc
- internal/venice-client-common/src/test/java/com/linkedin/venice/compute/ComputeUtilsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/client/store/StoreClientPerfTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceComputePath.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/path/TestVeniceComputePath.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/ComputeRouterRequestWrapper.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Prior to this commit, the ComputeRequestWrapper class was used across client, router and server, but these components all had different needs and the end result was a bit awkward, as it led to the class needing to be constructed in a way that was not fully initialized, only to have the rest of the init happen later by mutating its internal state. This seemed error-prone.
Furthermore, the class attempted to serve as a way to evolve the read compute wire protocol, and although we did evolve read compute, the way we evolved it was already compatible anyway, and if we had evolved it in less compatible ways, it's not clear that the original structure of this class would have been good enough to support such evolution.
In this commit, we are cleaning all of that up and simplifying many aspects …
> [tc][dvc][router][server] Cleaned up some read compute tech debt

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfig.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfigTest.java
Currently we extract Kafka client properties from VeniceProperties based on prefixes. However, this approach  
sometimes  leads to passing irrelevant properties to clients, as these properties may contain settings intended  
for other client types. When irrelevant properties are passed to Kafka clients they log a message which ends up
polluting logs and can cause confusion.  
Fixed this issue by adding an additional property check to ensure their validity for the specific client being constructed.  
Resolves #XXX
> [controller][server] Use only relevant configurations for Kafka client construction

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBSstFileWriter.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
For stores without pushstatus system store, controller logs get flooded with full excception stacktrace. Also in server most of the time RMD file sst writer are empty, so do not print any warn log for it.
> [controller][server] Reduce logging in controller, server

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/AbstractVeniceProducer.java
This commit allows the users of online producer to specify arbitrary configs for the underlying `VeniceWriter`
GH CI. Tested manually
> [producer] Allow online producer users to specify underlying VeniceWriter configs

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DataRecoveryTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/datarecovery/DataRecoveryManager.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/datarecovery/TestDataRecoveryManager.java
This rb targets several issues in the data recovery API:
1\. Today, during data recovery, only when the version number from the source equals to the current version in the dest fabric, we bump a store's version to LargestUsedVersionNumber+1 in parent and use the increased version for data recovery. So, if the version number from the source is less than the current version in the dest, we simply use it in the dest. As a result, data recovery can not complete successfully, because backup version cleanup thread can kick in, consider it as an expired backup version, and delete it.
As a fix to it, we should extends current condition, and increase the store version for such cases as well.
On the other hand, if the version number from the source fabric is larger than current version in dest …
> [controller][test] Fix issues in data recovery API

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroGenericStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroSpecificStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/VsonGenericStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpTransportClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/HttpsTransportClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/transport/TransportClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AbstractAvroStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/StatTrackingStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/TestAvroStoreClient.java
This change reverts a bunch of changes that were made in PR #472.
There was a deadlock in production that had the following stacktraces in the threaddump
Thread 1:
```
"veniceClient.WarmUpExecutorService-22-4":
at com.linkedin.venice.client.store.AbstractAvroStoreClient.discoverD2Service(AbstractAvroStoreClient.java:352)
- waiting to lock <0x00007f1f2e518070> (a com.linkedin.venice.client.store.VsonGenericStoreClientImpl)
at com.linkedin.venice.client.store.AbstractAvroStoreClient.getRaw(AbstractAvroStoreClient.java:459)
at com.linkedin.venice.client.store.InternalAvroStoreClient.getRaw(InternalAvroStoreClient.java:24)
at com.linkedin.venice.client.schema.RouterBackedSchemaReader.executeRouterRequest(RouterBackedSchemaReader.java:349)
at …
```
> [all][tc] Create a new internal store client for schema reader

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/ReplicationMeadataRocksDBStoragePartitionCFTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/ReplicationMetadataRocksDBStoragePartitionTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
For some DaVinci customers, they want to validate DaVinci memory limiter feature without affecting prod in canary instance, and currently, it is not possible since DaVinci memory limiter will apply globally.
To simplify the test, this code change introduces a new config: 
```
ingestion.memory.limit.store.list : default empty
```
When it is specified, only the stores configured will enforce memory limiter, and if it is not specified (default), all the stores in the same DaVinci instance will enforce memory limiter.
With this way, the customer can specify a test store to test DaVinci memory limiter feature, and when the bootstrapping of test store fails because of memory exhaust, only the push job to the test store will fail.
CI
> [da-vinci] Added one more config to simplify the DaVinci memory limiter test

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
During target colo push for stores with DaVinci client, or during data recovery,  Venice uses data recovery client endpoints to enable push to rest of the colos, but for DaVinci client running in follower mode does not have the configs needed for data recovery which leads to DaVinci host ingestion failure. 
This PR skip data recovery code path in Davinci clients.
GHCI
> [server] Do not set data recovery for DaVinci client

- docs/_config.yml
Tested on fork: https://nisargthakkar.github.io/venice/
> [doc] Disable markdowns from "javadoc/legal" dir from showing up on the website

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
The push job details are generated and send through controller for various offline tracking of pushjob health. During post canary colo job, it missed to send out pushjob details to the controller, thus it would appear in pushjob detail store that other colo did not finish the pushjob. This PR fixes that issue.
Integration test.
> [vpj] Send pushjob details during post-target pushjob

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/QueryTool.java
The CLI tools to read (`QueryTool`) and write (`ProducerTool`) data to Venice do not handle complex types currently. This commit adds the support to read and write data where the store has complex data types in the schema.
Tried locally for a user store
> [thin-client][producer] Handle complex types in query tool and producer tool

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/AbstractPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/AbstractStateModelFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelDualPoolFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumerAction.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ParticipantStateTransitionStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/AbstractVenicePartitionStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerParticipantModelFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
Previously in O/B/O mode, there is an explicit delay from OFFLINE to DROPPED transition; we missed this delay when building L/F mode. This PR added the delay back.
CI ongoing.
> [server][da-vinci] Added a configurable delay from OFFLINE to DROPPED transition

- build.gradle
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
We see some host contained in  `/CONFIG/PARTICIPANT` path but not in `/INSTANCE` of a cluster .  If queried a list of instances using `ZKHelixAdmin::getInstancesInCluster` and called `getDisabledPartitionsMap` which throws HelixException. This PR tries to skip such exception to continue cleaning the helix resources. Also bumps the Helix dependency to 1.1.0 which would resolve the exception log in zk node deletion code path.
GHCI
> [controller] Catch HelixException in deleteHelixResource

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/DumpAdminMessages.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
Previously admin tool construct `ApacheKafkaConsumerAdpater` without relying on `PubSubConsumerFactory#create()`, then bootstrap servers url property cannot be correctly translated into kafka property. In this change, using factory to create this adapter class to leverage the config translation functionality and unifying the factory usage of admin tool and naming. 
Test with building admin tool locally and run.
> [admin] Fix admin message dumper for admin tool.

- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriterFactory.java
Previous refactoring removed this constructor, it has caused downstream dependency issue. To unblock this we add back the constructor and mark it deprecated, as we want to let downstream to use the other constructor to pass specific `PubSubClientFactory`.
Github CI
> [venice-common] Adding back `VeniceWriterFactory` constructor to unblock dependency incompatible issues. 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/listener/response/AdminResponse.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/listener/response/AdminResponseTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/SslUtils.java
- internal/venice-client-common/src/main/java/org/apache/avro/io/ByteBufferToHexFormatJsonEncoder.java
- internal/venice-client-common/src/test/java/org/apache/avro/io/ByteBufferToHexFormatJsonEncoderTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-common/src/test/java/com/linkedin/venice/acl/StoreAclHandlerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinitionTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
This code change adds a new command to dump ingestion state, also Venice Server will skip the ACL check for admin request endpoint since there is no PII data.
In the meantime, this code change will skip compression dict in the response since it is not readable and string-format the `Fixed` type.
CI
> [server][admin-tool] Improve Server Ingestion State Dump

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
Recently, we've added support to emit `DELETE` messages to clean up leaked chunks (#535) but we hadn't handled this in the topic dumper tool.
Tested by dumping data from an actual topic
> [admin-tool] Handle DELETE messages for deprecated chunks in KafkaTopicDumper

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReader.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/VeniceKafkaInputReducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/chunk/ChunkAssembler.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/chunk/TestChunkAssembler.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
The behavior of the regression is as follows:
1. The chunk delete message will use `-10` as schema id.
2. When KIF encounters a delete message, it would ignore the schema id and treat the key as a top-level key and it would use non-chunk-suffix to decide the key portion from the composite key, which is wrong.
3. During shuffle and sort phase, if there is no collsion between the regular keys and the wrong key extracted from (2), no issue, and if there is a collision (which is rare), this entry will be removed from repush, which would result in data loss.
This code change fixes the regression in the following way:
1. Use delete.schema_id to decide how to handle delete key.
2. Skip the chunk cleanup message when assembling large message in repush. There is an existing E2E test for this …
> [vpj] Fixed KIF repush to handle chunk cleanup messages

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/listener/response/HttpShortcutResponse.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/OutboundHttpWrapperHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerConnectionStatsHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStatsContext.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StatsHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/grpc/handlers/GrpcOutboundStatsHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/AggServerHttpRequestStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerConnectionStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
- services/venice-server/src/test/java/com/linkedin/venice/grpc/ServerStatsContextTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ServerConnectionStatsHandlerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Two gauges (and its max) to show server's live connections count from routers and servers.
- router_connection_count (Gauge and OccurrenceRate)
- client_connection_count (Gauge and OccurrenceRate)
These metrics are collected by a new `ChannelInboundHandlerAdapter`, the `ServerConnectionStatsHandler` that will collect stats accordingly on `channelRegistered` and `channelUnregistered.
Additional per store and total metric for misrouted requests based on invalid store version.
- misrouted_store_version_request_count
The check only occurs on error requests, the corresponding flag is set on the `HttpShortcutResponse` if it's determined that the request had a misrouted store version. `StatsHandler` will emit the corresponding metric on its. `ServerStatsContext.errorRequest`
TODO will have unit …
> [server] Code change for server connection count metrics

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceClusterConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/AbstractStateModelFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/StateModelIngestionProgressNotifier.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionWiseKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StorePartitionDataReceiver.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicWiseKafkaConsumerService.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/InputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VsonSequenceFileInputFormat.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
Replace `.` with `_` in Kafka broker URL when logging since Log4J's class name logging splits at the last `.` and logs an incomplete name
GH CI
> [server][da-vinci] Replace '.' with '_' in Kafka broker URL when logging

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VeniceAvroRecordReader.java
Add back constructor method to maintain dependency.
N/A
> [vpj] Add back public constructor for VeniceAvroRecordReader used in downstream dependency

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StorageEngineFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/blackhole/BlackHoleStorageEngineFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/memory/InMemoryStorageEngineFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactoryTest.java
When bootstrapping server, if II is not enabled, by default all data partitions are restored. So even if there is offline->standby msg sent, storage engine will be created during restore, and if Helix think this resource should be dropped, it will send out a offline->dropped. This should be fine, as it can locate the partition in storage engine and drop it. 
For II, during server bootstrap, we do not do any partition restore at all. When there is any offline > standby message coming in, we will restore it first in II process, ingest it until COMPLETED and then handover to main process. If Helix does not even send offline>standby but send offline->dropped directly, our logic will try to execute it in main process. Since storage engine is not opened, drop will be ignored which leads to …
> [server][da-vinci-client] Restore storage engine if not found

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/StoreRepushCommand.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/datarecovery/meta/RepushViabilityInfo.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestDataRecoveryClient.java
Today, in data recovery client, `getRepushViability` inaccurately reports certain scenarios as failures, e.g. store's current version is newer than the provided timestamp, or an ongoing push is in-progress. These scenarios are in fact not failures, but cases that a new recovery action is not needed. However, there are other cases that we should consider as errors, e.g. when controller response contains errors.
To report them correctly, this rb introduces a new boolean to `RepushViabilityInfo` data structure to differentiate them and react/report task status differently.
Manually verified. By giving a very early datetime (so that current version is newer) to the command, the following compares the `before` and `after` reporting.
Before:
```
2023-08-30 15:22:18 INFO [DataRecoveryExecutor] …
```
> [admin-tool] Improve data recovery task reporting

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
Add log to print how long it takes for SharedKafkaConsumer to close. 
GHCI
> [server][da-vinci-client] Add log for SharedKafkaConsumer closing duration

- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClusterInitializer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/AbstractTestVeniceHelixAdmin.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClusterAgnosticTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciLiveUpdateSuppressionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DataRecoveryTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/NearlineE2ELatencyTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/OneTouchDataRecoveryTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHelixCustomizedView.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestLeaderReplicaFailover.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputFormat.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputRecordReader.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerDuringIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRouterRetry.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestStreaming.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/storagenode/ReadComputeValidationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/storagenode/StorageNodeComputeTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/storagenode/StorageNodeReadTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/throttle/TestRouterReadQuotaThrottler.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/utils/IntegrationTestPushUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/writer/VeniceWriterTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
Previously, integration test will create some adhoc topic manager, venice writer or producer by passing raw properties without additional properties needed for other pub sub system type. This will cause integration test failure with other pub sub system. To resolve this, we changed some interfaces of utility function of `TestUtils` function by passing these additional configs or adding these additional configs directly inside the utility function if `PubSubBroker` is available.
> [test] Support additional properties passing for test utils.

- .github/rawWorkflows/gh-ci-alpini-parametrized-flow.txt
- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/gh-ci-pulsar-tests.yml
- .github/workflows/gh-ci.yml
- build.gradle
- gradle.properties
Previously, builds using JDK8 would fail. Also, cleaned up the `alpn-boot` loading process for HTTP/2 on JDK 8 tests.
Running GH CI
> [build] Fix JDK8 builds and set up CI

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
This PR makes change to resolve race condition between:
(1) new partition ingestion
(2) store ingestion task idle timeout
This PR makes max idle counter configurable and set the default from 100 to 10000, so total timeout would be 1s -> 100s. This should make the race condition very very unlikely to happen. 
Also, to make the logic reliable, this PR makes a change that makes sure the retrieved SIT for startConsumption() is **active** SIT. It will try to reset the idle counter with synchronization guarantee.
New unit test
> [server] Make store ingestion task idle counter configurable

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBasedStoreSchemaFetcher.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/StoreSchemaFetcher.java
It will give users more context about the errors. New output format:
```
[ERROR] Value schema not found. Is a schema that is compatible with the specified data already registered?
Exception messages for each schema:
Schema Id: 1. Exception: org.apache.avro.AvroTypeException: Expected start-union. Got START_ARRAY
Schema Id: 2. Exception: org.apache.avro.AvroTypeException: Expected start-union. Got START_ARRAY
```
Tested locally. GH CI for the rest
> [producer] Log details if input doesn't match any value schema in ProducerTool

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallbackTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
If ingestion task errors out or topic got unsubscribed, per message logging floods the log files. This PR adds some redundant checker to it.
CI
> [server] Add redundant filter on per message logging

- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
In `isReplicaDisabled` returning emptySet will cause `java.lang.UnsupportedOperationException: null` exception to be thrown if we try to add any element to it
Instead return null so that it will later create a new HashSet when needed.
GHCI
> [controller] Return null instead of Collections.emptySet()

- .gitignore
- docs/Gemfile
- docs/_config.yml
- docs/proposals/proposals.md
- docs/proposals/vip-1.md
This PR upgrades the `github-pages` gem to the latest version. Note that Ruby 2.7+ is needed for using the gem's latest version.
It also fixes currently unreachable VIP-1 proposal page link.
It was tested locally via Ruby's `bundle` commands, by installing updated dependencies and building the website with Jekyll.
> [doc] Upgrade github-pages gem to the latest version and fix VIP-1 proposal link

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/AbstractVeniceProducer.java
- clients/venice-producer/src/test/java/com/linkedin/venice/producer/online/OnlineVeniceProducerTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
There is a race condition in the schema refresh logic in `RouterBackedSchemaReader` where if there are concurrent calls to fetch update schemas, then the `loadUpdateSchemas` flag is flipped earlier than it should have - causing future calls to assume that the schemas have already been fetched and to not try to take a lock to fetch schemas. However, since the schemas themselves have not yet been fetched, it incorrectly returns a `null` response.
GH CI
> [all] Fix race condition in RouterBackedSchemaReader when there are concurrent calls to check schema freshness

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfig.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfigTest.java
> [server] Apply default consumer receive buffer setting only if not provided via configs

- build.gradle
In one of our use-cases, we noticed this compilation failure:
```
FastSerdeBase [INFO] Starting compilation for the generated source file: <redacted>/MultiGetResponseRecordV1_GenericDeserializer_1339531883776153861_1339531883776153861.java 
warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.8'
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider lombok.launch.AnnotationProcessorHider$AnnotationProcessor not found
...
Caused by: com.linkedin.venice.exceptions.VeniceException: Failed to generate fast generic de-serializer for Avro schema: {"type":"record","name":"MultiGetResponseRecordV1","namespace":"com.linkedin. …
```
> [all] Bump avro-util to pick up a fix to disable the annotation processor during compilation

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
The shell producer can allow deleting records by accepting the value `null` regardless of the fact that it is compatible with the store schema or not. Note that other forms of `null` like `"null"`, `'null'`, etc are not allowed.
Tested locally
> [producer] Allow deleting records via the shell producer

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/utils/TestClientSimulator.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/AbstractVeniceProducer.java
- clients/venice-producer/src/test/java/com/linkedin/venice/producer/online/OnlineVeniceProducerTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputKeyComparator.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeRequestWrapper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/AvroGenericDeserializer.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/RecordDeserializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/chunking/ChunkKeyValueTransformerImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/schema/RecordSchemaAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/IdentityRecordDeserializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/update/UpdateBuilderImpl.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestWritePathComputation.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/MetaStoreShadowReader.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceComputePath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceMultiGetPath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/streaming/VeniceChunkedResponse.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/ComputeRouterRequestWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/MultiGetRouterRequestWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/MultiKeyRouterRequestWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/response/ComputeResponseWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/response/MultiGetResponseWrapper.java
There were many cases of FastSerializerDeserializerFactory.getAvro[...] rather than getFastAvro[...]. This is confusing since both the slow and fast methods are available in the same factory class. Since it is not possible to override static methods, it is not straightforward to make the code less error-prone. For now, this commit does not attempt to refactor the class structure but merely fixes the individual call sites that called a slow avro factory method on the fast factory.
Separately, the RecordDeserializer interface was also tweaked to return a List rather than a Iterable in its two deserializeObjects functions. This makes it more efficient to get the size of the list without iterating. The reason for having an Iterable was from an earlier version of the code where we attempted to …
> [server][router][tc][fc] Minor Avro-related optimizations

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- docker/venice-client/Dockerfile
- internal/venice-common/src/main/java/com/linkedin/venice/throttle/TokenBucket.java
- internal/venice-common/src/test/java/com/linkedin/venice/throttle/TokenBucketTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientGrpcServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/grpc/handlers/GrpcReadQuotaEnforcementHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/AggServerQuotaUsageStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerListenerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
The PR fixed several issues in the `ReadQuotaEnforcementHandler.java`:
1. The `ReadQuotaEnforcementHandler` used to only keep the token bucket of the current version. As a result when FC metadata is updated asynchronously it's possible that it will query the server for a different "current" version. During this transition period we don't have the corresponding token bucket and quota is not enforced.
2. In the old `channelRead0` there is a bug when handling retry requests. Retry request will not enter the if block but enter the else if unintentionally and trigger `handleEnforcingAndNoBucket` on the request.
3. `updateQuota` used to blindly replace existing token bucket with a new one even if they are identical. Now it checks if it's different and only replace it if it's different to avoid …
> [server] Fix storage node read quota enforcement

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- docker/venice-client/Dockerfile
- gradle/spotbugs/exclude.xml
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/SparseConcurrentList.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/SparseConcurrentListTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
The issue could happen in a scenario where the server lost its only partition of a store, the storage engine got closed, and then regained a partition for the store. See the JavaDoc of the new unit test for more details.
New unit test.
> [server] Fixed stale storage engine reference in server

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/utils/TestClientSimulator.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
1. streaming `batchGet` was not honoring max keys limit in a batch get. Returning `VeniceKeyCountLimitException` now.
2. setting the default max number of keys in a batch get in FC to 150. It was 2 before.
3. When there is a non-existing key in batch get, an exception was returned `Response was not complete`: Changed it to consider non-existing keys as part of response key count. 
4. Added unit tests/integration tests for the above cases.
GH CI
> [fc][test] Honor max batch get limit and return proper response for nonExistingKeys

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientUnitTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientGzipEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientZstdEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
1. Retry was not working for `streamingBatchGet(keys)` as the proper delegation was not happening in `RetriableAvroGenericStoreClient.java`. This change fixes this problem.
2. make streamingBatchGet use `--multiget_streaming_` rather than `--multiget_` as prefix for metrics.
- `batchGet()` using single get uses single get metrics
- `batchGet()` using streaming implementation uses `--multiget_`
- `streamingBatchGet` uses `--multiget_streaming_`
3. return an exception if every key hits no replica found issue. Before this change, even though this case didn't increment successful key count metric and increment no replica found metric, it was still considering the request to healthy. After this change, this is considered unhealthy metric. Even after this change, if at least one of the routes …
> [fc][test] Make retry work and add proper stats prefix for streamingBatchGet

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
Even though we use the DB Options to enable atomic flush, we were not passing the list of column family handles into the flush call, and since our WAL is disabled we did not implicitly get the atomic flush behavior either.
This commit fixes the usage to ensure atomic flushing of the data and RMD column families.
More details: https://github.com/facebook/rocksdb/wiki/Atomic-flush
> [server][dvc] Fix to RocksDB atomic flush usage

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
Today, only `venice-0` leader controller is allowed to register new KME schema into ZK. This change is intended to allow every other controller and server to register KME schema during startup.
Resolves VENG-10678
-->
> [server][controller] KME Schema Registration To ZK On Startup

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerService.java
This is a follow up change to a8af3a9 addressing comments about not to pull in guava classes if possible due to instability and compatibility concerns.
CI passed.
> [controller][server] Remove guava class usages in KME upgrade code path

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/VeniceViewWriter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ViewWriterUtils.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriterTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/view/ViewWriterUtilsTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestVeniceReducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/PubSubSharedProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/views/VeniceView.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/AbstractVeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/view/TestViewWriter.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/producer/MockInMemoryProducerAdapter.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/producer/TransformingProducerAdapter.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
The logic that we'll employ is that only after all view writers have ACK'd back, we'll then invoke the normal logic.
Also added a fix to squelch the spammy logs from abstract storage engine in the producer config, as well as fixing the linger time on the writer in the changecapture view writer.
Resolves #XXX
Integration tests
> [server] Don't block SIT on writing to a view

- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/OfflinePushStatus.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatus.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/OfflinePushStatusTest.java
We recently find out that NPE would be thrown when polling the incremental push status. This PR adds the NPE handling so we would have more information on which partition couldn't be found. Please note that this PR is NOT for resolving the real problem but attempts to provide more debugging information
unit tests
> [controller] Handle NPE for incremental push reporting

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
Refactored nearline metrics recording code. Ignore invalid timestamps and don't calculate latency for messages with no upstream.
Filtered out junk metric data and emit zero when latency values are unavailable. This avoids junk values for max latency when they are aggregated across time dimension.
Resolves #XXX
> [server] Ignore invalid time stamps for leaderProducerRecordContext.

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateClusterConfigTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/util/ParentControllerConfigUpdateUtils.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/utils/ParentControllerConfigUpdateUtilsTest.java
This PR adds two new config to enable partial update by default when converting a store from batch to hybrid:
"enable.partial.update.for.hybrid.active.active.user.stores"
"enable.partial.update.for.hybrid.non.active.active.user.stores"
If the update request does not explicitly enable/disable partial update, then it will rely on the above 2 configs to determine if a store should enable partial update. If the resolution determines it needs partial update, it will also enable chunking (and RMD chunking, if A/A is enabled).
Add a new integration test to validate the cluster level config.
> [controller] Add new controller cluster config to enable partial update by default when converting new store from batch to hybrid

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/KafkaConsumerServiceStats.java
If some consumer poll returns empty record count, the metric will record 0 which will affect the avg count for consumers which are actually polling non-zero records. For a clearer view of the poll result, this PR will add another metric which will record only when there is a non-zero results from the poll
CI
> [server] Add metric for poll count only if it returns non-zero record count

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlySchemaRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestReadOnlySchemaRepository.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridQuota.java
- services/venice-server/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorAccessor.java
This code change includes several fixes:
1. Bump up fast-avro lib tot pick up the recent serde optimizations.
2. Fix the meta system store schema race condition issue in Venice Server. Previously, the update schema may not be available for the latest superset schema since there is a delay between registering superset schema and its derived schema. The fix will always retrieve a latest value schema with a valid derived schema.
3. Use RocksDB API to fetch partition size to avoid the following race condition: RocksDB log compaction can delete file in the middle of measuring the directory size.
4. Let 'fast.avro.field.limit.per.method' to control fast serializer size as well.
CI
> [all][server][dvc] Fast-avro upgrade, fix meta system store schema update issue and partition size race condition

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
Previously, when OFFLINE => DROP transition happen, we will check if we can remove the partition from disk only based on partition consumption state exist or not. However, it is also possible that there are some pending state transitions in consume action queue of the `StoreIngestionTask`.  If we drop the partition and there is a pending SUBSCRIBE action in consumption queue, then it will cause data persistence failure due to partition not existed in disk. To avoid this, we add pending queue checking for the partition about to be deleted during the partition consumption check. 
internal CI
> Changing ingestion consumption check avoiding race condition.

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTestUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
* currently fast client `start()` is a non blocking call and when metadata update fails for the first time it schedules the update and returns leading to the read requests throwing exception until the metadata becomes ready in the background. This change makes it a blocking start until the metadata is ready. In case of `InterruptedException`, it will fall back to the old ways. 
* `testFastClientWithoutServers` as an integration test doesn't make sense anymore as it will keep on waiting, so removed it. The newly added unit test mimics this (a more general version where metadata update fails for any reason). Need to add more unit tests for metadata. Not in scope for this PR.
Added a unit test
- [] No. You can skip the rest of this section.
fast client start() is a blocking call now which …
> [fc][test] FC warmup part 1: delay fc startup until metadata is updated

- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixCustomizedViewOfflinePushRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/ResourceAssignment.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RoutingDataRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/listener/TestListenerManager.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helix/TestHelixCustomizedViewOfflinePushRepository.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helix/TestHelixExternalViewRepository.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/AggPartitionHealthStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerCalculationTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerListenerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
This PR intend to address two issues:
1. During init the pre-existing resources did not get subscribed to the routing data change listener. This means the corresponding quota calculation won't be accurate if there was a rebalance before the store was changed (we used subscribe to routing data change for  existing and new resources on store change).
2. We discovered that the customized view repository does not return the complete resource list right after server is started even after the future is completed. We are working with Helix to investigate and solve this issue but in the meantime we can add a new event onCustomizedViewAdded to be notified when the CV repository receives new resources. The read quota handler will respond to the event by initializing the corresponding token bucket. …
> [server] Fixed SN read quota not initialized properly for pre-existing resources

- build.gradle
As a pre-requisite for https://github.com/linkedin/venice/issues/705 this PR bumps the hadoop to 2.7.2. 
- Hadoop 2.6 introduces `hadoop-aws` which can become a runtime dependancy.
- 2.6 has a known [compatibility issue](https://stackoverflow.com/questions/36427291/illegalaccesserror-to-guavas-stopwatch-from-org-apache-hadoop-mapreduce-lib-inp) with guava thus, the update to 2.7.2.
Existing unit tests and integration tests
> [vpj] Bump hadoop to 2.7.2

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
In the current setup, we may inadvertently create a separate KafkaConsumerService for each alias address. 
This change prevents such unnecessary duplication.
CI
> [server] Avoid creating separate consumer services for broker alias addresses

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/system/store/MetaStoreWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/VeniceResourceCloseResult.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceResourceCloseResult.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/system/store/MetaStoreWriterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterFactoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
This commit addresses the issue in the current `MetaStoreWriter::close` implementation,  
which uses `parallelStream` to close Venice writers. Since no thread pool is specified for   
running `parallelStream`, it uses threads from `ForkJoin.commonPool`. This can lead to   
issues where other parts of the system monopolize the FJ thread pool, causing a lack of   
guaranteed concurrency during the close operation. In other cases, the `MetaStoreWriter`   
itself may monopolize the FJ thread pool, preventing other system components' access to it.  
This PR addresses the issue by eliminating the dependency on the FJ common pool during  
the MetaStore shutdown. It introduces the `VeniceWriter::closeAsync` API to close Venice  
writers asynchronously. This async operation runs in the Venice …
> [server][controller] Close VeniceWriters in MetaStoreWriter concurrently and in bounded time

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreViewUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
This PR introduces a new AdminTool command to configure (add/update/remove) a view of a store.
The command name is **--configure-store-view**. It takes the following parameter:
1. **--view-name**: Required at all time. Value: Name of the view to act on.
2. **--remove-view**: If present, this action is to remove an existing view from the store config. No Value.
3. **--view-class**: Required when it is not removing a view. Value: View class name of the view.
4. **--view-params**: Optional. Value: Additional parameters for the view in the format of string to string map. If not specified, meaning it is going to use **empty map**, instead of inheriting existing value.
The actual logic is inside update store logic. The reason to separate it into a new command is to make it more user friendly to …
> [admin-tool][controller] Add new admin tool command to configure/remove particular view for store

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/BootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ImmutableChangeCapturePubSubMessage.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/LocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangeCoordinate.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/TestVeniceChangeCoordinate.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactoryTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/ImmutablePubSubMessage.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubMessage.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
This change adds the BootstrappingVeniceChangelogConsumer interface and an implementation.
This interface is meant for users where local state must be built off of the entirety of a venice data set (i.e. Non-idempotent event ingestion), rather than dealing with an event at a time. THIS IS EXPENSIVE. It's highly recommended that users use the VeniceChangelogConsumer interface as a means to consume Venice Change capture data.
BootstrappingVeniceChangelogConsumerImpl works by maintaining a local rocksdb instance to store records as they are consumed from change capture.
This is like davinci, and potentially a future refactor should be davinci based, but an expeditious delivery was required, and it seemed that this would not have been a straightforward refactor. The way to think about the …
> Add bootstrap change capture consumer

- build.gradle
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/InstanceHealthMonitor.java
- gradle/helper/git.gradle
- internal/venice-common/src/main/java/com/linkedin/venice/exceptions/OperationNotAllowedException.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientGzipEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientZstdEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientGrpcServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Currently, servers will perform read-compute on compute requests for any store. This commit adds a check on servers to reject such requests so that servers don't spend resources for stores that aren't allowed to use read-compute
Added UT, Integration tests. GHCI for regression testing
- Servers will reject read-compute requests for stores that do not have read-compute enabled
> [server][fast-client] Reject read-compute requests on server when the store is not enabled with the config

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateClusterConfigTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestChangeCaptureIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/samza/VeniceSystemFactoryTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- Setup admin topic for a cluster before running cluster initialization routines
- Close cluster wrapper at the end of test in `PartialUpdateClusterConfigTest`
- Close local broker created during `TestActiveActiveIngestion::testAAIngestionWithStoreView`
- Use `volatile` `PubSubProducerAdapter::forceClosed` flag to make update visible to a callback thread
- Use unique data paths for venice-server-data in `AbstractClientEndToEndSetup` to avoid race condition
Internal CI and GHCI
> [controller][test] Fix race condition during controller startup and fix flakies

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
After adding read-compute support to fast-client (#664) , some FC tests added a "compute" test to them and this caused tests that were close to hitting the timeout now start getting timed out. This commit increases the timeout for one such test that we notice on our internal CI
CI
> [test] Increase test timeout for FC tests after adding compute to them

- build.gradle
Bump netty version to 4.1.74.Final
GHCI
> Bump netty version to 4.1.74.Final

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/guid/HeartbeatGuidV3Generator.java
- internal/venice-common/src/main/java/com/linkedin/venice/message/KafkaKey.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
For hybrid store only, periodically have the leader write a special SOS to the RT topic with the following properties:
- Special key with constant bytes so it will be compacted.
- A fixed/known producer GUID dedicated to heartbeats so DIV won’t break.
- The special segment will never contain any data so no EOS needed.
Upon consuming the new CM the leader will write it to its local VT. Once the record is processed in the drainer the leader can update its latest processed upstream RT topic offset accordingly. At this point the latest processed upstream RT topic offset will be correct regardless if the RT had trailing CMs or skippable data records due to DCR.
- Made sure existing unit and integration tests pass with heartbeat enabled by default at a 5 seconds interval.
- Modified an existing …
> [server][common] Periodically produce SOS heartbeat from leader replicas of hybrid store

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/schema/HDFSSchemaSource.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/ttl/TestVeniceKafkaInputTTLFilter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/schema/TestHDFSSchemaSource.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/controllerapi/MultiSchemaResponse.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSupersetSchemaUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/ActiveActiveReplicationForHybridTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/SchemaRoutes.java
As a side-effect in PR: #704 I changed the Json property in controller class SchemaRoutes and MultiSchemaResponse to try to clean up API naming to make it makes more sense - ID-RMD_VERSION_ID. This leads to breaking changes in controller, it needs controller deployment to release VPJ and it might have break the API JSON serialization/deserialization. 
To make it easy to release the new TTL repush AAWC feature, this PR reverts the part of the change, so it no longer requires controller deployment. I will try to make another attempt apart from this PR to gracefully deprecate improper naming of JSON property.
Existing test should pass to make sure it is not a regression.
> [controller][vpj] Revert changes to MultiSchemaResponse/SchemaRoutes that impacts controllerClient#getAllReplicationMetadataSchemas()

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFiles.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
This PR fixes repush failure in A/A partial update store 
Current checksum calculation will take every PUT message's key, schemaId, value into account. However, RMD chunk as it is also a chunk PUT message and it is calculated in the running checksum, while the expected checksum which iterates the SST file does not contain it (since RMD chunk is put into RMD CF). This is the reason that repush failed on checksum verification. 
During the investigation, we also found that default integration test config setup is not correct. It enables PlainTable mode by default and disable checksum verification by default, which is not consistent with current production behavior. This PR fixes the issue.
Existing integration test with tweaked default setting.
> [server][test] Fix checksum calculation bug in Active/Active Partial Update RMD chunking

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreWriteComputeProcessor.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolverFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/RmdSerDe.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/SortBasedCollectionFieldOpHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/Utils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/MapOrderPreservingDatumReader.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/MapOrderPreservingDeserializer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/MapOrderPreservingSerDeFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/MapOrderPreservingSerializer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/fast/MapOrderPreservingFastDeserializer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/fast/MapOrderPreservingFastSerDeFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/serializer/avro/fast/MapOrderPreservingFastSerializer.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeBase.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithValueLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/schema/TestSchemaUtils.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/serializer/avro/MapOrderPreservingSerDeTest.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/VeniceRmdTTLFilter.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/FastSerializerDeserializerFactory.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/SerializerDeserializerFactory.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/serializer/FastSerializerDeserializerFactoryTest.java
1. Adopt fast-avro in the AAWC code path.
2. Use a schema-id based serde cache to avoid expensive schema comparison.
3. Dynamically choose the right structure for different logics, such as
LinkedList vs ArrayList.
CI
> [server] A few WCAA performance improvements

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/SchemaUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/CollectionTimestampMergeRecordHelper.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/writecompute/WriteComputeHandlerV2.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallbackTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/schema/TestSchemaUtils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
There was a bug where we assumed unions always used null as the first branch.
Introduced a new SchemaUtils::unwrapOptionalUnion function which replaces several other functions from that class.
Thanks to @sixpluszero for finding that this is the root cause of an issue.
New existing unit tests.
> [server] Fixed union handling in AAWC

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreInfo.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/SystemStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ZKStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubTopicConfiguration.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-common/src/main/resources/avro/StoreMetaValue/v16/StoreMetaValue.avsc
- internal/venice-common/src/main/resources/avro/StoreMetaValue/v17/StoreMetaValue.avsc
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/TopicManagerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/resources/avro/AdminOperation/v74/AdminOperation.avsc
`max.compaction.lag.ms` is used to control the maximum time a message will remain ineligible for compaction. This is the config, which will trigger frequent compaction when there are a lot of duplicated messages in version topic. This config has been proved to help reduce the DaVinci bootstrapping time when the version topic contains many duplicate messages with high write throughput. So far, we will manually adjust this setting for the high-write throughput DaVinci stores.
CI
> [compat][controller][admintool] Added store-level max compaction lag support

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/RocksDBMemoryStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/InstanceStatusDecider.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/NodeRemovableResult.java
Added compaction cancellation metric to get more insight on rocksdb SST file size usage. Also adds more details to node removable result to indicate why a node considered removable as passing wrong ID silently tells its removable.
GHCI
> [server][da-vinci-client] Add compaction cancelled metric, add details to node_removable 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumerAction.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ConsumerActionTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
Problem:
The "ingestion_task_errored_gauge" metric checks ingestion errors for partitions which explicitly reports ERROR to ZK. However, for COMPLETED partition, ERROR will not be reported in order to protect read path, but ingestion will stop without any alerts until we see a high lag after rolling bounce or users notice data staleness/inconsistency.
Fix:
Added a new set to track the partition IDs whose ingestion has failed and stopped. Life cycles of the partitions IDs in the set:
1. When a partition encounters exceptions, update both the partition-to-exception list and failed-partitions set;
2. When an unsubscribe action is triggered by Helix for the failed partition, remove it from both the partition-to-exception list and failed-partitions set;
3. When an unsubscribe action is …
> [da-vinci][server] Alert on failed ingestions for both incomplete and completed partitions

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/SchemaUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/SortBasedCollectionFieldOpHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/schema/TestSchemaUtils.java
This PR removes strict optional collection type check before applying collection partial update in Active/Active store.
Previously it requires [null, collection] to be the union collection schema. This PR uses the SchemaUtils.unwrapOptionalUnion() API to retrieve the collection type.
> [server] Best effort to extract optional collection type for type validation before Active/Active partial update collection operation

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/RocksDBMemoryStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/RocksDBStats.java
> [server] Move rocksdb compaction cancelled metric under RocksDBStats

- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DisabledPartitionStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/ErrorPartitionStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorDelegator.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
Since disabled metric can cause a cluster to be in undeployable state, this PR is adding an alert to indicate disabled partition per cluster. 
The proposed action would be for oncall to investigate what error caused the alert and mitigate by restarting those hosts.
> [controller] Add metric for disabled partition map.

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
Added correct JSON parsing for command line inputs to admin-tool to read maps as JSON
Resolves #647 
CI
> [admin-tool] Enable venice-admin-tool to parse JSON map arguments from command line

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
This changes the behavior of the after image consumer so that it consumes the version topic instead of consuming the change capture topic.  In order to fully accomodate this, a few changes had to be applied, including:
- Seek API's for the After image consumer had to supply a topic suffix so as to always stay on version topics.
- seek to EOP for now has to basically consume the version topic and then find the coordinates of the EOP message.  Because this has to be done also when we detect that a new version is available, we use a second consumer which is doing the search/seek for the EOP message.  Once it finds it, it then resubscribes the client to the appropriate coordinate.
- Tweak message processing so that it returns deletes that are found on the version topic (tweaks to tests …
> [changelog] Tweak after image consumer to not consume view topic

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Add more test coverage for TTL repush feature.
This is the test.
> [test] Add RMD CF data validation for A/A partial update TTL repush integration test

- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTestUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/VeniceProperties.java
Metadata periodic refresh failed with below for `PartitionerParams`
```
java.lang.ClassCastException: class org.apache.avro.util.Utf8 cannot be cast to class java.lang.String
```
Fix is to use `toString()` in `VeniceProperties` constructor rather than `(String)`
GH CI
> Fix string cast issue in VeniceProperties

- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterExceptionAndTrackingUtils.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceHostHealth.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceMultiKeyPath.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Venice routers retry error requests only for 500+ http status codes. But when server returns BAD_REQUEST (400) for VeniceNoStoreException for existing resources, router does not trigger any error retries which causes unhealthy request on the client side. This PR changes the status code to 503 for such cases so that router can initiate error retries.
CI
> [router][server] Return Http status 503 for VeniceNoStoreException

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfig.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
-  Catch exceptions from `KafkaConsumer::paritionsFor` API
- Add a config to enable/disable topic-partition check before subscription action
> [server][controller] Disable topic-existence check by default and handle exceptions from KafkaConumer::paritionsFor API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
When server is deployed in a standalone fashion, the cluster does not have 
** venice_system_store_PUSH_STATUS_SYSTEM_SCHEMA_STORE**
So the new push status store writer initialization logic will fail.
This PR adds an exception catch logic and fall back to old fashion.
Will test in PCL testing.
> [server] Fix regression in new push status store write schema retrieval logic

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/stats/BasicClientStats.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceHttpStats.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ListenerService.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/AggServerHttpRequestStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerHttpRequestStatsTest.java
System store metrics are useful only in server side. This PR prevents emission of meta system store metrics in DaVinci/thin clients.
CI
> [client][server] Emit system store metric only for server

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubConstants.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
> [server][controller] Disable topic existence check in consumer subscribe API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
There seems to be a race condition where the RT offset gets persisted into the VT offset field of the PCS. This change guards against this bookkeeping error, and logs information if it happens.
CI
> [dvc][server] Added safeguard in LFSIT::updateOffsetsFromConsumerRecord

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
Currently when target region push is enabled, it picks the default NR source fabric as the target region. When source fabric region and default native replication source are different, there would be 2 issues for target region push.
1. The source VT would be created in default NR region which then will be replayed back to the source grid fabric VT, thus data would be making double hop.
2. The SOP for repush will be missing in source grid fabric as it was created only in default NR fabric, thus leading to stuck push.
This PR resolves the above.
> [vpj] Use source grid fabric for target region fabric

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/SortBasedCollectionFieldOpHandler.java
The SortBasedCollectionFieldOpHandler was using List::add instead of
PrimitiveLongList::addPrimitive. This was shown in a profiling to be a
big source of memory allocation, so we are eliminating this boxing in
this commit.
CI
> [server] Eliminated some boxing in WC code

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/AbstractVeniceProducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
In `VeniceWriter`, we send `EndOfSegment` messages periodically. However, if there is an exception from the pubsub implementation, it causes future writes in that VeniceWriter instance for that particular partition to be blocked. This commit makes the sending of `EndOfSegment` message best-effort.
The logic to periodically send `EndOfSegment` messages had been added to reduce the state that servers would persist in their state for DIV checks. Given that we now have a way to clean up DIV state older than some configured time, this best-effort behavior is acceptable.
GH CI
> [all] Make VeniceWriter sending EndOfSegment due to timeout best-effort

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumerSubscriptionCleaner.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
During my oncall shifts, I find the logging to detect non-existing topics is a bit noisy and doesn't provide much information when we filter by ERROR. It should be WARNING.
Also, sometimes I see stats failed to register but there was no reason. Add that as well.
ghci.
> [server] Tweak logs for better debugging

- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
When a connection lease attempt is made the state requested is null. However when the connection is put back into the pool the state is set to the X500Principal object of the SSL peer. This happens in the DefaultUserTokenHandler class. This PR overrides while creating the HttpClient class so that it will reuse the connections.
Before using httpclient5 using SSL.
client->router delay ~300ms from local mac to ltx1 due to SSL/TLS handshake while creating conn on every requests.
After this change
client->router delay ~100ms from local mac to ltx1.
testing using venice-thin-client.
> [client] Reset user token in httpclient5

- internal/venice-common/src/main/java/com/linkedin/venice/throttle/TokenBucket.java
TokenBucket relies on consumption itself to update/refill its tokens. There is a rare race condition that could happen and cause very few consumption requests to be rejected even when the token bucket is refilled and has sufficient tokens. The race is caused by the old implementation of tryConsume()
return noRetryTryConsume(tokensToConsume) || (update() && noRetryTryConsume(tokensToConsume));
This is problematic because a small window where token is empty so it enters update() but the bucket just got updated by another thread so the first nextUpdateTime check will be false and hence returning false from update() and causing the tryConsume() to return false when in fact there are plenty of token available and was just refilled.
An alternative fix would be to check the bucket within …
> [server] Fixed rare race condition for TokenBucket tryConsume()

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSupersetSchemaUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/TestAvroSupersetSchemaUtils.java
Merge field-level props when generating superset schema
CI
> [controller] Merge field-level props when generating superset schema

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/KafkaConsumerServiceStats.java
Constructing Venice Gauge metric with value is pointless; Venice Gauge metric can only work with function.
Tested in PR#756
> [server][da-vinci] Construct the MaxElapsedTimeSinceLastPoll Gauge metric with function instead of value

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/KafkaConsumerServiceStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/StuckConsumerRepairStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/stats/BasicClientStats.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceHttpStats.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStuckConsumerRepair.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ListenerService.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/AggServerHttpRequestStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerHttpRequestStatsTest.java
[server][da-vinci] Construct the MaxElapsedTimeSinceLastPoll Gauge metric with function instead of value (#781)
Constructing Venice Gauge metric with value is pointless; Venice Gauge metric
can only work with function.
[server] Introduced a repair service for stuck shared consumer (#757)
* [server] Introduced a repair service for stuck shared consumer
Recently, we noticed that some shared consumers were stuck since they
were blocked by producing to some non-existing topics, and many other
store versions got affected since the stuck consumer is being shared
by many other stores.
This PR introduces a way to detect and repair stuck consumer for above
situation.
In the high level, there will be a thread periodically check whether consumer#poll
is being invoked regularly or not, and if not, …
> Hotfix 0.4.161 stuck consumer metric and repair

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStuckConsumerRepair.java
This code change made a few fixes:
1. Added 3 new metrics to track Active/Active perf in store-level: 
```
leader_ingestion_active_active_put_latency
leader_ingestion_active_active_update_latency
leader_ingestion_active_active_delete_latency
```
2. Removed one existing metric from `ActiveActiveStoreIngestionTask#processMessageAndMaybeProduceToKafka`: consumed_record_end_to_end_processing_latency, which is supposed to be triggered in drainer.
3. Reduced flakiness of test: `TestStuckConsumerRepair`.
CI
> [server] Added metrics to track Active/Active perf

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
If StoreIngestionTask receives a kill-job command from Controller or operators, that means this store version is abandoned and it wouldn't have a chance to come online again. In that case, do a forced kill on resources like producer instead of trying to gracefully stop the ingestion task.
CI
> [server] Forced kill producers when ingestion task is killed

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
When controller zk listener thread handles error push and deletes user store version, it will produce a delete message to davinci push status system store RT. If RT does not exist, zk listener thread will wait infinitely. Since the thread holds the store write lock forever, admin execution task threads will be blocked when processing the store's admin operations. What's worse, as admin execution tasks are shared, other stores' admin operations cannot be processed either.
This commit submits a task to delete davinci push status, wait for up to 30s to get the result, and cancel the task after timeout.
New integ test
> [controller] Delete da-vinci push status asynchronously

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/SortBasedCollectionFieldOpHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdate.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/helper/ListCollectionMergeTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/schema/merge/CollectionMergeTest.java
This PR tries to fix a bug in AAWC logic on list element update.
The bug is: when trying to update a pre-existing element in the list field, it only check if the TS is different from the existing element, not greater than the existing element TS. It might lead to update timestamp rewind for the element, and if there is another DELETE that happens between the two updates TS, certain update order can lead to data being deleted - thus data loss.
Add new unit test.
> [server] Fix edge case in AAWC list element update

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerCallback.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerCallbackTest.java
> [server] Remove forceClosed check and rely only on message to skip ApacheKafkaProducerCallback processing

- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DisabledPartitionStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorDelegator.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
The metric for disabled partition only counts whenever a partition is disabled, but does not count down whenever its reenabled. This PR fixes that.
> [controller] Clear disabled partition metric on server restarts

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/RocksDBStats.java
The latest rocksdb release will enable this feature: `level_compaction_dynamic_level_bytes` by default to reduce the space amplification, and we did some study and we thought this can help us reduce the disk usage for high write throughput stores. Related post for this feature:
https://github.com/facebook/rocksdb/wiki/Leveled-Compaction
CI
> [build] upgraded rocksdb dep to 8.8.1

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AbstractKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
Based on the offline analysis, the logic to handle writes from Active/Active or Write-compute stores in consumer threads is much heavier than other stores, which would slow down the ingestion speed of regular stores significantly when there are some high write throughput to AA or WC stores.
This code change introduces an option to assign the leader replicas of AA or WC stores to a dedicated consumer pool, so that the regular store ingestion won't be affected by the above combination.
The write compute flag is store-level config, so it can change in the lifetime of a particular version, and this code change won't react of write compute flag change until a restart.
New configs:
server.dedicated.consumer.pool.for.aa.wc.leader.enabled: default false …
> [server] Add a new option to allocate dedicated consumer pool for leader replicas of AA/WC stores

- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceVersionFinder.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterCurrentVersionStats.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVenicePathParser.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceVersionFinder.java
This PR adds current version metric in router which gives us visibility of  in-memory vcurrent version being served for a store in the router.
CI
> [router] Add router current version metric

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
The exception now looks like this:
com.linkedin.venice.exceptions.VeniceException: No Kafka cluster ID found in the cluster ID to Kafka URL map. Got cluster ID -1 and ID to cluster URL map {0=>url0, 1=>url1}. Source Kafka: sourceKafkaURL; TP(topic: 'topic', partition: 0); Offset: 100; Message type: CONTROL_MESSAGE/TOPIC_SWITCH; ProducerMetadata: {"producerGUID": null, "segmentNumber": 0, "messageSequenceNumber": 0, "messageTimestamp": 0, "logicalTimestamp": 0}; LeaderMetadataFooter: {"hostName": null, "upstreamOffset": 0, "upstreamKafkaClusterId": -1}
New unit test.
> [server] Added info to the exception in AASIT::getUpstreamKafkaUrlFromKafkaValue

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangeCoordinate.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
Fix BootstrappingVeniceChangelogConsumer no metadata issue. Previously BootstrappingVeniceChangelogConsumer can store the data in local RocksDB. However, it couldn't successfully bootstrap from RocksDB as we didn't save the metadata correctly. This PR is to fix it.
Tested by running integration test `testBootstrappingVeniceChangelogConsumer_WithPollAndCatchUp` twice with same store name. On the second run, verified the log to show we could load data directly from rocksDB instead of running pollAndCatchUp.
> Fix BootstrappingVeniceChangelogConsumer no metadata issue

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedDIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStatsReporter.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggVersionedDIVStatsTest.java
We seem to have a pile of metrics that harken back to pre-NR. This change removes them.
Resolves #XXX
Ran CI and verified in production hosts these metrics are always blank.
> [server][da-vinci] Delete Unused non NR Metrics

- internal/venice-common/src/main/java/com/linkedin/venice/system/store/ControllerClientBackedSystemSchemaInitializer.java
- internal/venice-common/src/test/java/com/linkedin/venice/system/store/ControllerClientBackedSystemSchemaInitializerTest.java
Today controller client backed initializer sends a get_value_or_derived_schema_id for every meta system store value schema, to check if its partial update schema exists. But actually controller has get_all_value_and_derived_schema api to get all schemas so that we can check if any schema exists. This commit switches to use this api, which helps reduce the number of controller requests from n to 1.
Updated unit test `testCreateSystemStoreAndRegisterSchema` passed
Existing integ test `testStartServerWithSystemSchemaInitialization` passed
> Reduce the number of controller requests sent by system store initializer

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/ingestionHeartbeat/IngestionHeartBeatTest.java
Heartbeat successfully sent is logged per topic partitions leading to a lot of logs per minute if the server hosts a lot of topic partitions.
`maybeSendIngestionHeartbeat()` which sends HB to all RT partitions will generate either 1 error log if there are failures or 1 debug log if everything is successful.
`propagateHeartbeatFromUpstreamTopicToLocalVersionTopic()` which forwards HB from RT to VT sends 1 error/debug log per topic partition if it succeeds/fails respectively. 
Both are protected inside a redundant logging filter (1 min).
GH CI
> [dvc] Reduce the number of successful heartbeat info logs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/utils/ChunkAssembler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
This moves chunk deserialization and assembly to a utility, so it can be used in different areas in da-vinci. This is because other areas face the issue of message sizes being too large to be sent under one message, so they need to be serialized and chunked.
CI
> [da-vinci] Make chunk assembly a utility

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/InternalAvroStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/ClientConfigTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DualReadAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientGzipEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientZstdEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/grpc/VeniceGrpcEndToEndTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/fastclient/utils/ClientTestUtils.java
cleanup `useStreamingBatchGetAsDefault` config which enables using streaming backend for `batchGet` API, its related code and tests to make it the only supported behavior.
GH CI
> [fc][test] clean up useStreamingBatchGetAsDefault and associated tests

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/ingestionHeartbeat/IngestionHeartBeatTest.java
This PR tries to fix the flaky test. 
The cause is: in some cases: when evaluating the lag, the standby replica might already know the leader topic and get the lag == 1, instead of negative max long. This is calculated by local VT end offset - last processed VT. 
In the current test setup, inc push is always enabled in the test, in the non-aggregate mode, it will be subscribing to parent RT, and will not consume HB. Relaxing the requirement is needed for non-AA case.
In the future, let's consider blocking the non-agg mode + inc push
Also, we don't need to test with NR = T / F as NR is always true in prod env for long time.
> [test] Fix flaky test IngestionHeartBeatTest#testIngestionHeartBeat

- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
Currently the routers are registered using non-SSL port name on helix zk path, which makes direct to host (non D2) router requests to hit non-SSL port during store backup version cleanup service. This PR registers the routers on SSL port. 
GHCI
> [router][controller] Use SSL port to connect to router

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
This PR tries to address the issue of cleaning up data correctly for ingestion isolation enabled server.
Originally, we observed that certain data partition is not deleted when a OFFLINE -> DROPPED message is issued for stale version upon server restart. The message is not executed as we did not restore all the data partitions upon server start in any of the processes. 
The first fix we implemented is in  #617 , where we added a clean up service in isolated process. However, it is not correct, as the clean up service tries to remove partitions opened in the forked process, which is metadata partition only. This leaves the data partitions still unopened and lingering forever.
This PR tries to fix it thoroughly by adjusting the data restore logic for II. It will by default restore …
> [server] Restore data partition in isolated process in Venice Server

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- internal/venice-common/src/test/java/com/linkedin/venice/acl/StoreAclHandlerTest.java
Fast client warms up H2 connections by hitting the `/health` endpoint in servers but as uri validation for requests from clients to servers happens in `StoreAclHandler`, added changes to allow the `/heatlh` uri and by-pass acl validation since it is just a health check endpoint without any pii.
unit tests and GHCI
> [server][test] Allow and skip acl checks for health check uri  from clients to server

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/LagType.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/CachedPubSubMetadataGetter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/KafkaConsumerServiceStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBSstFileWriter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/KafkaConsumerServiceStatsTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceStats.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/LambdaStat.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/AbstractVeniceStatsTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/partitionoffset/InstrumentedPartitionOffsetFetcher.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/partitionoffset/PartitionOffsetFetcherImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/partitionoffset/PartitionOffsetFetcherStats.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/KafkaPartitionTopicOffsetMetrics.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/TopicPartitionsOffsetsTracker.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/EmptyPubSubMessageHeaders.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubMessage.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubMessageHeaders.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/TopicPartitionsOffsetsTrackerTest.java
[server][dvc] Lag measurement safeguard and logging improvements
It seems that sometimes the offset lag used in lag measurement can
be negative, which results in the lag being considered acceptable
and the replica becoming ready to serve (prematurely).
It seems that negative lag is a somewhat normal phenomenon since
the formula is basically max_offset - consumed_offset, and the
former is cached, so if stale it could be smaller than the latter
(which of course doesn't make sense, but is an artifact of the
caching). This is a benign case.
However, there is also a case where the max_offset retrieval can
fail, in which case a negative error code would be returned. This
also leads to negative lag, but it is a mistake.
This commit adds safeguards to prevent prematurely declaring
ready-to-serve. …
> [server][dvc] Lag measurement safeguard and logging improvements

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/ExceptionUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/TestExceptionUtils.java
Made recursiveMessageContains work even in an edge case where the message is null but a cause has the message we're looking for. Added a unit test for this. Note that this is the only functional change of this commit, but the recursiveMessageContains function is only used in tests, hence the tag of the commit is just [test]... The motivation for this change is that this function is being used in another project that depends on Venice.
Reduced code size (without functional changes) of recursiveClassEquals.
New unit test.
> [test] Slight tweaks to ExceptionUtils

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
In order to make sure that data is always ingested and transformed with the most up to date value output schema, we need to add an additional check in  `hasConflictPersistedStoreEngineConfig() ` to compare the new schema and the current schema. If there is a conflict in the schema, this function will return true.
Describe
> [dvc] Check to clear local data on record transformer value schema change between reinitializations

- internal/venice-client-common/src/main/java/com/linkedin/venice/security/SSLConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/SslUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/SSLConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/grpc/GrpcSslUtils.java
Currently, `GrpcSslUtils#getTrustManagers` loads the trust store but expects the trust store to be of the same type as the key store. While this is true in our tests, it might not always be true in practice. This PR fixes this by handling trust store types explicitly. 
GH CI. Tested in internal jobs.
> [common][server][fc] Fix trust store handling for Grpc with SSL

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
We want to be able to track the latency when using the DaVinci record transformer feature. 
CI
> [dvc] Collect transformer latency in ingestion stats

- build.gradle
- clients/venice-admin-tool/build.gradle
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/RecoverStoreMetadata.java
- gradle.properties
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/StoreMetadataRecoveryTest.java
When we accidentally remove some being-used stores from the Venice platform, we
can use the newly added command to recover the metadata and schemas, but not data.
The idea is as follows:
1. If the store already exists, the command will exit.
2. If the store is not found in store graveyard, not recoverable.
3. Then retrieve the store config from graveyard.
4. Scan the corresponding admin channel to collect the latest key/value schemas.
5. Create the store, register the schemas and then update the store configs.
Sample command:
java -jar venice-admin-tool-all.jar --recover-store-metadata --url ${parent.controller.url} --venice-zookeeper-url {parent zookeeper url} --zk-ssl-config-file ./zk.ssl --kafka-bootstrap-servers {Parent Kafka url} --kafka-consumer-config-file ./ssl.config --store …
> [admin-tool] Added command to recover stores from graveyard and admin channel

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/AbstractTestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
This PR adjusts the existing behavior that throws exception when trying to turn off hybrid on an inc push enabled store. This was added 1.5 year ago as part of tactical fix to prevent store to lose RT right away especially for inc push store. Based on my code reading, we will not delete RT right away, if there is active hybrid version. If that is true, the change should be considered safe.
The new behavior is: When disabling hybrid store config: 
1. If user also try to enable A/A or inc push together, we should fail loudly. 
2. Otherwise, we will disable A/A and inc push store config.
Added new unit test to confirm the logic is behaving as expected.
> [controller] Turn off A/A and inc push when turning off hybrid store config

- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixStoreGraveyard.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupServiceForParentController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/TopicCleanupServiceStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForMultiKafkaClusters.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForParentController.java
1. TopicCleanupService in child datacenters will now only delete RT topic if all version topics of the corresponding store is deleted in all child fabrics. This is to ensure there are no ongoing ingestions still polling for these RT topics before deleting them.
2. Cleaned up some excessive logging in store graveyard and FC related meta system store updates in cleanup service that's no longer applicable.
Existing tests and new unit tests.
> [common][controller] Delete all version topics before deleting RT topic

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/ValueAndDerivedSchemaData.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
This PR adds new mode to print data record (PUT/DELETE/UPDATE) as well as its corresponding RMD record to console, on top of its existing functionality of logging Kafka message metadata to console. It is very useful for debugging feature correctness. 
In the future, we can consider adding a key filter to log specific key only, to better focus on certain key.
Added new unit test to cover the message build up
> [admin-tool] Add support to dump UPDATE records and RMD records in Kafka Topic Dumper

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
The deserializer lookup is pretty expensive.  This change should speed things up.
Resolves #XXX
normal test suite
> [changelog] Use serializer cache to improve changecapture user performance

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/resources/avro/PersonV3.avsc
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/writecompute/WriteComputeSchemaConverter.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/writecompute/TestWriteComputeOperation.java
- internal/venice-client-common/src/test/resources/partialUpdateSchemaV1.avsc
This PR fixes NPE thrown in MergeConflictResolver#ignoreNewUpdate(): When checking a new UPDATE message, we will first check message timestamp and compared with old value RMD. The existing logic gets all the fields from update record and check operation type for each field. Here it makes a wrong assumption that field value cannot be null, and throw exception when a new field is being set to null.
The PR fixes the issue, removes code duplications in util methods.
New unit tests in different levels.
> [server] Fix NPE in MergeConflictResolver#ignoreNewUpdate()

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushMonitorUtilsTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushStatusCollectorTest.java
Some Venice Push Job failed with the error stating more than 2k offline replicas in the push. After checking the logic we believe the live replica count check is not accurate. Completed DVC replica will not emit heartbeat to push status store, and will not be counted as live replicas if the ingestion of certain partitions staggers or data skew happens among different partitions.
This PR fix the counting to make sure completed replicas are also considered when calculating offline replicas.
Modify existing unit tests to cover the new logic.
> [controller][dvc] Do not count COMPLETED Da Vinci replicas as offline replicas

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
I noticed some KafkaBrokerWrapper leaks were reported when running the integration test in our internal CI. This is a trivial PR to fix these leaks by simply moving them into a try-with-resource block. This is no meaningful changes otherwise.
> [test] Close PubSubBrokerWrapper in TestActiveActiveIngestion

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StoragePartitionConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBSstFileWriter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBSstFileWriterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFiles.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
This test originally had the following flow:
* Delete the SST files.
* Restart the servers to simulate a crash and restart in the midst of SST file move.
However, this flow introduced an issue when checksum was enabled:
Graceful shutdown of the server after SST file deletion triggers a final offset sync, which throws an exception when files are missing during checksum calculations.
Modified the test to:
Stop the server -> Delete the SST files -> Start the server.
GH CI
> [test] fix restartServerByDeletingSSTFiles tests with checksum enabled

- docs/quickstart/quickstart-single-datacenter.md
Fixes erroneous `create-store` command mentioned in "Single-Datacenter Docker Quickstart" page.
> [doc] Fix create-store command

- clients/venice-samza/src/main/java/com/linkedin/venice/pushmonitor/RouterBasedHybridStoreQuotaMonitor.java
- clients/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
- clients/venice-samza/src/test/java/com/linkedin/venice/pushmonitor/RouterBasedHybridStoreQuotaMonitorTest.java
This is to allow store moves to not break system producers.
Resolves #XXX
> [producer][samza] Reinitalize transport client if a store has moved

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- internal/venice-common/src/test/java/com/linkedin/venice/acl/StoreAclHandlerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
Server metadata fetch backup version deletion calls server current version endpoint to validate the backup version.
But in server Acl handler check fails for QueryAction.CURRENT_VERSION as its not authorized such request. This PR allows such metadata calls in server.
> [controller][server] Allow current_version request server endpoint in acl handler

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/ByteUtils.java
We discovered 3 issues with lossy rewind check:
1. The value comparison is not correct since the value decoded from KME is a ByteBuffer, and the backed array can contain non-value bytes.
2. For the batch push, the storage engine is not usable until receiving EOP, where Venice Server would ingest all the generated sst files into storage engine, so before that, storage engine lookup will always return null.
3. The lossy rewind function is currently being invoked after persisting current record into local storage engine, which means the check will always return true.
This PR fixes 1 & 2, and 3 requires more refactoring, and I will try to fix it in a different PR.
This PR also changed the lossy rewind check function to only swallow the lossy rewind issue after reporting completion and …
> [da-vinci][server] Fixed a couple of issues with lossy rewind check

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/DictionaryRetrievalService.java
1. Catch throwable in router dictionary fetching thread so the thread doesn't die when encountering issues fetching dictionary for one store.
2. Replaced static final field for empty push dictionary in ZstdWithDictCompressor to Lazy wrapped final fields in corresponding classes. This way it doesn't get initialized if it's not used. This is the case for routers since it was initialized but never used. Failure to initialize the field will render the entire ZstdWithDictCompressor class unable to initialize.
> [controller][h2v][common][router] Improve resiliency in ZSTD dictionary retrieval

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DisabledPartitionStats.java
There was a mismatch in increment and decrement count in disabled replica metric. On hitting ingestion error replicas are disabled for a partition, but during resetting them its done per host resources which can contain multiple partitions which can lead to mismatch in metric. This PR decrements the metric by the number of partition being reset. Also collect instances from live instance monitor instead of of 'INSTANCE' path which can contain stale resource.
GHCI
> [controller] Decrement replica count in disabled partition stat metric

- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
With low QPS, the clients close the connection between client and venice-server if its idle for a minute leading to new SSL Handshakes and latency spikes.  Revert the httpclient5 configs added in [PR 829](https://github.com/linkedin/venice/pull/829) and change `ConnectionConfig.setSocketTimeout()` from 1 minute to 0(indefinite) such that client won't initiate closing the connection if it is inactive for any period of time. 
GH CI
> [common] update http client socket timeout configs

- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreInfo.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestStoreInfo.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
When this function receives a null Store parameter, it will return null itself.
There are four calls to this function, and they have all been inspected to ensure that they deal properly with nulls.
In the case of VHA::migrateStore, there are some usability improvements so that the VeniceNoStoreException includes the cluster the store is in, if it is in a different one than the supplied source cluster. There is a new short-circuiting logic as well in case the store is already in the desired destination cluster.
Unit tests.
> [controller] Fixed NPE in StoreInfo::fromStore

- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/ReadRequestThrottlerTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/RouterRequestThrottlingTest.java
There could be a race condition where a listener of the ReadRequestThrottler got called while the constructor was not fully done executing, leading to a NPE for accessing a field that was not yet initialized. The fix is to register listeners at the very end.
Also eliminated the RoutingDataRepository constructor param and class property since it was unused.
New unit test.
> [router] Fixed NPE in ReadRequestThrottler

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciConfig.java
This PR is the first step to deprecate NonLocalAccessPolicy#QUERY_VENICE. This feature will be completely removed in a later release. Here are the reasons this feature doesn't work well:
1. Remote Venice query is much slower than DaVinci local lookup.
2. Typically, Venice Backend doesn't provision enough capacity for DaVinci use cases since we normally don't know the qps of DaVinci apps and for most of the scenarios, the DaVinci qps can be very high, and we don't want to pre-allocate a lot of backend resources for this feature since the remote resources won't be leveraged most of the time.
In the future, if there are DaVinci use cases, who would like to leverage such capability, we will need to evaluate it properly to make sure such requirement is reasonable or not. From a different …
> [da-vinci] Added deprecated flag to DaVinciConfig#NonLocalAccessPolicy

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggHostLevelIngestionStatsTest.java
I noticed we have a `global disk quota` metric which should always be flat when there's no quota change. We have had `disk_usage_in_bytes` to tell us the real-time disk usage and `storage_quota_used` which computes the percentage. The `global disk quota` is useless IMO and we should get rid of it as it's also a store-level metric so can be expensive. 
GHCI
> [server] Remove a global disk quota metric

- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
Currently the mtadata fetch request from server times out sporadically due to low future.get timeout of 500ms. This PR increase that resolve those timeouts. 
Canaried in controller host.
> [controller] Increase future timeout while fetching metadata

- internal/venice-common/src/main/java/com/linkedin/venice/meta/HybridStoreConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/HybridStoreConfigImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestClusterLevelConfigForActiveActiveReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
Use the ACTIVE_ACTIVE data replication policy when converting the store to an active-active  
replication-enabled hybrid store. With this change, lag will be considered caught up only if the  
lag in all regions is less than the threshold.
> [controller] Use the ACTIVE_ACTIVE data replication policy new hybrid AA enabled stores

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
Previously, we discovered that the lossy offset rewind check was applied after data persistence, which made the lossy check useless since the persisted data will be always same as the one just processed. This PR introduced a dry-mode to persisted offset persisting function:
1. Avoid big refactoring.
2. Run the dry-run mode before data persistence to check whether offset rewind is benign or not and run the regular mode after data persistence to persist the processed offset.
This PR also adds an integration test to validate the split brain issue handling logic.
CI
> [server] apply lossy offset rewind check before data persistence

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AbstractKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicPartitionIngestionInfo.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/MetadataRetriever.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/TopicPartitionIngestionInfoTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/davinci/listener/response/TopicPartitionIngestionContextResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/VeniceJsonSerializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/QueryAction.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/OutboundHttpWrapperHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/RouterRequestHttpHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/TopicPartitionIngestionContextRequest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/OutboundHttpWrapperHandlerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
This PR introduce an endpoint for obtaining topic partition ingestion information. Essentially, it needs version topic and topic partition information to get exact shared consumer to obtain offset and lag information. It returns to the admin tool a json string including offset related information of all topic partitions sharing one consumer. This will help us to debug stuck or slow ingestion and analyze which topic has the issue hurting. 
Essentially, we will get this information about the consumer thread:
-  Consumer Index
- Elapsed time since last successful poll to help us check if consumer is stuck
For each topic partition within the interested consumer thread, we can get theres information:
- Latest offset and offset lag to check if a specific partition is stuck. 
- record and byte …
> [server][admin-tool] Add server endpoint for topic partition ingestion context.

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
There are some code changed the naming of DEFAULT_KAFKA_OPERATION_TIMEOUT_MS. For this test, it seems the topic manager is not needed.
CI
> [test] Fix CI failure caused by legacy DEFAULT_KAFKA_OPERATION_TIMEOUT_MS

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStoreRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/ReadOnlyStoreRepositoryTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
Previously, if version info for a store wasn't available in the metadata repo,
the HB lag monitor would throw an exception, causing state transitions to fail.
This change adds a configurable wait for version info to become available. If it
doesn't, we skip the lag monitor setup and log the failure.
New config:
`server.max.wait.for.version.info.ms (default: 5000 milliseconds)`
A config to control the maximum duration to wait for the version  
information to become available in the store metadata repository  
before skipping Heartbeat (HB) lag monitor setup activity during  
state transition.
> [server] Skip lag monitor setup if the version info is not found in the store metadata

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStat.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStatReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatVersionedStats.java
The resulting metric name contained an extra set of '--' when being hooked up to the reporter.  Additionally, the metric was reporting the time of the last heartbeat, but not the time SINCE the last heartbeat.
Resolves #XXX
> [server] Metric Name fix and math fix for HeartbeatMonitor

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/OnlineVeniceProducer.java
Currently, the clients internal to online producer also registers metrics. While this is not an issue by itself, it could cause issues if online producer and Venice client are used in the same application. This PR disables the metric registration since these metrics are not very useful currently.
GH CI
- Store clients created internal to Online producer will not register and emit any metrics
> [producer] Skip metrics for the SchemaReaders inside online producer

- internal/venice-common/src/main/java/com/linkedin/venice/helix/ZkRoutersClusterManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RoutersClusterManager.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helix/ZkRoutersClusterManagerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/throttle/TestRouterReadQuotaThrottler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/ReadRequestThrottlerTest.java
Commit https://github.com/linkedin/venice/pull/548/files#diff-a543d0bd2b70372ac582bc358f240ee3507b8c3bf14f9e7c8829fb2e9c0de362 removed the live router count change listener in 'ReadRequestThrottler'  which made router quota susceptible to mismatched quota issues during router instances modifications.
This PR fixes that and add tests to capture this issue.
integ test.
> [Router] Add router count change listner in read quota throttler

- build.gradle
- clients/venice-push-job/build.gradle
Apache Spark has a critical vulnerability in versions prior to 3.3.3. ([CVE-2023-22946](https://github.com/advisories/GHSA-329j-jfvr-rhr6)). This PR bumps Spark version to 3.3.3 which has a fix for this vulnerability.
GH CI. Tested manually on test flows
> [vpj] Bump Apache Spark version to 3.3.3

- build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/PubSubHelper.java
This fix ensures that the timestamp used to retrieve `TM::getOffsetByTime`
distinctly identifies messages, preventing collisions that could cause this
test to become flaky.
> [test] Fix flaky TopicManagerE2ETest::testMetadataApisForExistingTopics

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStatReporter.java
This seems to be wreaking some havoc with how Tehuti namespaces metric names.  So replacing it with a '-'.
Resolves #XXX
> [venice-server][metrics] Remove period from metric name

- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/AvroSerializer.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/UnresolvedUnionUtil.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSchemaUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/serializer/AvroSerializerTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/serializer/SerializerDeserializerFactoryTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/update/UpdateBuilderImpl.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/update/UpdateBuilderImplTest.java
When Avro serialization fails for any reason, there is a ThreadLocal BinaryEncoder which can become corrupted. This showed up in unit tests where one test corrupted it and another then produced invalid payloads, but it could also (at least theoretically) happen in production code.
The solution is to catch all exceptions, rather than just IOException, and to make the reusable encoder null, so that another one gets built the next time we serialize. It seems there is no way to properly reset an encoder that has been corrupted in this way, so we abandon reuse in those cases.
In addition to the above fix, the improved union error handling logic has been moved from the online producer to the client-common lib. This requires doing a bit of trickery because the UnresolvedUnionException only …
> [all] Improved Avro serialization reliability

- clients/venice-producer/src/test/java/com/linkedin/venice/producer/online/OnlineVeniceProducerTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/TestAvroStoreClient.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/controllerapi/MultiSchemaIdResponse.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/client/store/AvroGenericStoreClientImplTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/client/utils/StoreClientTestUtils.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterResourceType.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
This PR refactors the RouterBackedSchemaReader implementation to make sure no batch schema fetching under new router endpoint. 
1. It will lazily fetch individual value schema by value schema ID and update schema by value schema ID. 
2. For get value schema id by schema and get latest value schema APIs, we introduced a new router endpoint to /value_schema_ids/schema_name. It will fetch all value schema IDs and then fetch all value schema IDs one by one and derive latest value schema id.
3. For schema refresher thread, it will use the same end point to perform schema refreshing.
4. If new router endpoint is not available, we should fall back to fetch schema by batch.
5. This PR introduces a behavior change: If get value schema / update schema failed router call (throws exception), we will …
> [thin-client][producer][router] SchemaReader will only fetch single schema for all the APIs

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/jobs/ComputeJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
1. Kill `DataWriterComputeJob` from VPJ only when it is in a non-terminal state.
2. Kill Spark job only when `SparkContext` is not closed. Spark doesn't allow performing operations when the `SparkContext` is not running.
3. Handle exceptions thrown by `DataWriterComputeJob#kill` gracefully.
GH CI. Tested manually on test flows
> [vpj] Kill Spark job only when SparkContext is not closed. Handle exceptions gracefully

- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/Segment.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/writer/VeniceWriterTest.java
Today, VeniceWriter (VW) has a bug to run into an infinite recursion when it sends a message in the VeniceWriter and eventually it throws StackOverflowError. For a particular partition, the conditions to trigger the issue are:
1. VW has a cached Segment
2. The segment is neither started nor ended
3. The elapsed time for the segment is greater than MAX_ELAPSED_TIME_FOR_SEGMENT_IN_MS
To fix it, we can break the infinite loop by always recording the new start time.
GH action
> [all] Fix an infinite recursion issue in VeniceWriter

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ImmutableChangeCapturePubSubMessage.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/DaemonThreadFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/ImmutablePubSubMessage.java
- Adjust the indexes of threads created with DaemonThreadFactory to use
zero-based indexing. This change simplifies mapping of threads with
drainer queues and consumers by eliminating the need for additional mental
calculations.
- Override the `ImmutablePubSubMessage::toString` method to include additional
information such as topic-partition and offset in the message output.
> [all] Improve debugging experience

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/recordreader/avro/AbstractAvroRecordReader.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/recordreader/avro/TestVeniceAvroRecordReader.java
- internal/venice-common/src/main/java/com/linkedin/venice/etl/ETLUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
Currently, ETL+VPJ flow makes strict assumptions about schema. It doesn't allow the value schema to have `null` as a default value if the original value schema didn't have a `null` default. This commit allows schemas where the `value` field has a `null` default.
Added unit tests, integration tests
> [vpj] Handle extra null default in ETL+VPJ value schema

- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/Segment.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/writer/VeniceWriterTest.java
* [all] Fix an infinite recursion issue in VeniceWriter
Today, VeniceWriter (VW) has a bug to run into an infinite recursion when it sends a message in the VeniceWriter and eventually it throws StackOverflowError. For a particular partition, the conditions to trigger the issue are:
1. VW has a cached Segment
2. The segment is neither started nor ended
3. The elapsed time for the segment is greater than MAX_ELAPSED_TIME_FOR_SEGMENT_IN_MS
To fix it, we break the infinite loop by always recording the new start time. A new integration test, as well as a unit test, is added to capture any regressions.
Resolves #XXX
> [all] Fix an infinite recursion issue in VeniceWriter (#879)

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AbstractVeniceAggVersionedStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStatReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatVersionedStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
VersionedStats assumes all metrics should be applied for all stores.  This change overrides methods which add stats to check to see if the node should report metrics for the store getting added or not.
Resolves #XXX
> [server][metrics] Add filtering to heartbeat versioned stats for hybrid stores

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/LocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
[changelog][BootstrappingVeniceChangelogConsumer] Update bootstrappingVeniceChangelogConsumer to sync offset during processing and allow multi-consumers with different consumer id.
- Update bootstrappingVeniceChangelogConsumer to sync offset during processing when processedRecordSizeSinceLastSync > databaseSyncBytesInterval.
- Add consumerId in the bootstrappingVeniceChangelogConsumer constructor so we can allow multi-consumers creation. Each consumer will have its own state, rocksDB path, etc.
- unit test
- integration test
> Update bootstrappingVeniceChangelogConsumer with sync offset and allow multi-consumers

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
Make VeniceProperties overridable in PubSubConsumerAdapterTest so that different implementations can tune the 
clients as per their requirement to achieve the desired behavior. 
Resolves #XXX
> [test] Make VeniceProperties overridable in PubSubConsumerAdapterTest

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/datawriter/jobs/DataWriterMRJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/guid/GuidUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/guid/GuidUtilsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
Recently, when abstracting compute engines, the logic to compute a deterministic GUID was changed to be less reliant on the underlying compute engine. However, this change had a bug where the uniqueness of the GUID was tied to the uniqueness of the `jobId` used to trigger the `VenicePushJob`. This commit generates a unique GUID per VPJ job.
GH CI. Updated an integration test
> [vpj] Fix deterministic GUID generation for VPJ

- services/venice-server/src/main/java/com/linkedin/venice/listener/RouterRequestHttpHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStatsContext.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StatsHandler.java
Metadata requests for otherwise unused stores triggers metric collection, which for clusters with high number of stores creates memory pressure. This PR skips metric recording for metadata requests which includes `current_version/health and metatdata` calls.
GHCI
> [server] Do not collect stats for metadata requests

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageEngineRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/ChunkingUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StorageEngineFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/blackhole/BlackHoleStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/cache/VeniceStoreCacheStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/memory/InMemoryStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/venice/cleaner/LeakedResourceCleaner.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/DeepCopyStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/chunking/ChunkingTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/AbstractStorageEngineTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/cache/backend/ObjectCacheBackendTest.java
- services/venice-server/src/main/java/com/linkedin/venice/cleaner/BackupVersionOptimizationService.java
- services/venice-server/src/test/java/com/linkedin/venice/cleaner/BackupVersionOptimizationServiceTest.java
- services/venice-server/src/test/java/com/linkedin/venice/cleaner/LeakedResourceCleanerTest.java
When a version is retired, both Helix resource and ingestion task will be deleted/killed; when Helix resource is deleted, OFFLINE->DROPPED transition message will be sent to server; and when ingestion task is killed, a kill-job message will be sent to servers; these two deletions are happening independently; if transitions are done before kill-job, and if ingestion task is trying to flush RESET_OFFSET actions, servers will fail to find metadata partition.
If metadata partition doesn't exist when trying to clear offsets, there is nothing left to clear and thus no point throwing exception for it.
CI
> [server][da-vinci] Remove noise when clearing offsets without metadata partition

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactoryTest.java
- Adds a new overloaded method getChangelogConsumer with an additional parameter consumerId
- This will be used for having multiple consumers subscribe in parallel to different partitions of the same store
- Added Unit Tests for the new method
Unit Tests for the new API being added.
- No. It adds a new API
> [clients][da-vinci-client] Adds getChangelogConsumer with storeName and consumerId

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AbstractVeniceAggVersionedStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStatReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatVersionedStats.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
We noticed NPE exceptions in deployed instances in the metric collection code paths. This commit handles `null` gracefully and prevents these NPEs.
`AbstractVeniceAggVersionedStats#updateStatsVersionInfo` has the following code:
```
if (newCurrentVersion != versionedStats.getCurrentVersion()) {
versionedStats.setCurrentVersion(newCurrentVersion);
}
...
if (futureVersion != versionedStats.getFutureVersion()) {
versionedStats.setFutureVersion(futureVersion);
}
```
If there is no future version, the `if` block will never get executed. The `setFutureVersion` is what sets the `stat` object. However, the `heartbeat_delay_ms` metric already got registered like:
```
(ignored, ignored2) -> getStats().getFollowerLag(region).getMax()
```
So, `getStats()` would return `null` in such a case.
For …
> [server] Fix NPE when collecting heartbeat_delay_ms and QuotaRcuPerSecondAllowed stats

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/DefaultInputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/InputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/KafkaInputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/ValidateSchemaAndBuildDictMapper.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJobConstants.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestVenicePushJobCheckpoints.java
Currently, `use.mapper.to.build.dictionary` is auto enabled when `compression.metric.collection.enabled` is enabled. This commit separates the two configs for migration purposes and `use.mapper.to.build.dictionary` will not be auto-enabled when `compression.metric.collection.enabled` is enabled and it now needs to be explicitly enabled. Eventually, `use.mapper.to.build.dictionary` will be removed along with the `ValidateSchemaAndBuildDict` job.
Operationally, we have noticed that often, the VPJ jobs wait in the queue to acquire resources from Yarn despite the job only requesting a container for one map task and no reduce tasks. When abstracting the compute engines used by VPJ, we decided to not abstract the `ValidateSchemaAndBuildDict` job. We decided this because the initial reasons to …
> [vpj] Allow enabling compression metric collection without using mapper to build dictionary

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/MultiKeyRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroSpecificStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/factory/ClientFactory.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientUnitTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
1. Error retry was already covered by long tail retry. This means we have error retry at the request level and not at the per route level. This means keys that are not done yet by the long tail retry threshold time will be retried regardless if it's due to latency or error. We have unit tests for various scenarios to complete the table: original request | retry request
fail             | fail
fail             | success
late success     | fail
late success     | success
2. Added the ability to differentiate 429 from other errors so retry is skipped altogether if we encountered 429 (assuming subsequent retry will also be rejected).
Unit and integration tests
> [fast-client] Complete error retry for fast client multi-get

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/datawriter/jobs/DataWriterMRJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
`PushJobSetting` has two configs that are specific to `DataWriterMRJob`. This is an anti-pattern and this commit moves them into `DataWriterMRJob`
GH CI
> [vpj] Clean up PushJobSetting to remove DataWriterMRJob specific fields

- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadOnlySchemaRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/HelixReadOnlySchemaRepositoryTest.java
Previous when user updates a new value schema to the AAWC store, the ongoing ingestion will get acknowledged by ZK store to refresh the schema. Previous retry for fetching the new schema from zk is 3 times with a fixed 100ms, which is very short. Without fetching new schema, the store ingestion could fail.  For a real-prod system, usually server need to wait for 3~5 seconds to fetch this schema after new schema registered.  Here we use exponential back off retry.
Test in prod system by update test store's value schema.
- [ *] No. You can skip the rest of this section.
> [server] Extend retry for new superset schema fetching.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SeparatedStoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedDIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/DIVStatsReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/KafkaConsumerServiceStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/StoreBufferServiceStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- gradle/spotbugs/exclude.xml
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggVersionedDIVStatsTest.java
This PR adds some metrics on the write path to provide fine-granular view, specifically:
1. Add `leader_div_completion_latency` to measure how long it takes for a leader node begins to process each record pulled from pubsub system, e.g. kafka, to the time it finishes DIV(date ingestion validation).
2. Add `internal_process_latency`, which measures how long for a drainer to process a record internally and `process_record_error`, which count the number of errors happen for internal processing in `StoreBufferService`(SBS). The term "internal process" refers to the process nodes persist records on the local disk.
3. Add `storage_engine_delete_latency`, which measures the long to delete a record from store engine.
4. Remove `memory_usage_for_writer_num_` metrics for SBS since they are not …
> [davinci][server] Add more write-path metrics for observability

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/ProducerTool.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
Commons CLI enables partial matching for CLI options. We do not wish to use this as it can lead to unintended commands in `AdminTool`. For example, Since there is no `--get-store` command, `--get-store` matches `--get-store-acl`. While this is benign, there could be other cases where it becomes critical
Tested locally
> [admin][producer] Disable partial matching for Apache Commons CLI

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientGrpcServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStatsContext.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerConnectionStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerQuotaUsageStats.java
1. client_connection_count gauge was not thread safe and resulting in negative numbers.
2. Ensure all KPS from different requests (single, multi and compute) are recorded by server stats so it can be used capacity planning for both thin-client and fast-client use cases.
3. Renamed a SN read quota metrics for clarity and fixed their behavior (QPS vs KPS).
Integration tests
> [server] Fixed a few server metrics that weren't working properly

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
In user onboarding we noticed that multiple consumer will spent extra time on creation. During log investigation, we found that this factory method is the root cause. 
The synchronized keyword makes consumer creation sequential, including Apache consumer creation and StorageService restoration. Each of them could take 1-2s so in total it took ~11 in practice to complete. 
This change should make it truly parallel in creation and save ~10s during bootstrap.
N/A
> [changelog] Make changelog consumer creation parallel in VeniceChangelogConsumerClientFactory

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
There is an edge case where an empty topic with an end offset of zero gets mistaken for an error code, and results in returning Long.MAX_VALUE as the lag instead.
It was not... tests should be added.
> [server][dvc] Lag arithmetic fix

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
While measuring nearline latency from local broker to ready to serve, the messages catching up after a push records longer latencies to these metrics. This changes records `lagCaughtUpTimeInMs` and considers the nearline messages that were ingested only after that time to ignore the already ingested messages. 
GH CI
> [dvc][server]Make recordNearlineLocalBrokerToReadyToServeLatency ignore catchup messages after push

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
The original issue is, when re-bootstrapping a current/backup version partition, when hitting proessTopicSwitch, it will calculate rewind and get the offset by rewind. It will persist the offset to the OffsetRecord. However, due to RT message retention, old messages got removed, and the newly calculated offset is pointing to newer message's offset. When it is processing the message in VT (which was consumed by leader from RT), the old message's offset < persisted offset, and SIT will throw exception, thinking multiple leader is consuming.
After checking the code, I think we do such logic in current code:
**Leader**
1.  processTopicSwitch(drainer): Calculate offset, persist.
2.  leaderExecuteTopicSwitch(consumer long running task thread): Calculate offset, persist, subscribe
**Follower** …
> [server] Remove upstream offset calculation and offset record update in processTopicSwitch() for both leader and follower

- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/OnlineProducerFactory.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/online/OnlineVeniceProducer.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
In #867, we skipped metric emission for `SchemaReader`, but we missed skipping metric emission for the store client that we create to query topic information from routers. This commit addresses this gap.
GH CI
> [producer] Skip metrics for the store client inside online producer

- internal/venice-avro-compatibility-test/src/test/java/com/linkedin/venice/VeniceClusterInitializer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/utils/IntegrationTestPushUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
During new store creation and new schema registration Venice does validate the union default for schemas using `AvroSchemaUtils.validateAvroSchemaStr`, but it does not check wrong numeric default types and allows wrong numeric default to be registered. This later causes ingestion error in server as it does strict validation of schemas. 
This PR will make sure controller schema addition code path does a strict validation.
CI test
> [controller] Check for bad default during new schema registration

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJobConstants.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputMapper.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputReducer.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/ttl/TestVeniceKafkaInputTTLFilter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/mapreduce/datawriter/reduce/TestVeniceReducer.java
- docs/ops_guide/repush.md
- docs/user_guide/ttl.md
- docs/user_guide/write_api/online_producer.md
Currently, [Repush with TTL](https://venicedb.org/docs/user_guide/ttl#repush-with-ttl) uses the store's `rewindTimeInSeconds` hybrid config  as the TTL time for eviction. Some use-cases might require configurable TTL times through configs on their Venice Push Jobs. This commit adds a new config `repush.ttl.seconds` that can be set to specify such TTL configs.
This commit also improves some unrelated logging in VPJ.
GHCI
> [vpj] Allow configuring explicit TTL age in VPJ

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
After customer adopts multiple changelog consumer, we encounter OOM and application killed by consumer. Based on current config setup, we suspect it is caused by multiple RocksDB instance opening 16GB block cache and eventually it use more memory than it should. Since we don't expose RocksDBMemoryStats today, we cannot make sure this is 100% the root cause, but from the behavior change from 1 consumer to 8 consumer with the same dataset, it is likely the cause.
Personally I think it will be great if multiple consumer can share same RocksDB instance without performance impact during bootstrap and consumption. Based on current implementation it would be hard to do so, so we will put this PR as an incremental improvement.
This PR opens up the config for user to set per consumer cache size …
> [changelog] Add RocksDB block cache metric to changeLogClientConfig; Expose RocksDBMemoryStats to changelogConsumer

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
Previously, admin tool only supports apache kafka clients, even it have used `PubSubClientsFactory`. In this change, we let admin tool read from system property to generate a specific implementation of `PubSubClientsFactory`, this will enable admin tool to adopt any implementation of  `PubSubClientsFactory`.
> [admin-tool] Let admin tool deal with PubSubClientsFactory to support various type of pub sub system.

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
The call to TopicManager::getAllTopicRetentions is expensive and unnecessary
for non-local region topic queries. We do not use the retention values from
remote version topics to decide whether to delete local real-time (RT) topics.
Replacing it with TM::listTopics, which is sufficient and more cost-effective.
CI
> [controller] Avoid expensive call to TM::getAllTopicRetentions in TopicCleanupService

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
Using process pid as instance name suffix will not work for VPJ when application slice is performing large scale restart.
This PR introduces a new config as instance suffix to replace PID. And if the config is not specified, we will still use PID as fall back (but not recommended)
Modified existing integration test to verify the new config is adopted.
> [dvc] Add a new config to replace pid as instance name suffix

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-producer/src/main/java/com/linkedin/venice/producer/AbstractVeniceProducer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/heartbeat/DefaultPushJobHeartbeatSenderFactory.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubClientsFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriterFactory.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubClientsFactoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterFactoryTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
This change removes hardcoded references to ApacheKafkaProducerAdapterFactory and
introduces dynamic creation of pub-sub client factories based on runtime configurations.
> [all] Create producer factory based on the runtime configuration

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
This is to screen out bootstrap time from the metric
Resolves #XXX
Normal test suite
> [server][metrics] Only wire heartbeat monitor at end of follower transition

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- internal/venice-common/src/main/java/com/linkedin/venice/common/PushStatusStoreUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReader.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReaderTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushMonitorUtilsTest.java
With changes in this PR, controller will try to compose a version level
key and use it to read from push status system store when checking batch
push status on DaVinci side:
{
keyStrings: {10} // Version 10
messageType: 1 // 1: Full Push
}
Then controller will always try to query the partition level keys, and combine
the result with the old keys, in case DaVinci instances are partially upgraded
and some of them are still populating statuses with old keys.
If controller gets null response for the new key, it will assume that
DaVinci is not upgraded yet, and fall back to partition level keys:
{
keyStrings: {10, 0} // Version 10, partition 0
messageType: 1 // 1: Full Push
}
Roll out steps in order:
1. After the controller changes are rolled out to production and stabilize,
deprecate all …
> [Controller] Implement dual read for Push Status System Store

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
This seems to be making graphs hard to read and causing some deployment noise.  After thinking on it more, this is probably ok since we would expect the alert to trip within 10's of minutes anyway even with a window of monitoring.
Resolves #XXX
> [metrics][server] Remove large sentinal value for default hearbteat lag

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/StorageClass.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
Today, for large batch-get request, the latency will be high even the customer is using `MEMORY_BACKED_BY_DISK` mode. For example, in avg, the lookup latency is about 20us and for a request with 3k keys, the latency will be roughly 60ms, which is high and we often recommend customers to break it down into smaller chunks and execute these chunks in parallel. Now, this PR will add such support for batch-get as a default behavior.
TODO: add such support for compute request.
CI
> [dvc] Split large batch-get to execute concurrently

- internal/venice-common/src/main/java/com/linkedin/venice/utils/ForkedJavaProcess.java
Inherit `-Djava.net.preferIPv6Addresses` config from parent process. If not set, we will default to false.
Existing tests.
> [server][dvc] Inherit ipv6 preference setting from parent process

- docker/venice-router/multi-dc-configs/dc-0.venice.router.properties
- docker/venice-router/multi-dc-configs/dc-1.venice.router.properties
- docker/venice-router/single-dc-configs/router.properties
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/MockVeniceRouterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-standalone/config/router.properties
Add a dedicated thread pool executor for SSL tasks in router. This same feature has been running in production and should be stable. The value of `router.client.ssl.handshake.threads` controls the number of threads that will be used. A value of 0 (default) disables the feature.
GH CI
> [router] Add a dedicated executor for SSL handshakes in routers

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
Exposed total partition count of store from VeniceChangelogConsumer to programmatically facilitate parallel processing (eg. VeniceIO).
GH CI
New method `getPartitionCount` added to experimental `VeniceChangelogConsumer` interface.
> [cc] Expose partitionCount from VeniceChangelogConsumer

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RetryManager.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/stats/RetryManagerStats.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RetryManagerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
1. Introduced RetryManager to measure and calculate retry budget based on a percentage of requests.
2. The RetryManager is only applied to long tail retries and currently hard coded to be 10% of the total original request rate. This means if there were any exception that's not a 429 the retry will be triggered without going through the RetryManager. If the retry budget is exhausted then the retry task will do nothing and the request will either complete eventually (original future) or time out.
Existing and new tests
> [fast-client] Long tail retry budget for fast client

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
During the analysis of DaVinci bootstrapping, we realized that metric collection takes a significant amount of cpu resources (>60%) when bootstrapping a store with many small entries. This PR adds a new config to disable record-level metrics when bootstrapping current version:
server.record.level.metrics.when.bootstrapping.current.version.enabled: default true
When disabling the above config, the record-level metrics will be disabled during bootstrapping, but the record-level metric emission will resume after all the subscribed partitions report ready to serve.
CI
> [server][da-vinci] Introduced a new mode to disable record-level metric when bootstrapping current version

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/stats/BasicConsumerStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
This works similar to the heartbeat lag measure done in server.  This tracks the time of last consumed heartbeat from the version topic.
Resolves #XXX
> Add heartbeat lag metrics to change capture client

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/DictionaryUtils.java
This PR enables the `KafkaTopicDumper` in Admin tool to dump compressed records. It also fixes `TopicMessageFinder` to use serialized key without the chunking suffix to determine the partition
Tested manually.
> [admin-tool] Enable decompression in admin tool topic dumper

- docs/README.md
- docs/dev_guide/dev_guide.md
- docs/dev_guide/how_to/CONTRIBUTING.md
- docs/dev_guide/how_to/design_doc.md
- docs/dev_guide/how_to/recommended_development_workflow.md
- docs/proposals/VIP_TEMPLATE.md
- docs/proposals/proposals.md
- docs/user_guide/write_api/stream_processor.md
Some links in our docs were broken. This PR standardizes to use relative paths, and fixes some broken links. These links work well in README and the website. 
Tested manually. Deployed here: https://nisargthakkar.github.io/venice/
> [doc] Standardize and fix links in docs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/ssl/SslInitializer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/HttpChannelInitializerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ListenerServiceTest.java
Currently Routers and Servers log the CN to help with investigation of the callers. However, this information is insufficient and we'd like to log the service principal name instead.
GH CI. Will be tested in staging env
> [router][server][alpini] Add support for IdentityParser in SslInitializer

- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreBackupVersionCleanupService.java
Since fetching the current version from all router and server is an expensive operation, we should not call backup version cleanup on stores without current version or backup version. Also add a keep-alive period of 1hr to the http client.
GHCI
> [controller] Dont call backup version cleanup service on stores without backup version

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
There was a bug in the previous optmization, which would pause the record-level metric emission for the current version bootstrapping. When the subscription is empty, we shouldn't resume it as it can happen when the store ingestion task is created, but the subscripition is not done yet.
CI
> [da-vinci][server] Don't resume record-level metrics if the subscription is empty

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/LeaderCompleteState.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/ingestionHeartbeat/IngestionHeartBeatTest.java
PR [775](https://github.com/linkedin/venice/pull/775) introduced a feature for hybrid stores' followers to go ready to serve only after leader is marked completed. But it was disabled for non-AA stores as the Heartbeats (which this feature piggybacks on) are written only to local RT's but certain non-AA cases' LFSIT consumes only from parent RT.  One fix considered for these non-AA stores to get onboard to this feature was to write HB to parent RT as well. But as Parent RT is soon to be deprecated and we don't want to add more to it, this PR works around that considering the below aspects and enabling this feature for all stores except non-AA and `DRP=AGGREGATE` stores.
1. All incremental push stores should be Active-active by default.
2. All stores not on AA without incremental push …
> [dvc][server]Enable leader complete status check for non Active-Active stores

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
The overall status should not be updated to COMPLETE till all the region are pushed when target region push is enabled.
GHCI
> [vpj] Do not mark overall status COMPLETE till all region finishes

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManagerStats.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
Currently, if a thread owning a consumer is interrupted, the consumer is not 
returned to the consumer pool. This occurs because the blocking calls throw an 
interrupted exception when invoked by a thread with the interrupt status set. 
In this case, it is the `LBQ::put` call in `TMDF::releaseConsumer`.
As a result, we eventually run out of consumers to execute metadata requests. 
This situation typically arises when non-blocking metrics collection threads 
cancel active executions to terminate slow queries.
CI
> [server] - Fix consumer leaks in TM that occur when the thread owning consumer is interrupted

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
Recently, in #886, we refactored some code around compression metric collection and using mapper to build dictionary. This refactoring had a bug where the dictionary building for repush jobs was skipped and if VPJ sends control messages directly, then the push would fail, as the `START_OF_PUSH` would not have any dictionary. This change fixes the issue and reenables a dictionary to be built for KIF repush as well.
Added an integration test. GH CI will do regression testing
> [vpj] Fix building or fetching dictionary for repush jobs

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
In `AbstractDataWriterSparkJob`, we need a `SparkSession` and to get one, we use `SparkSession.Builder()...getOrCreate()`. This either provides an existing `SparkSession`, or creates a new one if one doesn't exist already. `SparkContext` has a `ShutdownHook` that closes the session at the end of the JVM. When VPJ is executed via `spark-submit`, it executes in the Spark driver. In this case, we do not wish to close the `SparkSession` and instead let the `ShutdownHook` take care of it. This is also okay for client-mode of Spark execution as those can be expected to be short lived. If someone needs a way to explicitly close a `SparkSession`, we can add a new function that helps achieve that. We don't have such a need right now.
GH CI. Tested manually as well
> [vpj] Skip closing the SparkSession and let it be closed at app shutdown

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/MockVeniceRouterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/SecurityStats.java
Config to enable this feature:
router.resolve.before.ssl
When this config is enabled, "SslInitializer#enableSslTaskExecutor" will not be called, and the SSL handshake thread pool count will be used to construct the DNS resolution thread pool.
Besides, added two new SSL related metrics using the API from Netty: pending_ssl_handshake_count
total_failed_ssl_handshake_count
GHCI
> [router] Added config to enable DNS resolution before SSL

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SeparatedStoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
Make separate drainer for batch and hybrid store ingestions so that batch store ingestions does not affect hybrid store ingestions.
integ test
> [server] Make separate drainer for batch and hybrid store ingestions

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
Current state: when we create `AdminExecutionTask` , we did not check if there is `AdminExecutionTask` for one store on the fly, so if one `AdminExecutionTask`  is waiting for a lock (e.g. updating  store operation waiting for the store level write lock and that lock is currently unavailable), it is possible that `AdminConsumptionTask` will create multiple `AdminExecutionTask` s for a single store until they occupy all threads from `ExecutorService` 's thread pool, they are all waiting for the same store-level lock.
Besides, `executorService.invokeAll(tasks, processingCycleTimeoutInMs, TimeUnit.MILLISECONDS)`
will cancel every invoked tasks, even the task is emitted by not getting thread from pool to execute.  `ExecutorService` will try to cancel the `AdminExecutionTask`  waiting for a …
> [controller] Fix multiple AdminExecutionTasks working on the same store at the same time.

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/ChunkingUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/ReplicationMetadataRocksDBStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/chunking/ChunkingTest.java
This PR bumps up the RocksDB dep and expose a config to enable async io for multi-get and the default value is true.
rocksdb.read.async.io.enabled: default true
In theoy, with this config and posix filesystem, RocksDB multiget API will be speeded up quite a bit based on the benchmarking: https://rocksdb.org/blog/2022/10/07/asynchronous-io-in-rocksdb.html
So far, such optimization only applies to the chunk lookup for large value/rmd, and if it is proved to be more performant by checking the lookup latency for large value in the read path, we can apply such optimization in more areas:
1. DaVinci with DISK mode.
2. Ingestion code path by looking up entries in batch for AA/WC use cases.
3. Regular read path. So far, multi-get API can only be used against the same RocksDB database, so we might …
> [server][da-vinci] Bumped RocksDB dep and adopt multiget async io by default

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ReplicationMetadataSchemaRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/RmdDeserializerCache.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangeCoordinate.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestChangelogConsumer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/ingestionHeartbeat/IngestionHeartBeatTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
Fix a few places in the code that use RMD protocol ID instead of value schema id to deserialize value. 
Also, introduce a RMD schema cache to cache the schema.
Adjust existing integration tests to cover schema id > 1 cases.
> [changelog] Multiple fixes to changelog consumer logic

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientGzipEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientZstdEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientGzipTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientZstdTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerReadMetadataRepository.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ServerReadMetadataRepositoryTest.java
1. The idea is to block new fast-client traffic that do not have storage node read quota enabled. New client version will fail fast and have a clear error message to direct the user on what's missing. Old client versions will keep failing the metadata request and the user will also see the error message once dig deeper into the error trace.
Unit test and integration test
> [fast-client][server] Throw 403 for metadata request that does not have storage read quota enabled

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
Many commands expect a mandatory `--cluster` argument to be passed on the command line. The admin tool can also infer that if the store name is also provided. This commit makes the `--cluster` argument optional where possible
Tested locally:
```
$ java -jar clients/venice-admin-tool/build/libs/venice-admin-tool-all.jar --describe-store -u http://localhost:1500 -s "xyz"
...
Store xyz is discovered in cluster cluster-0
...
{
"cluster" : "cluster-0",
"name" : "xyz",
"error" : null,
"errorType" : null,
"store" : {
"name" : "xyz",
...
},
"exceptionType" : null
}
```
> [admin-tool] Make cluster argument optional in Admin tool where possible

- build.gradle
- internal/venice-test-common/src/main/java/com/linkedin/venice/testng/VeniceTestListener.java
- internal/venice-test-common/src/test/java/com/linkedin/venice/testng/TestInterruptContaminationClearing.java
There is an issue either in Gradle or TestNG where a test which sets the interrupt flag on the current thread can cause a later test to fail, due to checking for the interrupt flag (e.g. in sleep and syncrhonization-related primitives).
This commit fixes this by clearing the interrupt flag via the VeniceTestListener::onTestStart listener. Also registered this listener to unit tests (it was previously used only for integ tests), and added a minimal unit test which deterministically reproduces this issue (in the absence of the listener).
Miscellaneous:
- Added calls to super in all functions of VeniceTestListener, as recommended in the parent class' JavaDoc.
GHCI, including a new test.
> [test] Fix for cross-test interrupt contamination

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
1. updateLagMonitor was implemented to expect the version object to never be null. This assumption is wrong because when we are deleting a version the version object is removed from ZK first before the state transition occurs on the server from STANDBY->OFFLINE. Add the option for updateLagMonitor to accept null version if it's called for removeLagMonitor.
2. Separated the logging for null store and null version to be explicit and not logging store objects.
New unit test and existing unit+integration tests
> [server] Lag monitor should not expect corresponding version always exists in ZK

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
The PR: #846 modified the method responsible for handling lossy rewind checks: it updated
the function to suppress the lossy rewind issue only after reporting completion, rather
than upon receiving the EOP. It is important to note that the status of reported completion
is not permanent and can change during state transitions. As a result of this change, there
is an increased likelihood of ingestion stalls / failures due to lossy rewinds, compared
to the previous method based on the EOP signal.
This PR reverts the check function to its original state, where the lossy rewind issue is
suppressed after reporting the EOP signal, as it was before pull request #846.
This fix is intended to avoid serving stale data. The only downside is that data
for a few keys might be inconsistent, but this …
> [server] Revert lossy rewind criterion to EOP from completion reporting

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StoragePartitionConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/DeepCopyStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/AbstractStorageEngineTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestionWithReadWriteLeaderCompactionTuning.java
In the ingestion path, we often tune level0 compaction to optimize read/write/space optimization.
When AA/WC is enabled, the leader replica will read the same database while ingesting, which is different from standby replicas. To optimize the read perf of leader replica, this PR exposes the following config:
rocksdb.level0.compaction.tuning.for.read.write.leader.enabled: default false rocksdb.level0.file.num.compaction.trigger.for.read.write.leader: default 10 rocksdb.level0.slowdown.writes.trigger.for.read.write.leader: default 20 rocksdb.level0.stops.writes.trigger.for.read.write.leader: default 40
Essentially, there are 3 sets of level0 compaction tunings:
1. Leader replicas for AA/WC stores.
2. Future version.
3. Current version.
The main reason we would like to only optimize the …
> [server] Feature to tune level0 compaction tuning for read-write leader

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientGrpcServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/grpc/VeniceGrpcEndToEndTest.java
- Fix tests failures due to #975 
- Extracting the test fixes from #987 
- Reset storage node read quota enabled flag prior to each test in `FastClientIndividualFeatureConfigurationTest`
ran the failing tests locally in intellij and terminal
> [client][internal] Fix tests related to PR#975

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/input/hdfs/VeniceHdfsInputPartitionReader.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/input/hdfs/VeniceHdfsInputScan.java
The current spark job is incapable of reading from other file systems because it takes the default file system. This adds the fixes on such cases enabling to read from any file system. Related to https://github.com/linkedin/venice/pull/711
Tested on s3 which fails on the current code with error
```
java.lang.IllegalArgumentException: Wrong FS: s3a://.../.../a.avro, expected: file:///
```
Which now succeeds
> [vpj] Fix file system on spark push job
