- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
This change cleans up the code in PartitionTracker based on IDE warnings and there should have no semantics or functionality modifications.
passed CI tests.
> [davinci] PartitionTracker code cleanup

- build.gradle
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/GrpcClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/transport/GrpcTransportClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/GrpcClientConfigTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/transport/GrpcTransportClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientGrpcServerReadQuotaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationtest/java/com/linkedin/venice/fastclient/grpc/VeniceGrpcEndToEndTest.java
- [Functional] Introduce logic to use fallback Grpc port for netty server address -> Grpc server mapping
- [Refactor] Modularize request handling and remove boiler plate in `GrpcTransportClient`
- [Bug fix] Fix integration tests that was failing due to #975 
- [Clean up] Remove some validations, added few invariants check and reorganize some depending on the mode (local vs integration/production)
- [Clean up] Rename fields to remove type information
- [Test] Add unit tests for `GrpcTransportClient` class
- Unit test and integration tests
- Deployed client changes locally with test application
> [internal][client] Support GRPC port discovery for non-local environment

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
There is only one code path calling this function and it is part of deleting a store-version. Therefore, it is expected that a store-version would not be found and there is no point in logging an exception for it.
GHCI.
> [controller] Muted exception from a log in VHA::hasFatalDataValidationError

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/supersetschema/SupersetSchemaGeneratorWithCustomProp.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/supersetschema/TestSupersetSchemaGeneratorWithCustomProp.java
This PR fixes two issues:
1. Do the superset schema generation dry-run when first enabling read/write compute.
2. Fixed a bug that when the superset schema already contains custom prop, there is no need to mutate it (mutating an existing prop in Avro schema is not supported).
CI
> [Controller] Fixed superset schema generation issue

- build.gradle
This PR bumps the diff code coverage from 40% to 45%.
We used to have lots of integ tests and few unit tests. Since 2023, we invested some effort to enforce unit test coverage   so people would write more unit tests to catch some bugs that are expensive to test in a integ or cannot be tested by a integ test. The goal was aggressively set to 80% but it hurt devs' velocity to deliver codes since we have too many files that don't have a good test coverage. To get this rolled up slowly, we started with 33% and bumped it to 40% after several months. This PR is a part of effort to continuously raise the bar.
N/A
> [CI] bump the code coverage

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/AbstractPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumerAction.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StatusReportAdapter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/LogNotifier.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StoragePartitionConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/ReplicationMetadataRocksDBStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManagerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubTopicPartitionImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Currently, extracting logs for a specific replica is challenging due to varying log formats
chosen by developers. For instance, consider the complexity of this command:
grep -e " 205 " -e ": 205)" -e "=205," -e "=205 " -e ": 205 " -e "_205" -e "-205-" -e " 205;"
-e ": 205," venice-server-war.log.2023-11-2* | grep -v "205 ms" | grep -v "205 second"
Even with such a command, we might not retrieve all logs for the replica. The aim of this commit
is to adopt a standardized logging format for topic-partition/replica ID, to make log extraction
easier and more straightforward.
> [server][dvc] Adopt standard logging format for topic-partition/replica ID to simplify log extraction - PART 1

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
Offset from ConsumerRecord might not be a Long in future, log it as a string on purpose.
Added unit test to ensure new log is working.
> [server][da-vinci] Fixed lossy rewind logging bug

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManagerStats.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicManagerStatsTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicManagerTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/MockInMemoryAdminAdapter.java
Added a metric: `pub_sub_admin_op_failure_count` to track the count of failed admin operations. This will allow us to monitor these failures and set up alerts.
> [controller][server] Add metric to track pub-sub admin operation failures

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubClientsFactory.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupServiceForParentController.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForMultiKafkaClusters.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForParentController.java
Add dangling topic checking functionality,  `TopicCleanupService` will compare topics listed from source of truth pub sub system and topics from other type of pub sub client, if there is topic could not be found by source of truth pub sub system client but can be founded by other type of pub sub client, topic will be deleted if met by times more than `CONTROLLER_DANGLING_TOPIC_OCCURRENCE_THRESHOLD_FOR_CLEANUP` by such cases:
1.  Real-time topic, if store is not hybrid and no store version carries hybrid config,  that topic is not valid. 
2. Version topic, if store does not contain that version, the topic is not valid. 
3. If there is no store available for that topic, the topic is not valid. 
Add a config for source of truth admin client class: …
> [controller] Support dangling topic check and deletion in topic cleanup service.

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/transport/GrpcTransportClient.java
- internal/venice-test-common/build.gradle
- Fix package name in CI test bucketing logic for proper bucket allocation
- Also rearranged some tests so that overall time to run E2E is below 30mins
Resolves #XXX
> [CI] Correct package name in CI test bucketing logic for accurate bucket allocation

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/HelixScatterGatherRoutingStrategy.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/LeastLoadedClientRoutingStrategy.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/HelixScatterGatherRoutingStrategyTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/LeastLoadedClientRoutingStrategyTest.java
There is a bug in our getReplicas code for both routing strategies:  HelixScatterGatherRoutingStrategy and LeastLoadedClientRoutingStrategy where we accidentally cast requestId (a long) into an int and this can cause integer overflow and return negative index.
int startPos = (int) requestId % replicaCnt;
instead of 
int startPos = (int) (requestId % replicaCnt);
New unit tests
> [fast-client] IndexOutOfBoundsException in getReplicas due to bad casting

- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
Current default for retry limit per route for long tail retry is -1, which is equivalient to unlimited retries. During high traffic or slow server responses, that could lead to retry storm which will flood the servers with many requests. This PR limits per route maximum retry limit to 2. Also reduces the default threshold for pending connection per server to 100, so that router does not send too many requests to an already slow host.
1. `venice.router.long.tail.retry.max.route.for.multi.keys.req` to 2 to limit retry storm.
2. `venice.router.unhealthy.pending.connection.threshold.per.host` to 100 to protect the server better.
CI
> [router] Set default config value to limit long tail retries to 2

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestChangelogConsumer.java
Instead of implementing a listener as in #1012 , a simpler solution is just to provide an API that user can call to check whether all subscriptions have caught up.
Also, add specific record support for regular consumer
> [changelog] Add isCaughtUp() API to VeniceChangelogConsumer interface

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubProducerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestFatalDataValidationExceptionHandling.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapterITest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/admin/PubSubAdminAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/producer/MockInMemoryProducerAdapter.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/producer/TransformingProducerAdapter.java
The endAllSegments function will now write to all segments in parallel, and wait once at the end, rather than block for each one sequentially.
The close function now honors the venice.writer.close.timeout.ms config strictly. Previously, it could wait longer than this during close.
Deleted the following unused config from the VeniceWriter: venice.writer.sleep.time.ms.when.topic.missing
Deleted unnecessary overloads in ApacheKafkaProducerAdapter. In particular, stopped relying on the flush with timeout API, because it only exists in LinkedIn's fork of Kafka, and thus prevents moving to the Apache fork of Kafka.
Tweaked the synchronization to prevent race conditions when calling close multiple times. It should now be impossible to receive a RejectedExecutionException due to the …
> [dvc][server][vpj][producer][controller] Refactored VeniceWriter's close

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DelegatingAvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/DaVinciClientMetaStoreBasedRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DelegatingAvroStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroComputeRequestBuilder.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderV3.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderV4.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroGenericReadComputeStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/DelegatingStoreClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AbstractAvroStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AvroComputeRequestBuilderTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/StatTrackingStoreClientTest.java
- clients/venice-thin-client/src/test/resources/SameCanonicalAsRecordValueSchema2.avsc
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/ComputeRequestWrapper.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/SchemaData.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/SchemaReader.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixReadWriteSchemaRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlySchemaRepository.java
- internal/venice-common/src/test/java/com/linkedin/venice/schema/TestAvroSchema.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/client/store/StoreClientPerfTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Today, `getValueSchemaId` APIs in `SchemaReader`, `SchemaData` and `ReadOnlySchemaRepository` match the schemas exactly (with the exception of `HelixReadWriteSchemaRepository`). These APIs are generally used to get a schema id to write along with the data. In such cases, we only care about canonical schemas.
The exception is where we want to register a schema with a doc change. In our codebase, this schema check is not handled via `getValueSchemaId` APIs and happens in the `VeniceHelixAdmin#addValueSchema` code paths which handle this case explicitly.
This PR makes `getValueSchemaId` use canonical schema match in all places.
Updated tests. GH CI
> [all] Make getValueSchemaId APIs match the canonical schemas

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/input/hdfs/VeniceHdfsInputPartitionReader.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/spark/input/hdfs/TestSparkInputFromHdfs.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Incremental push has a user-friendly mode for partial update so users don't have to know the full update schema. VPJ would generate the full update request based on the input data's schema and the fields in that schema.
This feature is not implemented properly in Spark and causes deserialization exception in servers. This is quite critical because the Server cannot recover from this anymore without the RT data being truncated. This is also a data-loss.
Added a new unit test. Updated `PartialUpdateTest`. GH CI for regression tests.
> [vpj] Fix user-friendly partial update mode in Spark

- make_tag.py
Managing too many patch versions is hard. Bump the minor version when the patch version reaches 100.
Tested locally:
```shell
$ ./make_tag.py
Using remote: upstream
From github.com:linkedin/venice
* branch                main       -> FETCH_HEAD
From github.com:linkedin/venice
* branch                main       -> FETCH_HEAD
From github.com:linkedin/venice
* branch                main       -> FETCH_HEAD
Current branch tagBumpBuild100 is up to date.
New tag is 0.5.0. Continue? [y/N]:  
```
> [build] Bump minor version when patch versions reach 100

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/ValidateSchemaAndBuildDictMapperOutputReader.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/ValidateSchemaAndBuildDictOutputFormat.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJobConstants.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/schema/HDFSSchemaSource.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/utils/HadoopUtils.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestValidateSchemaAndBuildDictMapperOutputReader.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/utils/TestHadoopUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
Currently, VPJ uses temp directories for at least two features:
1. To store the output from ValidateSchemaAndBuildDict mapper job to pass the dictionary to the driver
2. To store schemas for TTL repush
In the future, we might add more such cases where data needs to be stored in a temp directory. Currently, each feature that needs a temp space, creates and manages it separately, leading to inconsistencies in the data format, and also facing the same issues each time (like permissions, etc).
For operational reasons, it is desirable to have a temp directory that is shared by all VPJ jobs, and inside this, we can create other feature-specific shared directories that are also shared by all VPJ jobs. These shared directories will have 777 permissions so any user can write to it. If features …
> [vpj] Unify shared temp directories for VPJ

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/utils/HadoopUtils.java
Remove extra call to PubSub to fetch partition count for data writer job. There was a job failure in production where the VeniceWriter tried to query PubSub to fetch the partition count during the PartitionWriter phase. Since the partition count is always available before the DataWriter job starts, we can specify it explicitly and reduce one call to the PubSub system.
Also, improve docs and logging for shared temp directory for VPJ
GH CI
> [vpj] Remove extra call to PubSub to fetch partition count for data writer job

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestUnusedValueSchemaCleanup.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
During unused schema cleanup, parent controller sends admin message to all admin including parent admin as well. Since the unused schema info is stored in meta store which is not available in parent cluster it would fail the admin message. This PR skips the query for parent colo and queries the schema set only from child controller.
integ test.
> [controller] Do not call metadata store in parent controller

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
1. When recordTransformer is enabled, `onStartIngestionTask() `and `onEndIngestionTask()` are invoked during the start/end of an IngestionTask.
2. Added sensors to measure the latency of `onStartIngestionTask() `and `onEndIngestionTask()`.
CI
> [dvc] Invoke lifecycle methods in StoreIngestionTask for RecordTransformer

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
The `testAssembledValueSizeSensor()` unit test from #1009 is flaky and fails very frequently on GHCI runs. The turns out to be due to the `verify()` assertions being outside the `runTest()` function, which causes the `StoreIngestionTask` to be prematurely closed before all messages have been processed. Moving the `verify()` lines solves the problem.
Thanks to @sixpluszero for the help.
GHCI
> [test] Fix Flaky testAssembledValueSizeSensor Unit Test

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
1. per region status returned by controller holds `ExecutionStatus` data, but is read as `PushJobDetailsStatus`. Have been working so far coincidently based on the resulting statuses, but adding new DVC statues uncovered this issue. Added a method to transform `ExecutionStatus` to `PushJobDetailsStatus` after reading in VPJ.
2. `VeniceHelixAdmin.STATUS_PRIORITIES` didn't include the new DVC error status resulting in these returning as ERROR and these new statuses were not getting checkpointed. Added these and added unit tests to check for proper returns.
GH CI
- [] No. You can skip the rest of this section.
> [vpj][controller] Fix mismatch in per colo status reporting and overall status priorities to include DVC error codes

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/validation/KafkaDataIntegrityValidatorTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/validation/TestPartitionTracker.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/checksum/AdHash.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/checksum/CheckSum.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/checksum/CheckSumType.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/checksum/IncDigestCheckSum.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/validation/SegmentTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/validation/checksum/TestCheckSum.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/CheckSumTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
[controller][server][client][test] Adds a new checksum type ADHASH for data integrity validation
This PR adds a new checksum type ADHASH for Venice's DIV. ADHASH adopts the
ideal of incremental hash from AdHash and leverages the CRC32 as the underlying
hashing algorithm.
CRC32 is commonly used in networks and storage devices for detecting data corruption.
The purpose of this algorithm is not to protect against intentional
changes (cryptographic hashing), but rather to catch accidents like network errors
and disk write errors, etc. The emphasis of CRC32 is more on speed than on security.
For testing, this PR extends all the existing checksum and DIV tests to include the
new ADHASH type.
- Extends existing related tests to include the new type.
- Enabled `ADHASH` as the default …
> [controller][server][client][test] Adds a new checksum type ADHASH for data integrity validation

- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/ingestion/IsolatedIngestionServerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientDiskFullTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientDaVinciClientCompatTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/DaVinciTestContext.java
Some flags (DAVINCI_P2P_BLOB_TRANSFER_PORT) were added to this [PR](https://github.com/linkedin/venice/pull/1046). However, they aren't needed.
Ran the integration tests
- [X ] No. You can skip the rest of this section.
> remove unnecessary blob transfer feature flags from tests

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/ChunkingUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/ReplicationMetadataRocksDBStoragePartition.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/chunking/ChunkingTest.java
This reverts commit 02591a119534377cbd1d993e8276d3548d6d3669.
One important partner discovers some TTL DB issue with this version and that particular feature is not being used by Venice.
In the future, we will roll-forward to pick up RocksDB-9.x, which has the fix and add back this feature during the 9.x version upgrade.
CI
> Revert "[server][da-vinci] Bumped RocksDB dep and adopt multiget async io by default (#950)

- internal/alpini/router/alpini-router-base/src/main/java/com/linkedin/alpini/router/ScatterGatherRequestHandlerImpl.java
- CompletableFuture.thenCompose requires functions that do not return null.
- The return from findPartitionName is a CompletionStage (async).
- dedup partition names after retrieving partition names for each key.
- only call appendError once when there are multiple partition keys.
Resolves #XXX
Not yet tested ;-)
> [router] Fix NPE in ScatterGatherRequestHandlerImpl

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
This PR makes the `--end-date` arg optional, and if it is not specified, or if the value is later than the current time, then the end offset of the topic is used to get the offset.
Tested manually
> [admin-tool] Make end-date arg optional in query-kafka-topic

- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatus.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusTest.java
Today, we see NPE during "kill-job" while checking for fatal DIV errors. This commit explicitly checks for a `null` and avoids the NPE
GHCI
> [controller] Avoid NPE in DIV check during kill-job

- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
In `handleValueSchemaLookup` it allocated the schema response into a array of size number of schemas and sets them using the schema id as index into the array.  But if there are schemas which are deleted then those insertions would throw `java.lang.ArrayIndexOutOfBoundsException`. This PR fixes that.
unit test
> [router] Fix MultiSchemaResponse fetch in metadata handler

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestClusterLevelConfigForActiveActiveReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestClusterLevelConfigForNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/AbstractTestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/CheckSumTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/MetaSystemStoreTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/ParticipantStoreTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/StoragePersonaTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestFatalDataValidationExceptionHandling.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridMultiRegion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridStoreDeletion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStaleDataVisibility.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreUpdateStoragePersona.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestWritePathComputation.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/ServiceFactory.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceMultiClusterCreateOptions.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceMultiRegionClusterCreateOptions.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/ssl/AdminChannelWithSSLTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/multicluster/TestMetadataOperationInMultiCluster.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestBlobDiscovery.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
There are several tests that create multi-region clusters through manual, non-standard setups. An example of this is that many tests create a multi-region cluster that shares the same Kafka cluster between them. While this might be valuable for some tests, it is a maintenance overhead for most of them. Our test suite already has `VeniceTwoLayerMultiRegionMultiClusterWrapper` that can be used directly for all current use-cases.
This commit replaces all tests that setup a multi-region test cluster through non-standard means to use `VeniceTwoLayerMultiRegionMultiClusterWrapper` instead. 
This commit also fixes an issue where if the config to enable active active by default for batch-only stores is enabled, new store creation for system stores makes them also active-active. This was masked …
> [test][controller] Fix multi-region tests to use VeniceTwoLayerMultiRegionMultiClusterWrapper

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Repush with DELETE as the last update to a certain key will fail the job, as before EOP, AASIT's processing will short-circuit to LFSIT logic, the DELETE handling there does not take the DELETE payload as it did not expect DELETE can carry RMD info and thus in the drainer side it will throw NPE.
Add a new integration test to validate the case.
> [server] Fix error in repush with DELETE in AASIT

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
When fetching schemas from routers in a thin client, any transient issues can cause requests to fail, leading the client to save a null schema for the schema ID, which results in further request failures. This PR addresses the issue by forcing a refresh during schema fetches and increasing both the retry count and delay for router requests.
unit test
> [venice-thin-client] Allow refresh while fetching value from router

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/datawriter/jobs/DataWriterMRJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreInfo.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriterOptions.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestSystemStore.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterFactoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushJobDetailsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoreRoutesTest.java
**NOTE:** This PR adds the code for enforcing record size limits, but no push jobs will fail by default until the controller config `controller.default.max.record.size.bytes` is adjusted and deployed for each cluster.
1. When users try to push Venice records larger than `maxRecordSizeBytes` (introduced in #1027), the Batch Push Job will fail, reporting a `RecordSizeTooLarge` error. This is the same error that is emitted when `chunkingEnabled=false` and a user tries to push a record surpassing the `1MB` Kafka record size limit (handled by `maxSizeForUserPayloadPerMessageInBytes`).
2. The default is unlimited / unset (`-1`), but the store-level config `maxRecordSizeBytes` can be adjusted on the store itself.
3. The intended way of changing the setting fleetwide is by modifying the …
> [vpj] [controller] Enforce Record Size Limit on Batch Push Jobs

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/ZkCopier.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestZkCopier.java
- internal/venice-common/src/main/java/com/linkedin/venice/zk/VeniceZkPaths.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/zk/TestMigrateVeniceZKPaths.java
- Implemented AdminTool command to migrate Venice-specific metadata from a source ZooKeeper to a destination ZooKeeper.
- Completed manual testing with ei-ltx1 ZooKeeper server and migrated some of its metadata to a local Apache ZooKeeper server in standalone mode.
- Reading and writing `data` for ZNode works!
**Future steps:**
- Folders on ZooKeeper contain `ACLs`, `Stat`, and `Context` so we should look into migrating this information as well.
- We tested migration from a live ZooKeeper server -> local Apache ZooKeeper server. We will test migrating metadata from local Apache ZooKeeper server -> live ZooKeeper server in future end-to-end testing.
- Currently, we are building a tree of paths that we want to migrate from the source ZK, then converting it to a list. We will refactor this …
> [admin-tool] Metadata migration from source ZK to destination ZK

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RetryManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/stats/RetryManagerStats.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/RetryManagerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRouterRetry.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceDelegateMode.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceComputePath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceMultiGetPath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceMultiKeyPath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VenicePath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceSingleGetPath.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceDelegateMode.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVenicePathParser.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/path/TestVeniceComputePath.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/path/TestVeniceMultiGetPath.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/path/TestVenicePath.java
1. Move RetryManager to venice-common so it can be used by both fast-client and venice-router. Refactored the constructor a bit so in Venice router we can initialize instances of RetryManager per store (max 2, single-get and multi-get) without  initializing multiple schedulers. 
2. RetryManager for fast-client has store level resource isolation because a fast-client instance is mapped to a single Venice store. RetryManager for venice-router in this change is also made to have store level resource isolation.
3. Updated the fast-client RetryManagerStats with store name in metric prefix to avoid conflict/confusion since a user host could have multiple instances of fast-client for multiple stores. 
Unit tests and integration tests
> [router][common][fast-client] Add RetryManager to venice-router

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/AbstractTestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
Some tests of `TestAdminSparkServer` were flaky or incorrect. Fixed them.
CI
> [test] Make some tests in TestAdminSparkServer less flaky

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePutWithFieldLevelTimestamp.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/VeniceChunkedPayloadTTLFilter.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/VeniceRmdTTLFilter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/ttl/TestVeniceChunkedPayloadTTLFilter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
This PR addresses two issues related to AAWC:
(1) SIT does not fail when it tries to merge PUT with existing value level RMD record. This can happen when user enables PartialUpdate for an AA store and performs either a restart or repush.
(2) TTL Repush job does not fail when DELETE is the latest value of a key.
Add new integration test and modify existing integration test.
Will also try to add new unit test for more coverage.
Now we can perform repush to create a new version or just execute a cluster wise restart to pick up the PU config change (the restart case it not ideal, there should be a future PR to refactor ParitalUpdate config to become a version aware config)
> [vpj][server] Fix DELETE handling in TTL repush and allow server to auto convert value level TS to field level TS

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionWiseKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicWiseKafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/IngestionThrottlerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
When working with DaVinci customers, we often tune the ingestion params to speed up the bootstrapping, but we don't want to use the same setup at the steady state since the high ingestion throughput would affect the performance of the read path. This PR introduces a way to dynamically switch ingestion throttlers based on the ingestion status.
Essentially, this new feature would switch to the speedup throttler when it detects any current version bootstrapping and otherwise, it will continue to use the regular throttler.
To optimize the bootstrapping perf, we can bump up the following pools together with this feature:
1. Consumer pool.
2. Drainer/writer pool. As the GC issue is mainly triggered by the ingestion speed, we can safely increase the pool size.
New configs: …
> [da-vinci] Added a speedup throttler when DaVinci is bootstrapping current versions

- internal/venice-common/src/main/java/com/linkedin/venice/acl/handler/StoreAclHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStoreAclHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ServerStoreAclHandlerTest.java
In venice server the resource for ServerStoreAclHandler is a version topic for STORAGE and COMPUTE query actions but it's still a store name if the query action is DICTIONARY. Always processing it as a version topic will result in an empty string as the resource name.
Added tests with a mock DynamicAccessController to verify basic request parsing and handling for ServerStoreAclHandler.
Added new unit tests
> [server] Fixed ServerStoreAclHandler unable to process DICTIONARY query action

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/ByteUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriterOptions.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPartialUpdateWithActiveActiveReplication.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/tehuti/MetricsUtils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/ChunkingTestUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
Added a metric to alert customers when they are nearing the record size limit by providing the percentage of the record limit reached.
1. **[Metric]** Added the metric `assembled_record_size_ratio` which is a ratio of the record size (for records that need chunking, similar to #1009) divided by the `maxRecordSizeBytes` record size limit.
2. **[Metric]** Replaced the metric `assembled_record_value_size_in_bytes` with `assembled_record_size_in_bytes` to pair with `assembled_record_size_ratio`, so we have both metrics that are measuring record size.
3. **[Functional]** Stopped counting RMD size towards the `maxRecordSizeBytes` limit (added in #1052), because it's an internal component and a user's write operation should not be failed because of it.
4. **[Config]** Renamed the controller …
> [server] Ratio Metric for Max Record Size

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- clients/venice-producer/src/test/java/com/linkedin/venice/producer/online/OnlineVeniceProducerTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/DataReplicationPolicy.java
- internal/venice-common/src/test/java/com/linkedin/venice/store/StoreStateReaderTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DataRecoveryTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/ingestionHeartbeat/IngestionHeartBeatTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
Deprecate the ACTIVE_ACTIVE data replication policy, as it is no longer necessary  
for lag measurements. Additionally, deprecate the NONE data replication policy.
CI
> [controller] Deprecate ACTIVE_ACTIVE and NONE data replication policies 

- internal/venice-common/src/main/java/com/linkedin/venice/helix/ZkRoutersClusterManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RoutersClusterManager.java
- services/venice-router/src/main/java/com/linkedin/venice/router/throttle/ReadRequestThrottler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/throttle/ReadRequestThrottlerTest.java
Set the ReadRequestThrottler.storesThrottlers AtomicReference at the definition site, containing an empty map, to fully eliminate NPEs, even if listeners are added before the end of the constructor. Also added a unit test to repro the issue.
Miscellaneous:
- Reduced accesses to the ReadRequestThrottler.storesThrottlers, to make it easier to see whether mutations are within the scope of a lock or not.
- Deleted the RoutersClusterManager::unSubscribeRouterCountChangedEvent function since it is unused.
New unit test.
> [router] NPE fix for ReadRequestThrottler constructor/listener

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/NettyP2PBlobTransferManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/client/P2PFileTransferClientHandler.java
When doing blob transfer the files passed in would have already been somewhat initialized instead of it being a clean file. This fix reorganizes the DefaultIngestionBackend file to ensure that blob transfer will be tried first with a clean file.
Local build and QEI testing
> [da-vinci] Open RocksDB after blob transfer is completed

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicPartitionIngestionInfo.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/TopicPartitionIngestionInfoTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
During ingestion debugging process, version topic information of all topic partitions on one consumer are still very useful. As we need this ingestion speed or last poll time for topic partition of all version topics for debugging slow ingestion issues.  The version topic is the destination of `DataReceiver` inside `ConsumptionTask` for each `PubSubTopicPartition`, so here adding a one method for `ConsumptionTask` to get version topic.
Resolves #XXX
> [server] Add version topic information to topic partition ingestion context.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdate.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithValueLevelTimestamp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
- internal/venice-test-common/src/main/resources/valueSchema/UserWithFloatArray.avsc
- internal/venice-test-common/src/main/resources/valueSchema/UserWithStringMap.avsc
There is an edge case when a chunk is assembled from batch push that the result of the assembling doesn't contain the schema id in the first few bytes of the resulting record (there's even a bit of code in the ingestion task today which adds it back later in the processing pipeline).  This means that the old code parsing the schemaid in this case would get a corrupted schema id.  Looking at the code, in this path the reader schema is always the latest superset schema id anyway, and should therefore be safe to utilize for deserialization of the record (no field drops should should occur).  This has the advantage of requiring not much change, though it might be more technically correct to make passing the original schema id more explicit in the code?
Unsure what might be more preferred.
> [server] Use chunk manifest schema id for writer when performing updates to chunked records

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/LogNotifier.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerConnectionStatsHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ServerConnectionStatsHandlerTest.java
**Switch to channelActive/channelInactive for Accurate Connection Tracking:**
Replaced the use of channelRegistered/channelUnregistered with
channelActive/channelInactive to improve the tracking of active connections.
**Safety Enhancements:** Added safeguards to ensure connections are only tracked if
they have been correctly marked as active. This prevents multiple
channelActive/channelInactive events from being processed for the same
connection and avoids tracking connections that are marked inactive before ever
being marked as active.
**Router Principal Update:** Updated the router principal name from CN=venice-router
to venice-router and switched to using a substring match instead of equals for
more flexible connection tracking from routers.
**Log Notifier Improvement:** Enhanced log …
> [server] Fix server side connection tracking and logging

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/MultiKeyRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/stats/FastClientStats.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
[fast-client] Added fanout size metric for FC to monitor multi-key HAR performance
Added `multi_key_fanout_size` Avg and Max metric so we can monitor FC multi-key request fanout size
for HAR.
Existing and new integration test
> [fast-client] Added fanout size metric for FC to monitor multi-key HAR performance

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicPartitionForIngestion.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
This PR is mainly for simplifying the logic of consumer pool assignment logic when subscribing one topic partition through `PartitionReplicaIngestionContext`.  Inside `KafkaConsumerServiceDelegator`, A `ConsumerPoolStrategyType` is defined to specify consumer pool allocation strategy implementation of `ConsumerPoolStrategy`.  
`AggKafkaConsumerService#subscribeConsumerFor` will pass `PartitionReplicaIngestionContext` with `VersionRole` and `WorkloadType` information to let `CurrentVersionConsumerPoolStrategy`  pick up the specific consumer pool.  Each instance of  `KakfaConsumerService` will be built inside `ConsumerPoolStrategy`.  
`CurrentVersionConsumerPoolStrategy` will support for 4 different consumer pools with these 4 configs:
1. …
> [server] Supporting 4 consumer pools for current version and isolation for AA WC leader.

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RetryManager.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/RetryManagerTest.java
Unlike routers where traffic from many thin-clients are funnelled through a relatively small set of routers, FC can have the following scenario:
1. Many FCs doing low QPS high batch size multi-key workload. e.g. 1-2 QPS with batch size of 500.
2. RetryManager will calculate to have the refill amount to be at least 1 for the token bucket.
3. If the long tail retry threshold for batch get is misconfigured and we are constantly retrying on all keys then we are not really limiting the retries to be 10% of traffic. The KPS will double for 1 QPS, 50% for 2 QPS and so on. The impact could be significant when there are many FCs with low QPS. The excessive retry could be triggered by bad configs or degrading servers. Both were the intended scenario for retry budget.
Enforcing the retry budget at …
> [fast-client] Make multi-key retry budget enforce at key level in FC

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/AbstractStoreMetadata.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/LeastLoadedClientRoutingStrategy.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientUnitTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/LeastLoadedClientRoutingStrategyTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/AvroStoreClientEndToEndTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
This PR fixed two issues:
1. Request banding issue and it was caused by the request-id-based replica selection while using least-loaded routing strategy, and the fix is to randomize the replicas for even distribution.
2. Only generate a new request id when trying to send out a request out.
This PR also disabled a few test cases, which rely on the deterministic replica selection while using least-loaded routing strategy and need to evaluate whether we should remove them completely or not.
This PR exposes one more config: `harClusters` and if the discovered server d2 service name fails into this category, `ClientRoutingStrategyType.HELIX_ASSISTED` will be used and if the customers would like to skip HAR routing algo, they can pass an empty set.
I also discovered a few issues when …
> [fast-client] Fixed request banding issue and request id generator

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicPartitionIngestionInfo.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/TopicPartitionIngestionInfoTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
This PR adds an integration test support for verifying the pool jumping strategy: `KafkaConsumerServiceDelegator.ConsumerPoolStrategyType.CURRENT_VERSION_PRIORITIZATION`, when version role and workload type changed.  
We also add consumer pool name into the `ConsumptionTask`'s id string, we are able to know the consumer thread comes from a certain pool. This will ensure `TopicPartitionIngestionContext` contains the `ConsumptionTask`'s id string for certain topic partition belonging to a specific version topic. To assert the pool changed or not, we rely on previous debugging method by querying `TopicPartitionIngestionContext` from server host. 
> [server][test] Add integration test for thread pool jumping by enabling/disabling AA or WC.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/httpclient5/HttpClient5Utils.java
During the fast-client experiment, I noticed that
the fast-client will take a quite long time to stablize the latency for medim/large response.
This behavior is reproducible, but the stablization periods vary. After several rounds of experiments, I realized that this can be related to the small Http2 InitialWindow/Frame settings being used by Fast-Client. Even Venice Server is using a large config value, but the handshake will choose the small ones sent by Fast-Client, H2 can automatically adjust the setting, but it will take time and the duration is non-deterministic. So this PR will use a same set of values as Venice Server to avoid this slow start issue.
CI and manual test.
> [fast-client][router] Fixed one slow start issue

- clients/venice-push-job/build.gradle
- internal/venice-common/build.gradle
Also reverted a7318c1d918af1d0c53214173200f9e1c254cd9c:
[controller][router][server][da-vinci] Pull jacksonCore into venice-common (#1124)
> [vpj] Exclude jackson dependency from HDFS dependency

- internal/venice-test-common/src/jmh/java/com/linkedin/venice/benchmark/TokenBucketBenchmark.java
We suspected that TokenBucket may be slow, though this microbenchmark indicates that it can run at ~microsecond latency even under high concurrency, and at sub-microsec under light load. So this is not the bottleneck we were looking for, but we'll keep the microbench checked in just in case we need it again in the future.
PR itself is just one more test.
> [test] Microbenchmark for TokenBucket

- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/server/P2PFileTransferServerHandler.java
- internal/venice-common/src/main/java/com/linkedin/venice/request/RequestHelper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/storagenode/StorageNodeReadTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/RouterRequestHttpHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/AdminRequest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/ComputeRouterRequestWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/CurrentVersionRequest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/DictionaryFetchRequest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/GetRouterRequest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/MetadataFetchRequest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/MultiGetRouterRequestWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/request/TopicPartitionIngestionContextRequest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/RouterRequestHttpHandlerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/request/MetadataFetchRequestTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/request/RequestHelperTest.java
During read request processing server calls String::split and creates URI object multiple times in the hot path. This PR tries to reuse those objects as much as possible. 
CI
> [server] Reuse resource names and URI object during server read request processing.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/StoreBufferServiceStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SeparatedStoreBufferServiceTest.java
Both sorted and unsorted drainer services are using the same metrics name, and sorted drainer service registers metric first; as a result, unsorted drainer service fails to register because it believes the metrics already exist - inside AbstractVeniceStats#registerSensor, it calls HashMap#computeIfAbsent, so whoever comes later with the same name would fail to register.
This PR fixes the bug by using different metric name prefix: StoreBufferServiceSorted
StoreBufferServiceUnsorted
Added unit test to ensure two sets of metrics are registered.
> [server][da-vinci] Bug fix: unsorted drainer service metrics failed to register

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggKafkaConsumerServiceStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/KafkaConsumerServiceStats.java
This PR adds 2 metrics:
1) `total_kafka_consumer_service_for_<pub sub region alias>--subscribed_partitions_num`: consumer pool level metric total subscribed topic partitions of all consumers, this could be used to verify specific pool subscription change when a new version push is happened.
2) `<store name>--resubscription_failure`: store level metric to alert on exception throwing during resubscription when ingestion role changed.
> [server] Add metric to verifying current version prioritization strategy.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceHostHealth.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceHostHealth.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ListenerService.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/OutboundHttpWrapperHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerStatsContext.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StatsHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ListenerServiceTest.java
This PR added a few changes:
1. A new server config to tune the write buffer high watermark and a higher write buffer high watermark will allow writing more data at one time as H2 typically works with a smaller number of connections, and this change will affect HTTP/1.1 connections as well.
2. Flush latency/response size metrics in Server.
3. Fixed an issue in Router unhealthy host tracking during node swap. Essentially, if the node is not alive, Router will remove it from the unhealthy host tracking.
New server config:
server.channel.option.write.buffer.watermark.high.bytes: default 64KB (Netty default)
CI
> [server][router] flush latency/response size metrics in Server and HB metric bug fix in Router

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
There is a resource leak in `DaVinciClientTest::testBlobP2PTransferAmongDVC` which causes subsequent tests to fail. This is occasionally masked by the `test-retry` plugin, though the retry itself is flaky and so it sometimes fails to retry at all. In any case, it is better to not fail in the first place...
Also did some minor tweaks to the main code to make debugging issues easier in the future. This includes extra logging in `DaVinciBackend` and a slightly more precise exception message in `AvroGenericDaVinciClient`.
Existing tests are deflaked.
> [dvc] Fixed DVC integration test resource leak

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DualReadAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/GetRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/InternalAvroStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/MultiKeyRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
1. Fast client multiget created 2 new contexts for the original and the retry request on top of the context passed to it which was used while recording metrics. Fix is to create a new context only for the retry and use the context passed for the original request.
2. Added additional check on the retry request context for partial response failure.
3. removed unused `isTriggeredByBatchGet` for single get
Resolves #XXX
GH CI
> [fc] Fix fast client multiget metrics to use the right context

- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreBackupVersionCleanupService.java
If there are old lingering version and there are newer repush version in regular cadence, today Venice will not delete the old version as the `getLatestVersionPromoteToCurrentTimestamp` updated and never fall off retention period. This PR fixed that by checking version creation time and delete if its older than retention period.
>  [controller] Remove older backup versions after retention period

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroBlackHoleResponseStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/StatTrackingStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/streaming/StreamingResponseTracker.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/streaming/StreamingResponseTrackerTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/read/RequestHeadersProvider.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/read/RequestHeadersProviderTest.java
1. Fast-client and thin-client use similar headers when making requests to the router/servers. Abstracted the common logic to a static utility class `RequestHeadersProvider` to ensure optimizations like providing key count in request header for early quota rejection is also available for fast-client (this PR does not include the server change that performs the early quota rejection).
2. Although fast-client's `FastClientStats` extends `com.linkedin.venice.client.stats.ClientStats`, we currently have two similar yet different approaches when it comes to metrics emission. Thin-client emits metrics using `TrackingStreamingCallback` which wraps the user callback, specifically the `StatTrackingStreamingCallback` implementation in `StatTrackingStoreClient` together with implementations of …
> [fast-client][thin-client] Common headers and metrics logic between thin-client and fast-client

- clients/venice-samza/src/main/java/com/linkedin/venice/pushmonitor/RouterBasedHybridStoreQuotaMonitor.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
Main fix is that there exists a condition in the router where during a store move, the store will have information in the routers internal store config repository, but it won't have it in the store repository after the store was deleted at the end of the store move.  This would then trigger an exception and 500 error, and would prevent producers from reinitializing their clients. This fix addresses that.
Added tests in the store migration test suite to include a running producer.  Also added some protection in the code against empty responses (which was encountered while running the debugger).
Resolves #XXX
> [router][samza] Harden up quota monitor requests

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStat.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStatReporter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatVersionedStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
Additionally mutes the metric of whichever one isn't getting updated
Resolves #XXX
> [server][metrics] Add new metric which distinguishes a serving partition from a catching up one

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestClusterLevelConfigForActiveActiveReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestClusterLevelConfigForNativeReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
If a batch store is converted to hybrid while a push is already running, it might convert the store to hybrid when its running the push in the target colo. After the target colo push finishes, the state of the store is mismatched in target vs child colo. Then during the push to other colo which does not support hybrid store ingestion and might not have the RT topic created which would make the pushjob hang forever.  This PR blocks conversion to hybrid store during actively running pushes.
CI
> [controller] Fail hybrid store conversion if a pushjob is running

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
This change is to fix unnecessary and wrong logging we find after change: https://github.com/linkedin/venice/pull/1096. 
Previously, `KafkaConsumerServiceDelegator` will check if there is a consumer found for these 3 calls:
1.`public long getOffsetLagBasedOnMetrics(PubSubTopic versionTopic, PubSubTopicPartition pubSubTopicPartition)`
2.`public long getLatestOffsetBasedOnMetrics(PubSubTopic versionTopic, PubSubTopicPartition pubSubTopicPartition)`
3.`SharedKafkaConsumer getConsumerAssignedToVersionTopicPartition(PubSubTopic versionTopic, PubSubTopicPartition topicPartition)`
And the caller did not expect to return non-null value, instead it has handling logic for no consumer found for `PubSubTopic versionTopic, PubSubTopicPartition pubSubTopicPartition`. 
After change: …
> [server] Handle unnecessary logging for non-existent consumer checking inside KafkaConsumerService.

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/VeniceRmdTTLFilter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestVeniceKafkaInputMapper.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/ttl/TestVeniceChunkedPayloadTTLFilter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/ttl/TestVeniceKafkaInputTTLFilter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Current AAWC TTL repush need to deserialize value and perform a TTL based delete on the record to see if it needs to be filtered. The code does not handle the case when source version has compression enabled thus deserialization can fail. This PR fixes it by building the source version compressor and fix the deserialization issue.
Add Compression Mode for AAWC TTL integration test.
> [vpj] Support AAWC TTL repush with compression

- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerQuotaUsageStatsTest.java
If a store's partition count is small it's normal and expectd to have some hosts in the cluster to not have any replicas assigned to them. The hosts should emit NaN for the SN read quota usage metric instead of -1. Emitting -1 or 0 will mess up aggregation of metrics used for monitoring.
The NaN should be ignored by aggregators and provide clear signals in case of unexpected null rate limiter.
> [server] SN read quota usage should return NaN for stores with no replicas

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
The following sequence of events causes the Helix status to wait 24-48 hours:
1. In the main `StoreIngestionTask` thread, the calls stack is [`run()`](https://github.com/linkedin/venice/blob/c8b95abd90a6c20601fdd79ae15552bd646e1ea8/clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java#L1369) -> [`processConsumerActions()`](https://github.com/linkedin/venice/blob/c8b95abd90a6c20601fdd79ae15552bd646e1ea8/clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java#L1391) -> [`processConsumerAction()`](https://github.com/linkedin/venice/blob/c8b95abd90a6c20601fdd79ae15552bd646e1ea8/clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java#L1644) -> …
> [server] Fail-Fast on Corrupted OffsetRecord 

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Previously, `testEnablePartialUpdateOnActiveActiveStore` was flaky due to no retry on verifying logic for consumer assignment with a fixed timeout. Besides, it has a wrong assumption:  the consumer we verify will only have one partition assignment.
> Fix flaky test of `testEnablePartialUpdateOnActiveActiveStore` due to no retry on verifying logic.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/resources/avro/PersonV3.avsc
If a field from update record is new field but it is NO_OP, we should skip this field, instead of letting it slip into checking TS from old TS record, which will result in exception and halt the ingestion
> [server] AAWC should ignore NO_OP new field from update record

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
Today, "ControllerClient#retryableRequest" retries when the controller returns an error response. It doesn't retry when an exception is thrown. We need to handle exceptions as an error condition and retry till the retryAttempt count is reached.
Also it misses to retry VeniceException from `getLeaderControllerUrl`  which could lead to data recovery pushes to fail on a single unsuccessful controller discovery call. 
GHCI
> [common] Retry controller client request on exceptions

- build.gradle
- clients/da-vinci-client/build.gradle
- clients/venice-admin-tool/build.gradle
- clients/venice-client/build.gradle
- clients/venice-pulsar/build.gradle
- internal/venice-common/build.gradle
- internal/venice-test-common/build.gradle
- services/venice-controller/build.gradle
- services/venice-router/build.gradle
- services/venice-server/build.gradle
Also upgrades zookeeper to 3.6.3. The exclusions are needed to provide JDK8 compatible APIs for various groups.
GHCI
> [all] Upgrade helix lib dependency to 1.4.1

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroSpecificDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/factory/CachingDaVinciClientFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
This PR makes the read chunk executor pluggable.
CI
> [dvc] Exposed an API to pass an executor to CachingDaVinciClientFactory

- build.gradle
- docs/dev_guide/how_to/workspace_setup.md
1. When users are on the wrong version, the error message when running gradle tasks can be cryptic. So verifying their JDK version before running other tasks will make it easier for users to debug.
2. The docs mention to download JDK 17, but it doesn't explicitly mention to add it to their JAVA_HOME.
Tested locally
Users will receive an explicit error message when using the incorrect JDK version.
> [doc][script] Automatically verify JDK version in gradle, and specify in docs users need to set their JAVA_HOME

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionNotificationDispatcher.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/PushStatusNotifier.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/VeniceNotifier.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/VersionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/VeniceOfflinePushMonitorAccessor.java
- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/OfflinePushAccessor.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatus.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-common/src/main/resources/avro/PartitionState/v13/PartitionState.avsc
- internal/venice-common/src/test/java/com/linkedin/venice/helix/OfflinePushMonitorAccessorTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/offsets/TestOffsetRecord.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/schema/TestAvroSchema.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatchReportIncrementalPush.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
This PR will try to batch the EOIP messages for historical incremental pushes and batch up them to ZK OfflinePushes Znode prior to replica ready-to-serve.
It is intended to reduce the volume of unnecessary update to ZK nodes.
Add integration tests and unit tests to cover the functionality.
> [server] Batch report EOIP for incremental push prior to replica ready-to-serve

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroComputeRequestBuilder.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/schema/RouterBackedSchemaReaderTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
If schema repo returns invalid schema id, that fails client requests. This PR adds safeguard against such invalid schemas in meta data handler and client side schema reader.
CI
> [router][venice-thin-client] Add safeguard against invalid schema ID

- build.gradle
This is to tell the user explicitly how to resolve the JDK version mismatch error. 
Tested locally
Error message will contain new instructions.
> [script] Explicitly tell the user to set their JAVA_HOME if their JDK version is invalid

- docs/dev_guide/how_to/style_guide.md
- internal/venice-client-common/src/main/java/com/linkedin/venice/compression/CompressionStrategy.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/compute/protocol/request/enums/ComputeOperationType.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/EnumUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/VeniceEnumValue.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compression/CompressionStrategyTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/compute/protocol/request/enums/ComputeOperationTypeTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/protocol/enums/ControlMessageType.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/protocol/enums/MessageType.java
- internal/venice-common/src/main/java/com/linkedin/venice/system/store/MetaStoreDataType.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/LeaderCompleteState.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/protocol/enums/ControlMessageTypeTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/protocol/enums/MessageTypeTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/system/store/MetaStoreDataTypeTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/LeaderCompleteStateTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/VeniceEnumValueTest.java
Added a valueOf function in EnumUtils to reduce code duplication and standardize the error message for badly handled enums.
Also added unit tests for the mappings of all VeniceEnumValue.
> [all] Minor code cleanup in various enums

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSupersetSchemaUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/TestAvroSupersetSchemaUtils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
- internal/venice-test-common/src/main/resources/valueSchema/NameV5.avsc
- internal/venice-test-common/src/main/resources/valueSchema/NameV6.avsc
Previous issue: During subset schema validation, we will compare field strictly including the customized props. Such props could be JSON string provided by customers, without strict string order.  And when we generate superset schema, we also did not check the props difference. 
The fix is avoiding the props checking when comparing field with the same name, between subset schema and superset schema. We will deep-copy fields from subset schema and superset schema and then do equlity check. 
ci
> [vpj] Ignore field props check during subset schema validation.

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/BatchGetRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ComputeRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/GetRequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RequestContext.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/StatsAvroGenericStoreClient.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/StoreMetadata.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/stats/ClusterRouteStats.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/stats/ClusterStats.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/stats/FastClientStats.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClientTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTestUtils.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/utils/TestClientSimulator.java
This PR is trying to reduce the total number of metrics emitted by fast-client.
Previously, Fast-Client will have the instance-level tracking for each store, which will create a lot of metrics when the application is using multiple stores, and this code change will only emit tacking metrics (qps, latency) in instance level rather than per store per instance.
This PR also removes the pending request metric, which is per store per route, and we will add back this metric in a separate PR when we improve `InstanceHealthMonitor` to be cluster-level instead of store-level.
CI
> [fast-client] Replace per-store per-route tracking by per-route tracking

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
In recent past we have seen cases where end offset fetch call stalls for a very long time. It could happen due to multiple reasons, like general Kafka outage, or mismatched VT vs RT partition count leading to non-existed partition or other network issues. 
Even though we cache the offset value, there is a blocking call before cache is updated. This hold the lock for a very long time and subsequent calls (either from metics collection) or the ready to serve call waits forever.  Since drainer thread is shared this blocks the processing of other resources in a drainer thread leading to cluster-wide impact. This PR check for cache miss and returns immediately with some sentinel value while a nonblocking call updates the cache asynchronously. 
GHCI
> [common][server][dvc-client] Make a true non-blocking end-offset fetcher

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/AbstractTestVeniceHelixAdmin.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
In order for the controller to be migrated to an ephemeral system like Kubernetes and provide isolation for cluster assignment, the controller needs to be able to dynamically set its instance tag.
This instance tag can be specified in the config by setting `controller.instance.tag.list`
Added new tests.
> [controller] Add support for controller instance tagging

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkHelixAdminClient.java
Make setting instance group tags for controller cluster resources configurable. This is needed to provide cluster resource level isolation.
Added new tests
> [controller] Make setting instance group tags for controller cluster resources configurable

- build.gradle
- clients/venice-push-job/build.gradle
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/spark/datawriter/jobs/DataWriterSparkJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/spark/utils/RowToAvroConverter.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/vpj/VenicePushJobConstants.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/spark/utils/RowToAvroConverterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestVsonStoreBatch.java
Currently, we implement a custom input data source to read Avro and VSON files from HDFS. This input data source isn't optimized for large files (i.e. files larger than HDFS block size) and is not aware of blocks and location of those on HDFS. This PR modifies the input logic to use Spark's native Avro and SequenceFile input formats that should be much more optimal for files larger than the block size on HDFS.
Additionally, internally at LinkedIn, we have another input format that reads from a Spark table. This commit adds a lot of the base code that can be used to add arbitrary Spark dataframes as supported input formats. The remaining gap is the schema validation done before the DataWriterComputeJob.
Note: This re-applies #1036, which was reverted in #1127
Unit tests. GHCI regression …
> [vpj] Use native Spark readers for reading from Avro and VSON files

- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
Based on testing using FULL_AUTO, Waged performed better than Crush and CrushEd. So we will be setting this as the default rebalancing strategy.
CI
> [controller] Set rebalancing strategy to Waged instead of Crush when adding a resource to controller cluster

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSchemaUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSupersetSchemaUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/TestAvroSupersetSchemaUtils.java
- internal/venice-client-common/src/test/resources/UnionV1.avsc
- internal/venice-client-common/src/test/resources/UnionV2.avsc
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestEmptyPush.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
- internal/venice-test-common/src/main/resources/valueSchema/UnionV1.avsc
- internal/venice-test-common/src/main/resources/valueSchema/UnionV2.avsc
- internal/venice-test-common/src/main/resources/valueSchema/UnionV3.avsc
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/supersetschema/DefaultSupersetSchemaGenerator.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/supersetschema/SupersetSchemaGeneratorWithCustomProp.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/util/ParentControllerConfigUpdateUtils.java
When user updates a field default value, we should reflect it in the changes in superset schema, which is used in read-compute / partial update store. This should apply to all the value type, including union schema. 
Add a new integration test to validate
> [controller] Superset schema generation should reflect default value updates in new value schema

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/VeniceProperties.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
Currently, if you provide an empty string for `controller.instance.tag.list`, it will result in an array that has an empty string as an element. This isn't desirable, because the code would then assign an empty string to an instance's tag list in the controller.
This change will make sure that if there is an empty string, it will result in an empty array.
Added a new test case
> [controller] Ensure empty string from config doesn't result in an array of an empty string for instance tag list

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
Recently we introduced re-subscription feature for different store versions. Leader and follower partitions from different version topics will experience re-subscription triggered by store version role change concurrently.  
Problem: 
Two `StoreIngestionTask` threads for different store versions (store version 1 and store version 2) try to do re-subscription (unsub and sub) for the same real-time topic partition concurrently. During re-subscription triggered by one store version, operation of `consumer.unSubscribe` to remove assignment of the topic partition and operation of `consumerToConsumptionTask.get(consumer).removeDataReceiver(pubSubTopicPartition)` are sequentially executed. It is possible that `StoreIngestionTask` thread for store version 2 got the same `ConsumptionTask`, but …
> [server] Race condition fix for re-subscription of real-time topic partitions.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainTopicIngestionStatus.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/StoreBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/VersionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/DefaultIngestionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/main/MainTopicIngestionStatusTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReader.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReaderTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushstatushelper/PushStatusStoreWriterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushMonitorUtilsTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushStatusCollectorTest.java
In Prod, we are seeing the bootstrapping nodes are blocking the new push, and this PR will let Controller ignore the status report from the nodes, which are still bootstrapping.
This feature is especially important for DaVinci apps, which are using multiple large stores and bootstrapping from an empty state can take a long time and it can delay the new push significantly.
> [da-vinci][controller] Filter out status reporting from the nodes, where the DaVinci app is still bootstrapping

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumptionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
This reverts commit 06cc1fc5a7648fbbb92e730742b7a7dd6ad61138.
This is used to unblock other PRs as the test case in the reverted PR is flaky and can lead unit test timeout.
CI
> Revert "[server] Race condition fix for re-subscription of real-time topic partitions. (#1192)"

- build.gradle
Bumped up the tehuti dep to the latest 0.12.3 which has the [fix](https://github.com/tehuti-io/tehuti/pull/34) to a deadlock issue involving lock in `MetricRepository` and `Sensor`.
GH CI
> [all] Bumped up the tehuti dep to the latest 0.12.3

- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubTopicPartitionInfoTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
The comparator used in TopicCleanupService to assign higher priority to RT topics over non RT topics `(s1, s2) -> s1.isRealTime() ? -1 : 0` is incorrect. It does not assign two RT topics (or two non RT topics) as equal priority, which violates the fundamental contract of sorting algorithms.
In some cases, this results in RT topic being assigned lower priority than a non RT topic. This PR fixes the comparator and uses both the topics in determining the relative priority.
Resolves #XXX
added a unit test in PubSubTopicPartitionInfoTest, which fails without the fix.
> [controller] fix topic priority determination in TopicCleanupService

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
Add more info in logger with exception log.
CI
> [vpj][common][dvc] Minor logging change

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- Enable incremental push status reads from PS3 based on cluster
configuration.  
- Query the push status store only if it’s enabled for the specific user store;
otherwise, fallback to Zookeeper for status reads.  
- Ensure removal of removeFromSupposedlyOngoingIncrementalPushVersions status from
PS3 when PS3 is enabled, regardless of read configuration.
> [controller] Make PS3 for incremental push status reads config cluster-specific; query PS3 only if it is enabled for user store

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/PushStatusNotifier.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/notifier/TestPushStatusNotifier.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/notifier/LeaderErrorNotifier.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
Currently, incremental push status updates are written to both Zookeeper and
PS3. As part of a phased approach to eventually discontinue Zookeeper updates,
this PR introduces a configuration option allowing selective control over where
these updates are written, enabling flexibility to disable updates to either
Zookeeper, PS3, or both.
E2ETest and UTs
> [server] Add option to disable incremental push status update writes to Zookeeper or PS3 (push status system store)

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/utils/AbstractClientEndToEndSetup.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
When materializing the meta store, we produce a snapshot of
readyToServeInstances for all user store versions. If a version is in an ERROR
state, its Helix resources may not exist. Attempting to check these resources
can throw exceptions, potentially causing the addVersion process to fail. 
The info about RTS instances in meta store was required in the past but it is no  
longer used by any clients so it's safe to stop writing this into meta system store.
> [controller] Stop writing writing ready-to-serve instances info in meta system store

- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkHelixAdminClient.java
Fix bug where setting the cloud config was only done on the controller cluster, not on storage clusters. This was done by adding `clusterName` to the method signature of `setCloudConfig`.
CI
> [controller] Fix bug where setting the cloud config was only done on the controller cluster, not on storage clusters

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/ThinClientMetaStoreBasedRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
In recent past we have seen cases where end offset fetch call stalls for a very long time. It could happen due to multiple reasons, like general Kafka outage, or mismatched VT vs RT partition count leading to non-existed partition or other network issues.
Even though we cache the offset value, there is a blocking call before cache is updated. This hold the lock for a very long time and subsequent calls (either from metics collection) or the ready to serve call waits forever. Since drainer thread is shared this blocks the processing of other resources in a drainer thread leading to cluster-wide impact. This PR check for cache miss and returns immediately with some sentinel value while a nonblocking call updates the cache asynchronously.
GHCI
> [server][da-vinci-client] Retry non-blocking metadata fetch

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
Trying to deflake `testDaVinciMemoryLimitShouldFailLargeDataPush`
> [test] Make sure meta store ready before DVC memory limiter test

- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/OfflinePushStatus.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitor.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/AbstractPushMonitorTest.java
The issue:
We observed such race condition in controller deployment/restart. When it restarts, it will call loadAllPushes() which load all OfflinePushStatus snapshot for all topics from ZK, it will then iterate the list and try to subscribe to the changes. If there is any change in between, it will be missed and push job can hang forever.
This PR adds a refresh offline pushes call after listener subscription. It is using the same store level lock, so it should not cause any race condition or deadlock with change listener callback.
Add an unit test
> [controller] Refresh OfflinePushStatus after change listener subscription during loadAllPushes() call

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/HelixParticipationServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
For a participant to auto-register with Helix without causing a rebalance every time a new participant joins the cluster (i.e. during deployment), we need to set the instance operation to UNKNOWN. Then these participants would be ENABLED in a batch, so it only rebalances once.
Added unit and integration tests.
> [server] Add ability to configure Helix InstanceOperation to UNKNOWN

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/ThinClientMetaStoreBasedRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/VeniceMetadataRepositoryBuilder.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/NativeMetadataRepositoryStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/repository/NativeMetadataRepositoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/NativeMetadataRepositoryStatsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/MetaSystemStoreTest.java
1. The existing TC internal retry implemented in RetriableStoreClient is vulnerable to a dead lock issue due to deserialization thread performing and waiting on the retry. Once the thread pool is exhausted all deserialization threads will be waiting forever because there won't be any threads left to handle the transport response. We will fix this internal retry in another commit.
2. Disable the TC internal retry in ThinClientMetaStoreBasedRepository because we recently added external retry with RetryUtils.executeWithMaxAttempt and timeout. Remove hardcoded retry configs from NativeMetadataRepository since it's no longer needed and it was leaking implementation details.
3. Added staleness metric in NativeMetadataRepository that should help us detect any issue causing the local metadata to …
> [changelog][dvc] Disable TC internal retry in ThinClientMetaStoreBasedRepository

- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatus.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/ReplicaStatus.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/ReplicaStatusTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestIncrementalPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
Offline push job polling checks replica's current status to determine if replicas are ready, if status is not terminal, it will also check if it is ready to start buffer rewind.
Incremental push will also update the replica's current status, so it is possible that it will flip the current status from terminal (COMPLETED) -> non terminal (SOIP)
If there are concurrent / consecutive incremental push, it could potentially result in offline push job polling could not complete forever (especially when there are other factors - slow nodes and such). 
This PR changes the behavior so that SOIP/EOIP won't affect replica current status polling.
Also, it should stop logging tons of "not ready to start buffer replay" due to certain partition status flipped to non-terminal status and which is not EOIP …
> [server] Incremental push status should not update replica current status

- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
Currently, the min replication factor (RF) for controllers is equal to replication factor. During a deployment, the number of instances could go below what is set to RF, which would cause a rebalance failure when using Waged.
To prevent this, we will be setting min RF = max(RF - 1, 1). This will be applied to the storage clusters too.
CI
> [controller] Set min RF on controllers and storage clusters to RF - 1 with a floor of 1

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestEmptyPush.java
##[server] Adjust retry limit in metadata fetch
Increase retry limit in for non-blocking metadata fetch method inside `getTopicPartitionEndOffSet` from 5 retries to 10 as too few retries made some tests fails.
> [server] Increase retry limit in metadata fetch

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferPayload.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferUtil.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/P2PFileTransferClientHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/BlobTransferNettyChannelInitializer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PBlobTransferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PFileTransferServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManagerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestNettyP2PBlobTransferManager.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestP2PFileTransferServerHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/BlobP2PTransferAmongServersTest.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
Blob transfer currently does not support hybrid stores because snapshot generation occurs only after Kafka ingestion is complete in batch store, which can result in outdated snapshots for hybrid stores.
To resolve this issue, this PR will:
1. Regenerate a new snapshot if snapshot is staled when a client sends a GET request.
2. Ensure that the transferred offset record accurately reflects the one immediately preceding the snapshot's recreation. If the snapshot manager generates the snapshot first and uses the current offset record for the client, the most recent/largest offset record may be excluded from the snapshot.
3. Throttle concurrent users. The blob snapshot manager will maintain a concurrentSnapshotUsers map to limit the number of hosts that can initiate a snapshot simultaneously …
> [server][dvc] support hybrid store in blob transfer with recreating snapshots

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/BlobP2PTransferAmongServersTest.java
Fix the flaky integration test in blob transfer. The offset records of server1 and server2 could differ because the ingestion speed may vary.
Integration test.
> [server] fix flaky test in blob transfer integration test

- internal/venice-client-common/src/main/java/com/linkedin/venice/D2/D2ClientUtils.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/exceptions/VeniceException.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/D2/D2ClientUtilsTest.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestBlobDiscovery.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterExceptionAndTrackingUtils.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VenicePathParser.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceComputePath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceMultiGetPath.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/path/VeniceMultiKeyPath.java
- In VeniceMultiKeyPath::initialize, we check the key count sooner, which is possible thanks to an earlier refactoring to the Avro deserialization code which now returns a List rather than an Iterable.
- In VenicePathParser::parseResourceUri, when the batch get key count is exceeded, we mark it as a 413, and then treat it as an "expected exception" in RouterExceptionAndTrackingUtils, which suppresses the stacktrace from the logs.
- In RouterExceptionAndTrackingUtils, we further improve the handling of "expected exceptions" so that not only we avoid logging the stacktrace, but we also skip filling it in in the first place. Previously, the stacktrace would be filled in and then suppressed, and filling in stacktraces can be expensive. This change should help not only batch get key count …
> [router] More efficient handling of batch get key count limit breach

- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceResponseAggregator.java
The router expects to get the same compression scheme from all server responses when performing a batch get, but it seems that this is not always the case. This change will log the response headers in case this happens, in the hope that it gives more clues about what went wrong.
GHCI.
> [router] Added more debugging details to compression inconsistency issue

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-CompatibilityTests.yml
- .github/workflows/VeniceCI-E2ETests.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
- .github/workflows/build-and-publish-docker-images.yml
- .github/workflows/build-and-upload-archives-on-demand.yml
- .github/workflows/build-and-upload-archives-upon-pushing-tags.yml
- .github/workflows/build-and-upload-archives.yml
- .github/workflows/publish-javadoc.yml
- docker/build-venice-docker-images.sh
- docker/venice-client/Dockerfile
- docker/venice-controller/Dockerfile
- docker/venice-router/Dockerfile
- docker/venice-server/Dockerfile
- Add a GitHub Action for manual triggering to build Docker images from
specified Git tags.
- The workflow checks out the repository, validates the tag, builds images
using a specified script, and pushes them to the GitHub Container Registry.
Verification steps confirm successful image creation and include metadata
annotations.
- Upgrade GitHub Actions dependencies:
- actions/upload-artifact from v3 to v4.  - actions/setup-java from v3 to v4.
- Replaced gradle/gradle-build-action@v2 with gradle/actions/setup-gradle@v3.
- Upgraded gradle/wrapper-validation-action@v1 to
gradle/actions/wrapper-validation@v3.
- Upload unit test artifacts for each JDK in a separate file.
GitHub actions with manual trigger
Sample run and output: https://github.com/sushantmane/venice/actions/runs/11531628776
> [docker] Add GitHub Action for building and publishing Docker images to GHCR

- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
Helix's doesn't have an API for setting `InstanceTags` for instances atomically. They can only be added and removed one-by-one. Also, each tag modification could lead to rebalances of resources.
There are a couple of other issues with our current implementation:
1. Currently, we only add instance tags, but didn't purge ones that are no longer valid
2. We register a participant in Helix first, and then add the tags one by one. This will lead to multiple rounds of rebalances
This PR sets the tags in the instance config at the time new instances are being registered. We can edit the tags for existing instances operationally as a one-time effort.
GH CI
> [controller] Set Helix instance tags automatically only when registering new participants

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionBatchProcessor.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PubSubMessageProcessedResultWrapper.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/utils/ByteArrayKey.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/IngestionBatchProcessorTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/SparseConcurrentList.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/SparseConcurrentListTest.java
This PR fixed the following issues:
1. AASIT should pass non-null `KeyLevelLocksManager` to `IngestionBatchProcessor`, otherwise, race condition will happen.
2. Fixed the locking order in `IngestionBatchProcessor` to avoid deadlock.
3. Updated `SparseConcurrentList#computeIfAbsent` to skip adjust list size if the computed result is `null`.
CI
> [server][common] Fixed bug in AA/WC parallel processing support

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionWiseKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreAwarePartitionWiseKafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceWithStoreAwarePartitionWiseTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumerTest.java
Add a new version of partition wise shared consumer assignment strategy.
We have been seeing subscriptions to the same topic / store be assigned to the same consumer, and for a particular store push's view (can be inc push / full push) it can be competing with each other and becomes the long-tail partition and slow down the overall progress. 
Assuming the store/topic itself does not have data-skew, then we should try to assign these subscriptions to different consumers as even as possible. Especially for RT topics, backup / current / future version will share the same input volume, so we should not treat them differently within the same pool, but we can further optimize that in different level (Pool assignment strategy) 
This PR adds the new strategy so when a new topic partition is …
> [server] Add store-aware partition-wise shared consumer assignment strategy

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
The classHash gets generated when DVRT is being used. This PR will automatically clean it up, so it doesn't get included when someone does `git add .`
CI
> [dvc] Automatically delete DVRT's classHash in DaVinciClientTest

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/AggregatedHealthStatusRequest.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/TestAggregatedHealthStatusRequest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
In Helix's aggregated stoppable check, the `to_be_stopped_instances` is optional and will be omitted in case there are no instances that have previously been approved. This commit makes our controller handle this.
Added unit test and integration tests. GHCI
> [controller] Make to_be_stopped_instances in aggregatedHealthStatus API optional

- services/venice-server/src/main/java/com/linkedin/venice/listener/OutboundHttpWrapperHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/OutboundHttpWrapperHandlerTest.java
In servers, when handling stats, we refer to a cached value of status code. However, in case of early exiting responses like `FORBIDDEN`, `UNAUTHORIZED`, etc. we missed updating the cached value, and that triggered incorrect code execution leading to excessive logging.
> [server] Fix stats handling handling for early exiting requests in servers

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/AbstractVenicePartitionStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
If not, system store can be come standby/leader prematurely for current version and serve stale data.
Add unit test
> [server] System store current version should also place latch when becoming from offline to standby

- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/TestHelixUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceControllerClusterConfig.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkHelixAdminClient.java
Currently, HelixAdminClient APIs accept a String-to-String map to set on the cluster configs. Changed to use strongly typed Helix `ClusterConfig` object instead.
Also, moved the `CloudConfig` creation at time of parsing configs, and reusing the created object instead of creating it at time of cluster creation.
Added unit tests. GH CI for regression testing
> [controller] Refactor HelixAdminClient APIs to accept strongly typed Helix objects

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/AggregatedHealthStatusRequest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceControllerClusterConfig.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkHelixAdminClient.java
Helix has added a new functionality that allows configuring a customized health check endpoint that Helix will invoke to decide on the health of the cluster. This URL can be configured by setting the controller config `controller.helix.rest.customized.health.url`.
Added unit tests. GH CI for regression testing
> [controller] Enable configuring a customized health check URL for storage clusters

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
> [da-vinci] Do not throw exception when trying to close a closed/not-ready DVC client

- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/AggServerQuotaUsageStats.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerReadQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerReadQuotaUsageStatsTest.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/ServerReadQuotaUsageStatsTest.java
1. Prevent NPE in ServerReadQuotaUsageStats's async gauges when a store has no version or traffic.
2. Set backup version using version list in handle store change since the old behavior will not set the correct backup version after server restart.
New unit test
> [server] Fix NPE for ServerReadQuotaUsageStats when store has no version or traffic

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/RouterExceptionAndTrackingUtils.java
Fix large batch get error getting classified as unhealthy request.
GHCI
> [router] Do not classify REQUEST_ENTITY_TOO_LARGE as unhealthy

- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
We do not need to detailed percentile metrics of the negative events in route.
GHCI
> [router] Replace unhealthy/tardy requests metrics from percentile to regular bucket

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreAwarePartitionWiseKafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
Current implementation does not cover the race condition case between pick consumer API call and actual consumer subscribe call. So the assignment size can be inaccurate during calculation. To address this issue, this PR adds maps to keep track of the basic load and store level load for each consumer, and update it during pickConsumerForPartition() API
Adjust unit test to more coverage.
> [server] Avoid race condition between pick consumer call and actual consumer subscribe API

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerReadQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
The currentVersion and backupVersion of ServerReadQuotaUsageStats are not set after server restart because handleStoreChanged is invoked for all stores when the store repo undergoing refresh before we initialize and register store change listener in ReadQuotaEnforcementHandler (part of the ListenerService). As a result metrics that depend on current and backup versions will not show up properly until store is updated.
The fix is to during initialization of ReadQuotaEnforcementHandler we will invoke handleStoreChanged for all stores after we register store change listener.
The bug is actually reproducible in existing integration test. However, it was not caught because the test was broken/misconfigured...
> [server] SN read quota versioned stats not initialized after restart

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatTimeStampEntry.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatVersionedStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
This tweaks the behavior of the follower metric to retain the highest value of the last received timestamp.  Prior to this, it was strictly reporting the last received timestamp.  The result of this was that when one data center was lagged, the follower metric would sawtooth between healthy and unhealthy signals.  This tweak makes it so the most recent timestamp will be retained and reported for the metric for all received data.
> [server][metrics] Fix sawtooth behavior on follower lag monitoring

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
This PR addresses a race condition caused by the `wait()` and `notifyAll()` mechanism between the `StoreIngestionTask` thread's call to `SharedKafkaConsumer#unSubscribeAction` and the `ConsumptionTask` thread's call to `SharedKafkaConsumer`#poll. This mechanism ensures that the next poll only occurs after the unsubscription has completed. The wait() inside `SharedKafkaConsumer#unSubscribeAction` releases the object-level lock on the `SharedKafkaConsumer`.
However, the changes introduced in [PR #1263](https://github.com/linkedin/venice/pull/1263) added a consumer intrinsic lock in `KafkaConsumerService` to protect unsubscription operations (inside `unSubscribe`, `unSubscribeAll`, and `batchUnsubscribe`) and data receiver settings (inside `assignConsumerFor`). These changes required the …
> [server] Fix resubscription race condition caused by consumer object level lock.

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/StoppableNodeStatusResponse.java
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/TestStoppableNodeStatusResponse.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/ControllerRoutesTest.java
Currently, controller logs audit logs for API requests and responses. These audit logs however, do not log the request body.
In the aggregated stoppable checks API endpoint, the request and response are JSON objects. This PR logs these objects to get visibility into these.
> [controller] Log request and response body for aggregated stoppable check

- clients/da-vinci-client/build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/compression/StorageEngineBackedCompressorFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/chunking/ChunkingTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
Previously, Venice Server is always using the max compression level(22) to compress the payload, which is very slow and this PR will change the compression level to the default level (3) by default, and the compression speedup is roughly 10-20x and it might introduce some more storage overhead, 5-10%, but it should be fine.
This PR doesn't change the compression level in batch push as it is offline, and if we see a need to speed up the map-reduce phase, we can do the same later.
New Server Config:
server.zstd.dict.compression.level: default 3
New metric:
leader_compress_latency
CI
> [server] Tuned zstd compression level in ingestion

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
Make `StoreIngestionTask::testStartServerAndShutdownWithPartitionAssignmentVerification` less flaky by checking that the number of partitions is 0 instead of storageEngines is 0. This is because after the node comes online, Helix tries to re-assign partitions to it immediately, which re-creates the storageEngine.
Also made `StoreIngestionTask::testCheckBeforeJoinCluster` less flaky by turning on maintenance mode on the Helix cluster after removing the node from the cluster.
CI
> [test] Make StoreIngestionTask::testStartServerAndShutdownWithPartitionAssignmentVerification & testCheckBeforeJoinCluster less flaky

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Provide extra data points to determine if a push job is killed by timeout setting prematurely.
Github CI
> [controller] Add push job duration in the push job details log

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
In a helix ideal state, helix maintains information in listfields and mapfields.  The mapfields inform which messages needs to be sent based on the current LIVEINSTANCES, and will therefore be reflective of what nodes are available to receive messages.  The listfields however will contain the assignment, and will only change if a rebalance is calculated.  For this clean up code, we rely on entries in the listfield based on which state transitions we're anticipating to receive.
Resolves #XXX
> [server] swap map for list fields when examining idealstate for disk cleanup

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestInstanceRemovable.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helixrebalance/TestRebalanceByDefaultStrategy.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/InstanceStatusDecider.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/NodesAndReplicas.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestInstanceStatusDecider.java
Currently, there is a bug where even if an instance is non-removable, if it doesn't share any partition with some locked instance, it returns a removable result for the instance.
This commit also depracates the cluster view in the `node_removable` check and removes the `instance_view` API param.
Added extra checks in unit tests
- Before this change, invoking `/node_removable` endpoint on controllers would check if the cluster view is healthy after removal of the specified instance. However, this is not desirable because it would block the removal of the instance even if it doesn't cause any change to the cluster's healthiness. This mode has been deprecated in favor of the `instance_view` mode that was previously available by specifying an API param. Specifying the API param is now a …
> [controller] Fix node removable check with locked instances

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixAdminClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkHelixAdminClient.java
Make `testDropStorePartitionAsynchronously` less flaky by disabling the instance instead of relying on Helix to rebalance after adding new participants.
CI
> [test] Make testDropStorePartitionAsynchronously less flaky

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
1. Made configurable the 30 minute maximum wait (introduced in #1213) for the next consumer poll, after unsubscribing from a topic, during a state transition.
2. Improved the log message when reaching the default 10 second maximum wait or if it waits longer than 15 seconds during a state transition.
GHCI. No change in functionality.
> [server] [config] Configurable Increased Max Wait After Unsubscribe

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/TestHelixUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHAASController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
Helix allows configuring `CloudConfigs` that can be used to populate instance `DOMAIN` fields on participant startup. In these configs, we can specify a class name and a package name. If a package name is not specified, Helix uses a default value of `org.apache.helix.cloud.<CLOUD_PROVIDER>`. This might not be desirable for all usecases, so, this commit allows overriding the package name.
Modified UTs
> [controller] Allow configuring cloud information processor package in Helix CloudConfig

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
Ensure the PubSub URL is present in the PubSub cluster map before  
subscribing to a topic. This prevents issues caused by attempting to  
subscribe to unknown PubSub URLs during message consumption.  
Example case:
If the cluster map contains entries like `[a: 0, b: 1]` and the TopicSwitch (TS) message references address c, the subscription check ensures c is present in the cluster map. If `c` is not found, the subscription fails, and ingestion errors out. This prevents consuming any records from address `c`, and hence no records with a` -1` upstream offset are produced to VT.
CI, UT, and local runs
> [server] Validate PubSub address against cluster map in AASIT::consumerSubscribe

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
Add support to dump details of TopicSwitch messages via the admin tool.  
This will help in debugging and root cause analysis of ingestion issues.
UT and local experiments
> [admin-tool] Add support for dumping topic switch message details

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
A NPE can happen when:
1. A store received standby to leader transition, but yet finished, thus VeniceWriterLazyRef remains null.
2. Later, it receives LEADER to STANDBY transition and today's code can hit this NPE.
This fix add a NPE check and also mark VeniceWriterLazyRef to volatile for visibility across threads.
- Passed newly added unit test
- Passed CI
> [davinci] Fix a NullPointerException when SIT processes a consumer action

- .github/workflows/UnitTests-core.yml
Resolves   FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
GHCI
> Increase heap size to 8G for CI reporting

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/MetricEntityState.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
If an invalid `TehutiMetricNameEnum` that was not registered with `MetricEntityState` is passed in, it will be skipped during record() and will be silently ignored. Found this issue for `healthy_request_latency` and this PR fixes this issue and adds logging with redundant logging filter to log such issues. Not throwing an exception as we will be moving a lot of the existing metrics to Otel and tracking this log will help find and fix the issue during the migration and not affect the rollout process.
unit test
> [router] Fix invalid tehuti sensor name passed in for latencies

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/RocksDBMemoryStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
This PR adds options to enable BlobDB feature in RocksDB to reduce write amplification for large value stores.
Currently, these options are only valid for block-based format.
New configs:
rocksdb.blob.files.enabled : default false
rocksdb.min.blob.size.in.bytes : default 4KB
rocksdb.blob.file.size.in.bytes : default 256MB
rocksdb.blob.garbage.collection.age.cutoff : default 0.25
rocksdb.blob.garbage.collection.force.threshold : default 0.8
rocksdb.blob.file.starting.level: default 0
This feature is not perfect, as the main goal is to reduce the write amplification, but space amplification will increase and we can tune the above params to find the right balance.
CI
> [da-vinci][server] Added flag to enable RocksDB blob file for blocked based format

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
This PR fixes an issue where hybrid store migration fails if a batch push job is ongoing
and a non-truncated version topic exists in the parent region.
The problem stemmed from a safeguard intended to prevent hybrid-to-batch conversion during
ongoing push jobs (added to address targeted region push issues). The safeguard failed to
account for store migration scenarios where hybrid configurations are added during the
updateStore operation.
This misclassification of the migration attempt as a batch-to-hybrid store conversion
caused unintended operations, including a call to VPHA::getTopicForCurrentPushJob. This
method attempts to issue a killOfflinePushJob when the version config is missing in the
store’s configuration. The kill job, in turn, tries to update the version status to
KILLED, …
> [controller] Fix hybrid store migration failure during ongoing batch push jobs

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParamsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/AdminToolE2ETest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
In certain scenarios, toggling the Store::isMigrating flag is necessary to safely clean up
lingering states in destination cluster during abort migration. However, the admin tool
currently lacks the capability to update this configuration.
This PR introduces support for enabling or disabling the Store::isMigrating config through
the admin tool.
E2E test
> [admin-tool] Add support for toggling Store::isMigrating config via Admin-Tool

- internal/venice-common/src/main/java/com/linkedin/venice/utils/DictionaryUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/DictionaryUtilsTest.java
This change ensures that the subscription is cleaned up from the PubSub consumer once the
dictionary is downloaded in DictionaryUtils::readDictionaryFromKafka. Without this
cleanup, subsequent attempts to resubscribe to the same topic partition are ignored which
can have side effects.
This issue particularly impacts the admin tool, as it uses the same consumer for
dictionary downloads and then tries to subscribe to the same partition for dumping
messages. The resubscription request is rejected because the consumer already has an
active subscription from the dictionary fetch operation. Consequently, the dumper cannot
seek to the provided offset if the partition being dumped is 0 (the same partition used
during dictionary download).
By removing the subscription after the dictionary is …
> [vpj][admin-tool] Remove subscription from consumer after dictionary download in DictionaryUtils::readDictionaryFromKafka

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/AbstractTestVeniceHelixAdmin.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForMultiKafkaClusters.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupServiceForParentController.java
When TopicCleanupService tries to delete RT topics, it does not have to wait for all the corresponding VT topics to get deleted if all the versions of the store has changed from hybrid to batch. If all the versions are batch, it can be safely assumed that no VT topic is consuming from that RT topic.
This was already done in https://github.com/linkedin/venice/pull/1234 but that commit was reverted in https://github.com/linkedin/venice/pull/1355
It was reverted because TCS was trying to get `Store` for which it was not the leader controller. Only leader controller caches and stores the information for all the stores in the cluster it is leader of. 
So this time, `isRTTopicDeletionPermittedByAllControllers` will not take `Store` object, it will use the ControllerClientMap to get Store …
> [controller] do not delay RT topic deletion if the store is no longer hybrid

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helix/TestHelixReadOnlySchemaRepository.java
For read compute store Venice warms the schema cache by generating the deserializers. But if we have schema deletion enabled and there is a gap in schema ID in schema repo, existing code could hit NPE. This PR fixes that. 
CI
> [server] Fix NPE in read compute store schema warm-up code

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VersionSwapDataChangeListener.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
This improves resiliency in a layered approach.  It:
- Makes the metadata update a change listener on the store repository 
- Makes the original detection thread a last ditch effort should something go wrong when reacting to that call back 
- Makes the unknown topic or partition exception a signal to try and force a refresh of metadata and fix the subscription
- Actually uses the correct executor task method so that the refresh is properly scheduled (as opposed to the original one which only did it once).
Resolves #XXX
> [changelog] Add resiliency to version swap in change capture client

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestTopicWiseSharedConsumerPoolResilience.java
For Da Vinci, when we close / retire a version, it will call shutdownIngestionTask API, which will try to unsubscribe and sync offset for graceful shutdown. Today the timeout is 10 seconds and it could timeout for topic with many partition assignment.
This will result in two kinds of exceptions:
1. When it is doing graceful shutdown and syncing offset, it may fail after the wait timeout as it will also remove storage engine
2. It may also failed to persist certain lingering data in drainer after timeout. 
This PR tries to do minimal changes to reduce the noises in application that runs DVC by increasing the total timeout for per SIT shutdown wait. 
N/A
> [server][dvc] Increase graceful shutdown time for Da Vinci to reduce timeout exception

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AbstractKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/TopicPartitionIngestionInfo.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
1. Add consumer topic partition ingestion info logging when consumer is detected as stuck consumer, this will snapshot important information when stuck consumer happen. Normally we need to know which partition with offset lag is attempting to ingest and blocking the thread. 
2. Make hybrid store quota debugging more informative with real-time disk usage in logs.
> [server] Ingestion Debugging Improvement by making logging more informative.

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
This commit adds support to the admin tool for dumping messages from a PubSub topic within a specified time range, using start and end date-time in the format "yyyy-MM-dd HH:mm:ss" (PST). Previously, the admin tool could not consume messages based on time ranges. This code change allows targeted message dumping to streamline troubleshooting.
CI and PROD
> [admin-tool] Add support for dumping messages within a specified time range

- build.gradle
Bump `avro-util` version to `0.4.22`. This is primarily to fix an issue with deserialization of `Fixed` field. This caused issues to our users because during setting of partial update fields through `UpdateBuilder`, we check if the provided data can be serialized into the partial update schema.
GH CI
> [all] Bump avro-util version to 0.4.22

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/VeniceCI-E2ETests.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
Often times developers push new commits to the same PR which kicks off new check runs, while the previous runs still running which causes longer wait times for the new workflow to start. This change will cancel the previous workflow runs on every new push leading to quicker check runs results for the new change.
GHCI
> Cancel previous workflow run on new push

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PushTimeoutTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestLeaderReplicaFailover.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ErrorPartitionResetTask.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
If ingestion task encounters any error, it just marks the CV to error state which never remediates. This PR makes user of a new [API](https://github.com/apache/helix/pull/2792) helix added to annotate a replica to ERROR state. This will later be picked by the error replica reset task `ErrorPartitionResetTask`  which will attempt to recover those replicas. 
Also added system stores to the controller error replica reset task.
GHCI
> [controller][server][da-vinci-client] Mark a helix replica to error state during ingestion error

- services/venice-router/src/main/java/com/linkedin/venice/router/stats/AggRouterHttpRequestStats.java
- services/venice-router/src/test/java/com/linkedin/venice/router/AggRouterHttpRequestStatsTest.java
The store level metrics in AggRouterHttpRequestStats are registered lazily. Add a flag in AggRouterHttpRequestStats to disable store level metric emission for non-streaming multiget request type. This is cleaner and the less intrusive than adding checks and handling elsewhere because AggRouterHttpRequestStats and the triggers to corresponding record functions are shared across different request types (SINGLE_GET, MULTI_GET, MULTI_GET_STREAMING, COMPUTE, etc...).
We will keep the total stats for non-streaming multiget to give us visibility in case any legacy clients start to make non-streaming multiget requests.
Fixed a bug where recordNoAvailableReplicaAbortedRetryRequest was calling the wrong method for the store metric recording.
Existing and new tests
> [router] remove store level metrics for non-streaming multiget

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/AbstractPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/AbstractVenicePartitionStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
Drop partition is performed asynchronously through consumer action in SIT. This behavior allowed a race to occur when we have OFFLINE->DROPPED followed by OFFLINE->STANDBY for the same partition on the same host. This is because we initialize the partition synchronously in OFFLINE->STANDBY and there is a chance the previously queued drop partition consumer action is executed after OFFLINE->STANDBY and that will cause ingestion to fail.
The fix is to block and wait on the drop partition consumer action future in the OFFLINE->DROPPED state transition. This way when the host is picked again for OFFLINE->STANDBY for the same partition, it can do so with a clean state without any lingering async actions.
Existing and new unit tests
> [server] Block OFFLINE->DROPPED ST to wait for drop partition action

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/DaVinciPushStatusUpdateTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/notifier/TestDaVinciPushStatusUpdateTask.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushstatushelper/PushStatusStoreWriterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/logger/TestLogAppender.java
This feature is controlled by config:
davinci.push.status.check.interval.in.ms
When the config value is non-negative (default value is -1, disabled), the feature is enabled, and DVC would batch both batch push status and incremental push status across all partitions hosted on the node.
For each incremental push version on a DVC node, there would be at most two status event messages:
START_OF_INCREMENTAL_PUSH_RECEIVED - at least one partition on the DVC
node starts ingesting data for this
incremental push version;
END_OF_INCREMENTAL_PUSH_RECEIVED   - all hosted partitions on the DVC node
finish ingesting data for this
incremental push version.
The batching feature for incremental pushes reuse the "DaVinciPushStatusUpdateTask" for batch push status; "DaVinciPushStatusUpdateTask" is a …
> [da-vinci] DVC batch incremental push status across all partitions on the same node

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/TehutiUtils.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerHttpRequestStatsTest.java
Currently, we record fine-grained percentiles for key and value of all single get requests. This bloats up the metrics significantly. This commit restricts key and value profiling only for cases where this config is enabled.
In addition to this, removed P77 and P90 metrics from latency metrics. We still have p50, p95, p99 and p99.9.
GH CI
> [router][server] Reduce the granularity of latency histogram percentiles and disable key value profiling for single gets

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java
We need to test this feature thoroughly before rolling it out in prod.
CI
> [server] Make cleaning up partitions on startup configurable. Off by default

- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerHttpRequestStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerHttpRequestStatsTest.java
In a previous commit (#1377), when removing some metrics, we ended up removing some key metrics about key and value size values for single_get requests as well. That change also led to NPEs as the caller expected the K/V stats to always be recorded for Single-get requests. This commit adds `Avg` and `Max` stats by default for key and value sizes in single get requests.
> [server] Fix stats handling for SINGLE_GET requests

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceMetricsConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceMetricsRepository.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricNamingFormat.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepository.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/metrics/MetricsRepositoryUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceMetricsConfigTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceMetricsRepositoryTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepositoryTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/dimensions/VeniceMetricsDimensionsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterMetricEntity.java
- services/venice-router/src/test/java/com/linkedin/venice/router/stats/AggRouterHttpRequestStatsTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/stats/RouterHttpRequestStatsTest.java
some minor cleanups and tests including
1. Not initializing `VeniceOpenTelemetryMetricsRepository` when otel is not configured
2. if `setMetricEntities` is not configured in VeniceMetricsConfig and if exponential bucket histogram is enabled (which is enabled by default), builder will fail fast.
3. Disabling OTel exporting to endpoint in routers for integration tests
4. Removing the explicit names passed in `RouterMetricEntity` and use the enum name itself to be less error prone
5. some tests around these changes
GH CI
> [client-common][router] minor cleanup and some tests for otel

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/vpj/VenicePushJobConstants.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/AbstractStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/VersionImpl.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestZKStore.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
Currently, when target region push is enabled, it only ingests the data & swap to the new version in if the current region matches the target region defined by the target region push list or the native replication source fabric. The ingestion for the remaining regions are kicked off after the first region is able to swap to the new version.
The pr adds in a deferred version swap option to the existing target region push. In this version, data is ingested in all regions, but it will only swap to the new version in the target region. The behavior to swap the version out in the remaining regions will be added in later.
unit & integration tests
This will be enabled if `targeted.region.push.with.deferred.swap` is passed in in the job settings
> [vpj][controller] Add deferred swap for target region push

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/TopicExistenceCheckerTest.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/heartbeat/DefaultPushJobHeartbeatSenderFactory.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/heartbeat/TestPushJobHeartbeatSender.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreVeniceWriterCache.java
- internal/venice-common/src/main/java/com/linkedin/venice/system/store/MetaStoreWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/ConsumerIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestSeparateRealtimeTopicIngestion.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ParticipantStoreClientsManager.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/UserSystemStoreLifeCycleHelper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
This is the continuation work of https://github.com/linkedin/venice/pull/1345 and https://github.com/linkedin/venice/pull/1349
Changing references for Version::composeRealTimeTopic to Utils::getRealTimeTopicName. Because there are too many references to review easily.
Resolves #XXX
existing tests cover the change
> [controller] use new getRealTimeTopicName API - part-2

- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
The E2E DVRT tests take a significant amount of time. To speed up the CI, this PR moves it to its own test file and GitHub workflow.
CI
> [test] Move RecordTransformer tests from DaVinciClientTest to DaVinciClientRecordTransformerTest

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeDeleteWithFieldLevelTimestamp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
When we enabled partial update as store config, existing SIT will pick up this config after a server restart and becomes AAWC SIT and requires to work on field level TS.
We solved the similar issue in PUT operation in #1081 , where we will make no assumption on existing RMD record and optionally convert it from value-level to field-level. This PR completes the fix by adding the same logic to DELETE operation.
Add a new unit test and new integration test.
> [server] AAWC delete operation should auto-convert value-level RMD record

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
In SIT internal close we drain the consumer action queue and process DROP_PARTITION and RESET_OFFSET messages. However, when we process them we did not complete their corresponding future. This breaks any logic that are waiting for those futures and create false positive timeout errors.
New unit test
> [server] Complete the corresponding consumer action future in SIT close

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controllerapi/TestControllerClient.java
This test is validating that as long as at least one of the hosts in the Controller urls is healthy, the `ControllerClient` won't see a `ConnectException`. However, the `ControllerClient` will randomize the controller order in every request, it is not deterministic that a single run will ever attempt to communicate with the unavailable controller. Our tests setup to retry failing tests multiple times, and if any of them passes, it assumes the test is good. So, regressions in this logic could get missed by our team. To prevent this, the test runs the test for 100 iterations.
However, this leads to a case where the test is running for 13 minutes on CI hosts. To speed up the test, we do two things:
1. Reduce the number of iterations to 50
2. Parallelize the loop to concurrently attempt …
> [test] Speed up TestControllerClient#testControllerClientWithInvalidUrls

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VersionSwapDataChangeListener.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
And other protections like subscribing to an empty set of partitions.
Resolves #XXX
> [changelog] Clean up consumer state on changelog client

- .github/workflows/UnitTests-core.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
The client module contains da-vinci-client which contains most of the server code. This PR splits the unit tests into more categories based on the venice components like router/server/controller etc which should improve total UT CI runtime further from 28 mins to 12mins. Also fixed the some flakiness in SIT tests for jdk8.
CI
> Further split services unit tests into Routers/Servers/Controllers

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreAwarePartitionWiseKafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
This PR only fixes NPE exception in StoreAwarePartitionWiseKafkaConsumerService#handleUnsubscription. 2nd call to the same TP unsubscription will be ignored, as expected, as it should be decrease twice.
There is still race condition in upstream call where unsubscribe and unsubscribeAll from SIT/Participant thread can dual unsubscribe on the same TP, due to race condition in certain map bookkeeping operation. This PR does not fix that, due to other unclear performance concern. It is harmless for now, as 2nd call to the same TP will be ignored by consumer.
Adjust unit test to cover the case.
> [server] Fix NPE in StoreAwarePartitionWiseKafkaConsumerService#handleUnsubscription

- .github/rawWorkflows/gh-ci-parameterized-flow.txt
- .github/workflows/UnitTests-core.yml
- .github/workflows/VeniceCI-CompatibilityTests.yml
- .github/workflows/VeniceCI-E2ETests.yml
- .github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/BatchGetAvroStoreClientUnitTest.java
- Replaced test reporter checks with annotation-only execution.
- Failed and flaky tests will now appear under the “Summary” tab and in the “Files Changed” tab (at the end for tests in unchanged files).
- Removed Gradle summary reporting.
> [CI] Remove checks for test reports to avoid CI failures

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/StateModelIngestionProgressNotifier.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
For hybrid stores whose current version is ingesting the real time data from a real time topic, if there is any exception/error thrown during ingestion they would log error message, sit still and stop ingestion, resulting in stale replicas. 
The mitigation mechanism is for oncall to manually restart every impacted cluster, which is very labor-intensive. 
This PR tries to resolve that by marking such replicas to ERROR state, which later in a controller task to reset such error replicas, will try to initiate new state transition of those replicas which can possibly mitigate such stale replica issue.
GHCI
> [server] Reset current version replica to ERROR on ingestion error

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/VeniceProperties.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/VenicePropertiesTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestVeniceRouterConfig.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/TestVeniceDelegateMode.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/AggServerReadQuotaUsageStatsTest.java
There are only two exceptions, related to throttling, which are allowed to be mutated post-init.
Miscellaneous:
- Deleted a dead config: router.compute.fast.avro.enabled
- Made VeniceProperties::getMap return an unmodifiable map.
N.B.: This is a carve out of #1367 to make that other PR smaller. It is the most trivial part of that PR.
> [router] Made most VeniceRouterConfig fields final

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
1. Continuation of #1213 and #1339.
2. `SharedKafkaConsumer.unSubscribe()` was missing the `timeoutMs` parameter, which was overwritten as a merge conflict in #1308.
> [server] Increased Wait After Unsubscribe Timeout Fix

- build.gradle
- clients/da-vinci-client/build.gradle
- clients/venice-admin-tool/build.gradle
- clients/venice-client/build.gradle
- clients/venice-producer/build.gradle
- clients/venice-push-job/build.gradle
- clients/venice-thin-client/build.gradle
- integrations/venice-beam/build.gradle
- integrations/venice-pulsar/build.gradle
- integrations/venice-samza/build.gradle
- internal/venice-client-common/build.gradle
- internal/venice-common/build.gradle
- services/venice-controller/build.gradle
- services/venice-router/build.gradle
- services/venice-server/build.gradle
- services/venice-standalone/build.gradle
We've been running into a lot of NPEs lately, so we decided to bring in the Checker Framework for nullness type-checking to help catch and prevent these issues. The checker is off by default and will be turned on gradually for each module. To enable it, pass the `-PskipCheckerFramework=false` flag when running Gradle.
Example:
```bash
./gradlew -PskipCheckerFramework=false compileJava
```
For more info about checker framework, see [Checker Framework](https://checkerframework.org)
> [build] Add checker framework for nullness type-checking

- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerReadQuotaUsageStats.java
- services/venice-server/src/test/java/com/linkedin/venice/stats/ServerReadQuotaUsageStatsTest.java
`Int2ObjectOpenHashMap` is not thread safe and using it for `ServerReadQuotaUsageStats` could result in unexpected behaviors during race conditions since the map is accessed and modified by multiple triggers and threads:
1. Read traffic
2. CV/routing change events
3. Version creation and deletion events
Added a test and confirmed that it will hang/timeout with `Int2ObjectOpenHashMap` but succeed with a thread safe map like `VeniceConcurrentHashMap`
Also minor defensive code change in `getReadQuotaUsageRatio` to avoid NPE since the map could change in between check and access.
New unit test and existing integration tests
> [server] Use thread safe map for versioned stats in SN read quota

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceClusterConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/StoreBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestClusterLevelConfigForNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/ActiveActiveReplicationForHybridTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushJobDetailsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreMultiColoTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatchReportIncrementalPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/ingestionHeartbeat/IngestionHeartBeatTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
Ready-to-serve check happens in two threads today:
(1) Drainer: which is reasonable
(2) SIT thread: there are two sub-cases:
- During L/F transition: It is only for empty RT topic, and today we have HB for non-agg and A/A already, so it only applies to the lingering AGG system store. In this PR, it is checked against store data replication type, if it is AGG we will still have it. We will completely remove it once AGG mode is removed.
- Before subscribe, it has a pre-check for short circuit to complete, and this is fine, as it is before the subscribe.
Also, I noticed that there are a bunch of integration tests which **enables incremental push on NON-AA store**. This is totally invalid setup and after removing the additional RTS check, these tests start to fail/very flaky. 
To make sure we …
> [controller][server] Remove SIT ready-to-serve check for A/A and non-AGG store during L/F transition

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ServerConnectionStatsHandler.java
- services/venice-server/src/main/java/com/linkedin/venice/stats/ServerConnectionStats.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ServerConnectionStatsHandlerTest.java
The previous connection tracking is not working properly because of two reasons:
1. `ServerConnectionStatsHandler` is being executed in the sub-channel, which is measuring the QPS rather than the new connection rate.
2. The way to extract the identity from cert is not right, so router connectin count is always 0.
To fix the above issues, this PR:
1. Move `ServerConnectionStatsHandler` up to be executed in the parent channel.
2. Use the correct identity parser to extract the application name from the cert, so that it can differentiate Router connections from Fast Client.
3. In function: `channelActive`, we can't extract `SslHandler` as SSL hasn't kicked in yet when the connection is established, so this PR introduces an async way to track new connections util the SSL handshake is fully …
> [Server] Fixed the connection tracking

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/AbstractVeniceStats.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceDelegateMode.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/VeniceResponseAggregator.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/routing/helix/HelixGroupLeastLoadedStrategy.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/routing/helix/HelixGroupRoundRobinStrategy.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/routing/helix/HelixGroupSelectionStrategy.java
- services/venice-router/src/main/java/com/linkedin/venice/router/api/routing/helix/HelixGroupSelector.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/HelixGroupStats.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/routing/helix/TestHelixGroupLeastLoadedStrategy.java
- services/venice-router/src/test/java/com/linkedin/venice/router/api/routing/helix/TestHelixGroupRoundRobinStrategy.java
Update Venice Router HAR least-loaded algo to take group latency into account and here
are the reasons:
a. When the total qps is relatively low, the pending request count based load rebalancing
algo doesn't work well as most of the time, the pending count is 0. One example: let us
say, the avg latency of one group is 10ms, and if the group qps is 10, that means very likely
only 10-20% of the time, there are some pending requests and even another group latency is
much lower: 1-2ms, the faster group won't be selected, and the latency-based LB algo will kick
in when the above case happens to prefer the faster group if the pending count is equal among all
the groups.
b. Completely getting rid of pending request count based LB will result in another issue as the relatively
slower group will …
> [router] Improve HAR routing in Router

- docs/quickstart/quickstart-multi-datacenter.md
- docs/quickstart/quickstart-single-datacenter.md
[doc] Update the guide for quickstart for single dc
doc only, no test is required.
> [doc] Update guide for quick start single dc

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
The test case validates the BlobDB in the following way:
1. Disable BlobDB and insert a bunch of entries and make sure no blob files are generated.
2. Enable BlobDB and insert more entries and validate there are some blob files are generated and validate all the entries added in 1&2.
3. Disable BlobDB again and insert more entries and make sure the the total number of blob files doesn't change.
4. Validate all the entries inserted in 1&2&3.
CI
> [test] Test to validate fully compatiblity of RocksDB BlobDB integration

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
Since the `drainerList` is allocated during startInner, initial metric calls to `StoreBufferServiceStats` would return `IndexOutOfBoundsException` in the code. This PR fixes that.
GHCI
> [server] Fix IndexOutOfBoundsException in memory usage in SBS

- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/HelloWorldTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
Currently supports converting an Avro schema into a CREATE TABLE statement.
Does not yet support  Map/Array/Enum/Struct types.
> [duckdb] Avro to SQL converter

- internal/alpini/common/alpini-common-base/src/test/java/com/linkedin/alpini/base/misc/TestTimeScheduledThreadPoolExecutor.java
- internal/alpini/common/alpini-common-base/src/test/java/com/linkedin/alpini/base/registry/TestResourceRegistry.java
> [test] Add timeouts for tests in TestTimeScheduledThreadPoolExecutor and TestResourceRegistry

- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBAvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/HelloWorldTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
By leveraging a different CREATE TABLE syntax, we can support composite primary keys, which previously did not work. This also simplifies the upsert syntax by letting us use CREATE OR REPLACE INTO, rather than the more verbose ON CONFLICT DO UPDATE SET x = EXCLUDED.x syntax.
Also simplified the upsertStatement and upsertProcessor APIs to have one fewer param each.
> [duckdb] Composite primary key support

- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/InsertProcessor.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBAvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformerTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
- internal/venice-test-common/src/main/resources/valueSchema/SingleFieldRecord.avsc
This refactoring lets the calling code pass the two kinds of schemas, for keys and values, as separate params. Previously, the calling code would have had to assemble a new schema equivalent to the SQL row, which was unwieldy.
Also added support for projecting columns (unused for now).
Unit tests.
> [duckdb] Refactored AvroToSQL to make key schemas first-class

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- gradle/spotbugs/exclude.xml
- internal/venice-common/src/main/java/com/linkedin/venice/acl/NoOpDynamicAccessController.java
- internal/venice-common/src/test/java/com/linkedin/venice/acl/NoOpDynamicAccessControllerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestControllerSecureGrpcServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ControllerRequestHandlerDependencies.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerAccessManager.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerGrpcServiceImpl.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerRequestHandler.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/grpc/ControllerGrpcSslSessionInterceptor.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/ControllerRequestHandlerDependenciesTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/VeniceControllerAccessManagerTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/grpc/ControllerGrpcSslSessionInterceptorTest.java
This commit introduces a gRPC interceptor that ensures all incoming connections use SSL/TLS 
and extracts client SSL attributes for downstream processing.
Key features:
- Validates the presence of an SSL session for each gRPC call.
- Extracts client certificate and remote address details.
- Injects extracted attributes into the gRPC context for downstream access.
- Rejects calls without SSL/TLS with an UNAUTHENTICATED status.
> [controller] Add interceptor to enforce SSL/TLS and propagate client attributes in gRPC controller server

- gradle/spotbugs/exclude.xml
- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/ColumnDefinition.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/IndexType.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/SQLUtils.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/TableDefinition.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBAvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBHelloWorldTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBSQLUtilsTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/AvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/SQLHelloWorldTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/sql/SQLUtilsTest.java
This is used to check whether a pre-existing table on disk has a schema equal to the one we want.
Did this by introducing various utility classes, including:
- ColumnDefinition
- TableDefinition
- IndexType
- SQLUtils
Also refactored unit tests to decouple from DuckDB, so that it's easier to test other engines in the future (e.g., SQLite).
> [duckdb] Utility to compare table schemas

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottlerTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/throttle/EventThrottler.java
This PR introduces a dynamically adjustable throttler that responds to various boolean signals. These signals, such as heartbeat lags or read latencies, can increase or decrease the throttler's quota, allowing for more responsive and performant responses.
GHCI
>  [server] Added adaptive throttler for tuning ingestion bandwidth dynamically

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/BatchMaintenanceTaskRunner.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/ClusterTaskRunner.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/SystemStorePushTask.java
This is just a side-effect PR I created for batch processing all stores in cluster when I am empty pushing all system stores to apply config updates.
Add the new command so you can write your **store-oriented task** and execute it cluster-wide with the admin-tool. It supports basic checkpointing and parallel processing. 
With this, there is a **system store empty push task** in this PR as well, it did sanity checks and empty push to all system stores for a specific user store.
I think it can be further optimized and used for other purpose, but I found it efficient to empty push system store to apply ZK-shared store config update.
This tool has been directly used in test environment and production environment.
> [admin-tool] Add a cluster batch processing framework command and a system store empty push task

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminOperationWrapper.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
This is based on Felix's commit with some additional changes to add an unit test for timed out or cancelled AdminExecutionTask to verify the fix. The original commit message is below:
The main bug fix in this commit is that in the AdminConsumptionTask's executeMessagesAndCollectResults function, tasks for many stores could be scheduled, but if some of them never began running, and the whole set of tasks timed out (after 30 minutes), then the tasks that didn't start at all would leave a lingering reference to the corresponding store in the storeToScheduledTask map, which is a class property. This in turn would cause the next execution of this function to skip the affected store, therefore never letting it run any task again. Since it is not actually needed to hang on this map at the class …
> [controller] AdminConsumptionTask fix around timed out or cancelled AdminExecutionTasks

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferPayload.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferUtil.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/NettyP2PBlobTransferManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/NettyFileTransferClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/P2PFileTransferClientHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/P2PMetadataTransferHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PFileTransferServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManagerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestNettyP2PBlobTransferManager.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestP2PFileTransferClientHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestP2PFileTransferServerHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/DefaultIngestionBackendTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/BlobP2PTransferAmongServersTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
There is an edge case where multiple file formats may coexist within a single cluster. For instance, DVC1 might use a plain-table format while DVC2 uses a block-based format. If DVC2 requests data from DVC1 during bootstrap, it could end up with a plain-table store in DVC2, leading to read issues.
This PR addresses the issue by:
- Receiver side: Including the table format in the bootstrap request URI. An example URI: `[0]""/[1]"store"/[2]"version"/[3]"partition/[4]"table format"`.
- Sender side: Storing the current snapshot format in the snapshot manager. When a bootstrap request arrives, the snapshot manager compares the existing snapshot format with the requested table format. If they do not match, it returns a 404 error to reject the blob transfer request.
Integration test …
> [server][dvc] add table format info in the blob transfer

- .github/workflows/VeniceCI-E2ETests.yml
- build.gradle
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- settings.gradle
This is necessary because DuckDB 0.9.0..1.2.0 has a regression where it cannot run in the same JVM that also depends on RocksJava. This has been fixed but is not released yet. When release 1.2.0 comes out, we will be able to remove the snapshot dependency and repository.
Miscellaneous:
- Bumped up the timeout on DuckDBDaVinciRecordTransformerIntegrationTest
- Created a new 1001 integration tests bucket for Duck DVRT, and moved the (regular) DVRT tests to bucket 1000.
Works around https://github.com/duckdb/duckdb-java/issues/14
> [duckdb] Changed DuckDB dep to be a snapshot

- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
Only wipe the non-current versions (e.g. backup).
New assertion in existing integ test.
> [duckdb] Do not wipe current version in onEndVersionIngestion

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
Instantiate the gracefulShutdownLatch lazily to avoid waiting for the latch when shutting down an ingestion task that was just initialized. This is more of an issue in unit tests where we mock out certain parts and the run() method of SIT never get to execute so waiting on the latch that was originally initialized during instance instantiation will timeout.
Existing unit and integration tests.
> [server][da-vinci] Instantiate the gracefulShutdownLatch lazily

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
We already has global record throttler, adding this bytes throttler as it can be more flexible to test.
N/A
> [server] Add global bandwidth throttler into adaptive throttler

- internal/venice-common/src/main/java/com/linkedin/venice/acl/NoOpDynamicAccessController.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/transport/GrpcRequestResponseConverter.java
- internal/venice-common/src/main/proto/VeniceControllerGrpcService.proto
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestControllerSecureGrpcServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestControllerGrpcEndpoints.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterCreateOptions.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerCreateOptions.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceControllerWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerGrpcServiceImpl.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/grpc/ControllerGrpcSslSessionInterceptor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/grpc/GrpcControllerClientDetails.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/VeniceControllerGrpcServiceImplTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/grpc/GrpcControllerClientDetailsTest.java
- Use access controller manager to enforce ACL checks in gRPC createStore API.
- Add support for running E2E tests with a custom access controller.
- Introduce `GrpcControllerClientDetails` to encapsulate gRPC session details for 
authorization checks.
> [controller] Enforce ACL checks on gRPC createStore API

- .github/workflows/VeniceCI-CompatibilityTests.yml
- .github/workflows/VeniceCI-E2ETests.yml
- build.gradle
- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- internal/venice-test-common/build.gradle
Added a new CI task dedicated to Duck Vinci.
Dependency changes:
- Re-introduced the snapshot dependency for duckdb.
- Removed the dependency on venice-duckdb from venice-test-common, so that this artifact is not tainted by a snapshot dependency.
Verified that existing tests still run after the CI refactoring.
> [duckdb] Moved integ test out of venice-test-common

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/BlockingDaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/config/DaVinciConfigTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/TestStringRecordTransformer.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformerTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestIntToStringRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestSkipResultRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStringRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestUnchangedResultRecordTransformer.java
Time to force-feed the duck. Pre-allocated all Avro deserializers, connection, prepared statement as well as the InsertProcessor, so that the hot path has as little to do as possible.
Miscellaneous:
- Changed the unhandled type policy from FAIL to SKIP.
- Made DVRT implement Closeable.
- Added a new useUniformInputValueSchema() API to DVRT:
- If false (default), SIT will give whatever incoming record in the schema it comes in.
- If true (which the DuckDB DVRT does), SIT will use Avro schema evolution to decode the incoming records into the same schema which it passed into the DVRT constructor.
> [duckdb] Operation Foie Gras

- all-modules/build.gradle
- build.gradle
- gradle/spotbugs/exclude.xml
- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformerTest.java
The view created by DuckDBDVRT was called current_version, so it could not work with multiple stores. Changed it so that the view inherits the store name instead.
Miscellaneous build changes:
- Fixed the duckdb exclusion rule in all-modules.
- Bumped up the duckdb snapshot dep to the current latest one.
New unit test.
> [duckdb] Fixed multi-store bug

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputDictTrainer.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputFormat.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReader.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputSplit.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReaderTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputDictTrainer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputFormat.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/hadoop/input/kafka/TestKafkaInputRecordReader.java
Replace the usage of Kafka TopicPartition with Venice PubSubOffset instances to enable support for non-Kafka   
pub-sub clients. This change is part of the broader effort to decouple Venice from Kafka-specific classes and  
ensure compatibility with other pub-sub systems.
> [vpj] Replace org.apache.kafka.common.TopicPartition with PubSubTopicPartition in VPJ

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
Update the topic metadata producer timestamp fetch logic to include heartbeat messages. Previously, the getProducerTimestampOfLastDataMessage function only considered data messages when retrieving the producer timestamp from the most recent messages. However, for real-time topics without data ingestion, the last messages could be heartbeat control messages, causing endless searching during the ready-to-serve check due to the continuous arrival of new heartbeat messages.
> [server] Enhance the producer timestamp fetch logic to include both data and heartbeat messages.

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
The current timeout is large and doesn't really seem to be necessary, it's just slowing things down
Resolves #XXX
> [tests] Reduce timeout on test to speed up test runs

- internal/venice-common/src/main/java/com/linkedin/venice/exceptions/VeniceUnauthorizedAccessException.java
- internal/venice-common/src/main/java/com/linkedin/venice/grpc/VeniceGrpcServer.java
- internal/venice-common/src/main/java/com/linkedin/venice/grpc/VeniceGrpcServerConfig.java
- internal/venice-common/src/main/proto/VeniceControllerGrpcService.proto
- internal/venice-common/src/main/proto/controller/ControllerGrpcRequestContext.proto
- internal/venice-common/src/main/proto/controller/StoreGrpcService.proto
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/transport/GrpcRequestResponseConverterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/exceptions/VeniceUnauthorizedAccessExceptionTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/grpc/VeniceGrpcServerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/grpc/VeniceGrpcServerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestControllerSecureGrpcServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestControllerGrpcEndpoints.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/grpc/GrpcRequestResponseConverter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/grpc/server/ControllerGrpcServerUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/grpc/server/StoreGrpcServiceImpl.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRequestParamValidator.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateStore.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoreRequestHandler.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerGrpcServiceImpl.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerRequestHandler.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/grpc/server/ControllerGrpcServerUtilsTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/grpc/server/StoreGrpcServiceImplTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/ControllerRequestParamValidatorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateStoreTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoreRequestHandlerTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/VeniceControllerGrpcServiceImplTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/VeniceControllerRequestHandlerTest.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ListenerService.java
- Introduced `StoreGrpcServiceImpl` for store-related gRPC endpoints (update, get, delete ACLs).
- Added `VeniceUnauthorizedAccessException` to handle unauthorized access scenarios.
- Refactored `VeniceGrpcServerConfig` to support multiple `BindableService` instances.
- Updated `VeniceGrpcServer` to register multiple services and interceptors.
- Added `StoreRequestHandler` to process store-specific gRPC requests.
- Introduced `ControllerGrpcServerUtils` for common gRPC request handling and error responses.
- Added unit tests for `StoreRequestHandler` and enhanced existing gRPC server tests.
UT and E2E tests
> [controller] Add StoreGrpcService for store related gRPC endpoints and reduce boilerplate

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ConsumerPoolType.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
Fixed two issues found in tests:
(1) region level metrics should not be resolved to non-sep region, it will cause confusion as we can't tell whether it is coming from RT or sepRT.
(2) Add separate pool and throttler for sep RT in dedicated AAWC leader consumer pool mode. This is addition to original implementation in current version prioritization mode separate pool, as not all clusters have rolled out this feature.
Updated unit test.
> [server] A few changes for separate RT ingestion

- build.gradle
- integrations/venice-duckdb/build.gradle
- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/AvroToSQL.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/KeyOnlyPreparedStatementProcessor.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/KeyValuePreparedStatementProcessor.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/sql/PreparedStatementProcessor.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBAvroToSQLTest.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformerTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
- internal/venice-test-common/src/main/resources/valueSchema/TwoFieldsRecord.avsc
Delete used to work only for key schemas that had a single string field named "key". Now it works for any schema.
Miscellaneous:
- Refactored the InsertProcessor code to be more generic.
- Bumped DuckDB snapshot dep to the latest.
New test.
> [duckdb] Fixed delete bug in DuckDB DVRT.

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AbstractRoute.java
VeniceController refactoring, where the DynamicAccessController (DAC) was inadvertently passed to the  
Admin Server even when SSL was disabled. The presence of a DAC was incorrectly interpreted as ACL  
checks being enabled, causing the Admin Server to enforce ACLs on both secure and non-secure  
channels. This happened because a valid DAC was applied universally to both secure and non-secure  
admin servers.  
The fix ensures that the DynamicAccessController is no longer passed to the Admin Server when using  
a non-secure channel. Additionally, when the NoOpDynamicAccessController is set, it is now explicitly  
treated as a signal that ACL checks are disabled for HTTP requests in the controller. These changes  
restore the expected behavior.  
CI
> [controller] Fix regression in ACL handling for non-secure admin server

- internal/venice-common/src/main/proto/controller/ClusterAdminOpsGrpcService.proto
- internal/venice-common/src/test/java/com/linkedin/venice/controllerapi/transport/GrpcRequestResponseConverterTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/grpc/GrpcRequestResponseConverter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/grpc/server/ClusterAdminOpsGrpcServiceImpl.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminCommandExecutionRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminTopicMetadataRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ClusterAdminOpsRequestHandler.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRequestParamValidator.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerRequestHandler.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/grpc/server/ClusterAdminOpsGrpcServiceImplTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/AdminCommandExecutionRoutesTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/AdminTopicMetadataRoutesTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/ClusterAdminOpsRequestHandlerTest.java
- Added `ClusterAdminOpsGrpcServiceImpl` to support gRPC-based cluster admin operations.
- Implemented methods for admin command status, metadata, and execution ID retrieval.
- Introduced `ClusterAdminOpsRequestHandler` for handling gRPC service requests.
- Added unit tests for the service and request handler to validate functionality.
UT
> [controller][grpc] Add ClusterAdminOpsGrpcService with handler and tests

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushJobDetailsTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
Add a dual write to child region for push job details, so when the system store is converted to A/A it will still be able to consume the updates.
The hard-coding of AGG mode in system store initialization routine will not be changed, as it will only kick in if no such store is found. We will update this after second phase when we remove the parent RT write.
Added new unit test and new integration test
> [controller] Dual write push job details to both parent and child region

- .github/workflows/limit-pr-files-changed.yml
During  reviewing large PR, reviewer often times miss out critical bugs which later can cause production issues. 
This PR limits the maximum number of lines changed in a PR to 500. It excludes test file changes.
To override the check, developer can add OVERRRIDE keyword in the title or description.
CI
> Limit maximum number of lines changed in file

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceController.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DeferredVersionSwapStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
Add in a new background service, `DeferredVersionSwapService`, to the parent controller to perform version swap for the remaining regions after the specified wait time has passed in target region push
Unit tests for the new class
> [controller] Add deferred version swap service to parent controller

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHybridStoreRepartitioningWithMultiDataCenter.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
So far, real time topic name could only be changed during partition count update (https://github.com/linkedin/venice/pull/1404).
In this PR, I am making it changeable directly with update store command. The benefits of this change will that users will be able to delete and recreate stores with a different real time topic name. If real time topic name is not changed, it is observed that the old real time topic, with the same name, sometimes, hang in there longer and does not let the new store create.
Resolves #XXX
added an integration test
> [controller] update real time topic name with UpdateStore admin command

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- gradle/spotbugs/exclude.xml
- internal/venice-common/src/main/java/com/linkedin/venice/annotation/UnderDevelopment.java
- internal/venice-common/src/main/java/com/linkedin/venice/annotation/VisibleForTesting.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubPosition.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/consumer/MockInMemoryConsumer.java
Introduce a new overload of `subscribe` in `PubSubConsumerAdapter` that accepts a  
`PubSubPosition`. This change is aimed at supporting non-numeric offsets. This allows  
consumers to specify positions such as `EARLIEST`, `LATEST`, or an implementation-specific  
position type. Implementors must map this `PubSubPosition` to the appropriate offset in  
the underlying pub-sub system.
- **PubSubConsumerAdapter:**  
Added a new `subscribe` method that uses `PubSubPosition` to determine the starting  
offset for consumption. This method is marked with the `UnderDevelopment` annotation.  
(`PubSubConsumerAdapter.java`)
- **PubSubPosition Updates:**  
Added `EARLIEST` and `LATEST` positions to the `PubSubPosition` interface.  
(`PubSubPosition.java`)
- **ApacheKafkaConsumerAdapter …
> [server][controller][vpj] Add PubSubConsumerAdapter::subscribe with PubSubPosition parameter

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClient.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientRetryBudgetTest.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/RetriableAvroGenericStoreClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
So far, the retry budget feature doesn't work well with low QPS (retry requests are being rejected),
so this PR introduces a config option to enable/disable this feature and it also disables this feature by default.
We will re-enable it by default once we figure out a way to make it work for all kinds of scenarios.
New client config:
retryBudgetEnabled: default false
CI
> [fast-client] Added option to enable/disable retry budget

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/DataRecoveryRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/RoutersClusterConfigRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/SkipAdminRoute.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoreRoutesTest.java
Handle cases where `is_abort_migration_cleanup` is null by setting it to false. This ensures that the system remains backward compatible even when the value is not explicitly provided.
Tested by adding comprehensive unit tests that cover the new functionality and ensure its correctness.
> [controller] Set default for `is_abort_migration_cleanup` to false when null

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/ClientConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/RetryManager.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/RetryManagerTest.java
This PR fixed a bug in RetryBudget, and previously, if the request volume becomes 0, the retry budget won't be refreshed any more even there are more traffic later on.
This PR also re-enables retry budget by default.
CI
> [fast-client] Fixed retry budget freshness issue

- build.gradle
- internal/venice-common/src/main/resources/avro/PartitionState/v16/PartitionState.avsc
This change introduces fields in `PartitionState.avsc` to replace long 
offsets with PubSub positions. The new fields include:
- `lastProcessedVersionTopicPubSubPosition`: Tracks the last successfully consumed 
position in the version topic.
- `latestObservedTermId`: Stores the most recent termId observed by this replica.
- `currentTermStartPubSubPosition`: Marks the PubSub position where the current 
leader's term starts in the version topic.
- `upstreamRealTimeTopicPubSubPositionMap`: A map tracking the last PubSub position 
consumed from upstream topics, keyed by the bootstrap server URL.
- `upstreamVersionTopicPubSubPosition`: Stores the last persisted upstream version 
topic PubSub position; remains `null` if the batch native-replication source is the 
same as the local region. …
> [protocol] Add PartitionState schema v16 to replace long offset with PubSubPosition

- .github/pull_request_template.md
- build.gradle
- docs/dev_guide/how_to/recommended_development_workflow.md
- internal/venice-common/src/main/resources/avro/KafkaMessageEnvelope/v12/KafkaMessageEnvelope.avsc
This update introduces a new schema version: `v12` for `KafkaMessageEnvelope` to add fields aimed  
at eventually replacing long-based offsets with `PubSubPosition`. Specifically:
- **`localHighWatermarkPubSubPositions`** is introduced to eventually replace
`localHighWatermarks`, which stores the latest consumed positions for all real-time topics.
- **`upstreamPubSubPosition`** is introduced to eventually replace `upstreamOffset`, which
stores the message position in the upstream pubsub system.
Misc Addition:
- **`termId`** is introduced to track the unique term in which the message was produced,
typically using a Helix message timestamp of the leader state transition.
`termId` is intended to uniquely represent a leader session or term in the replication log.
In scenarios like …
> [protocol] Add KafkaMessageEnvelope schema v12 to replace long offsets with PubSubPosition

- .github/workflows/limit-pr-files-changed.yml
Fix PR limit workflow to check for different schema files limits and total line changes in a PR. Following are the limits a PR must follow.
MAX_LINES per file is 500 
MAX_TOTAL_LINES_ADDED is 2000
Also schema changes should be reviewed separately in a different PR before doing any code changes.
There's an option in build.gradle to isolate schema changes, allowing them to be integrated without affecting the existing code picking up the new generated class.
def versionOverrides = [
//        project(':internal:venice-common').file('src/main/resources/avro/StoreVersionState/v5', PathValidation.DIRECTORY)
]
CI
> Fix PR limit workflow to check for schema files limits

- internal/venice-client-common/src/main/java/com/linkedin/venice/exceptions/VeniceNoStoreException.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
When deleting stores, we check for hybridness in child colos, if one of the colo has already deleted the store, the check returns false, which can block RT deletion forever.
This PR fixes such cases.
GHCI
> [controller] Skip checking RT for deleted stores

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionStorageMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageEngineMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageMetadataService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/offsets/DeepCopyStorageMetadataService.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/offsets/InMemoryStorageMetadataService.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
Because of the blob-db integration, `SIT` will forcibly set `sorted` to `false` for hybrid stores and inconsistent `sorted` can happen during the rolling out/rolling back blob-db features. Here is one case how it can happen during the rolling out of blob-db:
1. P1 processes `SOP` with `sorted=true` and persist it in `StoreVersionState`.
2. P2 hasn't started processing `SOP` yet.
3. Restart the cluster and roll out blob-db feature.
4. when P2 processes `SOP` with `sorted=true`, it will forcibly set `sorted=false`, and it will be different from the previously persisted `StoreVersionState`.
5. This is fine as long as we just follow the previously persisted `StoreVersionState`.
6. Here are the reasons why step 5 is true: a. If the input for a given partition is truly sorted, it can always be …
> [da-vinci][server] Fixed the race condition during BlobDB rolling out/back

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionStorageMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageEngineMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageMetadataService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/offsets/DeepCopyStorageMetadataService.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/offsets/InMemoryStorageMetadataService.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
* [da-vinci][server] Fixed the race condition during BlobDB rolling out/back
Because of the blob-db integration, `SIT` will forcibly set `sorted` to `false` for hybrid stores and inconsistent `sorted` can happen during the rolling out/rolling back blob-db features. Here is one case how it can happen during the rolling out of blob-db:
1. P1 processes `SOP` with `sorted=true` and persist it in `StoreVersionState`.
2. P2 hasn't started processing `SOP` yet.
3. Restart the cluster and roll out blob-db feature.
4. when P2 processes `SOP` with `sorted=true`, it will forcibly set `sorted=false`, and it will be different from the previously persisted `StoreVersionState`.
5. This is fine as long as we just follow the previously persisted `StoreVersionState`.
6. Here are the reasons why step 5 is …
> [da-vinci][server] Fixed the race condition during BlobDB rolling out/back (#1500)

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
The `venice-thin-client` utilizes the ForkJoinPool common pool, which can cause spurious timeouts during application startup, potentially resulting in startup failures. The recommended solution is to use a different thread pool to mitigate contention issues. Here we adopt a single thread pool for warm-up logic.
> [venice-thin-client] Avoid using common thread pool for store client warming up.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/BlockingDaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformerFunctionalInterface.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/DaVinciRecordTransformerUtility.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/config/DaVinciConfigTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/DaVinciRecordTransformerConfigTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/RecordTransformerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/transformer/TestStringRecordTransformer.java
- docs/user_guide/read_api/da_vinci_client.md
- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- integrations/venice-duckdb/src/main/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformer.java
- integrations/venice-duckdb/src/test/java/com/linkedin/venice/duckdb/DuckDBDaVinciRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/DaVinciUserApp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestIntToStringRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestSkipResultRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStringRecordTransformer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestUnchangedResultRecordTransformer.java
1.  Previously, the configs for `DaVinciRecordTransformerConfig` were set by passing in all of the values into its constructor. This means that anytime we wanted to add another config, it would be a breaking change. To resolve this, I refactored `DaVinciRecordTransformerConfig` to use a Builder pattern.
2. Fixed a bug where if a user set `storeRecordsInDaVinci`, it would always bootstrap from VT and ignore the on-disk state. This isn't deseriable behavior. To fix this, I introduced a new config called `alwaysBootstrapFromVersionTopic`. Although most users won't use this, this can serve use-cases where the user is only storing their records in-memory. It is more preferable for users to at least have `storeRecordsInDaVinci` set to true so they can bootstrap from disk and utilize blob …
> [dvc][doc] Refactor DaVinciRecordTransformerConfig to use Builder pattern and update DVRT docs

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/tehuti/MockTehutiReporter.java
In production, we previously observed no state transition metrics emitted, here we add test logic to verify these metrics will be emitted for every Venice server instances. 
ci
> [test] Add test logic for verifying thread pool metric emitted before server shutdown during integration test.

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferUtil.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/DaVinciBlobFinder.java
- internal/venice-common/src/test/java/com/linkedin/venice/blobtransfer/DaVinciBlobFinderTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestBlobDiscovery.java
When testing blob transfer on DVC hosts with multiple stores, it was found that some stores encountered errors while finding peers. The error message is as follows:
`2025/01/30 18:41:32.990 ERROR [DaVinciBlobFinder] [ForkJoinPool.commonPool-worker-58] [flip-war] [] Error finding DVC peers for blob transfer in store: FeedEngagementCounts4dByRootObjectUrn, version: 191, partition: 198
java.lang.IllegalArgumentException: argument "src" is null
at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:5072) ~[com.fasterxml.jackson.core.jackson-databind-2.18.0.jar:2.18.0]
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3920) ~[com.fasterxml.jackson.core.jackson-databind-2.18.0.jar:2.18.0]
at …
> [da-vinci] Bug fix for peer discovery in DVC with multi-stores

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePutWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/resources/avro/NestedRecordV1.avsc
- clients/da-vinci-client/src/test/resources/avro/NestedRecordV2.avsc
Today, in AAWC DCR code, we always use incoming schema as both reader/writer schema to deserialize the incoming PUT.
The problem is, if we update the complex record in schema evolution by adding new nested field, and incoming PUT is using old schema, then after merge, the updated value record will be missing the newly added nested fields and unable to be serialized back by superset schema.
The fix is simple, just also use resolved schema as reader schema to up-convert the incoming PUT.
The resolved schema is defined as: If old value schema and incoming value schema is the same, then it is the old value schema. Otherwise, use superset schema of them.
**Behavior Change:**
This PR has certain behavior change: Due to PUT potentially being up-converted to superset schema, it may contain fields …
> [server] Up-Convert PUT message schema in AAWC

- .github/workflows/limit-pr-files-changed.yml
Typo fix in pr limit action.
tested with PR diff.
File: internal/venice-common/src/main/java/com/linkedin/venice/writer/WriterChunkingHelper.java, Lines Changed: 5 
File: internal/venice-common/src/main/resources/avro/KafkaMessageEnvelope/v12/KafkaMessageEnvelope.avsc, Lines Changed: 368
The PR has both schema and Java code changes, please make a separate PR for schema changes.
For schema file changes, please update build.gradle to update 'versionOverrides' inside compileAvro task to use fixed protocol version
> Typo fix in pr limit action

- internal/venice-common/src/main/proto/controller/ClusterAdminOpsGrpcService.proto
[protocol] Add adminOperationProtocolVersion into proto schema AdminTopicMetadata
This is the preparation for PR: #1418 
Since we are introducing a new field in AdminTopicMetadata, we will need to update the API `getAdminTopicMetadata` to return the full metadata map on remote. To do that, we need to add this key into the response object. 
Only schema changed
> [protocol] Add adminOperationProtocolVersion into proto schema AdminTopicMetadata

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
Based on the prod experiment, the SSD being used is not performing well when enabling parallel processing for AA/WC workload as the database lookup concurrency will be roughly same as the concurrency of parallel processing and we saw a higher lookup latency with high cpu wait.
This PR introduces a separated thread pool for ingestion database lookup (value and RMD) and the concurrency can be controlled separately from the parallel processing concurrency, and based on a canary test, a lower concurrency of DB lookup can reduce cpu wait while delivering a slightly better overall throughput.
New Config:
server.aa.wc.ingestion.storage.lookup.thread.pool.size: default 4
CI
> [server] Allocated a dedicated thread pool for ingestion DB lookup

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VersionSwapDataChangeListener.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/rmd/RmdUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/rmd/TestRmdUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/views/ChangeCaptureView.java
- internal/venice-common/src/main/java/com/linkedin/venice/views/MaterializedView.java
- internal/venice-common/src/main/java/com/linkedin/venice/views/VeniceView.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
[tests incoming]
These changes make it so that the venice after image consumer is able to now consume view topics. View topics internally very much resemble version topics, which the after image consumer understands today.  So the logic is largely the same.  The only difference we add here is that we now have to consult store repositories which are view aware, and we have to chnage how we maintain local highwatermark information.  Highwatermarks are meant to be compared on RT partitions, and new view types map 1:N and N:N RT partitions to view partitions.  This means we need to add an additional dimensionality to highwatermark filtering where instead of keeping a single map of topic partitions to offsets, but a map of topic partitions to maps of RT partitions to highwatermarks.
There's …
> [changelog] Make changes for venice view consumption

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/AbstractStorageEngineTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/ReplicationMeadataRocksDBStoragePartitionCFTest.java
- docker/venice-server/single-dc-configs/server.properties
- integrations/venice-duckdb/src/integrationTest/java/com/linkedin/venice/endToEnd/DuckDBDaVinciRecordTransformerIntegrationTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/ingestion/IsolatedIngestionServerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/ActiveActiveReplicationForHybridTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientDiskFullTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientMemoryLimitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClusterAgnosticTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciComputeTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatchReportIncrementalPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMaterializedViewEndToEnd.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientDaVinciClientCompatTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/DaVinciTestContext.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestBlobDiscovery.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
If operator deploys config with exceeds system resource limits, it makes the cluster into inoperable state and finally destroys the cluster. This PR fails rolling out such config for blockcache.
GHCI
> [server] Validate block-cache config against system memory

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
There exists a deadlocking race condition when a version swap happens. The version swap data change listener locks itself and then proceeds with the version swap on the consumer.  However, other function calls would also call refresh() on the metadata repository.  This in turn would trigger more callbacks on the data change listener.  In some scenarios, this can cause deadlocking.
This change makes sure that we no longer leverage manual refreshes and instead let the whole process get driven by the scheduled metadata refresh.  This also makes the refresh time configurable, and seems to speed up tests (yay!) as there were frequent retries on consuming events as we had to wait for the version swap to happen internally before we could consume the events we expected.
Resolves #XXX
> [changelog] Fix metadata refresh deadlock scenario

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/AdminTopicMetadataResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestAdminToolEndToEnd.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/admin/InMemoryAdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/AdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkAdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminTopicMetadataRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ClusterAdminOpsRequestHandler.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdminWithAcl.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkAdminTopicMetadataAccessor.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/AdminTopicMetadataRoutesTest.java
- services/venice-controller/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- Add admin operation version into ZK as a config and allow admin-tool to update the version. 
We will introduce a new field in adminTopicMetadata in ZK at cluster-level to store the admin operation version to serialize/deserialize the message.
- Add HTTP API for admin-tool to set the version.
Please take a look at the design doc [here](https://docs.google.com/document/d/1JrLeuRzgW3VrYzWf844P8geD1vC1CZol6QCWDrD2pX0/edit?tab=t.0#heading=h.fut1ik6kdppl). This PR is the first step to remove protocol upgrade deployment order. The expectation is that, with the remote protocol version at cluster-level, the deserializer will use the version, which the writer used to serialize AdminOperation, to deserialize the message. We will fail fast if necessary if the schema versions mismatch.
added UTs and …
> [admin-tool][controller] Add new config into ZK and allow admin-tool to update the config

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestSeparateRealtimeTopicIngestion.java
Produce heartbeat to separate RT topic at the same time as producing to RT.  
This is needed in the edge case where if the rewind time is shorter than the  
previous separate RT write, there will be no data to replay in separate RT,  
and the ready-to-serve check will never pass because no offset has been  
persisted for the separate RT region.  
Add test in integration test. Without this patch, due to short rewind time in test setup, it will fail complete new push.
> [server] Produce heartbeat to separate RT topic

- build.gradle
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
Logs are added before a single-get request is sent, and every potential routes of response on the client side.
Hot fix release only
> [thin-client] Added debug logging for thin client single-get

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/grpc/server/ClusterAdminOpsGrpcServiceImpl.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminTopicMetadataRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ClusterAdminOpsRequestHandler.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRequestParamValidator.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/grpc/server/ClusterAdminOpsGrpcServiceImplTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/AdminTopicMetadataRoutesTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/ClusterAdminOpsRequestHandlerTest.java
Within #1418, we have added the HTTP endpoint for --update-admin-operation-protocol-version in admin-tool to update admin operation protocol version, and we would do the same for gRPC endpoint.
CI
> [admin-tool] Add gRPC endpoint for updateAdminOperationProtocolVersion

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
If the empty push of system store fails, the current code retries another empty push. We should not throw exception to block the admin channel on such cases.
GHCI
> [controller] Do not throw exception on retrying empty push

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
A simple fix for Kafka consumer ID generation.
Added the pool type so that different pool's consumer won't share same client ID.
This is helpful when debugging consumption with JMX.
Added a new unit test
> [server] Add pool type information to Kafka consumer client ID

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferUtil.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/NettyP2PBlobTransferManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/NettyFileTransferClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestNettyP2PBlobTransferManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/blobtransfer/DaVinciBlobFinder.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
During testing on the dark hosts, we observed a few issues:
1. Previously, the per-partition bootstrap process worked as follows: it finds peers (e.g., 1500+ peers) and attempts to connect to each one. If the connection is successful, it sends the bootstrap request; if the connection fails, it moves on to the next candidate host. 
When there are many partitions, such as 200, this results in 200 * 1500 connection attempts. This process is unnecessarily time-consuming (waiting time = reject response time * 200 * 1500). Some partitions share the same peer-finding results, leading to redundant connection attempts to unreachable hosts. To address this, this PR introduces two map (a connectable host map and an unconnectable host map) to avoid redundant reconnections. The connectivity status …
> [dvc][server] verifying discovered host connectivity before initiating blob transfer request

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
Introduced `beginningPosition` and `endPosition(s)` methods in `PubSubConsumerAdapter`  
to fetch positions (PubSubPosition` objects). These replace `beginningOffset` and `endOffset(s)`,  
which previously returned numeric offsets.  
CI
> [server][dvc][vpj][controller] Add beginningPosition and endPosition(s) as replacements for beginningOffset and endOffset(s)

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
Introduced new default methods `getPositionByTimestamp` in `PubSubConsumerAdapter`  
to fetch offsets based on timestamps, returning a `PubSubPosition` object.  
This replaces the `offsetForTime` API, which previously returned a numeric offset.  
UT/CI
> [server][dvc][vpj][controller] Add getPositionByTimestamp as a replacement for offsetForTime

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
In Non-Aggregate mode, we reserve special keyword for upstream offset map. During resubscribe as leader action, current code does not look for correct key in the map, and resubscribe to the beginning of the RT topic during pool jump. This will result in a spike in leader HB delay, and a lot of duplicate messages (skipped).
This PR fixes it by using the correct key for upstream offset based on SIT mode.
Added new unit test and integration test to cover this fix.
> [server] Use correct offset when non-agg leader is resubscribing for workload change action

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VersionSwapDataChangeListener.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/rmd/RmdUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/rmd/TestRmdUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
A few fixes that include:
**RMDUtils.hasOffsetAdvanced**: This method did not handle correctly some cases where the offset vectors dimensionality didn't line up 
**VeniceAfterImageConsumer**: Version swap could get stuck if the store repo for in the internal consumer and external consumer were out of sync. This change adds a new method where the outer consumer can instruct the inner consumer directly which version it wants to seek on.
**Heartbeats in CDC**: There was it seemed a forgotten and not so clever lambda attempt to record the timestamp.  This did some unfortunate math and failed to perform a System.currentTimeMillis - timestamp, which in turn recorded a very large value. This fixes that and it now reports the lag correctly.
Resolves #XXX
> [changelog][client] Some clean up and bug fixes in CDC

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactoryTest.java
This is to enable cases where we need to be able to consume different views for different stores.
Resolves #XXX
> [changelog][client] Add viewname to changelog client factory

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/schema/merge/SortBasedCollectionFieldOpHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/helper/MapCollectionMergeTest.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/ttl/VeniceRmdTTLFilter.java
Prior to this, the FieldOpHandler was assuming an empty collection should be the result of clearing a field which is of a collection type.  However, this is contrary to the behavior of other types which instead set the field value to the default value specified in the schema.  This change normalizes that behavior.
Additionally, tweaked TTL repush to provide the incoming colo id as -1 so that should timestamp ties occurr, the TTL repush insert loses out to what's in the store.  This is basically a tweak of if the timestamp in ttl repush should be inclusive or not.  Setting to -1 seems to make this behavior consistent regardless of what colo this comes from (where previously it's possible for a particular colo to be zero indexed).
This will change how empty collections are treated by TTL …
> [server][vpj] Alter collection field delete to use schema defaults

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/AbstractStore.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushStatusCollectorTest.java
The current dvc heartbeat is set from checking if there is a dvc push status and if the status is `NOT_CREATED` This, however, is inaccurate because the status is set to `NOT_STARTED` when there is no status found  if we're under the num of polling retry attempts. We should, instead, check if `daVinciStatus.isNoDaVinciStatusReport` returns false before marking if there is a heartbeat reported and mark it as false otherwise if we've exceeded the dvc status retry attempts
Other minor changes included:
* Gate dvc heartbeat check behind controller config `skip.deferred.version.swap.for.dvc.enabled`
* Do not set target regions for stores with a dvc heartbeat reported if `skip.deferred.version.swap.for.dvc.enabled` is enabled
* Check version target region config instead of store target region …
> [controller] Fix dvc heartbeat value in store and version config

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- services/venice-router/src/main/java/com/linkedin/venice/router/InFlightRequestStat.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/AggRouterHttpRequestStats.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
- services/venice-router/src/test/java/com/linkedin/venice/router/RouteHttpRequestStatsTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/stats/AggRouterHttpRequestStatsTest.java
- services/venice-router/src/test/java/com/linkedin/venice/router/stats/RouterHttpRequestStatsTest.java
Fix: Properly Track In-Flight Requests During Router Shutdown
When the router is shutting down, it checks for in-flight requests to ensure they are properly drained — otherwise, clients may encounter errors.
Currently, this uses a Rate sensor to increment and decrement the request count. However, calling record(-1) on a Rate sensor does not actually decrease the sensor’s rate value.  This can lead to incorrect tracking of in-flight requests and potentially leave requests unaccounted for during shutdown. 
This PR addresses that behavior to ensure request counts are accurately managed and clients don’t see unexpected errors during router shutdown by replacing the `Rate` with `Gauge` stat.
CI tests
> [router] Fix in-flight request check in router shutdown

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatStatReporter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDumpIngestionContext.java
Separate HB metrics should only be applied to leader, not for follower. This will reduce unnecessary metric count.
New Unit Test.
> [server] Do not register separate RT region heartbeat metrics for follower

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
It's been reported that since patching a stricter checkpoint tracking on afterimageconsumer we've been filtering too many messages.
this doesn't effect the correctness of the consumer, but it does mean consumers will get played back more events then maybe strictly necessary.  However, as it stands this is causing some production issues, so this change just reverts that tweak back to what it was doing originally.
Resolves #XXX
> [changelog][client] Partial rollback of checkpoint maintenance

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
Return value from `getTopicPartitionEndOffSet` used to indicate the status of the invalid/non-existent topic vs valid LOWEST_OFFSET return value. But in PR https://github.com/linkedin/venice/pull/1232 that assumption was violated. This caused some partitions to think it has caught up even when it has not due to some transient issues. This PR fixes that.
GHCI
> [server][da-vinci-client] Return proper error code from getTopicPartitionEndOffSet

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AdaptiveThrottlerSignalService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AdaptiveThrottlingServiceStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/config/VeniceServerConfigTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AdaptiveThrottlerSingalServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottlerTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/throttle/EventThrottler.java
This PR involve 2 major changes:
1. Having a new `AdaptiveThrottlingServiceStats` class to track the current throttling limit for a specific adaptive consumer pool added to `AdaptiveThrottlerSignalService`, this will help our monitoring for this feature. 
2. Making previous hardcoded throttling factors for each pool easy to configure, using a comma spearated string in the configuration file to indicate list of factors and # of factors.  We should have 1.0 to be added in to the config string, otherwise we will not have base throttle limit.  Configs added: 
`SERVER_THROTTLER_FACTORS_FOR_CURRENT_VERSION_AA_WC_LEADER`
`SERVER_THROTTLER_FACTORS_FOR_CURRENT_VERSION_NON_AA_WC_LEADER`
`SERVER_THROTTLER_FACTORS_FOR_CURRENT_VERSION_SEPARATE_RT_LEADER` …
> [server] Adding metric of pool current throttling limit and make factors easy to configure.

- integrations/venice-samza/build.gradle
- integrations/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
- integrations/venice-samza/src/test/java/com/linkedin/venice/samza/VeniceSystemProducerTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/BoundedHashMap.java
Use a thread-safe bounded cache for schema parsing
CI
> [venice-samza] Use a thread-safe bounded cache for schema parsing

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfig.java
When serializer classes were specified as strings in the producer configuration, Kafka attempted  
to load them using `Thread.currentThread().getContextClassLoader()`, which led to  
ClassNotFoundException issues, particularly in JDK 11 environments. To address this, the producer  
adapter now explicitly loads serializer classes, ensuring they are correctly resolved regardless of  
the class loader context. This change improves reliability and prevents unexpected failures due to  
class loading inconsistencies.   
CI
> [server][vpj][controller] Fix ClassNotFoundException in ApacheKafkaProducer when serializers are passed as strings

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
Do not record heartbeat lag for sep RT region if it is not enabled in version config
changed unit test
> [server] Do not record heartbeat lag for sep RT region if it is not enabled in version config

- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerConfigTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestServerStorePropertiesEndpoint.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
This test verifies that the key and value serializer and deserializer configurations for the Kafka 
clients are correctly set as `Class` objects rather than string class names. It helps catch  
unintended modifications that could lead to serialization issues in specific environments,   
even if tests pass in a controlled CI environment. A failure indicates a misconfiguration that   
could cause incompatibilities due to class loading behavior differences across JVMs.  
UT
> [test] Add test to ensure Kafka serializer and deserializer configs remain consistent

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/IngestionThrottler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/VeniceAdaptiveIngestionThrottlerTest.java
For dynamic throttling, during limiting signals, such as high read latency or heartbeat lag, step down should be faster than step up to prevent further breach of SLA and quicker recovery. This PR also adds throttler for leader pool type for AAWC ingestion (both non-current/current versions).
GHCI
> [server]  Adjust dynamic throttler limiting at faster rate

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/AvroSupersetSchemaUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/TestAvroSupersetSchemaUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/resources/UserV1.avsc
- internal/venice-test-common/src/integrationTest/resources/UserV2.avsc
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
- internal/venice-test-common/src/main/resources/valueSchema/UserWithNestedRecord.avsc
- internal/venice-test-common/src/main/resources/valueSchema/UserWithNestedRecordAndDefault.avsc
This issue was detected via an legacy check in Active/Active Partial Update code that resulted in ingestion error:
1. User created store with schema v1(no default), v2(has default)
2. User put data with old value schema. 
3. User enabled and disabled AAWC, but user continue to put data with new value schema (or doesn't matter new->old, as long as old value and new value is using different schema id) 
4. When the logic checks incoming write, since it has field level RMD already, it will go to AAWC path to check and there we need to resolve the superset schema and there it will check if superset(v1, v2) is v1's superset schema, and superset(v2,v1) is v2's superset schema. 
In current implementation, new schema's default will always overwrite old schema's, but if new schema does not have …
> [server][controller] Superset schema generation should carry default if new value schema does not have default value

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/RegionNameUtilTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/ControlMessageDumper.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/DumpAdminMessages.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/RecoverStoreMetadata.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/input/kafka/KafkaInputRecordReader.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/ImmutablePubSubMessage.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/ApacheKafkaOffsetPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/DefaultPubSubMessage.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/ApacheKafkaOffsetPositionTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/api/PubSubMessageDeserializerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/ChunkingTestUtils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/PubSubHelper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
Previously, DefaultPubSubMessage was a marker interface extending PubSubMessage without  
defining any explicit methods. This change introduces explicit getter methods for key,  
value, and position, ensuring a consistent API for retrieving message components.  
- Added `getKey()`, `getValue()`, and `getPosition()` to expose KafkaKey, KafkaMessageEnvelope,  
and PubSubPosition directly.  
- Improves clarity and enforceability of message structure in pub-sub implementations.  
CI
> [server][controller][dvc][vpj][cc] Extend DefaultPubSubMessage with explicitly defined getter methods  

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/StoreBackend.java
Da Vinci client throws a lot of exception during shutdown due to the fact that it is unsubscribing to store repo while doing other checkpointing in async way. They will throw exception when store is not found from the repo.
There are two ways to fix it: (1) Just don't unsubscribe it from store repository, as the subscription is fixed during client life cycle and there is no harm to keep the existing subscription during shutdown (2) Make all the shutdown work first and then perform unsubscribe, which will have more changes and potentially slow down. This PR goes with (1) as it is simpler and cleaner to achieve.
Existing test
> [dvc] Do not unsubscribe store from store repository during Da Vinci shutdown

- internal/venice-client-common/src/main/java/com/linkedin/venice/schema/rmd/RmdUtils.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/schema/rmd/TestRmdUtils.java
This allows for extracting the latest timestamp of all operations enacted on a record given some RMD
Resolves #XXX
> [common] Add getLastUpdateTimestamp to RmdUtils

- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreType.java
- internal/venice-common/src/test/java/com/linkedin/venice/common/TestVeniceSystemStoreType.java
CPU profiles for venice-server showed that approximately 5% of execution time was spent  
in VeniceSystemStoreType::getSystemStoreType(). This change improves performance by  
introducing a cache to store computed store types for quick retrieval, eliminating redundant  
iterations over all system store types in repeated lookups.  
UT
> [server][controller][dvc] Cache VeniceSystemStoreType for faster lookup

- internal/venice-common/src/main/resources/avro/StorePropertiesPayloadRecord/v1/StorePropertiesPayloadRecord.avsc
Schema to by used in https://github.com/linkedin/venice/pull/1596
Schema is not used in code path.
> add new store properties schema to replace old

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TopicMessageFinderTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/PartitionerConfigImpl.java
This PR introduces the `--get-partition-id` command in `AdminTool`, allowing users to compute  
the partition ID for a given key based on store settings. The implementation includes the  
`findPartitionIdForKey` method in `TopicMessageFinder`, which retrieves store metadata,  
applies partitioner configurations, and determines the partition ID.  
This pull request introduces a new feature to the `venice-admin-tool` for retrieving partition IDs for keys, along with some refactoring and additional test coverage. The most important changes include the addition of the `GET_PARTITION_ID` command, the implementation of the `findPartitionIdForKey` method, and the creation of new test cases to ensure the functionality works as expected.
* …
> [admin-tool] Add new command to compute partition id for a given key using store settings

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/ExecutionStatusWithDetails.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/ExecutionStatusWithDetailsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestControllerGrpcEndpoints.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMultiDataCenterAdminOperations.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
This PR includes logging improvement in the `PushStatusCollector` class and fixes flaky tests  
in TestMultiDataCenterAdminOperations and StoreIngestionTaskTest
* `internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMultiDataCenterAdminOperations.java`: 
- Increased the `NUMBER_OF_CLUSTERS` to 2 and ensured `venice-cluster1` is not used for testing failed admin messages.
- Added `alwaysRun = true` to the `@BeforeClass` and `@AfterClass` annotations to ensure setup and cleanup methods always run. [[1]](diffhunk://#diff-cde9da822dbd8ce1d89e314bb66a504ef2b1118dee32264c0220a87a2d510724L65-R67) [[2]](diffhunk://#diff-cde9da822dbd8ce1d89e314bb66a504ef2b1118dee32264c0220a87a2d510724L105-R107)
- Removed outdated comments about a known bug in the controller and …
> [controller][test] Log server status and dvc status during status polling and fix flaky tests

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestVenicePushJobCheckpoints.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestIncrementalPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/JobRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/JobRoutesTest.java
For a target region push with deferred swap, we only poll for the job status of the target regions. This, however, is incorrect because we ingest data in all regions concurrently so the push completion should mean that >50% of all regions are in terminal status. Once the push is in terminal status, we need to truncate the kafka topic so that future pushes can start, but for target region push with deferred swap, this isn't the case currently. We only truncate the kafka topic once we roll forward in the remaining non target regions. This is also incorrect because when a push is marked as complete (when >50% of the regions are in terminal status), we should be able to start another push regardless if the version is swapped in all regions
Changes included for a target region push w/ deferred …
> [vpj][controller] Fix push job status for target region push w/ deferred swap

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
Currently, in updateStore, targetSwapRegions is always set to "" if it is not present. The type of it is a nullable string so it's default value is expected to be null, not an an empty string, and this fails with the new semantic usage detector. This pr changes it to not set the targetSwapRegion value if it is not present and default to null instead
Updated unit test
> [controller] Set target regions to null in update store if not present

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
In production, we found that servers had been querying PubSub offsets from an completely unintended region in some cases. This is pretty gnarly and can lead to data-loss.
We found a concurrency issue in `KafkaStoreIngestionService` where the shared server config object would be replaced by temporarily created configs for different regions. The expectation of this code was to only create this object for local use.
> [server] Fix multi-threading bug in shared multi-region PubSub configs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/DivSnapshot.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/KafkaDataIntegrityValidator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/Segment.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ComplexVeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/validation/SegmentTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/VeniceWriterWithNewerProtocol.java
When the `isGlobalRtDivEnabled()` feature flag is enabled, the drainer will no longer sync the VT DIV to the `OffsetRecord` in the StorageEngine. In the `ConsumptionTask` stage, leader will produce a (Global) RT DIV to VT to replicate to the followers. On the callback, it will enqueue a `DivSnapshot` (VT DIV + RT DIV) to the `Drainer`. `Drainer` will put the RT DIV (possibly chunked) in the storage engine, and sync the `OffsetRecord` with VT DIV. Note that the `GlobalRtDivState` will be compressed because it's being sent to VT.
The Drainer component will be handled in a future PR.
Note that the Global RT DIV is on a per-broker / region basis. `PartitionTracker#rtSegments` is a map of `Broker URL -> Producer GUID -> Segment` whereas the VT version is only `Producer GUID -> Segment`. There …
> [server] Global RT DIV: Leader

- build.gradle
- services/venice-controller/src/main/resources/avro/AdminOperation/v85/AdminOperation.avsc
Adding a field for `largestUsedRTVersionNumber` in `addVersion` and `updateStore` operations.
- It is added in `addVersion` so that parent controller will pass this value to child controllers and we do not end up different child controllers having different value for this field.
- It is added in `updateStore` for two reasons - a) write test case `testOldStoresWithHybridStoreVersioning` of future PR https://github.com/linkedin/venice/pull/1555/  , I am verifying the effect of that work on existing stores that do not have `largestUsedRTVersionNumber` value (backward compatibility testing). So I have to update this value from 1 to 0 to make a test store act like an existing store in prod. b) disaster recovery , if we create a wrong RT name at any component of Venice, we can update …
> [compat] [controller] add largestUsedRTVersionNumber to updateStore and addVersion admin commands

- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/handlers/ConnectionControlHandler.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/handlers/ConnectionHandleMode.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/handlers/ConnectionLimitHandler.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/ssl/SslInitializer.java
- internal/alpini/netty4/alpini-netty4-base/src/test/java/com/linkedin/alpini/netty4/ssl/TestSslInitializer.java
- internal/alpini/router/alpini-router-impl/src/main/java/com/linkedin/alpini/router/impl/Router.java
- internal/alpini/router/alpini-router-impl/src/main/java/com/linkedin/alpini/router/impl/netty4/Router4.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/ThreadPoolStats.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/ThreadPoolStatsTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/MockVeniceRouterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestStreaming.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterSslVerificationHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/SecurityStats.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ListenerService.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/HttpChannelInitializerTest.java
Previously a separate thread pool is only used for DNS resolution before SSL handshakes; it turns out that
we can assign a thread pool for SSL handshake as well. If both features are enabled, the execution order in
the Netty pipeline would be:
Decode, verify SSL is enabled -> Run DNS resolution asynchronously -> Retry DNS resolution within a budget
and if connection is active -> Regardless if resolution is successful, start SSL handshake if connection is still
active by swapping current handler to SSL handler -> SSL handshake -> log after handshake completes
Commends with "Step" prefix are added to improve readability of alpini SslInitializer.
Configs updates:
1. Changed "router.resolve.before.ssl" to "router.resolve.threads": 0 means DNS resolution before SSL is disabled; positive number …
> [router] Enable SSL handshake offload to a thread pool and DNS resolve through a thread pool at the same time

- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Current Version is needed to determine the RT topic name, so extract the real time topic names before it is unset in `deleteStore`
Resolves #XXX
> [controller] extract real time topic names, before store versions are deleted

- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/handlers/ConnectionControlHandler.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/handlers/ConnectionLimitHandler.java
- internal/alpini/router/alpini-router-impl/src/main/java/com/linkedin/alpini/router/impl/Router.java
- internal/alpini/router/alpini-router-impl/src/main/java/com/linkedin/alpini/router/impl/netty4/Router4.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/LongAdderRateGauge.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestStreaming.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/SecurityStats.java
Missing a metric for rejected connection, which should be easier for
setting up alerts.
A rate metric is added when connections are rejected due to breaching limit.
Metric name: rejected_connection_count
> [router] Added metric for rejected connection when limit is breached

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/RetryUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
In method `getTopicPartitionEndOffSet` we have retries builtin. But the method it calls has another layer of retries leading to retry storm. 
This PR removes the lower layer of retries in getTopicPartitionEndOffSet using `getLatestOffsetNoRetry`.
> [server] Remote extra layer of retry on getLatestOffsetWithRetriesAsync

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/DefaultInputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/InputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/KafkaInputDataInfoProvider.java
In a previous PR, we made the `pushJobZstdConfig` field private, and it broke an internal consumer using this field. Ideally, we should not be relying on member variables to open access for some custom implementations.
This change makes the `initZstdConfig` function return the `pushJobZstdConfig` object so the caller has a handle on the object.
This change is backwards compatible because a `void` function now returns an object. Since it was previously `void`, it is guaranteed that no one is expecting any value to be returned.
> [vpj] Return Zstd configs after initialization

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestAdminOperationWithPreviousVersion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMultiDataCenterAdminOperations.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/protocol/serializer/AdminOperationSerializer.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/protocol/admin/AdminOperationSerializerTest.java
Initial start: Producers (parent controllers) need to generate AdminConsumptionTask to put into the admin topic queue. Messages will be consumed by consumers (parent controllers + child controllers). If producers produce the message that consumers cannot read, we are having troubles.
Current solution: Child controllers when upgraded to the newer version, will need to be completed BEFORE parent controllers. (Since parent controllers is currently using their latest version code, and child controller don't have the schema for latest version yet).
New solution:
We put a version number in parents' ZK metadata, specifying the version that producers will use (let's called it X)
Producer: OK, I will always use version X to produce message.
In deployment, parent and child controllers can freely …
> [controller] Apply SemanticDetector inside AdminOperationSerializer to detect bad usage for new semantics

- internal/venice-client-common/src/main/java/com/linkedin/venice/exceptions/VeniceProtocolException.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/protocol/serializer/AdminOperationSerializer.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/protocol/admin/AdminOperationSerializerTest.java
[controller] Add leader discovery for parent helix admin
- Currently, `updateAdminOperationProtocolVersion` API will not fail if the request is sent to non-leader, which can cause the racing issue if Helix has a state transfer in the middle of the request.
- `updateAdminOperationProtocolVersion` for child controller is not necessary since we never try to consume the config from child controller.
- Add leader discovery for parent helix admin for updateAdminOperationProtocolVersion API to allow us to fail if the current parent controller is not leader.
- Removing support for `updateAdminOperationProtocolVersion` in child controller
- Convert all execeptions in AdminOperationSerializer to `VeniceProtocolException`
> [controller] Add leader discovery for parent helix admin for updateAdminOperationProtocolVersion API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
It seems that our pubsub consumer adapter doesn't even tolerate concurrent calls to poll, so removing locking on this function is pointless. 
So we add back an exclusive lock on the poll and in order to reduce the pause time on the version swap seek we shrink the scope of the read lock on version swap to just the short part.
> [changelog] Add back synchronization around poll()

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/NativeMetadataRepository.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/repository/RequestBasedMetaRepository.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/repository/RequestBasedMetaRepositoryTest.java
DVC NativeMetadataRepository uses a icProvider to wrap store metadata requests to enable request contexting. This request wrapper was unused in RequestBasedMetaRepository. 
Additionally, executing d2 discovery for every invocation is wasteful.
Wrap app server requests for metadata with the icProvider wrapper.
Cache storename to service name in map, only trigger rediscovery on exceptions.
> [dvc] wrap server metadata request with ic provider and add d2 cache

- internal/venice-test-common/build.gradle
Move some integration tests to bucket 1440
- Move lengthy test to some other buckets to reduce CI time.
- Moving below tests to bucket 1440
```
"com.linkedin.venice.endToEnd.TestAdminOperationWithPreviousVersion",
"com.linkedin.venice.endToEnd.TestMaterializedViewEndToEnd",
"com.linkedin.venice.endToEnd.TestDeferredVersionSwap"
```
> [test] Move some integration tests to bucket 1440

- internal/venice-common/src/main/resources/avro/PartitionState/v16/PartitionState.avsc
`testStringMapInPartitionState()` in `TestAvroSchema` was testing serializing `PartitionState` with the current version and deserializing with `v10`. For some reason, it doesn't work if the fields are added before `upstreamOffsetMap`. Since `v10`, "java-key-class" and "avro.java.string" were added to upstreamOffsetMap:
```
{
"name": "upstreamOffsetMap",
"type": {
"type": "map",
"values": "long",
"java-key-class": "java.lang.String",
"avro.java.string": "String"
},
"doc": "A map of upstream Kafka bootstrap server url -> the last Kafka offset consumed from upstream topic.",
"default": {}
}
````
Move the new fields after `upstreamOffsetMap`.
> [protocol] PartitionState/v16 Fix

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/VersionStatus.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
**1. Davinci heartbeat check in deferred version swap service + parent admin**
Currently, in the deferred version swap service, we check for a dvc heartbeat for only one target region before skipping the store, but a dvc client can only be present in some regions and not all regions. To accurately skip a dvc store, we will need to check for a dvc heartbeat in *all* regions instead.
**2. Version swap logic in deferred version swap service**
Currently, the version swaps happen in the following cases:
1. Version status is `PUSHED` (this is set upon successful push in *all* regions)
2. Target region is complete in > 50% of the target regions
3. Non target regions have all reached terminal status
4. Non target regions is complete in > 50% of non target regions
And it fails to account for cases …
> [controller] Check dvc heartbeat in all regions & update version swap logic for deferred swap service

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/exceptions/VeniceInvalidInputException.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/spark/datawriter/jobs/AbstractDataWriterSparkJobTest.java
In Spark ComputeJob, some cases of `DATASET_CHANGED` were not getting tracked correctly, and were instead getting tracked as `START_DATA_WRITER_JOB`.
This was because of an incorrect assumption that Spark jobs would get executed only when the final action stage is encountered. But in practice, the spark stages were starting to get executed when the `repartitionAndSortWithinPartitions` call was getting invoked. This was previously done in the `configure` phase, and exceptions thrown in this stage are not handled as errors during the execution of the compute job.
This commit moves all Spark execution logic inside the `runComputeJob` method instead.
In addition to this, this commit also moves all other input validation inside the same function too so that they can be reported with valid …
> [vpj] Make Spark job exceptions be thrown during execution instead of configuration

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/D2Stats.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
This PR adds metrics to track D2 store discovery requests in Venice, specifically for MetaDataHandler’s `handleD2ServiceLookup` endpoint.
As discussed with @xunyin8, D2 store discovery calls are part of the initialization step for DVC and CC users so while a user may not be exercising the read/write path, their code could still be initializing the DVC and CC, which includes the D2 Store Discovery step. As part of the process before deleting a store (not detecting if a store is dead), we need to track the store discovery endpoint to ensure there were no inquiries against the store, otherwise it's still in use and can't be deleted yet.
- Introduced a new `D2Stats` class to track:
- `storeDiscoverySuccessCount`
- `storeDiscoveryFailureCount`
- Injected `MetricsRepository` into …
> Adding Store Discovery Metrics for CC/DVC users access history

- internal/venice-common/src/main/java/com/linkedin/venice/meta/Version.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestVersion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestHybridStoreRepartitioningWithMultiDataCenter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
PR https://github.com/linkedin/venice/pull/1555/ made RT topics versioned, i.e. they will be named like "storeName_v1_rt" "storeName_v2_rt". This has a problem; given an RT name, we cannot deterministically tell the store name.
e.g. if the RT name is "myStore_v1_rt", the store name, could be "myStore" (if the store is following RT versioning), or it could also be "myStore_v1" (if the store is not following the RT versioning).
The root of the problem is the special keyword "v1" in the end of the store name. 
Special keyword "rt" in the end of the store name, also creates problem.  If we are provided a kafka topic name "store_rt_v1", we cannot tell if it is a VT topic of `store_rt` or an RT topic of `store`
The solution is to move versions after the `_rt` not before it, so the versioned …
> [controller] change in naming convention of versioned RT topics

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/tehuti/MetricsUtils.java
The `assembled_record_size` metric is currently per-store, but it would be useful to have a global / total view, so we can easily see that there's something awry within the cluster. Using `consolidate` on this per-server metric should give us the per-cluster level view.
Adding per-server / total metric for `assembled_record_size`.
> [server] Per-Server Assembled Record Size Metric

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/BlobTransferUtils.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/BlobSnapshotManagerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/BlobTransferUtilsTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestNettyP2PBlobTransferManager.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/blobtransfer/TestP2PFileTransferServerHandler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/DefaultIngestionBackendTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/BlobP2PTransferAmongServersTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatchForRocksDB.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
Before initiating bootstrap from blob transfer, ensure the RocksDB folder is cleaned up. Otherwise, both existing old blobs and newly transferred blobs may coexist. During blob transfer, if a transferred file shares the same name as a pre-existing file, it will overwrite the old file. However, if the file names differ, particularly for MANIFEST files, both old and new blobs will persist, necessitating a cleanup of the entire partition's RocksDB folder.
Before clean up this partition folder, we need to make sure that the partition is closed and also clean up the offset. 
1. Clean up partition folder.
2. Close partition storage engine.
3. Clean partition offset. 
> [server][dvc] clean up partition folder and offset after decide to use blob transfer

- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/InstanceStatusDecider.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestInstanceStatusDecider.java
After a Store Migration, a Store's ZK Config may still have the old cluster's min active replica config and because a Store's ZK Config is something we're not trying to have be the SOT for MAR, there's a need to use Ideal State instead of ZK Store Config for Min Active Replicas. A Repush will fix the inconsistency of MAR in the Store's ZK Config but we should be looking at SOT to avoid the problem seen here
./gradlew build
> [controller] Using Ideal State instead-of ZK Store Config for Min Active Replicas

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatLagMonitorAction.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerParticipantModelFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
During migration dest cluster leader is not actually promoted to leader and is still replicating local VT. During this stage, we should not track leader lag as it is not valid. We should track follower lag and once this stage is lifted we can track leader lag. 
There are two ways to fix it:
1. Remove leader lag tracking when transition is paused and resumed it after
2. Just move the whole leader tracking when it is fully transitioned into leader
In this PR we change to (2), as follower will already been tracking leader replication lag, so when leader truly stuck during transition, follower lag will be going up and alarm.
Also, this PR fixes a small bug when calculating the max follower lag. It was using the leader map and changed to follower map. It is not used today so no current impact. …
> [server] Do not track leader lag in when STANDBY->LEADER is paused due to migration

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/controllerapi/ControllerResponse.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/controllerapi/RepushJobResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestAdminToolEndToEnd.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkServer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/logcompaction/CompactionManager.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/logcompaction/LogCompactionService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/logcompaction/TestCompactionManager.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoresRoutesTest.java
Need to send request to new repush store controller API from admin tool. This allows store repush jobs to be triggered adhoc.
add `repushStore()` command to venice-admin-tool
- `ControllerClient`
- `Command`
- `AdminTool`
- allows users to trigger repush job on store / using the `admin-tool` / with the args `--repush-store --url $CONTROLLER_URL --store $STORE_NAME`
> [repush][controller][admin-tool] Add admin tool command for repush store controller API

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/protocol/serializer/AdminOperationSerializer.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/protocol/admin/AdminOperationSerializerTest.java
[controller] Modify the error message to contain current schema version
- Modify the error message to contain more information .
```
Before: Field AdminOperation.payloadUnion.UpdateStore.separateRealTimeTopicEnabled: Boolean value true is not the default value false or false
After: Current schema version: 74. New semantic is being used. Field AdminOperation.payloadUnion.UpdateStore.separateRealTimeTopicEnabled: Boolean value true is not the default value false or false
```
> [controller] Modify the error message to contain current schema version

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
The quota update operation currently is not recorded if batch stores are unsubscribed after pushjob completed which leads to stale metric.
This PR fixed that issue by moving the recording quota before unsub opetation.
> [server] Move storage quota record before unsub operation

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/DefaultIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/DefaultIngestionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStoreRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreVersionInfo.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/ReadOnlyStoreRepositoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/StoreVersionInfoTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestTopicWiseSharedConsumerPoolResilience.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
The bug happens is:
When a leader transits into follower, we will first clear leader HB entry and initialize follower HB entry and then submit request to transition into follower to KafkaStoreIngestionService.
The problem is, in between, leader will need to drain all the consumed messages before turning into follower and start consuming VT, and in between if we see any leader HB message, it will be recorded into leader entry but then this will remain as stale leader heartbeat and get recorded. 
The fix is simple, just move the tracking change once we finished draining leader messages and update leader role in PartitionConsumptionState.
This PR also remove one of the big Pair usage in ReadOnlyStoreRepository#waitVersion. We should stop using Pair and use simple Java class to be less error …
> [server][misc] Move leader->follower heartbeat tracking action to after transition complete

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
1. When we check if a store has a dvc heartbeat and get the child store in `isDavinciStore`, the store can be null and we need to exit early to avoid a NPE
2. We currently do not update the `storePushCompletionTimes` cache and this causes unnecessary cycles in the service 
3. The `extraInfoUpdateTimestamp` in `OfflinePushStatusInfo` is not guaranteed to contain a value for every region. This causes a NPE when we try to cast a null into a long value in L112 in `didWaitTimeElapseInTargetRegions`
1. Add in an early exit in isDavinciStore to skip the rest of the checks if the store doesn't exist
2. Update `storePushCompletionTimes` cache with the completion times map if the wait time hasn't elapsed yet
3. Check if a region exists in the map before getting the value & casting it to a long
Both …
> [controller] Fix NPE in DeferredVersionSwapService

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/AdminOperationProtocolVersionControllerResponse.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixState.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/TestHelixState.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestAdminOperationVersionDetection.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/ControllerRoutesTest.java
[controller] Controller API to get all Admin Operation Version for leader+standby controllers given cluster name
We have introduced the new adminOperationProtocolVersion into the parent ZK at the cluster level, which is the SOT for all serialization. Additionally, we have implemented a new semantic detector that prevents message processing if it uses the new semantic.
Currently, after deployment, the on-call engineer must manually update the version pinning to the latest protocol version.
Proposal
To eliminate the manual task for on-call engineers, we propose automating the detection of the protocol version to use. The selected version should be the smallest protocol version among all consumers (child controllers + parent controllers).
Implementation Steps:
1. **(This PR)** Introduce a …
> [controller] Controller API to get all Admin Operation Version for leader+standby controllers given cluster name 

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
There was no public way for users to programmatically query which stores are considered "dead" by Venice.
This made it difficult to surface lifecycle decisions driven by ACL access logs and discovery mechanisms.
Additionally, there was no CLI toolchain integration for easily invoking or testing this logic in staging or production.
Introduced a new `GET_DEAD_STORES` endpoint in `ControllerRoute`, mapped it to the existing ACL-based evaluation logic.
Added a method `getDeadStores` to `ControllerClient` which wraps the request to the controller.
Implemented a matching CLI command in `AdminTool` that allows users to call this endpoint from the terminal using:
```
./venice-admin-tool.sh get-dead-stores -url <url> -cluster <cluster> [-store <store>] [-include_system_stores true]
```
This …
> [controller][admin-tool] Add support for get-dead-stores API and admin tool command

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/MaterializedViewWriter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriterTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/views/VeniceView.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/view/TestView.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/view/TestViewWriter.java
MaterializedViewWriter did not implement the close() method defined in VeniceView. This means when SIT's internalClose is called the VeniceWriter in MaterializedViewWriter will not be closed. This can cause stuck consumer because a consumer thread could be waiting for the last VT produce future in checkAndWaitForLastVTProduceFuture to ensure CMs that don't need to be produced to view(s) will not be produced to VT out of order. Without closing/flushing the view writer and potentially shortcircuit the lastVTProduceCallFuture the consumer thread could be waiting on a lastVTProduceCallFuture forever and here is one example how this could occur with the old code:
1. For each incoming record we get the lastVTProduceCallFuture to be part of a new future that is completed when the view writers …
> [server][common] close MaterializedViewWriter properly in LFSIT

- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReader.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReaderTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
DVC peer discovery involves calls to router _**pushStatusStoreReader.getPartitionStatus**_ for fetching instance information. Within method getPartitionStatus, it waits for a response using **_PushStatusValue pushStatusValue = client.get(pushStatusKey).get(60, TimeUnit.SECONDS)._**
However, if the same Netty thread does: (1) initiates the original blob discovery request, (2) subsequently calls getPartitionStatus, which blocks while waiting for a response, and (3) also handles incoming requests from the thin client, it becomes unable to process these incoming requests because it remains blocked, waiting for a response to its own initial request.
Add a new async getPartitionStatus and use it in peers finding. 
> [router][dvc] use async getPartitionStatus method in dvc peer finding

- .github/workflows/build-and-upload-archives-on-schedule.yml
Current releasing cadence is 2 times a week; each release contains multiple commits,
which makes it hard to investigate regressions and triage bugs.
Increasing releasing cadence to every workday at 8:30pm.
> [build] Increase releasing cadence from 2 times a week to daily

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/RmdSerDe.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/StringAnnotatedStoreSchemaCache.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/RmdSerDeTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/RetryUtils.java
RMD schemas are used to build the RMD deserializer objects. RMD schemas are retrieved and cached in memory by listening to the corresponding ZooKeeper node for any updates to the schemas. In this procedure, there could be delays in getting the most up-to-date schema updates. When it happened, the workflow to build the latest RMD deserializer object could fail and related StoreIngestionTask thread could terminate.
It is probably impossible to eliminate such delays and this change allows for retries in building the RMD deserializer object. The idea is to give more chances for the internal ZK listener to receive the schema updates even if the first several attempts might fail. However, we can't afford infinite retries as this is done in the shared consumer threads and it could impact other …
> [server] Allow retry for fetching RMD deserializer

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithIsolatedEnvironment.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeadStoreStatsPreFetchTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/HelixVeniceClusterResources.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerStateModel.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/DeadStoreStatsPreFetchTaskTest.java
There is a race condition where the `DeadStoreStatsPreFetchTask` begins execution before the controller has officially become the leader for a given cluster.
This results in exceptions such as:
`VeniceException: This controller:<host> is not the leader controller for cluster: <cluster>`
The issue occurs because `initClusterResources()` triggers the task during the STANDBY->LEADER transition, before `VeniceHelixAdmin` is ready.
Added a leadership check with a 60-second timeout to `DeadStoreStatsPreFetchTask.run()` to block pre-fetching until the controller becomes leader.
This ensures we don’t prematurely call `preFetchDeadStoreStats()` on a non-leader node.
Also updated `clearResources()` to call `stopDeadStoreStatsPreFetchTask()` **before** `clusterResources.clear()` to ensure the task …
> [controller] Fixing race condition in STANDBY->LEADER for Dead Store Stats

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFolloweStorageIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMultiDatacenterVenicePushJob.java
Before [the change](https://github.com/linkedin/venice/pull/1555) , for batch-only store, we always return false for `shouldCompressionData()` when leaderTopic is null or VT and **`realTimeTopic` would never be `null` even if the store is batch only**.
After the change, for batch-only store, since realTimeTopic is now null, `realTimeTopic != null` would break the if condition immediately, and then `!compressionStrategy.equals(CompressionStrategy.NO_OP)` would return true for a compression enabled store; as a result, we compress the compressed data in VT again.
```
protected boolean shouldCompressData(PartitionConsumptionState partitionConsumptionState) {
if (!isLeader(partitionConsumptionState)) {
return false; // Not leader, don't compress
}
PubSubTopic leaderTopic = …
```
> [vpj] [server] fix bug in SIT in deciding if compression is needed

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
It seems under certain scenarios the PubSub API will throw a null position.  In the previous code this wasn't really expected.
We can add protections to both scenarios where we can't find the EOP message (for whatever reason) and if we can't get a position for a heatbeat.
Also adding some other null checks
> [changelog][client] Add protection for null positions

- docs/user_guide/write_api/stream_processor.md
The Venice documentation page for Stream Processor under Write APIs contained incorrect GitHub links for VeniceSystemProducer and VeniceSystemFactory classes, pointing to non-existent locations.
Updated the links in stream_processor.md to link to the correct locations of these classes in the `integrations/venice-samza` directory instead of the incorrect `clients/venice-samza` directory.
> [doc] Fix links in stream processor user guide

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixInstanceConfigRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/HelixInstanceConfigRepositoryTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestRead.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestVeniceRouterConfig.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
Today, routers only support `zone` and `group` as the `FAULT_ZONE_TYPE` when the routing strategy is `HELIX_ASSISTED` (HAR). Assuming `FAULT_ZONE_TYPE` is set to `zone`, routers will look for a property with key `zone` in the Helix `DOMAIN` of all server instances to find a replica to route requests to.
When the `FAULT_ZONE_TYPE` changes (say to `group`), Helix will immediately start rebalancing replicas and the constraints we create for HAR are no longer valid. Currently, the value of `FAULT_ZONE_TYPE` that routers look for is configured through it's configs. To make routers use the updated `FAULT_ZONE_TYPE` (`group`), we need to update the configs of the routers and deploy them. This process is slow and there will be performance degradation when the value set in router configs does not …
> [router] Use Helix FAULT_ZONE_TYPE as the group for HAR routing

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
When a repush job is killed, an incorrect push status of `NOT_CREATED` is sometimes surfaced. This causes vpj to continue to poll for the job status for 24 hours until it times out as it never receives a terminal job status. This also makes it difficult to triage as we have to dig through the logs to find out if the job was killed due to another push being submitted vs actually failing due to falling out of the 24 hour sla
When a push job is killed, the version statuses are marked as `KILLED`. We can use this status to know if a job was killed even if the aggregate push status is not in a terminal state. This pr adds a check to `getOfflineJobStatus` to check for a `KILLED` version status and if it is `KILLED`, we will mark the push job as `ERROR` so vpj stops polling
Both reviewer and PR …
> [controller] Mark push status as ERROR for killed jobs

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/VeniceAdminStats.java
[controller] Add metric to catch the failed admin message serialization
Add stat metric to capture VeniceProtocolException in serializing admin operation message.
- Add stat metric to capture VeniceProtocolException in serializing admin operation message.
- Add error log line for debug purpose
> [controller] Add metric sensor to catch the failed admin message serialization

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceWithTopicWiseTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithSAwarePWiseAndBufferAfterLeaderTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithSAwarePWiseWithoutBufferAfterLeaderTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITWithTWiseAndBufferAfterLeaderTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestTopicWiseSharedConsumerPoolResilience.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartController.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
Also changed the default for this config from topic-wise to partition-wise, which is the setting we have been running in production for many years now.
Test changes:
- Marked all t-wise related tests as deprecated.
- Added some test permutations for the new strategy, store-aware p-wise, which was missing in some cases.
- Deflaked TestRestartController.
> [dvc][server] Deprecated topic-wise shared consumer strategy

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineFactory.java
Today we enforce system ram vs block-cache size check before server startup.  But for hosts with plain table (PT) format need to enforce this check which can cause server start up failure for PT enabled stores.
This PR fixed that.
> [server] Check PT format enable before enforcing rocksDB block cache size

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallbackTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
There was an inconsistency where the transient record cache (which is used for WC and AA ingestion) had different criteria for whether to write and read to it. We would not write to it when pre-EOP (which is the right behavior), but we would systematically read from it in the setChunkingInfo function of the LeaderProducerCallback, regardless of the EOP status.
This commit adds an extra PartitionConsumptionState parameter to the SIT::isTransientRecordBufferUsed function, and calls this function in more locations, thus eliminating duplicate conditions littered across the code.
Miscellaneous:
- Fixed the logger class name in the LeaderProducerCallback.
- Eliminated a few unused partitionId parameters in SIT functions.
> [dvc][server] Refactored Transient Record usage code

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreBufferService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubTopicRepository.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
Drainers are assigned by hashing the topic name and partition. Separate RT has a suffix of `_rt_sep` and RT has a suffix of `_rt`, meaning that they can be assigned to different drainers and thus run into concurrency issues.
Separate RT should be hashed and assigned drainers like RT.
Added new unit test `testGetDrainerIndexForConsumerRecordSeparateRt()`.
> [server] Separate RT Drainer Assignment

- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/VeniceProperties.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/VenicePropertiesTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/ConsumerIntegrationTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProducerAdapterITest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/admin/PubSubAdminAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerIntegrationTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
PubSub producers require access to the position type registry during construction. For  
pub-sub backends not defined in the Venice OSS repo, the registry contents may differ.  
Producers created inside the controller or server already receive the updated registry.  
However, ad-hoc producers previously used only the reserved registry. This change updates  
the logic to ensure ad-hoc producers also use the dynamic registry.  
> [controller][test] Use dynamic position type registry for ad-hoc producer construction 

- internal/venice-common/src/main/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReader.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushstatushelper/PushStatusStoreReaderTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/DaVinciUserApp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushStatusStoreTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
- services/venice-router/src/test/java/com/linkedin/venice/router/TestMetaDataHandler.java
As some Venice DVC clients transition to batch reporting, which reports push status at the version level, while metadata handlers in routers continue querying at the partition level to find blob transfer peers. This mismatch results in empty peer returns, causing blob transfer failures for stores using batch reporting.
This PR updates the router to query both partition and version levels for identifying completed DVC peers during push operations. It prioritizes querying the partition level first; if the response indicates errors or is empty, it then falls back to querying the version level.
unit test. 
integration test:
> 2025-04-30 10:50:32 - [] INFO [MetaDataHandler] [Venice-Store-Deserialization-t0] No partition instances found for store: …
> [router][dvc] dvc blob transfer query both version-level and partition-level push status from router

- internal/venice-common/src/main/java/com/linkedin/venice/common/VeniceSystemStoreUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/HelixSchemaAccessor.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/PartitionUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
In a system store creation code path, made use of default partition count rather than failing, in some scenario.
Miscellaneous:
- Reduced log message size in HelixSchemaAccessor, by printing only schema IDs and not full schema literals.
- Fixed string interpolation in VeniceParentHelixAdmin::initiateDataRecovery.
Reduced log volume, actually.
> [controller] System store init resiliency tweak

- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
No import line causing reference error. Fixing this to unblock all tests on main and PRs. ~Somehow the original code can checkin into the main without compile error...~ It is due to a bad merge resolve of GH for PR #1741
```
/home/runner/work/venice/venice/services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java:427: error: cannot find symbol
Mockito.reset(topicManager);
^
symbol:   variable Mockito
location: class com.linkedin.venice.controller.TestVeniceHelixAdmin
```
Add import line
> [controller] Fix symbol reference

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/counter/MRJobCounterHelper.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/datawriter/task/CounterBackedMapReduceDataWriterTaskTracker.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/datawriter/task/ReporterBackedMapReduceDataWriterTaskTracker.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractInputRecordProcessor.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/DataWriterTaskTracker.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/spark/datawriter/task/DataWriterAccumulators.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/spark/datawriter/task/SparkDataWriterTaskTracker.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/mapreduce/datawriter/map/TestVeniceAvroMapper.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/mapreduce/datawriter/reduce/TestVeniceReducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestBatch.java
Currently, the max record size enforcement is on the compressed size of the record. This causes some uncertainly since two record of the same uncompressed size may have different compressed sizes.
We would like to enforce the max record size pre-compression in the InputProcessor.
This enforcement will be gated using a VPJ config `venice.writer.enable.uncompressed.record.size.limit`
> [vpj] Enforce record size limit on batch pushes for uncompressed record sizes

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriterFactory.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/EndToEndKafkaWithSASLTest.java
Replaced all `record.getPosition()` calls with `record.getPosition().getNumericOffset()`  
in KafkaTopicDumper. Also switched a non-critical log in VeniceWriterFactory from  
`info` to `debug`. Updated `EndToEndKafkaWithSASLTest` to use `@AfterMethod`  
instead of `@AfterClass` for better resource cleanup.  
> 
> 
> ## AI Generated Summary of Changes
> This pull request introduces several changes across multiple files, primarily focusing on improving logging precision, modifying test cleanup behavior, and adjusting logging levels. Below is a categorized summary of the most important changes:
> 
> ### Logging Improvements:
> * Updated all instances of `record.getPosition()` to use `record.getPosition().getNumericOffset()` for more precise logging of Kafka offsets in …
> [admin-tool] Use numeric offset in Admin tool

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
When a store does a target region push with deferred swap, it sets the following version level configs: `versionSwapDeferred` and `targetSwapRegions`. These two configs are how we know we are doing a target region push with deferred swap. When a store migration happens, we copy the child version configs over to the store and copy over `versionSwapDeferred` and `targetSwapRegion` configs as well. This is a problem because the controller now thinks we are doing a target region push with deferred swap and will only swap to the new version in the target region. The non target regions never get a chance to swap because the `DeferredVersionSwapService` thinks the version swap is complete already from the first push before store migration as the parent version status is already marked `ONLINE`. …
> [controller] Fix store migration after a target region push with deferred swap

- services/venice-server/src/main/java/com/linkedin/venice/listener/HttpChannelInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandler.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerListenerTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/ReadQuotaEnforcementHandlerTest.java
Previously the init() call in ReadQuotaEnforcementHandler is made async due to CV repository may not be ready by the time when the constructor of ReadQuotaEnforcementHandler is called. The async init() implementation had several flaws which are addressed in this PR:
1. Exceptions thrown in init() are not caught and logged resulting in silent failures.
2. If init() fails or takes too long to finish all requests are failing open without invoking recordAllowedUnintentionally which also results in silent failure.
3. The async init was done by the common fork join pool which comes with some undesirable traits like it could be exhausted, no control over external dependencies and etc.
1. A single thread executor with DaemonThreadFactory will be used to perform the async init. The executor is …
> [server] Improve ReadQuotaEnforcementHandler init() behavior and visibility

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubPositionTypeRegistry.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubPositionTypeRegistryTest.java
Previously, all PubSubPositionFactory implementations were eagerly instantiated at startup  
based on configuration. This caused runtime failures when new factory class names were  
added in config before the corresponding code was deployed.  
This change defers factory instantiation to the first usage via computeIfAbsent on a  
ConcurrentHashMap, avoiding unnecessary class loading and improving robustness in mixed-  
version rollouts.  
> This pull request refactors the `PubSubPositionTypeRegistry` class to improve memory efficiency and error handling by switching to a lazy initialization approach for `PubSubPositionFactory` instances. It also updates the test cases to align with the new lazy-loading behavior.
> 
> ### Refactoring for Lazy Initialization:
> * Replaced the eager …
> [server][controller][dvc][cc] Lazily instantiate PubSubPositionFactory on demand

- docs/dev_guide/how_to/workspace_setup.md
- integrations/venice-samza/src/main/java/com/linkedin/venice/samza/VeniceSystemProducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/TestHelixUtils.java
- The current `compareAndUpdate` implementation in ZkBaseDataAccessor retries immediately when an update fails. As shown in [issue #656](https://github.com/linkedin/venice/issues/656), ZK replica status updates can be interrupted by temporary network issues or disconnects, causing partitions to move to error state
- The Venice Workspace Setup documentation examples for running tests have inconsistent formatting with unnecessary `$` prefixes
- Added exponential backoff between retry attempts in the `compareAndUpdate` method, which will sleep for `2^retry` seconds (1s, 2s, 4s) between each attempt, improving resiliency against temporary ZK connection issues
- Removed unnecessary `$` prompts from command examples for clarity and consistency in documentation
- [] Introduced new **log lines**. …
> [dvc][server][doc] Add exponential backoff for zk update retries + doc cleanup

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/ConsumerIntegrationTest.java
Currently, servers accept all START_OF_PUSH (SOP) messages—even when the replica is already  
in a COMPLETED state. This causes a regression in the replica's state when it processes an  
SOP, flipping its status from COMPLETED back to STARTED. As a result, the server becomes  
unavailable for reads, and the router fails to find any online replicas for the partition.  
This typically occurs when the controller receives a second empty push request from the client  
using the same push ID and re-issues the SOP and EOP messages on the client's behalf. Since  
the server already received the EOP during the first push, it ignores the second EOP as a  
duplicate—leaving the replica stuck in STARTED state indefinitely.  
This change fixes the issue by rejecting incoming SOP messages if the server …
> [server] Reject SOP if EOP has already been received to prevent regress in replica state

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineTest.java
The version topic collects duplicate keys for writing or delete to the same keys. During Kafka log compaction those are they are de-duped and VT size is maintained under control. 
But without log-compaction, we need to find stores with lots of duplicate writes which can be repushed to trim the VT topic size. This PR adds a metric to find the duplicate key count from rocksdb statistics.
> [server][dvc] Add duplicate key count metric for rocksDB

- build.gradle
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
Bumped up avro-util version to pick up the recent fixes of fast-avro. Optimized the help text for admin tool.
Bumped up avro-util version to pick up the recent fixes of fast-avro. Optimized the help text for admin tool.
When supplying a specfic command with `-h`, it will only print the help for that specific command. Example output:
```
java -jar clients/venice-admin-tool/build/libs/venice-admin-tool-all.jar --kill-job -h
usage: java -jar venice-admin-tool-all.jar --<command> [parameters]
Commands:
--kill-job   Kill a running push job.
Requires: --url --store --version
Optional args: --cluster
usage: Parameters:
-c,--cluster <arg>   Name of Venice cluster
--kill-job        Kill a running push job.
Requires: --url --store --version
Optional args: --cluster
-s,--store <arg>     Name of …
```
> [build][admin-tool] Bumped up avro-util version and optimize help text of admin tool

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubAdminAdapterContext.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubAdminAdapterFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/ApacheKafkaUtils.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapterFactory.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfig.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubAdminAdapterContextTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubClientsFactoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/ApacheKafkaUtilsTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminConfigTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicManagerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/admin/PubSubAdminAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
Introduced PubSubAdminAdapterContext to encapsulate all required configurations and
runtime dependencies for creating PubSub admin clients via factory APIs. This includes passing
components like PubSubPositionTypeRegistry and PubSubTopicRepository to downstream
consumers in a clean, unified way.
Updated all call sites to use this new context object when invoking
PubSubAdminAdapterFactory#create, replacing individual parameter passing.
> [server][controller][vpj][dvc][cc] Pass PubSubPositionTypeRegistry to admin clients

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
Update the calculation for startProcessing metric in AdminConsumptionTask
```
/**
* The time difference between the message's delegated time and the first attempt to process the message.
*/
final private Sensor adminMessageStartProcessingLatencySensor;
```
`adminMessageStartProcessingLatencySensor` is the metric to calculate the time that the message is queuing for process in internalTopic. However, it is recorded as the time from message arrived to the broker (getLocalBrokerTimestamp) --> the first time it is processing.
```
* @param localBrokerTimestamp the time when this admin operation arrived at the local admin kafka topic or broker.
```
Update the record to calculate based on the `delegateTimestamp`.
> [controller] Update the calculation for startProcessing metric

- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
When the controller receives a duplicate empty push request with the same push job ID, it
correctly skips creating a new version. However, it still proceeds to broadcast START_OF_PUSH
and END_OF_PUSH control messages, which is unnecessary and can lead to replica state
regression or confusion.
This commit fixes that by ensuring SOP and EOP are not sent when the version already exists.
> ## AI Generate Summary of Changes
> 
> This pull request enhances the `emptyPush` functionality in the `CreateVersion` class by adding validation for store existence, ensuring proper handling of duplicate push job IDs, and introducing comprehensive tests to cover new scenarios. These changes improve error handling, logging, and test coverage.
> 
> ### Enhancements to `emptyPush` functionality:
> 
> * Added …
> [controller] Avoid writing SOP and EOP for duplicate empty push requests

- internal/venice-client-common/src/main/java/com/linkedin/venice/serializer/AvroSerializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/MockVeniceRouterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceRouterWrapper.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/VeniceRouterConfig.java
Test results show that Netty SSL handshake offloading feature doesn't work with OpenSSL.
Removed the SSL handshake offloading feature and all its related configs.
> [router] Removed SSL handshake offloading feature

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/stats/BasicClientStats.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/stats/BasicClientStatsTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepository.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/ModuleMetricEntityInterface.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/ModuleMetricEntityInterfaceTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/RouterServer.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterMetricEntity.java
To set up exponential histogram for certain metrics, multiple views are registered with all the relevant metric names. If there are more than 1 `MetricEntity(ME)` with the same name (for instance, `CALL_TIME` and `CALL_TIME_DVC` both have the same metric name: `call_time`), passing all of them to `setExponentialHistogramAggregation` will result in duplicate metrics (attaching an image for reference)
Added `getUniqueMetricEntities` to 
1. get only unique ME based on metric names instead of duplications
2. validate if there are multiple ME with the same name but with different types.
> [tc][fc][dvc][router] Remove duplication of metrics for Exponential histograms in Otel

- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwapWithFailingRegions.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
The tests for dvc delayed ingestion are flakey because the push status store may not be ready yet when we start the dvc client. The current deferred swap tests share a common multiclusterwrapper and that is problematic because we modify the leader error notifier in some tests and it causes the other tests to have unexpected side effects. And the test for the killed repush job status is flakey because the admin message isn't always consumed right away and we need to wait for it to be consumed. 
1. For dvc delayed ingestion tests, add a check to wait for the push status and meta store to be ready before starting the dvc client
2. Move failed target region push w/ deferred swap to a separate file to not corrupt the shared multi cluster wrapper
3. For the killed repush job test, add in a …
> [test] Fix flakey dvc delayed ingestion and killed repush status test

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Version.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestVersion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/VeniceParentHelixAdminTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceMultiClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcherTest.java
Use RT versioning in all the tests run. more on this feature is in https://github.com/linkedin/venice/pull/1555
Fixed a bug in RealTimeTopicSwitcher, in finding using RT topic name correctly.
Also fixed a bug in parseStoreFromRealTimeTopic in finding store from separate rt.
There are five scenarios where we have to consider where to send version swap message to.
1) both previous and next versions are batch - we can continue sending the VSM to the next vt topic, even though it is not required and does not serve any use case for CDC client **no change here**
2) prev version is batch and next version is hybrid - current code sends VSM to the RT (the only RT it thinks can exist), and this PR's change will send VSM to both RTs, **no change here** except that a VSM is written unnecessarily
3) …
> [test][controller] fix bug and enable rt versioning in integration tests

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/AddVersionLatencyStats.java
We have seen the high latency in addVersion (10-80s) on avg. To find the bottleneck of the operation, we will add the latency metrics to measure heavy ops step. This result will enable us to detect the bottleneck and modify the code correspondingly.
Add `AddVersionLatencyStats` at cluster level. There are multiple sensors added:
| **Sensor Name**                                  | **Description**                                                                 |
|--------------------------------------------------|---------------------------------------------------------------------------------|
| `retireOldVersionsLatencySensor`                | Measures the time taken to retire outdated store versions.                      |
| `resourceAssignmentWaitLatencySensor`           | Captures the …
> [controller] Add latency metrics for addVersion

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerMultiClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DeferredVersionSwapStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
For monitoring deferred version swaps, we are missing a metric to know when a version swap hasn't happened and it is stalled without manually monitoring a store.
Add a new metric to track stalled version swaps. A version swap for a store is considered stalled if the push completion time and more than 110% of the store wait time has passed. If this happens, we will emit a count and decrement this count when the version swap happens for this store.
> [controller] Add metric for stalled version swap

- build.gradle
upgrade opentelemetry version to 1.47.0 to bring in https://github.com/open-telemetry/opentelemetry-java/pull/6851 to lazy initialize some data structures (which are not used when only otel metrics are used) to be more memory efficient.
> [all] upgrade opentelemetry version to 1.47.0

- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/schema/RouterBackedSchemaReader.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AbstractAvroStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroBlackHoleResponseStoreClientImpl.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/ClientConfig.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/D2ServiceDiscovery.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/DelegatingStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/InternalAvroStoreClient.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/AbstractAvroStoreClientTest.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/TestAvroStoreClient.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/client/store/AvroGenericStoreClientImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/client/store/AvroSpecificStoreClientImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/router/TestStreaming.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/client/utils/StoreClientTestUtils.java
The async warmup in venice-thin-client has introduced a lot of confusions and issues in the past and the hope was to mitigate the cold start issue when the users don't start the client in the internal startup aware callback, which is typically this case, and that was why we introduced async warmup since the dependent d2 client might not be ready when `start` is invoked and we hope the startup procedure can be done before sending out the first request, but in practice, it doesn't hold true for most of the cases.
We discovered a new way to invoke the `start` method of the store clients in the startup aware callback, and it will be more deterministic than the best-effort async warmup.
So this PR removes the async warmup completely.
This PR exposes a new method: …
> [venice-thin-client] Removed async warmup in Venice Thin Client

- build.gradle
- internal/venice-common/src/main/resources/avro/PartitionState/v17/PartitionState.avsc
Introduced schema v17 to include the 'lastConsumedVersionTopicOffset' field. This tracks the  
last successfully consumed offset from the version topic, aiding dual write scenarios during  
resubscription when Global RT DIV is enabled.  
The existing field lastConsumedVersionTopicPubSubPosition is always populated using the Kafka  
offset position format, which is incompatible with Xinfra adapters and could lead to broken  
assumptions. Introducing a parallel offset field allows us to make consistent decisions about  
dual writes and determine the correct source to read from.  
Added:
- PartitionState.v17.avsc
- Updated build.gradle to ignore v17
> [protocol] Add PartitionState schema v17 with lastConsumedVersionTopicOffset field

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducedRecordContext.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderProducerCallback.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ProducedRecordTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreBufferServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/mapreduce/datawriter/reduce/TestVeniceReducer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/SimplePubSubProduceResultImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/producer/ApacheKafkaProduceResult.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubProduceResult.java
- internal/venice-common/src/test/java/com/linkedin/venice/memory/InstanceSizeEstimatorTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/SimplePubSubProduceResultImplTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/InMemoryKafkaBroker.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/InMemoryKafkaTopic.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/InMemoryPubSubPosition.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/consumer/poll/DuplicatingPollStrategy.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/producer/MockInMemoryProducerAdapter.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdminWithAcl.java
Refactored offset handling in LeaderProducedRecordContext class to use PubSubPosition  
instead of raw numeric offsets. This improves abstraction and prepares the codebase  
for more flexible position semantics.  
> ## AI Generate Summary of Changes
> This pull request refactors how offsets are handled in Kafka ingestion tasks by replacing numeric offsets with `PubSubPosition` objects, improving abstraction and consistency in the codebase. The most significant changes include updates to the `LeaderProducedRecordContext` class, modifications to methods across ingestion tasks to use `PubSubPosition`, and adjustments to utility functions and constructors.
> 
> ### Refactoring of Offset Handling
> 
> 
> * `LeaderProducedRecordContext.java`:
>   - Replaced `long consumedOffset` and `long …
> [server][dvc] Replace numeric offsets with PubSubPosition in LeaderProducedRecordContext

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/AdminOperationProtocolVersionControllerResponse.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestAdminOperationVersionDetection.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestProtocolVersionAutoDetection.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ProtocolVersionAutoDetectionService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/ControllerRoutes.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestProtocolVersionAutoDetectionService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/ControllerRoutesTest.java
During testing, we identified the following issues:
- **Cause:** `initialDelay` is set to `0`, so the task runs immediately. This triggers a leadership check before the host is fully initialized.
- **Effect:** Although the host is the leader, it fails the check because it's not ready. The second retry usually succeeds.
- **Solution:** Increase the `initialDelay` to give the host time to complete setup before the check runs.
- **Cause:** The `controllerUrlToVersionMap` uses `http://` as keys, but incoming `requestURL`s are in `https://`.
- **Effect:** Lookup in the map fails due to the protocol mismatch, as no matching key is found.
- **Solution:** Use HTTP/HTTPS based on SSL Factory, and remove the protocol from the key string of `controllerUrlToVersionMap`
1. Increase the initial delay …
> [controller] Fix bug in ProtocolVersionAutoDetectionService

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/CompositeVeniceWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/LeaderMetadataWrapper.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/memory/InstanceSizeEstimatorTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicManagerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestFatalDataValidationExceptionHandling.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridMultiRegion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
Upgrade to KafkaMessageEnvelope v12 to start dual writing PubSubPositions alongside
numeric offsets. This enables a gradual transition and sets the foundation for
eventually deprecating numeric offsets in the future.
> [compat] Use KafkaMessageEnvelope v12 to support dual writing PubSubPositions

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/DefaultInputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestDefaultInputDataInfoProvider.java
Currently, as part of `DefaultInputDataInfoProvider`, we throw `RuntimeException` when the source is empty or invalid. However, we want to treat this as user error instead of an runtime exception.
Treating invalid input as user error by throwing the appropriate exception, helps `VenicePushJob` classify the error correctly with the right checkpoint. 
**Note**: `DefaultInputDataInfoProvider` is an API that can be extended for various input data info providers. We don't have the right structure / abstractions for handle errors as part of this API and as a result, extension of this API may still need to handle invalid input as recommended by this PR. However, we can't enforce consistent handling across the implementations and to enforce that would be out of the scope for this bug fix.
- Throw …
> [vpj] Report empty input source as user error

- build.gradle
- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
Switches from hardcoded PubSub position bytes to storing the numeric last consumed VT offset 
directly. The previous hardcoded bytes encoded the numeric offset in a static Kafka-specific 
format, which would require special handling in the future. 
Since this field is not currently used (GlobalDIV is not enabled), we can safely migrate to 
a numeric field now. The byte-based PubSub position field will be populated dynamically 
rather than using the existing hardcoded value.
> [compat][server][dvc] Use PartitionState v17 to persist numeric last consumed VT offset for GlobalDIV

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/ChangelogConsumerDaVinciRecordTransformerUserApp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestBootstrappingChangelogConsumer.java
1. Internally, our users don't have access to the `ChangelogClientConfig`, so they're unable to enable `SpecificRecord` support for DVRT CDC.
1. Create a new getter in `VeniceChangelogConsumerClientFactory` that allows DVRT CDC users to enable the use of SpecificRecord.
> [cc] Add the ability to create a Specific DVRT CDC client from VeniceChangelogConsumerClientFactory

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/mapreduce/datawriter/jobs/DataWriterMRJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/jobs/DataWriterComputeJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/spark/datawriter/jobs/AbstractDataWriterSparkJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
Venice Push Job Diagram as a refresher:
There is no timeout on the Compute Engine `DataWriterComputeJob`. This leads to some push jobs taking days and even sometimes weeks to complete, which significantly delays the debugging process. There is an existing timeout (`bootstrapToOnlineTimeoutInHours`) on the job status polling, but that takes place after the data writer job portion (which is where we've been witnessing significant delays). With the increased frequency of KIF repushes, this issue will become even more pronounced.
There should be a timeout on the entire push job as a whole. If exceeded, the push job should be cancelled. The existing configuration `bootstrapToOnlineTimeoutInHours` can be repurposed for this, and this should've be the original purpose of the configuration.
Both …
> [vpj] Push Job Timeout

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangeCoordinate.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubUtil.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/common/ApacheKafkaOffsetPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/EarliestPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/LatestPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubPosition.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubUtilTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/common/ApacheKafkaOffsetPositionTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/api/EarliestPositionTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/api/LatestPositionTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/unit/kafka/InMemoryPubSubPosition.java
Removed the comparePosition and diff APIs from PubSubPosition. These methods will be supported  
through a separate service in the future (e.g., TopicManager).  
For now, the logic has been moved to static utility methods:  
- PubSubUtil.comparePubSubPositions  
- PubSubUtil.diffPubSubPositions  
> [cc] Drop comparePosition and diff from PubSubPosition; migrate to PubSubUtil

- internal/venice-client-common/src/main/java/com/linkedin/venice/exceptions/AdminMessageConsumptionTimeoutException.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceParentHelixAdmin.java
After we send the delete store admin message, it is possible that we timeout while waiting for the message to be consumed. When this happens, we never cleanup the acls and have leaked acls
1. Add in a new VeniceException type, `AdminMessageConsumptionTimeoutException`, to identify when we timeout from waiting for an admin message to be consumed
2. Catch the new `AdminMessageConsumptionTimeoutException` and delete the acls for the store
3. Catch all other Exceptions and log it so they do not fail silently
> [controller] Cleanup acls from store deletion if admin consumption times out

- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
This [PR](https://github.com/linkedin/venice/pull/1824) added a new metric called `call_count` to measure QPS for the router of type Count. However, in order for this be registered internally as a counter the metric name needs to be formatted in a certain way.
To fix this, we rename the metric name from `call_count` to `request_call_count`.
> [router] Rename call_count metric for qps to request_call_count

- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestStoreMigration.java
After a store was migrated, certain store configurations—minCompactionLagSeconds, maxCompactionLagSeconds, nearlineProducerCountPerWriter, and isDavinciHeartbeatReported—were not being replicated. This change ensures that those configurations are preserved during migration.
The solution is to add setter methods for these configurations to the UpdateStoreQueryParams class.
> [Controller]Fix omission of specific store configurations during store migration

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
Remove tracking of ignored upstream RT offsets from PartitionConsumptionState (PCS).  
This was previously used to compute lag when a leader ignored messages and there was  
no guarantee of future data. Now that heartbeat messages ensure continuous traffic,  
this mechanism is no longer needed and can be safely removed to simplify the code.  
> [server] Delete ignored upstream RT offset tracking from PCS

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/vpj/VenicePushJobConstants.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestVenicePushJobCheckpoints.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientDiskFullTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PushJobDetailsTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestWriteUtils.java
Venice Push Job could previously send multiple terminal failure statuses (ERROR, KILLED) to the  
controller—once during status polling (e.g., ERROR) and again later if the job was canceled      
(e.g., ERROR or KILLED). This led to misleading metrics and inaccurate SLO reporting.            
This change introduces a check to track the last reported status and skip sending updates if it  
was already terminal.                                                                            
Also, fixed an issue in `setupPushJobTimeoutMonitor()` where a 0-hour bootstrap timeout               
would cause the job to be canceled immediately, making several tests flaky due to unexpected     
KILLED or ERROR statuses in checkpoint validations.                                              
To address …
> [vpj] Avoid duplicate emission of terminal failure statuses to controller

- build.gradle
> [lib][controller][fc] Bump gRPC to 1.68.3 and protobuf to 3.25.5

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveIngestion.java
- services/venice-controller/src/main/java/com/linkedin/venice/ingestion/control/RealTimeTopicSwitcher.java
The test runs verification checks immediately after the push completes, which may happen  
before the leader has processed all real-time records. This led to nondeterministic results  
due to timing differences in ingestion and verification steps.  
To fix this, a fresh MARKER record is appended to the RT, and the test waits until it can  
be fetched. This ensures that all prior records have been processed (either accepted or  
dropped in DCR) by the leader before verification begins, making the test deterministic.  
> [test] Fix flaky test TestActiveActiveIngestion::testLeaderLagWithIgnoredData

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
Da Vinci ingestion can fail during A/A repush when the sorted key is associated with the DELETE operation. Since Da Vinci does not use RMD-based RocksDB implementation, it will go into the regular RocksDB DELETE path and if the deferred write is true, it throws the exception.
This PR addressed the issue by simply skipped the delete op.
> [dvc][server] Do not fail ingestion when handling regular DELETE when deferred write is enabled

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/DelegatingStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/DeepCopyStorageEngine.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
For now, the only class extending this is the DeepCopyStorageEngine.
In a later commit, it will also be used in order to fix a bug in the ingestion code.
This is a non-functional change.
> [dvc][server] Added a DelegatingStorageEngine

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/stats/BasicConsumerStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/BasicConsumerStatsTest.java
1. The current CDC metrics such as `records_consumed.Count` sample at the minute level, so we're unable to see at the second level granularity.
2. The metrics format for the BootstrappingConsumer is incorrect. It looks like this: `vcc---chunked_record_fail_count.Count.rrd`. It's missing the store name in the metric.
1. Change some of the CDC metrics from Count to Rate so we can see at the second level granularity. This has been confirmed by performing a jar drop on a test client, and reading the Rate metrics.
2.  For the BootstrappingConsumer, we're not providing a way for that client to read the `consumerName`. So we add it to the `ChangelogClientConfig`. We also need to remove the `viewName` when constructing the `consumerName`. The BootstrappingConsumer doesn't support Views, so if we …
> [cc] Change Count metrics for CDC from Count to Rate, and fix the metrics reporter name for BootstrappingConsumer

- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DeferredVersionSwapStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
When VPJ stops polling early, the parent version status will never be updated to `PUSHED`. This causes the DeferredVersionSwapService to never perform a version swap for a store because it thinks the push isn't complete yet. 
When checking if a push is complete, we will also check if the target version status is ONLINE. If the target version status is ONLINE, that means the push is complete in the target region and we can start monitoring the push for a version swap
Existing tests
> [controller] Check target region version status for DeferredVersionSwapService

- internal/venice-client-common/src/main/java/com/linkedin/venice/controllerapi/RepushJobResponse.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybrid.java
Currently, `RepushJobResponse` doesn't take in storeName on initialisation. `RepushJobResponse` extends `ControllerReponse` which does have storeName.
Add `storeName` as `RepushJobResponse` constructor variable. Leverage `setName` in `ControllerResponse` parent class to populate `storeName`.
> [log-compaction][controller]add storeName for RepushJobResponse initialisation

- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceHelixAdmin.java
When we have rebalancing stages, Helix can pick any instances in instances list, which means the controller with lower version can be picked even when it is not leader or standby. We will broadcast the request to all controllers instead of limiting the check for leader and standby only.
Get the full list of controllers from Helix LIVEINSTANCES and broadcast the request to those instances.
- In case we dont find any live instances, we will let the task fail since it should not happen.
- If we get a list of live instances and one of them does not response good, we still continue the process and skip the check for that controller.
> [controller] Broadcast the adminOperation version check request to all controller instances instead of standby only

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedStorageEngineStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HostLevelIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/AbstractStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/StorageEngineNoOpStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngine.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartition.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/AggVersionedStorageEngineStatsTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStorageEngineTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
During key count metric collection we sometime see the associated rocksdb intances are closed which cause exception in the drainer thread blocking ingestion.
This PR fixes that by checking for closed DB during metric collection.
> [server] Fix key count metric exception

- internal/venice-client-common/src/main/java/com/linkedin/venice/read/RequestType.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/read/RequestTypeTest.java
- services/venice-router/src/main/java/com/linkedin/venice/router/stats/RouterHttpRequestStats.java
This is part of an effort to reduce metric usage across Venice services and this PR is targeting venice router metrics.
For `SINGLE_GET` request type, this PR removes the following metrics:
"--key_num"
"--fanout_request_count"
"--multiget_fallback"
"--unavailable_replica_streaming_request"
For `MULTIGET_STREAMING`:
"--multiget_streaming_read_quota_usage_kps"
"--multiget_streaming_request_usage"
"--multiget_streaming_multiget_fallback"
For `COMPUTE_STREAMING`:
"--compute_streaming_request_usage"
CI and unit tests
> [router][client] Unused router metrics cleanup

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/chunking/AbstractAvroChunkingAdapter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/client/AvroGenericDaVinciClientTest.java
- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/DispatchingAvroGenericStoreClient.java
- clients/venice-thin-client/src/main/java/com/linkedin/venice/client/store/AvroGenericStoreClientImpl.java
- clients/venice-thin-client/src/test/java/com/linkedin/venice/client/store/TestAvroStoreClient.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/client/store/AvroGenericStoreClientImplTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/PartialUpdateTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPartialUpdateWithActiveActiveReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/fastclient/FastClientIndividualFeatureConfigurationTest.java
Reader schema in Venice generic client today can be somewhat unpredictable from user’s perspective and create side effects such **as longer detection and mitigation time** when a bad schema is added.
Client libraries always use the writer schema as reader schema:
This would give users full control over the reader schema behavior. Since a bad schema can only create impact after a data push or write. In addition, a data version rollback will take care of the mitigation without  restart. With colo by colo push this will also allow users to roll out new schemas one colo at a time.
For read compute and similar features such as the DVRT we will keep today's behavior for now. Which is to use the latest superset or value schema to deserialize and used as the input/base to perform transformations. …
> [thin-client] Change reader schema behavior to use writer schema

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/AggVersionedIngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
Currently, we emit `_rt_consumed_offset` as a metric, but it hasn't been very useful.  
Additionally, it won't be supported after migrating to non-numeric position types.  
Hence, we're removing it to reduce noise and simplify the metrics surface.  
> [server] Delete RT offset emission metrics

- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
Right now, when we call `requestTopicForPushing`, we may call `hasWriteAccessToTopic` and `hasReadAccessToTopic` twice if it fails one check, which is not necessary. The call is quite expensive on memory profiling result. Refactor the code to reduce the calls.
- Only request access check unless necessary
- Remove `disableParentRequestTopicForStreamPushes` due to unused params
> [controller] Refactor code to reduce call to check access in CreateVersion

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelDualPoolFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- internal/venice-common/src/test/java/com/linkedin/venice/utils/UtilsTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
During ST from offline to standby, ready to serve future versions will take a latch to stall the transition until the future version replica is ready to serve. This is to account for manual and automatic deferred swaps that can make future versions online at any moment and if ST is not stalled for future versions, it is possible that there won't be enough replicas.
The problem with the current state is that in SIT, there is short circuit logic for current versions holding a latch to release the latch for hybrid stores that have caught up to VT, but this logic is not being applied to future versions that are now holding a latch too. This results in the future version holding the latch forever and blocking new pushes because it can use up the entire future version thread pool if ingestion …
> [server] Mark latch as created in SIT for future versions

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceClusterConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/AbstractPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/HelixParticipationService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModelFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManager.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/DaemonThreadFactory.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/utils/LogContext.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/utils/LogContextTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/admin/ApacheKafkaAdminAdapter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridQuota.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
This change enables emission of versioned storage quota usage stats by adding a new  
metric. To ensure accurate quota tracking, we no longer shut down SIT belonging to  
the current version during idle task cleanup.  
Shutting down SIT prematurely:  
1) Clears partition consumption state maps, which are required to compute quota usage.  
2) Removes the store change listener, StorageUtilizationManager, which is needed   
to react to quota config changes.  
These changes help maintain quota observability and ensure that the metrics remain  
accurate for online versions.  
> [server] Emit versioned storage quota stats and keep SIT open for current store version

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/utils/IngestionTaskReusableObjects.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceServerWrapper.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
The AASIT hangs on to a private property of thread-local type, where each instance can contain a 1 MB blob. When there are lots of AASIT instances, accessed from lots of ingestion threads, this can add up to a lot of big thread-local state.
In a production heap dump with 191 AASIT instances, 51% of all bytes were occupied by byte[] (though not all of them came from this particular AASIT field).
With this commit, the default behavior is the same as before, but a new config allows passing an enum to select alternative behaviors:
server.ingestion.task.reusable.objects.strategy
And the valid values are:
- NO_REUSE: will pass null into the relevant code paths, which will result in new objects getting allocated on the fly, and needing to be garbage collected.
- THREAD_LOCAL_PER_INGESTION_TASK: …
> [server][dvc] IngestionTaskReusableObjects.Strategy config

- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushStatusCollector.java
`topicToNoDaVinciStatusRetryCountMap` is a global variable that we use to track how many times we did not receive any DVC status report, and we call the above code periodically
int noDaVinciStatusRetryAttempts = topicToNoDaVinciStatusRetryCountMap.compute(pushStatus.topicName, (k, v) -> {
if (v == null) {
return 1;
}
return v + 1;
});
if (noDaVinciStatusRetryAttempts <= daVinciPushStatusNoReportRetryMaxAttempts) {
...
} else {
topicToNoDaVinciStatusRetryCountMap.remove(pushStatus.topicName);
...
}
Here, if we exceed daVinciPushStatusNoReportRetryMaxAttempts, then we remove it from the topicToNoDaVinciStatusRetryCountMap map, and the next call will again start the counter from 1 
This PR check for previous dvc pushstatus query retry count before checking again.
Both reviewer and PR author …
> [server][dvc] Check for previous dvc pushstatus retry count

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
We have observed that there are cases where a store is eligible to enter the DeferredVersionSwapService loop and perform a version swap, but it does not seem to be entering at all. This could be due to the parent version status being marked ONLINE already even though a swap did not happen, leading to a version status mismatch and roll forward never happening. This pr adds a check to account for this case if it is happening and emit a metric
Emit a metric if the parent version status is marked ONLINE and allow it to enter the DeferredVersionSwapService loop to perform a version swap
New unit and e2e test
> [controller] Emit metric for ONLINE parent version status mismatch

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestBootstrappingChangelogConsumer.java
Previous bootstrapping changlog consumer test created separate `PubSubBroker` by its own, even the `VeniceClusterWrapper` already came with `PubSubBroker` inside. The separate `PubSubBroker` has its own different broker address, so `VeniceClusterWrapper#getPubSubClientProperties` will not include properties with that broker address. As a result, test with specific PubSub will not pick properties with this borker address up. 
Avoid creating separate `PubSubBroker` , using `VeniceClusterWrapper#getPubSubBorkerWrapper()` instead. 
> [test] Fix bootstrapping changelog consumer test creating separate PubSubBroker.

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubProducerCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/ChainedPubSubCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/CompletableFutureCallback.java
- internal/venice-common/src/main/java/com/linkedin/venice/writer/VeniceWriter.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/BatchingVeniceWriterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/VeniceWriterUnitTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/writer/WriterCallbackTest.java
During the testing of the BatchingVeniceWriter, NPE was thrown in VeniceWriter producer callback thread, as we always call onCompletion() API for the PubSubCallback. 
For CompletableFutureCallback, when VW sends message, it will insert an internal SendMessageErrorLoggerCallback and onCompletion() will also invoke it. However, ChainedPubSubCallback does not register the same callback, but will still invoke onCompletion() API and will also invoke it's internal callback's onCompletion() API. If internal callback is a CompletableFutureCallback, NPE will be thrown.
This PR address the issue and verify through test logs that it does not appear.
> [samza] Make ChainedPubSubCallback also take in SendMessageErrorLoggerCallback when sending messages

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/consumer/TestChangelogConsumer.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMaterializedViewEndToEnd.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/IntegrationTestUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/utils/IntegrationTestPushUtils.java
For change log consumer integration test,  it could be flaky if we assume one poll could fetch all messages. Besides, as venice is an eventual consistency system, we could not guarantee data is written exactly after data is produced. When switching to other pub sub systems, previous tests easily failed. 
Adding retry and keep polling until no message available.
> [test] Stablizing change log consumer integration test.

- internal/venice-common/src/main/proto/VeniceReadService.proto
**Title**: [protocol] Add gRPC countByValue RPC method to VeniceReadService
The current VeniceReadService gRPC protocol only supports basic get and batchGet
operations. To enable server-side countByValue aggregation functionality, we need to
extend the protocol with new RPC methods and message types.
This is a prerequisite change for implementing true server-side countByValue
aggregation in the Venice fast-client, which will reduce network traffic and improve
performance by moving aggregation logic from client to server.
Added new gRPC protocol definitions to `VeniceReadService.proto`:
- **New RPC method**: `countByValue(CountByValueRequest) returns
(CountByValueResponse)`
- **New message types**:
- `CountByValueRequest`: Contains keys, resource name, topK limit, and field names
- …
> Add gRPC countByValue RPC method to VeniceReadService protocol

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubUtil.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/common/ApacheKafkaOffsetPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/LatestPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubSymbolicPosition.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubUtilTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/common/ApacheKafkaOffsetPositionFactoryTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/common/ApacheKafkaOffsetPositionTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/adapter/consumer/MockInMemoryConsumerAdapter.java
- internal/venice-test-common/src/test/java/com/linkedin/venice/pubsub/mock/MockInMemoryPubSubClientTest.java
This change introduces three new methods in the PubSubConsumerAdapter interface to standardize
handling of PubSubPosition objects:
- comparePositions(): compares two positions for ordering
- positionDifference(): returns signed difference (p1 - p2), with symbolic resolution
- decodePosition(): reconstructs PubSubPosition from a ByteBuffer or byte[]
These APIs allow Venice components (controller, server, Da Vinci) to reason about
topic positions uniformly across symbolic and concrete implementations.
> [server][controller][dvc] Add PubSubPosition position compare, diff, and decode APIs in PubSubConsumerAdapter

- clients/venice-client/src/main/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadata.java
- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/meta/RequestBasedMetadataTest.java
No available replicas during version switch.
Today, in Fast Client, during the metadata update, once a new version is discovered, Fast Client will switch to the new current version right away even though the routing info for the new current version doesn't contain replicas for every partition and this can happen as the metadata fetched is from Venice Server, which can be suffering from a delay from Zookeeper since Controller is making a decision about when to switch to the new version.
This PR will delay the current version switch until the returned routing info contains at least some ready-to-serve replicas for every partition.
There is an edge case when the being-used current version gets deleted, even the routing info is not complete, Fast Client will switch to the new version.
TODO: …
> [fast-client] delay version switch until the newly fetch version is ready

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestDeferredVersionSwap.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/DeferredVersionSwapService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DeferredVersionSwapStats.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeferredVersionSwapService.java
1. We've observed that sometimes the child status is `ONLINE` in the in memory store map even though it is `PUSHED` in zookeeper. This prevents an automatic version swap from happening because there is an assumption that `ONLINE` means that the version has been swapped already
2. When a roll forward fails after 5 tries, we stop trying to roll forward, but we do not truncate the parent topic and this blocks the next push
1. Check that the current version is the same as the future version if the version status is ONLINE, otherwise continue and perform a roll forward
2. Truncate the parent topic after failed roll forward to unblock next push
3. Move updateVersionStatus to the end so that the version status update is only performed once
> [controller] Check for child version status mismatch for deferred swap

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/EarliestPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/LatestPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubPosition.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/api/EarliestPositionTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/api/LatestPositionTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/adapter/consumer/MockInMemoryConsumerAdapter.java
> [server][controller] Add PubSubPosition resolve and diff APIs in TopicManager

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangeCoordinate.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubPositionDeserializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubPosition.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubPositionDeserializerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicManagerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestFatalDataValidationExceptionHandling.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridMultiRegion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/kafka/KafkaConsumptionTest.java
Previously, only the raw bytes of the position were being serialized, omitting the type ID  
and producing an incomplete PubSubPositionWireFormat. This caused deserialization failures  
when attempting to reconstruct the full position.  
This change ensures that the full PubSubPositionWireFormat—including the type ID and raw  
bytes—is serialized and used consistently during conversion.  
> [server][dvc][cdc] Fix PubSubPosition serialization helper to include typeId

- build.gradle
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/PushJobSetting.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/vpj/VenicePushJobConstants.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/UpdateStoreQueryParams.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ReadOnlyStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Store.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/StoreInfo.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/SystemStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/Version.java
- internal/venice-common/src/main/java/com/linkedin/venice/meta/ZKStore.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
- internal/venice-common/src/test/java/com/linkedin/venice/meta/TestVersion.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestParentControllerWithMultiDataCenter.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/hadoop/TestVenicePushJob.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
Regular batch push and TTL re-push today are incompatible features. This is because regular batch push will wipe out the RMD needed to perform TTL re-push.
Added a new self-managed `storeProperties.ttlRepushEnabled` property to signal ttl-repush is enabled for a given store. The property is set to true once a TTL re-push is attempted for a store. Once the property is set to true we will disallow regular batch push.
We allow incremental push, re-push, empty pushes and batch push with record level timestamp to go through. Users can also override this check via VPJ property allow.regular.push.with.ttl.repush.
New integration test and unit test
> [vpj] Prevent regular batch push when there are TTL re-pushes

- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/DaVinciUserApp.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientRecordTransformerTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java
In venice-client MP, the integration tests related to DaVinciUserApp failed because the argument list was too long.
```
2025-07-17T21:45:39.6303048Z Gradle suite > Gradle test > com.linkedin.venice.XinfraDaVinciClientTest > testBlobP2PTransferAmongDVCWithServerShutdown[0](false) FAILED
2025-07-17T21:45:39.6304084Z     java.io.IOException: Cannot run program "/export/apps/jdk/JDK-17_0_5-msft/bin/java": error=7, Argument list too long
2025-07-17T21:45:39.6304848Z         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
2025-07-17T21:45:39.6305474Z         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
2025-07-17T21:45:39.6306127Z         at com.linkedin.venice.utils.ForkedJavaProcess.exec(ForkedJavaProcess.java:67)
2025-07-17T21:45:39.6306819Z …
```
> [test] Fix Argument List Too Long Issue in E2E Test DaVinciUserApp by Using Config File

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceClusterConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskFactory.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionStateTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/PushTimeoutTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StorageUtilizationManagerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubContext.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubContextTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/InMemoryPubSubPosition.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/InMemoryPubSubPositionFactory.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/TestUtils.java
- internal/venice-test-common/src/test/java/com/linkedin/venice/pubsub/mock/InMemoryPubSubPositionTest.java
- services/venice-server/src/test/java/com/linkedin/venice/listener/StorageReadRequestHandlerTest.java
This change makes pub-sub related dependencies available in  
ParticipantConsumptionState, enabling correct serialization,  
deserialization, and comparison of PubSubPosition objects.  
> [server][dvc] Propagate pub-sub dependencies to participant consumption state

- build.gradle
- clients/venice-admin-tool/build.gradle
- clients/venice-push-job/build.gradle
- gradle/helper/packaging.gradle
- gradle/helper/publishing.gradle
We have a special gradle module called `all-modules`. This is supposed to be a single-module to add watchers on to know when new versions of Venice are released. By default, Gradle publish plugin publishes to Maven repo in alphabetical order. Due to it's name, `all-modules` is the first module that gets published.
By ensuring that `all-modules` gets published last, we can use the same watcher to also ensure that all other modules have been published successfully, and the published version is ready to be used.
Tried manually locally. This is a build-only change
> [build] Make "all-modules" be published after all other modules are published

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AbstractKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/IngestionStatsReporter.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceDelegatorTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/IngestionStatsTest.java
Removed the following offset-based metrics as part of the ongoing shift to HB based tracking:
- follower_offset_lag
- leader_offset_lag
- hybrid_leader_offset_lag
- hybrid_follower_offset_lag
- batch_replication_lag
- batch_leader_offset_lag
- batch_follower_offset_lag
- leader_stalled_hybrid_ingestion
These metrics are no longer relevant in the context of PubSubPosition-based tracking.
> [server] Delete offset-based lag metrics from Venice Server

- build.gradle
- gradle/helper/publishing.gradle
In a previous PR (#1995), I tried to make `all-modules` publish last, and in the latest commit, due to refactoring, it didn't work as intended - and the result was almost a no-op. This PR fixes the issue and makes the feature work.
Fixed refactored build code
Tried locally on `mavenLocal`
> [build] Fix catch-all module publishing order

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubUtil.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubUtilTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/adapter/consumer/MockInMemoryConsumerAdapter.java
- Added a new `subscribe` API to `PubSubConsumerAdapter` that supports inclusive or  
exclusive subscription. This is necessary because the current API only supports  
exclusive mode, which forces us to manually adjust positions (e.g., subtract 1).  
Such arithmetic is not allowed with generic `PubSubPosition`, so native support  
for inclusive/exclusive behavior is required.  
- Replaced `PubSubConsumerAdapter.beginningOffset` with `beginningPosition` to support  
non-Kafka `PubSubPosition` implementations and symbolic positions.  
> [server][controller] Add subscribe API with inclusive flag

- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceMetricsConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepository.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceMetricsConfigTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepositoryTest.java
When applications use multiple Venice client libraries to access different Venice stores, each library may initialize its own `OpenTelemetry` (OTel) instance, in addition to the one already initialized by the application. This duplication can increase resource usage, especially during periodic metric exports with each instance allocating resources to aggregate and export metrics. 
This PR introduces an option to reuse the `GlobalOpenTelemetry` singleton instead of creating new ones for each Venice component.
Configs added:
1. `setUseOpenTelemetryInitializedByApplication()` or `otel.venice.use.opentelemetry.initialized.by.application` (Default `false`)
If `true`: `GlobalOpenTelemetry.get()` will return an instance initialized by the applications or throw an exception if its not already …
> [tc][fc][dvc][cdc] Use GlobalOpenTelemetry singleton for clients usecases

- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/HelixUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/AbstractTestVeniceHelixAdmin.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithSharedEnvironment.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceControllerClusterConfig.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestVeniceControllerClusterConfig.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkHelixAdminClient.java
Helix supports topology-aware partition placement, and it is being widely used in production at LinkedIn. However, configuring this is an operational task, and done after the cluster is created.
This change allows configuring the topology-aware configs of the Helix cluster at time of cluster creation, so that it can be handled automatically.
Also cleaned up some code and tests that previously configured this incorrectly
- Previously, new clusters would get created with partial topology-aware configs - `TOPOLOGY = /instance` and `FAULT_ZONE_TYPE = instance`. However, this would not take effect as Helix needs another config `TOPOLOGY_AWARE_ENABLED = true` to enable topology-aware routing
- Hence, this change doesn't change the behavior of the cluster by …
> [controller] Support configuring cluster topology when creating storage clusters in Helix

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/BootstrappingVeniceChangelogConsumerDaVinciRecordTransformerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/utils/ChunkAssembler.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/utils/ChunkAssemblerTest.java
Update changelog consumer to adopt `PubSubPosition` (including  
`PubSubSymbolicPosition.EARLIEST`) in place of numeric offsets and  
Kafka-specific types. Improves abstraction, flexibility, and compatibility  
with non-numeric position types.  
Key changes:  
- Replace `ApacheKafkaOffsetPosition.of(0)` / `OffsetRecord.LOWEST_OFFSET` with  
`PubSubSymbolicPosition.EARLIEST`.  
- Update subscription and seeking logic to use `PubSubPosition`.  
- Remove legacy helpers for numeric offset conversions.  
- Update logging to print `PubSubPosition` directly.  
- Drop unused legacy offset imports.  
- Default `-1` offsets to `PubSubSymbolicPosition.EARLIEST`.  
This pull request updates the Da Vinci client consumer code to consistently use the new `PubSubSymbolicPosition.EARLIEST` and the generic …
> [cc] Use PubSubPosition instead of numeric offsets in changelog code

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerApiConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/TestVeniceHelixAdminWithIsolatedEnvironment.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/DeadStoreStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestDeadStoreStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoresRoutesTest.java
The current GetDeadStores API lacks the ability to specify a time window for dead store detection. In cases where the lookback window needs to be reduced such that the the store is considered dead recently but would have been considered NOT dead in the full lookback window.
Added an optional lookBackMS parameter to the GetDeadStores API using method overloading to maintain full backwards compatibility. The solution propagates this parameter through the entire stack:
- **DeadStoreStats interface**: Added overloaded method with lookBackMS parameter
- **Admin interface**: Added overloaded getDeadStores method  
- **Controller implementations**: VeniceHelixAdmin and VeniceParentHelixAdmin support new parameter
- **REST API**: StoresRoutes handles optional look_back_ms query parameter
- …
> [controller][admin-tool] Add lookback time parameter to GetDeadStores API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/helix/LeaderFollowerPartitionStateModel.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/LeaderFollowerParticipantModelFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/helix/VeniceLeaderFollowerStateModelTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java
Problem: Due to network issue or other gaps in the Helix state transition we found that the HeartbeatMonitoringService is still monitoring resources that are no longer assigned to the node. e.g. A replica that went from STANDBY->ERROR->DROPPED or a network disruption causing a replica going from STANDBY resetting to OFFLINE and then going from OFFLINE->DROPPED without gracefully transitioning from STANDBY->OFFLINE
Solution: Added the cleanup logic from OFFLINE->DROPPED to cover more scenarios since removeLagMonitor is relatively cheap. Added new mechanism in HeartbeatMonitoringService's logging thread to also perform cleanup by checking against existing monitors with the customized view. To deal with potential races and staleness of the CV repository we will collect the replicas and only …
> [server] Improve HeartbeatMonitoringService cleanup

- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestProducerBatching.java
`TestProducerBatching` doesn't cleanup its setup after testing is finished. This change closes and releases resources after each test run.   
> [Test] Close MultiClusterWrapper in TestProducerBatching

- services/venice-router/src/main/java/com/linkedin/venice/router/stats/SecurityStats.java
The active ssl connection count is not working as intended. 
Removed the bad metric as it's superseded by connection_count_gauge.
> [router] Removed active_ssl_connection metric

- .github/workflows/VeniceCI-E2ETests.yml
- internal/venice-test-common/build.gradle
- Rebalanced E2E test buckets to distribute load evenly and reduce total CI runtime  
- Reduced per-bucket timeout from 120 mins to 30 mins, which will force developers  
to adjust buckets when changes impact runtime and prevent test accumulation that  
can make CI slow and unpredictable  
> [build][ci] Remap E2E test buckets to lower overall CI runtime

- build.gradle
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/PartitionConsumptionState.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/SITFastReadyToServeTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
- internal/venice-common/src/main/java/com/linkedin/venice/serialization/avro/AvroProtocolDefinition.java
This PR adds support for checkpointing replica's message (today only stores heartbeat) timestamp in OffsetRecord and use it in server fast restart feature. 
The semantic of the fast restart threshold will be changed:
**Before**: The offset relax factor is controlled by a config. If previous ready to serve replica comes back with previous lag + lag threshold * factor > current lag we will allow it to be ready to serve.
**Now**: The time lag threshold will be controlled by a config. If previous ready to serve replica comes back with certain  time lag, we will allow it to be ready to serve.
**Config name**: "time.lag.threshold.for.fast.online.transition.in.restart.minutes", default -1 (disabled)
> [server] Add time lag threshold support for fast server restart

- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/init/SystemSchemaInitializationRoutine.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/TopicCleanupService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/StoresRoutes.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/VeniceControllerRequestHandler.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/TestTopicCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/StoresRoutesTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/VeniceControllerRequestHandlerTest.java
Today, `Admin#discoverCluster` does cluster discovery, and d2 service resolution for the cluster.Most cases only need the cluster discovery, though.
This change extracts the d2 service resolution out of `Admin#discoverCluster` into a new function `Admin#getRouterD2Service`
> [controller] Separate cluster discovery and d2 service discovery for VeniceHelixAdmin

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/AbstractMerge.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/Merge.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeByteBuffer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeConflictResolver.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/replication/merge/MergeGenericRecord.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/view/ChangeCaptureViewWriter.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/DataIntegrityValidator.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/MergeGenericRecordTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeBase.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeConflictResolver.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeDelete.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeDeleteWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePut.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergePutWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdate.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithFieldLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeUpdateWithValueLevelTimestamp.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/replication/merge/TestMergeWithValueLevelTimestamp.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/Segment.java
- internal/venice-common/src/main/resources/avro/GlobalRtDivState/v1/GlobalRtDivState.avsc
- Change long with PubSubPosition in code as well as tests
VALIDATION_OVERRIDE
> [server] Replace numeric offsets with PubSubPosition in DCR and WC code paths

- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/PushMonitorUtils.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PushMonitorUtilsTest.java
Currently, when a Venice Push Job (VPJ) hangs for a specific region, it's often due to one or a small subset of partitions not completing. However, VPJ does not explicitly surface which host with which partition is causing the delay. As a result, on-call engineers must investigate multiple sources—including controller and server logs, ZooKeeper—to identify the blocking partition and server.
One example logging:
`1827/1840 Da Vinci instances completed.. However, some instances are still reporting partition level status keys and they are not completed yet. 19/20 partitions completed in 7318 Da Vinci replicas.. Following partitions still not complete (capped at 10) [0]`
This challenge is even more pronounced for Da Vinci, where identifying the problematic host and partition requires …
> [controller] Improve davinci push status debugging logging by adding host information for remaining partitions.

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubUtil.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestMultiDataCenterAdminOperations.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/admin/InMemoryAdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/AdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/ZkAdminTopicMetadataAccessor.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminExecutionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminMetadata.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminOperationWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/stats/AdminConsumptionStats.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestZkAdminTopicMetadataAccessor.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/TestAdminMetadata.java
This pull request refactors the admin topic consumption logic to use the generic `PubSubPosition` abstraction instead of raw numeric offsets throughout the codebase. This improves compatibility with different pub/sub systems and makes the code more robust and future-proof. The changes touch several key classes and methods, updating member variables, method signatures, and internal logic to consistently use `PubSubPosition`.
* Replaced all usages of numeric offsets with `PubSubPosition` in `AdminConsumptionTask`, including member variables such as `failingOffset`, `lastPersistedOffset`, `lastOffset`, and `lastConsumedOffset`, as well as related logic and comments. This includes updating error tracking (`AdminErrorInfo`), store operation queues, retry maps, and checkpoint variables.
* …
> [controller] Migrate from long offset to PubSubPosition abstraction in admin message consumption

- .gitignore
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/stats/BasicConsumerStats.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/stats/BasicConsumerStatsTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/OpenTelemetryDataPointTestUtils.java
1. The version swap count metric in CDC will emit a NaN by default, so when you go to query it the data is unavailable.
2. There is an issue where you can't test multiple OTEL metrics in one unit test.
1. We will emit a default value of 0 for the version swap metrics.
2. The reason why you couldn't test multiple OTEL metrics in one unit test is because the helper functions fetching the metrics didn't filter by the passed in attributes. It would only return the latest metric emitted. Now, it will filter by the expected attributes.
> [cc][test] Add default metric emission for version swap, and fix OTEL metrics test validation

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/BootstrappingVeniceChangelogConsumerDaVinciRecordTransformerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/IsolatedIngestionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionRequestClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/isolated/IsolatedIngestionServerHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionMonitorService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionReportHandler.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/ingestion/main/MainIngestionStorageMetadataService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/PushStatusNotifier.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/VeniceOfflinePushMonitorAccessor.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubProducerAdapterConcurrentDelegator.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/OfflinePushStatus.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/Utils.java
- services/venice-controller/src/main/java/com/linkedin/venice/pushmonitor/AbstractPushMonitor.java
- services/venice-router/src/main/java/com/linkedin/venice/router/MetaDataHandler.java
Continuing the effort from #989, standardized logging of `store name` + `version` + `partition` as replica. This will make searching through logs easier as the partition won't be separate from the `store` + `version`.
Asked Windsurf to refactor and make these changes. Also asked it to address review comments, push changes, and reply to the comments.
```mint build```
Many existing log messages were modified, so anything relying on the previous log message will be breaking.
> [server] [dvc] Replica Id Logging 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerServiceTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaStoreIngestionServiceTest.java
Enhanced heartbeat monitoring with detailed ingestion context logging when lag is detected, improving debugging capabilities for consumer performance issues.
Key Changes
- **New [getIngestionInfoFor()](cci:1://file:///Users/xhao/Projects/venice_os/venice/clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java:517:2-532:3) method** in [AggKafkaConsumerService](cci:2://file:///Users/xhao/Projects/venice_os/venice/clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/AggKafkaConsumerService.java:51:0-560:1) for region-based ingestion info retrieval
- **Enhanced `HeartbeatMonitoringService`** with context logging when heartbeat lag occurs
- **Updated ingestion services** to integrate heartbeat monitoring
Provides detailed …
> [Server] Add ingestion context logging when heartbeat lag happened.

- .github/workflows/VeniceCI-E2ETests.yml
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/ActiveActiveStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/SharedKafkaConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerIntegrationTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/adapter/consumer/MockInMemoryConsumerAdapter.java
- Replace offsetForTime with getPositionByTimestamp API across ingestion tasks
- Update ApacheKafkaConsumerAdapter and TopicManager interfaces  
- Standardize logging patterns in ingestion task implementations
> [server][ci][build] Replace offsetForTime with getPositionByTimestamp API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/store/rocksdb/RocksDBServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/http2/SSLContextBuilder.java
- internal/alpini/netty4/alpini-netty4-base/src/main/java/com/linkedin/alpini/netty4/ssl/SslInitializer.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/VeniceHttp2PipelineInitializerBuilder.java
Some logs to consider removing as a stretch goal. 🤷
```
PartitionTracker(topic: StoreName_v10, partition: 739) Will initialize new segment with a non-START_OF_SEGMENT message, endOfPushReceived=true, tolerateAnyMessageType=true
```
* Removed the warning log in `handleUnregisteredProducer()` if the segment can be initialized without `START_OF_SEGMENT`.
* This log message is very noisy at **250M+ logs / day** and does not provide much value other than being possibly indicative of a problem.
* To compensate, whether the segment was registered is included in the actual error when the actual error is reported.
```
StoreIngestionTask SIT-StoreName_v928 Not subscribed to any partitions
StoreIngestionTask SIT-StoreName_v928 Going back to sleep as consumption has finished and topics are …
```
> [server] [dvc] Noisy Log Removal

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Arg.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/Command.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerClient.java
- internal/venice-common/src/main/java/com/linkedin/venice/controllerapi/ControllerRoute.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/AdminToolE2ETest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskIntegrationTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/adapter/consumer/poll/FilteringPollStrategy.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumerService.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminOperationWrapper.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/AdminSparkServer.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/SkipAdminRoute.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
This pull request introduces support for skipping admin messages by execution ID in addition to offset, improving error handling and control for admin operations. The changes add new arguments and methods across the Venice admin tool, controller, and consumer service, ensuring that execution IDs can be used to skip problematic messages more precisely. 
**Admin message skipping enhancements:**
* Added support for skipping admin messages by execution ID, including new `EXECUTION_ID` argument in the CLI (`Arg.java`, `Command.java`, `AdminTool.java`) and updated method signatures in controller and admin interfaces to accept execution ID.
* Updated `AdminConsumerService` and `AdminConsumptionTask` to handle execution ID skipping, including new state variables, error tracking, and logic for …
> [controller] Skip admin message by execution id

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTaskTest.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/KafkaTopicDumper.java
- clients/venice-admin-tool/src/main/java/com/linkedin/venice/TopicMessageFinder.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestAdminToolConsumption.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TestKafkaTopicDumper.java
- clients/venice-admin-tool/src/test/java/com/linkedin/venice/TopicMessageFinderTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubConstants.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcher.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicManagerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/manager/TopicMetadataFetcherTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestActiveActiveReplicationForIncPush.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestPushJobWithNativeReplication.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/api/consumer/PubSubConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerE2ETest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/pubsub/manager/TopicManagerIntegrationTest.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
This change updates all code paths to use the new endPosition API instead of relying  
on topic manager and consumer endOffset calls. Tests are updated accordingly.  
> [server][dvc][controller][test] Replace endOffset with endPosition API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/notifier/PushStatusNotifier.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/notifier/TestPushStatusNotifier.java
- internal/venice-common/src/main/java/com/linkedin/venice/helix/VeniceOfflinePushMonitorAccessor.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/OfflinePushAccessor.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/PartitionStatus.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/ReadOnlyPartitionStatus.java
- internal/venice-common/src/main/java/com/linkedin/venice/pushmonitor/ReplicaStatus.java
- internal/venice-common/src/test/java/com/linkedin/venice/helix/OfflinePushMonitorAccessorTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pushmonitor/ReplicaStatusTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/davinci/notifier/LeaderErrorNotifier.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/helix/HelixOfflinePushMonitorAccessorTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/pushmonitor/PartitionStatusBasedPushMonitorTest.java
Progress was previously reported as a numeric offset. While this was easy to  
interpret, it was rarely, if ever, used in practice. With the new PubSubPosition,  
progress is represented as raw bytes, which are not meaningful or helpful for  
troubleshooting. Instead of adding extra code to report this unused information,  
the reporting logic is removed.  
> [server] Remove unused replica progress reporting in ReplicaStatus  

- services/venice-controller/src/main/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTask.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/kafka/consumer/AdminConsumptionTaskTest.java
This pull request updates the logic for subscribing to Kafka topics in `AdminConsumptionTask` and adds targeted tests to verify the new behavior. The main improvement is that the subscription logic now correctly distinguishes between local and upstream checkpoint positions depending on whether remote consumption is enabled, ensuring more reliable recovery and consumption behavior.
**Subscription logic improvements:**
* Updated the `subscribe()` method in `AdminConsumptionTask` to use the upstream checkpoint position when remote consumption is enabled, and the local checkpoint position otherwise. This avoids incorrectly using the local checkpoint when remote consumption should use the upstream checkpoint.
**Test coverage enhancements:**
* Added …
> [controller] fix to decide correctly if the offset for admin topic exist

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriter.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/task/datawriter/AbstractPartitionWriterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/TestHybridMultiRegion.java
As part of support for logical timestamp and RMD support for VPJ, we did not pass the right rmd schema id to the Writer and as a result the payload written to the server did not carry any writer schema information. As a result, any subsequent consumption of the RMD data would result in NPE due to lack of writer schema id.
This is was noticed in our testing RMD pushes E2E and here is the stacktrace
```
ava.lang.Exception: java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema.hashCode()" because "this.writer" is null
at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:491) ~[hadoop-mapreduce-client-common-2.10.2.jar:?]
at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:551) [hadoop-mapreduce-client-common-2.10.2.jar:?]
Caused by: …
```
> [vpj] Fix AbstractPartitionWriter to pass the correct rmdSchemaId

- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
fix: update error message formatting and add response validation in CreateVersionTest
CI
> [vpj] [controller] Fix Missing ACL Message

- services/venice-controller/src/main/java/com/linkedin/venice/controller/StoreBackupVersionCleanupService.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/TestStoreBackupVersionCleanupService.java
`cleanupBackupVersion()` in `StoreBackupVersionCleanupService` was not cleaning up all source backup versions from frequent repushes, which can lead to ingestion failures. It only cleans up one source backup source version.
Delete all versions repushed into the current version, but keep one backup version subject to the retention period. Since the current version is based off these previous versions, they should be unnecessary except for the TTL repush case.
* Reduced `waitTimeDeleteRepushSourceVersion` to `30 mins` from `1 hour`.
* Synced the comment saying that the source backup of the current repushed version would be deleted, but it was still respecting the 7 days backup because of the lack of parenthesis.
* Fixed `mockStore()` in `TestStoreBackupVersionCleanupService`:
* It was not …
> [controller] Delete Repush Source Backup Versions

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
Improve the logging in readGlobalRtDivState to contain the `key` string (thus `brokerUrl`) when exception happens.
> [server] Improve logging in readGlobalRtDivState

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/store/rocksdb/RocksDBStoragePartitionTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/TimingUtils.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceMultiClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/integration/utils/VeniceTwoLayerMultiRegionMultiClusterWrapper.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/restart/TestRestartServerAfterDeletingSstFilesWithActiveActiveIngestion.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/utils/DataProviderUtils.java
Optimized shutdown performance across all levels of Venice test cluster wrappers by  
parallelizing independent service shutdowns while preserving proper dependency ordering.  
Changes:  
- VeniceTwoLayerMultiRegionMultiClusterWrapper: Parallelize parent controller and  
child region shutdowns independently, keeping sequential order  
(controllers → regions → pubsub → zk).  
- VeniceMultiClusterWrapper: Parallelize individual controller and cluster shutdowns  
with dependency management (controllers → clusters → d2 → pubsub → zk).  
- VeniceClusterWrapper: Parallelize router, server, and controller shutdowns within  
each cluster while preserving order (client → routers → servers → controllers →  
infrastructure → process).  
> [test] Implement parallel shutdown for Venice test infrastructure to improve performance

- clients/venice-admin-tool/src/main/java/com/linkedin/venice/AdminTool.java
The `--disable-log` option seems to still leak some logs and I think it's because the `PubSubClientsFactory` is initialized before `LogConfigurator.disableLog()` on line `226`.
Move `PubSubClientsFactory` to be created after logging is disabled.
CI
> [admin-tool] Disable Log Fix

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/HeartbeatMonitoringServiceStats.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/stats/ingestion/heartbeat/HeartbeatMonitoringService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/StoreBackendTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/VersionBackendTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-test-common/build.gradle
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientIsolatedAndHybridStoreTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTestWithHeartbeatReadyToServeCheckTest.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/systemstore/SystemStoreRepairTaskTest.java
This PR adds heartbeat monitoring support for Da Vinci. With this support, Da Vinci will be able to switch to measure time lag, instead of offset lag when performing ready-to-serve check.
> [dvc] Add heartbeat monitoring service for Da Vinci

- .gitignore
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/controller/server/TestAdminSparkWithMocks.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/Admin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/VeniceParentHelixAdmin.java
- services/venice-controller/src/main/java/com/linkedin/venice/controller/server/CreateVersion.java
- services/venice-controller/src/test/java/com/linkedin/venice/controller/server/CreateVersionTest.java
Currently controller is picking configs from a random cluster when checking push job eligibility.
This PR fixed the issue by specifying the right cluster name when retrieving configs.
> [controller] Check cluster specific multi-region configs for batch push eligibility

- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubPositionDeserializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/PubSubUtil.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/PubSubPositionDeserializerTest.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
Remove the deprecated static `PubSubPositionDeserializer::getPositionFromWireFormat`
method to avoid accidental usage. This API only supported a limited set of default
position types, which could lead to incorrect behavior. Callers should instead use
a custom `PubSubPositionDeserializer` to handle all position types properly.
> [server][dvc][test] Delete deprecated PubSubPositionDeserializer::getPositionFromWireFormat API

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTask.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/manager/TopicManager.java
Update LeaderMetadata handling to treat PubSubPosition as the primary field for  
tracking leader state. Retain numeric offset only as a fallback for cases where  
a position is unavailable, ensuring forward compatibility while preserving safety.  
> [server] Use PubSubPosition as primary field from LeaderMetadata with offset fallback 

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/client/NettyFileTransferClient.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PBlobTransferService.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/blobtransfer/server/P2PFileTransferServerHandler.java
The P2P blob transfer server was experiencing severe performance bottlenecks that limited throughput to ~200 MB/s on enterprise NVMe hardware capable of 3,000+ MB/s. Analysis revealed multiple issues:
1. Thread pool starvation: Only 6 worker threads couldn't generate sufficient concurrent I/O operations to utilize enterprise NVMe's 8+ controller cores. 
2. Low queue depth: Server iostat showed queue depth of only ~4, indicating massive underutilization of NVMe parallel processing capability. 
```
Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
nvme0n1       13193.00 377560.00     0.00   0.00    0.14    28.62    3.00     48.00     0.00   0.00 …
```
> [server][dvc] Optimize P2P file transfer by increasing thread pool and chunk size

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/validation/PartitionTracker.java
- internal/venice-common/src/main/java/com/linkedin/venice/kafka/validation/Segment.java
- internal/venice-common/src/test/java/com/linkedin/venice/kafka/validation/SegmentTest.java
Fixed `NullPointerException` in `Segment.toProducerPartitionState()` when the `checkSum` is `null`.
> [server] Global RT DIV: Fixed `toPartitionState()` NPE

- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
- internal/venice-common/src/test/java/com/linkedin/venice/offsets/TestOffsetRecord.java
If a deserialized PubSubPosition is behind the provided offset, fall back to the  
offset value instead. Ideally this situation should not occur, but this is added  
as extremely defensive coding to prevent duplicate processing.  
> [server] Fallback to offset if PubSubPosition is lower to avoid duplicate work

- .github/workflows/UnitTests-core.yml
- .github/workflows/VeniceCI-CompatibilityTests.yml
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
> [server][dvc] Use RedundantExceptionFilter to rate limit position to offset fallback logs

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapter.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubConsumerAdapter.java
- internal/venice-common/src/test/java/com/linkedin/venice/pubsub/adapter/kafka/consumer/ApacheKafkaConsumerAdapterTest.java
- internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciLiveUpdateSuppressionTest.java
- internal/venice-test-common/src/main/java/com/linkedin/venice/pubsub/mock/adapter/consumer/MockInMemoryConsumerAdapter.java
This commit makes all PubSubConsumerAdapter implementations thread-safe to  
support concurrent access from multiple threads, addressing potential race  
conditions in consumer operations.  
> [server][controller][dvc][cc] Make PubSubConsumerAdapter implementations thread-safe

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/config/VeniceServerConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/InactiveTopicPartitionChecker.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerService.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/InactiveTopicPartitionCheckerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/KafkaConsumerServiceTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
We observed that when two topic-partitions with the same leader Kafka broker are assigned to the same consumer, if one is idle, it may impact fetch performance of the other topic-partition.
To address this issue, a few ideas have been proposed offline. 
This PR implements one of the solution: Introduce a checker service that periodically check current version pool's consumers and pause idle topic-partition for some times.
For now, the check works as follows:
The check will be scheduled every **server.inactive.topic.partition.checker.internal.in.seconds** seconds.
In the check, it will examine every topic-partition that, if delta between previous message and now is beyond certain threshold "server.inactive.topic.partition.checker.threshold.in.seconds", it will try to add them to the pause …
> [server] Add InactiveTopicPartitionChecker to pause/resume inactive topic partition periodically

- clients/da-vinci-client/src/test/java/com/linkedin/davinci/kafka/consumer/LeaderFollowerStoreIngestionTaskTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/offsets/OffsetRecord.java
OffsetRecord::deserializePositionWithOffsetFallback added a safeguard to  
prefer an offset-based position if the provided offset is greater than the  
deserialized position. However, since 0 is the default long value, cases  
with EARLIEST + offset=0 incorrectly produced ApacheKafkaOffsetPosition(0)  
instead of EARLIEST. This breaks checks relying on EARLIEST semantics.  
Fix by ignoring offset=0 and returning the original position to preserve  
correct validation behavior.  
> [server] Ignore offset in OffsetRecord::deserializePositionWithOffsetFallback if it's zero

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/VersionBackend.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/VersionBackendTest.java
If DVC client users registers a DVC client with empty partition list, it still tries to subscribe to the empty list and started reporting ingestion status to the controller, which later declares as dead instance.
This PR blocks ingestion state reporting for empty partition subscription.
> [da-vinci-client] Do not subscribe to empty partition list

- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/ChangelogClientConfig.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/LocalBootstrappingVeniceChangelogConsumer.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceAfterImageConsumerImpl.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactory.java
- clients/da-vinci-client/src/main/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImpl.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/InternalLocalBootstrappingVeniceChangelogConsumerTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerClientFactoryTest.java
- clients/da-vinci-client/src/test/java/com/linkedin/davinci/consumer/VeniceChangelogConsumerImplTest.java
- internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java
- internal/venice-common/src/main/java/com/linkedin/venice/pubsub/api/PubSubMessageDeserializer.java
- internal/venice-common/src/main/java/com/linkedin/venice/utils/DictionaryUtils.java
CDC currently fails when KME schema evolves, since records encoded with newer schema  
cannot be deserialized. This change introduces a KME schema reader so that records  
with updated schema versions can be deserialized and processed correctly.  
> [cdc] Add KME schema reader in CDC to support schema evolution

- internal/venice-common/src/main/java/com/linkedin/venice/listener/ServerHandlerUtils.java
- services/venice-server/src/main/java/com/linkedin/venice/listener/StorageReadRequestHandler.java
It is difficult to understand which host initiated a read request from an error log. This could be useful in determining the health of the host who made the request at the time of the request, when identifying potential issues.
This is all that we get from the error logs:
```
9/29/2025, 12:08:10.6838281 PM [com.linkedin.davinci.store.AbstractStorageEngine] Failed to get the partition with msg: Partition: 98 of store: {store_name} does not exist
9/29/2025, 12:08:10.6838493 PM [com.linkedin.venice.listener.StorageReadRequestHandler] Exception thrown for {resource}
com.linkedin.venice.exceptions.PersistenceFailureException: Partition: 98 of store: {store_name} does not exist:
at com.linkedin.davinci.store.AbstractStorageEngine.getPartitionOrThrow(AbstractStorageEngine.java:719)
at …
```
> [server] Add Remote Address to Read Request Error Log

- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/DefaultInputDataInfoProvider.java
- clients/venice-push-job/src/main/java/com/linkedin/venice/hadoop/VenicePushJob.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/TestDefaultInputDataInfoProvider.java
- clients/venice-push-job/src/test/java/com/linkedin/venice/hadoop/VenicePushJobTest.java
VPJ failures due to invalid input source or dataset changes are mis-categorized as non-user errors.
- Make the exception thrown consistent in case of input data not present
- Move `checkForLastModificationTime` after input validations
- Cascade `FileNotFoundExceptions` as `VeniceInputInvalidException` to report it as user errors
- Added few getters for unit testing
- Added both unit and partly integration tests to validate the flow
> [vpj] Fix issues with mis-categorization of invalid inputs and dataset changes for VPJ

- clients/venice-client/src/test/java/com/linkedin/venice/fastclient/ClientConfigTest.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceMetricsConfig.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepository.java
- internal/venice-client-common/src/main/java/com/linkedin/venice/stats/metrics/AsyncMetricEntityState.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceMetricsConfigTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/VeniceOpenTelemetryMetricsRepositoryTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/AsyncMetricEntityStateTest.java
- internal/venice-client-common/src/test/java/com/linkedin/venice/stats/metrics/MetricEntityStateTest.java
Otel can be enabled/disabled, but tehuti metrics are enabled always.
1.  Add config to enable/disable tehuti metrics that are created via new Otel `MetricEntityState` APIs.
2. The metrics created directly without use these APIs will still be enabled.
new config: `tehuti.venice.metrics.enabled`
new setter: `emitTehutiMetrics(Boolean)`
> [all] add config to enable/disable tehuti metrics
